INSERT INTO ingredients_dictionary (ingredient_id,canonical_name,aliases,product_count,occurrence_count)
VALUES
  ('ING0001','Glycerin','Glycerin; GLYCERIN; glycerin; Glycerin*; Glycerin (Vegetable/ Végétale)',555,557),
  ('ING0002','Aqua','Aqua; Aqua (Water); AQUA; AQUA (WATER); aqua; Aqua (water); Aqua (Water, Eau); AQUA (WATER, EAU); Aqua(Water); AQUA(WATER); Aqua (Water Eau); Aqua (Water\ Eau); AQUA (WATER EAU); Aqua*',375,378),
  ('ING0003','Citric Acid','Citric Acid; CITRIC ACID; citric acid; Citric acid; Сitric Acid; Сitric acid; Citric Acid**; Citric Acid*',348,350),
  ('ING0004','Phenoxyethanol','Phenoxyethanol; PHENOXYETHANOL; phenoxyethanol; PHENOXYETHANOl; Рhenoxyethanol',323,328),
  ('ING0005','Parfum','Parfum; PARFUM; parfum; PARFUM (FRAGRANCE); Parfum (Fragrance); Pаrfum; parfum (fragrance); PARFUM*',287,287),
  ('ING0006','Butylene Glycol','Butylene Glycol; BUTYLENE GLYCOL; butylene glycol; Butylene glycol',278,280),
  ('ING0007','Ethylhexylglycerin','Ethylhexylglycerin; ETHYLHEXYLGLYCERIN; ethylhexylglycerin',276,277),
  ('ING0008','Water','Water; Water (Aqua/Eau); WATER; WATER (AQUA); Water (Aqua); Water (Aqua) (Eau); WATER (AQUA/EAU); water; water (aqua/eau); Water (Eau/Aqua); WATER (EAU); Water(10000ppm); Water(Aqua)',274,276),
  ('ING0009','Panthenol','Panthenol; panthenol; PANTHENOL; Panthenol (Д-пантенол); Рanthenol; panthenol (d); Panthenol (20000ppm); Panthenol(Vitamin B5); Panthenol (D); panthenol (1.00%); Panthenol (11250ppm); Panthenol (5%)',261,261),
  ('ING0010','Tocopherol','Tocopherol; TOCOPHEROL; tocopherol; Tocopherol (Vitamin E); Tocopherol (Vitamin E)*; TOCOPHEROL (VITAMIN E); Tocopherol (2ppm); Tocopherol (31ppm); TOCOPHEROL (MIXED)',239,240),
  ('ING0011','Cetearyl Alcohol','Cetearyl Alcohol; CETEARYL ALCOHOL; cetearyl alcohol; Cetearyl alcohol; CЕTEARYL ALCOHOL',238,239),
  ('ING0012','Disodium EDTA','Disodium EDTA; DISODIUM EDTA; Disodium Edta; disodium edta; disodium EDTA',217,218),
  ('ING0013','Linalool','Linalool; LINALOOL; linalool',210,210),
  ('ING0014','Sodium Benzoate','Sodium Benzoate; SODIUM BENZOATE; sodium benzoate; Sodium benzoate; Sodium Benzoate.; Sodium Benzoate*',205,207),
  ('ING0015','Sodium Hyaluronate','Sodium Hyaluronate; SODIUM HYALURONATE; sodium hyaluronate; sodium Hyaluronate; Sodium Hyaluronate (10 ppm); Sodium Hyaluronate (1 ppm); Sodium hyaluronate; Sodium Hyaluronate (800 ppm); sodium hyaluronate (30 ppm)',199,200),
  ('ING0016','2-Hexanediol','2-Hexanediol; 2-hexanediol; 2-HEXANEDIOL; 2 Hexanediol; 2-hexaneDiol; 2- Hexanediol; 2-Hеxanediol',187,187),
  ('ING0017','Limonene','Limonene; LIMONENE; limonene',186,186),
  ('ING0018','Propylene Glycol','Propylene Glycol; PROPYLENE GLYCOL; propylene glycol; Propylene glycol; Рropylene Glycol',177,178),
  ('ING0019','Niacinamide','Niacinamide; NIACINAMIDE; niacinamide; Niacinamide(10%); Niacinamide (витамин PP); Niacinamide (4%); Niacinamide(Sebum control agent); niacinamide (1.00%); Niacinamide 10.0%; Niacinamide (50000ppm); niacinamide (150000ppm); Niacinamide(15%); Niacinamide (2%)',174,175),
  ('ING0020','Fragrance','Fragrance; Fragrance (Parfum); fragrance; FRAGRANCE (PARFUM); FRAGRANCE; FRAGRANCE (NATURALLY DERIVED); fragrance (parfum); fragrance (naturally derived); Fragrance (Parfum)**; Fragrance(Parfum)',169,173),
  ('ING0021','Benzyl Alcohol','Benzyl Alcohol; BENZYL ALCOHOL; benzyl alcohol; Benzyl alcohol',168,169),
  ('ING0022','Cetrimonium Chloride','Cetrimonium Chloride; CETRIMONIUM CHLORIDE; cetrimonium chloride; Cetrimonium chloride',164,164),
  ('ING0023','Sodium Chloride','Sodium Chloride; SODIUM CHLORIDE; sodium chloride; Sodium chloride; sodium сhloride; SODIUM СHLORIDE',161,162),
  ('ING0024','Propanediol','Propanediol; PROPANEDIOL; propanediol',161,161),
  ('ING0025','Dimethicone','Dimethicone; DIMETHICONE; dimethicone',154,158),
  ('ING0026','Cocamidopropyl Betaine','Cocamidopropyl Betaine; COCAMIDOPROPYL BETAINE; cocamidopropyl betaine; Cocamidopropyl betaine; Cocamidopropyl Betaine*',142,143),
  ('ING0027','Potassium Sorbate','Potassium Sorbate; POTASSIUM SORBATE; potassium sorbate; Potassium sorbate; Potassium Sorbate**',140,141),
  ('ING0028','Caprylyl Glycol','Caprylyl Glycol; CAPRYLYL GLYCOL; caprylyl glycol; Caprylyl glycol',139,139),
  ('ING0029','Xanthan Gum','Xanthan Gum; XANTHAN GUM; xanthan gum; Xanthan gum',138,138),
  ('ING0030','Caprylic/Capric Triglyceride','Caprylic/Capric Triglyceride; CAPRYLIC/CAPRIC TRIGLYCERIDE; Caprylic/capric Triglyceride; Caprylic/ Capric Triglyceride; caprylic/capric triglyceride; Caprylic/Сapric Triglyceride; Caprylic / Capric Triglyceride; CAPRYLIC /CAPRIC TRIGLYCERIDE; Caprylic/Capric Triglyceride*',134,136),
  ('ING0031','Lactic Acid','Lactic Acid; LACTIC ACID; lactic acid; Lactic acid; Lactic acid**',129,130),
  ('ING0032','Hexyl Cinnamal','Hexyl Cinnamal; HEXYL CINNAMAL; hexyl cinnamal; Hexyl cinnamal; Hexyl Сinnamal',124,124),
  ('ING0033','Tocopheryl Acetate','Tocopheryl Acetate; TOCOPHERYL ACETATE; tocopheryl acetate; Tocopheryl (Vitamin E) Acetate; Tocopheryl Acetate (витамин Е); Tocopheryl Acetate (Витамин Е); Tocopheryl Acetate (Vitamin E); Tocopheryl Acetate (D-alpha); ТOCOPHERYL ACETATE',117,117),
  ('ING0034','Sodium Hydroxide','Sodium Hydroxide; SODIUM HYDROXIDE; sodium hydroxide; Sodium hydroxide',116,116),
  ('ING0035','Behentrimonium Chloride','Behentrimonium Chloride; BEHENTRIMONIUM CHLORIDE; behentrimonium chloride; Behentrimonium chloride; Behentrimonium Сhloride; Behentrimonium Chloride**; behentrimonium сhloride',115,115),
  ('ING0036','Pentylene Glycol','Pentylene Glycol; PENTYLENE GLYCOL; pentylene glycol; Pentylene glycol',110,111),
  ('ING0037','Arginine','Arginine; arginine; ARGININE',105,106),
  ('ING0038','Dipropylene Glycol','Dipropylene Glycol; DIPROPYLENE GLYCOL; dipropylene glycol; Dipropylene glycol',103,104),
  ('ING0039','Glyceryl Stearate','Glyceryl Stearate; GLYCERYL STEARATE; glyceryl stearate; Glyceryl Stearate*',100,100),
  ('ING0040','Amodimethicone','Amodimethicone; AMODIMETHICONE; amodimethicone',97,97),
  ('ING0041','Carbomer','Carbomer; CARBOMER; carbomer',97,97),
  ('ING0042','Guar Hydroxypropyltrimonium Chloride','Guar Hydroxypropyltrimonium Chloride; guar hydroxypropyltrimonium chloride; GUAR HYDROXYPROPYLTRIMONIUM CHLORIDE; Guar hydroxypropyltrimonium chloride',96,97),
  ('ING0043','Cyclopentasiloxane','Cyclopentasiloxane; CYCLOPENTASILOXANE; cyclopentasiloxane; СYCLOPENTASILOXANE; сyclopentasiloxane',96,96),
  ('ING0044','Adenosine','Adenosine; ADENOSINE; adenosine',94,94),
  ('ING0045','Allantoin','Allantoin; ALLANTOIN; allantoin',93,94),
  ('ING0046','Methylisothiazolinone','Methylisothiazolinone; methylisothiazolinone; METHYLISOTHIAZOLINONE; Мethylisothiazolinone',87,87),
  ('ING0047','Hydrolyzed Keratin','Hydrolyzed Keratin; hydrolyzed keratin; HYDROLYZED KERATIN; Hydrolyzed keratin; Hydrolyzed Keratin (кератин); Hydrolyzed Кeratin',86,86),
  ('ING0048','Citronellol','Citronellol; CITRONELLOL; citronellol',83,83),
  ('ING0049','Hydrolyzed Wheat Protein','Hydrolyzed Wheat Protein; HYDROLYZED WHEAT PROTEIN; hydrolyzed wheat protein; Hydrolyzed wheat protein',83,83),
  ('ING0050','Hydrogenated Lecithin','Hydrogenated Lecithin; hydrogenated lecithin; HYDROGENATED LECITHIN; Hydrogenated lecithin',83,83),
  ('ING0051','Ceramide NP','Ceramide NP; CERAMIDE NP; ceramide NP; Ceramide Np; Ceramide NP (=Ceramide 3); ceramide np',82,83),
  ('ING0052','Sodium Laureth Sulfate','Sodium Laureth Sulfate; SODIUM LAURETH SULFATE; sodium laureth sulfate; Sodium laureth sulfate',80,81),
  ('ING0053','Salicylic Acid','Salicylic Acid; SALICYLIC ACID; salicylic acid; Salicylic acid; Salicylic Acid (4%)',80,82),
  ('ING0054','Betaine','Betaine; BETAINE; betaine',77,77),
  ('ING0055','Methylchloroisothiazolinone','Methylchloroisothiazolinone; methylchloroisothiazolinone; METHYLCHLOROISOTHIAZOLINONE; Methylchlоroisothiazolinone',76,76),
  ('ING0056','Isopropyl Alcohol','Isopropyl Alcohol; ISOPROPYL ALCOHOL; isopropyl alcohol; Isopropyl alcohol',74,74),
  ('ING0057','Cetyl Alcohol','Cetyl Alcohol; CETYL ALCOHOL; cetyl alcohol; Cetyl alcohol; Cetyl Alcohol*',74,74),
  ('ING0058','Polyquaternium-10','Polyquaternium-10; POLYQUATERNIUM-10; polyquaternium-10',72,73),
  ('ING0059','Centella Asiatica Extract','Centella Asiatica Extract; CENTELLA ASIATICA EXTRACT; Centella asiatica extract; Centella Asiatica Extract (0.98 ppm); Centella Asiatica (Gotu Kola) Extract; CENTELLA ASIATICA (HYDROCOTYL) EXTRACT; Centella Asiatica Extract(4315ppm); Centella Asiatica Extract (9700ppm); Centella Asiatica Extract (1045 ppb)',71,71),
  ('ING0060','Benzyl Salicylate','Benzyl Salicylate; benzyl salicylate; BENZYL SALICYLATE; Benzyl salicylate',70,70),
  ('ING0061','Camellia Sinensis Leaf Extract','Camellia Sinensis Leaf Extract; Camellia Sinensis (Green Tea) Leaf Extract; CAMELLIA SINENSIS LEAF EXTRACT; Camellia Sinensis (Green Tea) Leaf Extract*; Camellia sinensis Leaf Extract; camellia sinensis leaf extract; Camellia sinensis leaf extract; CAMELLIA SINENSIS (GREEN TEA) LEAF EXTRACT; Camellia Sinensis (White Tea) Leaf Extract',70,70),
  ('ING0062','Dimethiconol','Dimethiconol; dimethiconol; DIMETHICONOL',70,70),
  ('ING0063','Glycine','Glycine; GLYCINE; glycine',69,69),
  ('ING0064','Squalane','Squalane; SQUALANE; Squalane*; SQUALANE (PLANT); squalane',69,69),
  ('ING0065','PARFUM / FRAGRANCE','PARFUM / FRAGRANCE; Parfum / Fragrance; Parfum/Fragrance; parfum / fragrance; PARFUM/FRAGRANCE; parfum/fragrance; Parfum/ Fragrance; PARFUM [FRAGRANCE]; PARFUM / FRAGRANCE. (F.I.L. Y70013577/1); Parfum / fragrance; parfum/ fragrance',68,68),
  ('ING0066','Argania Spinosa Kernel Oil','Argania Spinosa Kernel Oil; Argania Spinosa (Argan) Kernel Oil*; Argania Spinosa (Argan) Kernel Oil; argania spinosa kernel oil; ARGANIA SPINOSA KERNEL OIL; ARGANIA SPINOSA (ARGAN) KERNEL OIL; Argania spinosa kernel oil; ARGANIA SPINOSA KERNEL OIL (ARGAN OIL); ARGANIA SPINOSA (ARGAN) KERNEL OIL*',65,65),
  ('ING0067','Polysorbate 20','Polysorbate 20; Polysorbate-20; POLYSORBATE 20; POLYSORBATE-20; polysorbate 20; polysorbate-20; Polysorbatе - 20; Polysorbatе-20',63,63),
  ('ING0068','Geraniol','Geraniol; GERANIOL; geraniol',63,63),
  ('ING0069','Tromethamine','Tromethamine; TROMETHAMINE; tromethamine',62,62),
  ('ING0070','Sodium Citrate','Sodium Citrate; SODIUM CITRATE; sodium citrate',60,60),
  ('ING0071','Hyaluronic Acid','Hyaluronic Acid; hyaluronic acid; HYALURONIC ACID; Hyaluronic acid; hyaluronic aсid; Hyaluronic Acid (0.01PPM); Hyaluronic Acid (0.01 ppm).; Hyaluronic Acid (30 ppm); Нyaluronic Аcid',58,58),
  ('ING0072','Simmondsia Chinensis (Jojoba) Seed Oil','Simmondsia Chinensis (Jojoba) Seed Oil; SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL; Simmondsia Chinensis Seed Oil; simmondsia chinensis (jojoba) seed oil; simmondsia chinensis (jojoba oll) seed oil; Simmondsia Chinensis (Jojoba ) Seed Oil; Simmondsia Chinensis (Jojoba)Seed Oil; Simmondsia Chinensis seed oil; Simmondsia chinensis (jojoba) seed oil; Simmondsia Chinensis (jojoba) Seed Oil; Simmondsia Chinensis (Jojoba) Seed Oil (1500ppm)',57,58),
  ('ING0073','Hydroxyethylcellulose','Hydroxyethylcellulose; HYDROXYETHYLCELLULOSE; hydroxyethylcellulose',57,57),
  ('ING0074','Methylparaben','Methylparaben; methylparaben; METHYLPARABEN',56,57),
  ('ING0075','Acrylates/C10-30 Alkyl Acrylate Crosspolymer','Acrylates/C10-30 Alkyl Acrylate Crosspolymer; ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER; Acrylates/C10- 30 Alkyl Acrylate Crosspolymer; acrylates/c10-30 alkyl acrylate crosspolymer; Acrylates / C10-30 Alkyl Acrylate Crosspolymer; ACRYLATES / C10-30 ALKYL ACRYLATE CROSSPOLYMER; Acrylates/ C10-30 Alkyl Acrylate Crosspolymer',56,56),
  ('ING0076','Sodium PCA','Sodium PCA; Sodium Pca; sodium pca; SODIUM PCA',55,55),
  ('ING0077','Helianthus Annuus (Sunflower) Seed Oil','Helianthus Annuus (Sunflower) Seed Oil; HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL; Helianthus Annuus Seed Oil; Helianthus Annuus (sunflower) Seed Oil; HELIANTHUS ANNUUS SEED OIL; helianthus annuus (sunflower) seed oil',52,53),
  ('ING0078','Serine','Serine; serine; SERINE',52,52),
  ('ING0079','PEG-40 Hydrogenated Castor Oil','PEG-40 Hydrogenated Castor Oil; PEG-40 HYDROGENATED CASTOR OIL; Peg-40 Hydrogenated Castor Oil; PEG-40 hydrogenated castor oil; PEG 40 Hydrogenated Castor Oil',52,52),
  ('ING0080','Coco-Glucoside','Coco-Glucoside; COCO-GLUCOSIDE; Coco Glucoside; COCO GLUCOSIDE; Coco-glucoside; coco glucoside; coco-glucoside',52,52),
  ('ING0081','Silica','Silica; silica; SILICA',52,54),
  ('ING0082','Proline','Proline; proline; PROLINE',51,51),
  ('ING0083','Butyrospermum Parkii (Shea) Butter','Butyrospermum Parkii (Shea) Butter; Butyrospermum Parkii Butter; BUTYROSPERMUM PARKII (SHEA) BUTTER; BUTYROSPERMUM PARKII BUTTER; butyrospermum parkii butter; Butyrospermum parkii (shea) butter; Butyrospermum Parkii (Shea) Butter*; Butyrospermum Parkii (shea) Butter',51,51),
  ('ING0084','Hydrolyzed Hyaluronic Acid','Hydrolyzed Hyaluronic Acid; hydrolyzed hyaluronic acid; HYDROLYZED HYALURONIC ACID; Hydrolyzed Hyaluronic Acid(1PPM); Hydrolyzed Hyaluronic Acid (1ppm); Hydrolyzed Hyaluronic Acid (29,049 ppm); Hydrolyzed Hyaluronic Acid (100 ppm)',51,51),
  ('ING0085','Stearyl Alcohol','Stearyl Alcohol; STEARYL ALCOHOL; stearyl alcohol; Stearyl alcohol',50,50),
  ('ING0086','Titanium Dioxide','Titanium Dioxide; Titanium Dioxide (CI 77891); TITANIUM DIOXIDE; TITANIUM DIOXIDE (CI 77891); Titanium Dioxide (nano); titanium dioxide; TITANIUM DIOXIDE (NANO); Titanium Dioxide (Nano); Titanium Dioxide (Cl 77891); titanium dioxide (CI 77891)',50,51),
  ('ING0087','Aloe Barbadensis Leaf Juice','Aloe Barbadensis Leaf Juice; aloe barbadensis leaf juice; ALOE BARBADENSIS LEAF JUICE; Aloe barbadensis leaf juice; Aloe Barbadensis (Aloe Vera) Leaf Juice',49,49),
  ('ING0088','Stearamidopropyl Dimethylamine','Stearamidopropyl Dimethylamine; stearamidopropyl dimethylamine; STEARAMIDOPROPYL DIMETHYLAMINE; Stearamidopropyl dimethylamine',49,49),
  ('ING0089','Ascorbic Acid','Ascorbic Acid; ASCORBIC ACID; ascorbic acid; Ascorbic Acid (Vitamin C); Ascorbic Acid (Vitamine C); Ascorbic Acid (200000 ppm)',49,49),
  ('ING0090','Threonine','Threonine; threonine; THREONINE',49,49),
  ('ING0091','Stearic Acid','Stearic Acid; STEARIC ACID; stearic acid; Stearic acid',49,49),
  ('ING0092','Alanine','Alanine; alanine; ALANINE',48,48),
  ('ING0093','AQUA / WATER','AQUA / WATER; Aqua/Water; Aqua / Water; aqua / water; AQUA/WATER; Aqua/ Water; AQUA [WATER]; AQUA /WATER; Aqua/water; Aqua / water',48,48),
  ('ING0094','Histidine','Histidine; histidine; HISTIDINE',47,47),
  ('ING0095','Aspartic Acid','Aspartic Acid; aspartic acid; ASPARTIC ACID; Aspartic acid',47,47),
  ('ING0096','Diethylamino Hydroxybenzoyl Hexyl Benzoate','Diethylamino Hydroxybenzoyl Hexyl Benzoate; DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE; diethylamino hydroxybenzoyl hexyl benzoate',47,47),
  ('ING0097','Ethylhexyl Triazone','Ethylhexyl Triazone; ETHYLHEXYL TRIAZONE; ethylhexyl triazone; Ethylhexyl triazone',47,47),
  ('ING0098','Polyquaternium-7','Polyquaternium-7; POLYQUATERNIUM-7; polyquaternium-7; Polyquaternium 7',46,46),
  ('ING0099','Alcohol','Alcohol; alcohol; ALCOHOL',46,47),
  ('ING0100','Benzoic Acid','Benzoic Acid; BENZOIC ACID; benzoic acid',45,45),
  ('ING0101','Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine','Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine; BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE; bis-ethylhexyloxyphenol methoxyphenyl triazine; BIS- ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE; Bis-ethylhexyloxyphenol methoxyphenyl triazine; Bis-ethylhexyloxyphenol Methoxyphenyl Triazine',45,45),
  ('ING0102','Hydroxycitronellal','Hydroxycitronellal; hydroxycitronellal; HYDROXYCITRONELLAL',44,44),
  ('ING0103','Coumarin','Coumarin; COUMARIN; coumarin',43,43),
  ('ING0104','Biotin','Biotin; BIOTIN; biotin; Biotin (Vitamin H); Biotin*',42,43),
  ('ING0105','Methylpropanediol','Methylpropanediol; methylpropanediol',42,42),
  ('ING0106','Cocos Nucifera (Coconut) Oil','Cocos Nucifera (Coconut) Oil; Cocos Nucifera Oil; COCOS NUCIFERA (COCONUT) OIL; cocos nucifera oil; cocos nucifera (coconut) oil; COCOS NUCIFERA OIL; Cocos nucifera (coconut) oil; Cocos Nucifera Oil (Масло кокосовое)',41,41),
  ('ING0107','1,2-Hexanediol','1,2-Hexanediol; 1,2-HEXANEDIOL; 1,2-hexanediol; 1-2-Hexanediol; 1.2-Hexanediol; 1, 2-Hexanediol; 1,2 Hexanediol',41,41),
  ('ING0108','Hydrolyzed Soy Protein','Hydrolyzed Soy Protein; HYDROLYZED SOY PROTEIN; hydrolyzed soy protein; Hydrolyzed soy protein',41,41),
  ('ING0109','Valine','Valine; valine; VALINE',41,41),
  ('ING0110','Ammonium Acryloyldimethyltaurate/VP Copolymer','Ammonium Acryloyldimethyltaurate/VP Copolymer; AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER; Ammonium Acryloyldimethyltaurate/ VP Copolymer; Ammonium AcryloyldimethylTaurate / Vp copolymer',41,41),
  ('ING0111','Trideceth-12','Trideceth-12; trideceth-12; TRIDECETH-12',40,40),
  ('ING0112','AQUA / WATER / EAU','AQUA / WATER / EAU; Aqua/Water/Eau; Aqua / Water / Eau; AQUA/WATER/EAU; Aqua / Water / Eau (вода); aqua/water/eau; Aqua / water / eau; AQUA /WATER / EAU',40,40),
  ('ING0113','Hydrolyzed Silk','Hydrolyzed Silk; hydrolyzed silk; HYDROLYZED SILK; Hydrolyzed silk',40,40),
  ('ING0114','Menthol','Menthol; menthol; MENTHOL',40,41),
  ('ING0115','Lecithin','Lecithin; LECITHIN; lecithin',40,40),
  ('ING0116','Isoleucine','Isoleucine; isoleucine; ISOLEUCINE',39,39),
  ('ING0117','Alpha-Isomethyl Ionone','Alpha-Isomethyl Ionone; alpha-isomethyl ionone; ALPHA-ISOMETHYL IONONE; Alpha-isomethyl Ionone; ALPHA ISOMETHYL IONONE; alpha-Isomethyl Ionone; аlpha-Isomethyl Ionone',39,39),
  ('ING0118','Sorbitol','Sorbitol; SORBITOL; Sorbitol*; sorbitol',39,39),
  ('ING0119','Behenyl Alcohol','Behenyl Alcohol; BEHENYL ALCOHOL; Behenyl alcohol',39,39),
  ('ING0120','Glycol Distearate','Glycol Distearate; GLYCOL DISTEARATE; glycol distearate',38,38),
  ('ING0121','Phenylalanine','Phenylalanine; phenylalanine; PHENYLALANINE',38,38),
  ('ING0122','Hydroxyacetophenone','Hydroxyacetophenone; HYDROXYACETOPHENONE; hydroxyacetophenone',38,38),
  ('ING0123','Isopropyl Myristate','Isopropyl Myristate; ISOPROPYL MYRISTATE; isopropyl myristate; Isopropyl Myristate*',37,37),
  ('ING0124','Sodium Lactate','Sodium Lactate; sodium lactate; SODIUM LACTATE; Sodium lactate',37,37),
  ('ING0125','Ethylhexyl Methoxycinnamate','Ethylhexyl Methoxycinnamate; ETHYLHEXYL METHOXYCINNAMATE; Ethylhexyl methoxycinnamate; ethylhexyl methoxycinnamate',37,37),
  ('ING0126','Dehydroacetic Acid','Dehydroacetic Acid; DEHYDROACETIC ACID; dehydroacetic acid; Dehydroacetic acid; Dehydroacetic Acid (DHA)',37,37),
  ('ING0127','Propylparaben','Propylparaben; PROPYLPARABEN; propylparaben',36,36),
  ('ING0128','ALCOHOL DENAT.','ALCOHOL DENAT.; alcohol denat; Alcohol Denat; Alcohol Denat.; ALCOHOL DENAT; Alcohol denat.; alcohol denat.; Alcohol Denat. (8.60% об.)',36,36),
  ('ING0129','Glucose','Glucose; GLUCOSE; glucose; Glucose(0.4PPM)',36,36),
  ('ING0130','Chlorphenesin','Chlorphenesin; CHLORPHENESIN',36,37),
  ('ING0131','Maltodextrin','Maltodextrin; maltodextrin; MALTODEXTRIN',36,37),
  ('ING0132','Decyl Glucoside','Decyl Glucoside; DECYL GLUCOSIDE; decyl glucoside; Decyl Glucoside*',35,35),
  ('ING0133','Magnesium nitrate','Magnesium nitrate; Magnesium Nitrate; magnesium nitrate; MAGNESIUM NITRATE',35,35),
  ('ING0134','Hydrolyzed Collagen','Hydrolyzed Collagen; hydrolyzed collagen; HYDROLYZED COLLAGEN; Hydrolyzed collagen*',35,35),
  ('ING0135','Trehalose','Trehalose; TREHALOSE; trehalose',35,35),
  ('ING0136','Dibutyl Adipate','Dibutyl Adipate; DIBUTYL ADIPATE; dibutyl adipate',35,35),
  ('ING0137','Behentrimonium Methosulfate','Behentrimonium Methosulfate; BEHENTRIMONIUM METHOSULFATE; behentrimonium methosulfate; Behentrimonium methosulfate',34,34),
  ('ING0138','Glutamic Acid','Glutamic Acid; Glutamic acid; glutamic acid',34,34),
  ('ING0139','Glycolic Acid','Glycolic Acid; GLYCOLIC ACID; glycolic acid; Glycolic acid; Glycolic Acid (AHA 17%)',34,34),
  ('ING0140','Caprylyl Methicone','Caprylyl Methicone; CAPRYLYL METHICONE; caprylyl methicone',34,34),
  ('ING0141','Myristyl Alcohol','Myristyl Alcohol; Myristyl alcohol; MYRISTYL ALCOHOL; myristyl alcohol',33,33),
  ('ING0142','C12-15 Alkyl Benzoate','C12-15 Alkyl Benzoate; C12-15 ALKYL BENZOATE; c12-15 alkyl benzoate; C12-15 alkyl benzoate; c12 -15 alkyl benzoate',33,33),
  ('ING0143','Magnesium chloride','Magnesium chloride; Magnesium Chloride; magnesium chloride; MAGNESIUM CHLORIDE',33,33),
  ('ING0144','Cholesterol','Cholesterol; CHOLESTEROL; cholesterol',33,33),
  ('ING0145','Sodium Hyaluronate Crosspolymer','Sodium Hyaluronate Crosspolymer; SODIUM HYALURONATE CROSSPOLYMER; Sodium Hyaluronate Crosspolymer (30 ppm); sodium hyaluronate crosspolymer; sodium Hyaluronate Crosspolymer',33,34),
  ('ING0146','Butylphenyl Methylpropional','Butylphenyl Methylpropional; butylphenyl methylpropional; BUTYLPHENYL METHYLPROPIONAL; Butylphenyl methylpropional',32,32),
  ('ING0147','BHT','BHT; Bht; bht',32,32),
  ('ING0148','Lauryl Glucoside','Lauryl Glucoside; LAURYL GLUCOSIDE; lauryl glucoside; lauryl glucosidе',32,32),
  ('ING0149','Sodium Acetylated Hyaluronate','Sodium Acetylated Hyaluronate; SODIUM ACETYLATED HYALURONATE; Sodium Acetylated Hyaluronate (1 ppm); sodium acetylated hyaluronate (0.1 ppm); sodium Acetylated Hyaluronate',32,32),
  ('ING0150','Tetrasodium Glutamate Diacetate','Tetrasodium Glutamate Diacetate; TETRASODIUM GLUTAMATE DIACETATE; tetrasodium glutamate diacetate',31,31),
  ('ING0151','Polyglyceryl-10 Laurate','Polyglyceryl-10 Laurate; POLYGLYCERYL-10 LAURATE',30,30),
  ('ING0152','Tetrasodium EDTA','Tetrasodium EDTA; tetrasodium edta; TETRASODIUM EDTA; Tetrasodium Edta; tetrasodium EDTA',29,29),
  ('ING0153','Houttuynia Cordata Extract','Houttuynia Cordata Extract; Houttuynia cordata Extract; HOUTTUYNIA CORDATA EXTRACT; Houttuynia Cordata Extract(77%); Houttuynia Cordata Extract (9800ppm)',29,29),
  ('ING0154','Coco-Caprylate/Caprate','Coco-Caprylate/Caprate; COCO-CAPRYLATE/CAPRATE; coco-caprylate/caprate; Coco Caprylate/Caprate; COCO CAPRYLATE CAPRATE; Coco-caprylate/caprate; Coco-caprylate / Caprate',29,29),
  ('ING0155','Polymethylsilsesquioxane','Polymethylsilsesquioxane; POLYMETHYLSILSESQUIOXANE; polymethylsilsesquioxane',29,29),
  ('ING0156','Aloe Barbadensis Leaf Extract','Aloe Barbadensis Leaf Extract; ALOE BARBADENSIS LEAF EXTRACT; aloe barbadensis leaf extract; ALOE ВARBADENSIS LEAF EXTRACT; Aloe Barbadensis (Aloe Vera) Leaf Extract',28,28),
  ('ING0157','Lysine','Lysine; LYSINE',28,28),
  ('ING0158','Ceteareth-20','Ceteareth-20; ceteareth-20; CETEARETH-20',28,28),
  ('ING0159','Dicaprylyl Carbonate','Dicaprylyl Carbonate; DICAPRYLYL CARBONATE; dicaprylyl carbonate; Dicaprylyl carbonate',28,28),
  ('ING0160','Citral','Citral; CITRAL',28,28),
  ('ING0161','Melia Azadirachta Leaf Extract','Melia Azadirachta Leaf Extract; Melia Azadirachta (Neem) Leaf Extract',28,28),
  ('ING0162','Sorbitan Olivate','Sorbitan Olivate; SORBITAN OLIVATE; sorbitan olivate',28,28),
  ('ING0163','Asiaticoside','Asiaticoside; ASIATICOSIDE',28,28),
  ('ING0164','Madecassoside','Madecassoside; MADECASSOSIDE; madecassoside',28,28),
  ('ING0165','Cocamide MEA','Cocamide MEA; cocamide mea; COCAMIDE MEA; Cocamide Mea',27,27),
  ('ING0166','Macadamia Ternifolia Seed Oil','Macadamia Ternifolia Seed Oil; macadamia ternifolia seed oil; MACADAMIA TERNIFOLIA SEED OIL; Macadamia Ternifolia Seed Oil (масло макадамии)',27,27),
  ('ING0167','Sodium Cocoyl Isethionate','Sodium Cocoyl Isethionate; SODIUM COCOYL ISETHIONATE; sodium cocoyl isethionate',27,27),
  ('ING0168','Hexylene Glycol','Hexylene Glycol; HEXYLENE GLYCOL; hexylene glycol',27,27),
  ('ING0169','Hydrolyzed Corn Protein','Hydrolyzed Corn Protein; hydrolyzed corn protein; HYDROLYZED CORN PROTEIN; Hydrolyzed corn protein',27,27),
  ('ING0170','Prunus Amygdalus Dulcis (Sweet Almond) Oil','Prunus Amygdalus Dulcis (Sweet Almond) Oil; Prunus Amygdalus Dulcis Oil; PRUNUS AMYGDALUS DULCIS OIL; PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL; Prunus Amygdalus Dulcis (Sweer Almond) Oil; prunus amygdalus dulcis oil; Prunus Amygdalus Dulcis Oil (масло миндальное)',27,27),
  ('ING0171','PEG-7 Glyceryl Cocoate','PEG-7 Glyceryl Cocoate; PEG-7 GLYCERYL COCOATE; Peg-7 Glyceryl Cocoate; PEG-7-Glyceryl Cocoate; peg-7 glyceryl cocoate',27,27),
  ('ING0172','Sodium Polyacrylate','Sodium Polyacrylate; SODIUM POLYACRYLATE; sodium polyacrylate',27,27),
  ('ING0173','Xylitol','Xylitol; XYLITOL; Xylitol(1.2PPM); xylitol',27,27),
  ('ING0174','Polyquaternium-37','Polyquaternium-37; POLYQUATERNIUM-37; polyquaternium-37',26,26),
  ('ING0175','Persea Gratissima (Avocado) Oil','Persea Gratissima (Avocado) Oil; PERSEA GRATISSIMA (AVOCADO) OIL; Persea Gratissima Oil; Persea Gratissima (Avocado) Oil*; PERSEA GRATISSIMA OIL; persea gratissima (avocado) oil; Persea gratissima (avocado) oil; persea gratissima oil',26,26),
  ('ING0176','Trisodium Ethylenediamine Disuccinate','Trisodium Ethylenediamine Disuccinate; TRISODIUM ETHYLENEDIAMINE DISUCCINATE; trisodium ethylenediamine disuccinate',26,27),
  ('ING0177','Copper Tripeptide-1','Copper Tripeptide-1; COPPER TRIPEPTIDE-1; copper tripeptide-1; Copper Tripeptide-1(3ppb)',26,27),
  ('ING0178','Cyclohexasiloxane','Cyclohexasiloxane; CYCLOHEXASILOXANE; cyclohexasiloxane',26,26),
  ('ING0179','Sorbitan Isostearate','Sorbitan Isostearate; SORBITAN ISOSTEARATE',26,26),
  ('ING0180','Phenyl Trimethicone','Phenyl Trimethicone; PHENYL TRIMETHICONE; phenyl trimethicone',25,25),
  ('ING0181','Rosmarinus Officinalis (Rosemary) Leaf Extract','Rosmarinus Officinalis (Rosemary) Leaf Extract; Rosmarinus Officinalis Leaf Extract; ROSMARINUS OFFICINALIS (ROSEMARY) LEAF EXTRACT; Rosmarinus officinalis leaf extract; rosmarinus officinalis (rosemary) leaf extract',25,25),
  ('ING0182','Cetearyl Olivate','Cetearyl Olivate; CETEARYL OLIVATE; cetearyl olivate',25,25),
  ('ING0183','Sodium Ascorbyl Phosphate','Sodium Ascorbyl Phosphate; sodium ascorbyl phosphate; SODIUM ASCORBYL PHOSPHATE; SODIUM ASCORBYL PHOSPHATE (VITAMIN C); Sodium Ascorbyl Phosphate (витамин С)',25,25),
  ('ING0184','Triethanolamine','Triethanolamine; TRIETHANOLAMINE; triethanolamine',25,25),
  ('ING0185','Disodium Laureth Sulfosuccinate','Disodium Laureth Sulfosuccinate; DISODIUM LAURETH SULFOSUCCINATE; disodium laureth sulfosuccinate; Disodium laureth sulfosuccinate',24,24),
  ('ING0186','Leuconostoc/Radish Root Ferment Filtrate','Leuconostoc/Radish Root Ferment Filtrate; LEUCONOSTOC/RADISH ROOT FERMENT FILTRATE; Leuconostoc/ Radish Root Ferment Filtrate; Leuconostoc/radish root ferment filtrate; Leuconostoc/radish Root Ferment Filtrate; leuconostoc/radish root ferment filtrate; Leuconostoc/Radish Root Ferment Filtrate*; Leuconostoc/Radish Root Ferment Filtrate**',24,24),
  ('ING0187','PEG-100 Stearate','PEG-100 Stearate; PEG-100 STEARATE; Peg-100 Stearate; peg-100 stearate',24,24),
  ('ING0188','Caffeine','Caffeine; CAFFEINE; caffeine; Cаffeine',24,25),
  ('ING0189','Chamomilla Recutita (Matricaria) Flower Extract','Chamomilla Recutita (Matricaria) Flower Extract; Chamomilla Recutita Flower Extract; Chamomilla recutita Flower Extract; CHAMOMILLA RECUTITA FLOWER EXTRACT; CHAMOMILLA RECUTITA (MATRICARIA) FLOWER EXTRACT; Chamomilla recutita (Matricaria) Flower Extract; chamomilla recutita (matricaria) flower extract',24,24),
  ('ING0190','Glyceryl Caprylate','Glyceryl Caprylate; GLYCERYL CAPRYLATE; glyceryl caprylate',24,24),
  ('ING0191','Sorbitan Oleate','Sorbitan Oleate; SORBITAN OLEATE; sorbitan oleate',24,24),
  ('ING0192','Bisabolol','Bisabolol; BISABOLOL; bisabolol',24,24),
  ('ING0193','Butyl Methoxydibenzoylmethane','Butyl Methoxydibenzoylmethane; butyl methoxydibenzoylmethane; BUTYL METHOXYDIBENZOYLMETHANE; Butyl methoxydibenzoylmethane',24,24),
  ('ING0194','Sodium Phytate','Sodium Phytate; SODIUM PHYTATE; sodium phytate',24,24),
  ('ING0195','Madecassic Acid','Madecassic Acid; MADECASSIC ACID',24,24),
  ('ING0196','Ethylhexyl Salicylate','Ethylhexyl Salicylate; ETHYLHEXYL SALICYLATE; ethylhexyl salicylate',24,24),
  ('ING0197','Beta-Glucan','Beta-Glucan; Beta-glucan; BETA-GLUCAN; Beta- Glucan',24,24),
  ('ING0198','PCA','PCA; Pca; pca',23,23),
  ('ING0199','Hydrogenated Polyisobutene','Hydrogenated Polyisobutene; HYDROGENATED POLYISOBUTENE',23,23),
  ('ING0200','GLYCERYL OLEATE','GLYCERYL OLEATE; Glyceryl Oleate; glyceryl oleate',23,23),
  ('ING0201','Gluconolactone','Gluconolactone; GLUCONOLACTONE; gluconolactone',23,23),
  ('ING0202','Glycine Soja (Soybean) Oil','Glycine Soja (Soybean) Oil; GLYCINE SOJA (SOYBEAN) OIL; Glycine Soja Oil; Glycine Soja (Soybean) Oil*; GLYCINE SOJA OIL; Glycine Soja (soybean) Oil',23,23),
  ('ING0203','Palmitic Acid','Palmitic Acid; PALMITIC ACID; palmitic acid; Palmitic acid',23,23),
  ('ING0204','Retinol','Retinol; Retinol (Vitamin A); RETINOL; Retinol (0.1 %); Retinol(475ppm); retinol (461 ppb); Retinol(0.1%); Retinol (10 ppm)',23,23),
  ('ING0205','Zinc Oxide','Zinc Oxide; ZINC OXIDE; ZINC OXIDE (NANO); zinc oxide',23,23),
  ('ING0206','Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer','Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer; HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER; HYDROXYETHYL ACRYLATE / SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER; Hydroxyethyl Acrylate/ Sodium Acryloyldimethyl Taurate Copolymer',23,23),
  ('ING0207','Vitis Vinifera (Grape) Seed Oil','Vitis Vinifera (Grape) Seed Oil; Vitis vinifera seed oil; Vitis Vinifera (Grape) Seed Oil*; VITIS VINIFERA (GRAPE) SEED OIL',22,22),
  ('ING0208','Trideceth-6','Trideceth-6; TRIDECETH-6; trideceth-6',22,22),
  ('ING0209','Glycyrrhiza Glabra (Licorice) Root Extract','Glycyrrhiza Glabra (Licorice) Root Extract; Glycyrrhiza Glabra Root Extract; GLYCYRRHIZA GLABRA ROOT EXTRACT; Glycyrrhiza Glabra (licorice) Root Extract; GLYCYRRHIZA GLABRA (LICORICE) ROOT EXTRACT',22,22),
  ('ING0210','Polysorbate 80','Polysorbate 80; Polysorbate-80; POLYSORBATE 80; POLYSORBATE-80; polysorbate-80',22,22),
  ('ING0211','Water/Aqua/Eau','Water/Aqua/Eau; Water\Aqua\Eau; Water/ Aqua/ Eau; Water/aqua/eau; WATER / AQUA / EAU; WATER\AQUA\EAU; water/aqua/eau; WATER / AQUA /EAU',22,22),
  ('ING0212','Rosmarinus Officinalis (Rosemary) Leaf Oil','Rosmarinus Officinalis (Rosemary) Leaf Oil; Rosmarinus Officinalis (Rosemary) Leaf Oil*; ROSMARINUS OFFICINALIS (ROSEMARY) LEAF OIL',22,22),
  ('ING0213','Curcuma Longa (Turmeric) Root Extract','Curcuma Longa (Turmeric) Root Extract; Curcuma Longa (turmeric) Root Extract; CURCUMA LONGA (TUMERIC) ROOT EXTRACT; Curcuma Longa Root Extract',22,22),
  ('ING0214','Asiatic Acid','Asiatic Acid; ASIATIC ACID',22,22),
  ('ING0215','Acetyl Hexapeptide-8','Acetyl Hexapeptide-8; Acetyl Hexapeptide-8(2ppb); Acetyl hexapeptide-8',22,23),
  ('ING0216','Hydrolyzed Sodium Hyaluronate','Hydrolyzed Sodium Hyaluronate; HYDROLYZED SODIUM HYALURONATE; Hydrolyzed Sodium Hyaluronate (30 ppm)',22,22),
  ('ING0217','Melia Azadirachta Flower Extract','Melia Azadirachta Flower Extract',22,22),
  ('ING0218','Isododecane','Isododecane; ISODODECANE; isododecane',21,21),
  ('ING0219','Urea','Urea; UREA; urea',21,21),
  ('ING0220','Olea Europaea (Olive) Fruit Oil','Olea Europaea (Olive) Fruit Oil; OLEA EUROPAEA (OLIVE) FRUIT OIL; olea europaea fruit oil; Olea europaea (olive) fruit oil; Olea Europaea (Olive) Fruit Oil*',21,21),
  ('ING0221','Octyldodecanol','Octyldodecanol; octyldodecanol; OCTYLDODECANOL',21,21),
  ('ING0222','Dipotassium Glycyrrhizate','Dipotassium Glycyrrhizate',21,21),
  ('ING0223','Purified Water','Purified Water; Purified water; purified water; PURIFIED WATER',21,21),
  ('ING0224','Biosaccharide Gum-1','Biosaccharide Gum-1; Biosaccharide gum-1; BIOSACCHARIDE GUM-1',21,22),
  ('ING0225','Sodium Stearoyl Glutamate','Sodium Stearoyl Glutamate; SODIUM STEAROYL GLUTAMATE',21,22),
  ('ING0226','Cetyl Palmitate','Cetyl Palmitate; cetyl palmitate; CETYL PALMITATE',20,20),
  ('ING0227','Retinyl Palmitate','Retinyl Palmitate; RETINYL PALMITATE; Retinyl (Vitamin A) Palmitate; retinyl palmitate; Retinyl Palmitate(2.36%); retinyl palmitate (10000 IU/g)',20,20),
  ('ING0228','Benzyl Benzoate','Benzyl Benzoate; BENZYL BENZOATE; benzyl benzoate; Benzyl benzoate',20,20),
  ('ING0229','Steartrimonium Chloride','Steartrimonium Chloride; STEARTRIMONIUM CHLORIDE; Steartrimonium chloride; steartrimonium chloride',20,20),
  ('ING0230','Leucine','Leucine',20,20),
  ('ING0231','Sorbic Acid','Sorbic Acid; SORBIC ACID',20,21),
  ('ING0232','Sodium Coco-Sulfate','Sodium Coco-Sulfate; SODIUM COCO-SULFATE; Sodium Coco Sulfate; SODIUM COCO SULFATE; sodium coco sulfate',20,20),
  ('ING0233','Polysorbate 60','Polysorbate 60; POLYSORBATE 60; polysorbate 60; Polysorbate-60; POLYSORBATE-60',20,20),
  ('ING0234','Ethoxydiglycol','Ethoxydiglycol; ETHOXYDIGLYCOL; ethoxydiglycol',20,21),
  ('ING0235','Polyacrylate Crosspolymer-6','Polyacrylate Crosspolymer-6; polyacrylate crosspolymer-6; POLYACRYLATE CROSSPOLYMER-6',20,20),
  ('ING0236','Disteardimonium Hectorite','Disteardimonium Hectorite; DISTEARDIMONIUM HECTORITE',20,20),
  ('ING0237','Glutathione','Glutathione; Glutathione(L)',20,20),
  ('ING0238','Dimethicone/Vinyl Dimethicone Crosspolymer','Dimethicone/Vinyl Dimethicone Crosspolymer; DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER; Dimethicone/vinyl Dimethicone Crosspolymer',20,20),
  ('ING0239','Aluminum Hydroxide','Aluminum Hydroxide; ALUMINUM HYDROXIDE; aluminum hydroxide',20,20),
  ('ING0240','Phytosphingosine','Phytosphingosine; PHYTOSPHINGOSINE; phytosphingosine',20,20),
  ('ING0241','Trideceth-10','Trideceth-10; TRIDECETH-10; trideceth-10',19,19),
  ('ING0242','Zea Mays (Corn) Starch','Zea Mays (Corn) Starch; ZEA MAYS STARCH; ZEA MAYS (CORN) STARCH; Zea mays (corn) starch; Zea Mays Starch; Zea mays starch',19,19),
  ('ING0243','Urtica Dioica Leaf Extract','Urtica Dioica Leaf Extract; urtica dioica leaf extract; Urtica dioica Leaf Extract; URTICA DIOICA (NETTLE) LEAF EXTRACT; Urtica Dioica (Nettle) Leaf Extract; Urtica Dioica (Nettle) Leaf Extract*; URTICA DIOICA LEAF EXTRACT',19,20),
  ('ING0244','Hydroxyethyl Urea','Hydroxyethyl Urea; HYDROXYETHYL UREA; Hydroxyethyl urea',19,19),
  ('ING0245','Cocamide DEA','Cocamide DEA; cocamide DEA; COCAMIDE DEA; cocamide dea',19,19),
  ('ING0246','PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE','PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE; Pentaerythrityl Tetra-di-t-butyl Hydroxyhydrocinnamate; Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate; pentaerythrityl tetra-di-t-butyl hydroxyhydrocinnamate; Pentaerythrityl tetra-di-t-butyl hydroxyhydrocinnamate; Pentaerythrityl Tetra-Di-t-Butyl Hydroxyhydrocinnamate',19,19),
  ('ING0247','Dextrin','Dextrin; DEXTRIN; dextrin',19,19),
  ('ING0248','Hydroxypropyl Guar Hydroxypropyltrimonium Chloride','Hydroxypropyl Guar Hydroxypropyltrimonium Chloride; HYDROXYPROPYL GUAR HYDROXYPROPYLTRIMONIUM CHLORIDE; Hydroxypropyl guar hydroxypropyltrimonium chloride; hydroxypropyl guar hydroxypropyltrimonium chloride',19,19),
  ('ING0249','Glycereth-26','Glycereth-26; GLYCERETH-26',19,19),
  ('ING0250','Triethoxycaprylylsilane','Triethoxycaprylylsilane; TRIETHOXYCAPRYLYLSILANE',19,19),
  ('ING0251','Methionine','Methionine',18,18),
  ('ING0252','Palmitoyl Tripeptide-1','Palmitoyl Tripeptide-1; PALMITOYL TRIPEPTIDE-1; Palmitoyl Tripeptide-1(0.5ppb)',18,19),
  ('ING0253','Isohexadecane','Isohexadecane; ISOHEXADECANE',18,18),
  ('ING0254','Ceramide AP','Ceramide AP; CERAMIDE AP; ceramide AP',18,18),
  ('ING0255','Sodium Gluconate','Sodium Gluconate; SODIUM GLUCONATE; Sodium gluconate; sodium gluconate',18,18),
  ('ING0256','Ethylhexyl Palmitate','Ethylhexyl Palmitate; ethylhexyl palmitate; ETHYLHEXYL PALMITATE',18,18),
  ('ING0257','Portulaca Oleracea Extract','Portulaca Oleracea Extract; PORTULACA OLERACEA EXTRACT',18,18),
  ('ING0258','Fructooligosaccharides','Fructooligosaccharides; FRUCTOOLIGOSACCHARIDES',18,18),
  ('ING0259','Potassium Cetyl Phosphate','Potassium Cetyl Phosphate; potassium cetyl phosphate; POTASSIUM CETYL PHOSPHATE',18,18),
  ('ING0260','Sodium Methyl Cocoyl Taurate','Sodium Methyl Cocoyl Taurate; SODIUM METHYL COCOYL TAURATE; sodium methyl cocoyl taurate',17,18),
  ('ING0261','Acetic Acid','Acetic Acid; ACETIC ACID; acetic acid',17,17),
  ('ING0262','Cetyl Esters','Cetyl Esters; CETYL ESTERS; Cetyl esters; cetyl esters',17,17),
  ('ING0263','Linoleic Acid','Linoleic Acid; LINOLEIC ACID',17,17),
  ('ING0264','Isononyl Isononanoate','Isononyl Isononanoate; ISONONYL ISONONANOATE; isononyl isononanoate',17,18),
  ('ING0265','Magnesium Sulfate','Magnesium Sulfate; magnesium sulfate; MAGNESIUM SULFATE',17,17),
  ('ING0266','Potassium Hydroxide','Potassium Hydroxide; POTASSIUM HYDROXIDE; potassium hydroxide',17,17),
  ('ING0267','Saccharide Isomerate','Saccharide Isomerate; SACCHARIDE ISOMERATE; saccharide isomerate',17,17),
  ('ING0268','Isopentyldiol','Isopentyldiol; ISOPENTYLDIOL',17,17),
  ('ING0269','Anhydroxylitol','Anhydroxylitol; ANHYDROXYLITOL; Anhydroxylitol (2.8PPM); Anhydroxylitol(2.8PPM); anhydroxylitol',17,17),
  ('ING0270','Sodium Cocoamphoacetate','Sodium Cocoamphoacetate; sodium cocoamphoacetate; SODIUM COCOAMPHOACETATE',17,17),
  ('ING0271','Melaleuca Alternifolia (Tea Tree) Leaf Oil','Melaleuca Alternifolia (Tea Tree) Leaf Oil; Melaleuca Alternifolia Leaf Oil; Melaleuca Alternifolia (Tea Tree) Leaf Oil*; MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL*; Melaleuca Alternifolia (tea Tree) Leaf Oil',17,17),
  ('ING0272','Lactobacillus Ferment','Lactobacillus Ferment; LACTOBACILLUS FERMENT',17,17),
  ('ING0273','Bifida Ferment Lysate','Bifida Ferment Lysate; Bifida Ferment Lysate (66.94%); Bifida Ferment Lysate (1000 ppm); Bifida Ferment Lysate(85%); Bifida Ferment Lysate(23.59%)',17,17),
  ('ING0274','Polyisobutene','Polyisobutene; POLYISOBUTENE',17,17),
  ('ING0275','3-O-Ethyl Ascorbic Acid','3-O-Ethyl Ascorbic Acid; 3-O-ETHYL ASCORBIC ACID; 3-O Ethyl Ascorbic Acid; 3-o-ethyl ascorbic acid; 3-O-Ethyl Ascorbic Acid (107ppm)',17,17),
  ('ING0276','Corallina Officinalis Extract','Corallina Officinalis Extract',17,17),
  ('ING0277','Benzophenone-4','Benzophenone-4; benzophenone-4',16,16),
  ('ING0278','Prunus Armeniaca (Apricot) Kernel Oil','Prunus Armeniaca (Apricot) Kernel Oil; Prunus Armeniaca Kernel Oil; PRUNUS ARMENIACA (APRICOT) KERNEL OIL; prunus armeniaca kernel oil',16,16),
  ('ING0279','Diazolidinyl Urea','Diazolidinyl Urea; DIAZOLIDINYL UREA',16,16),
  ('ING0280','Cocamidopropyl Hydroxysultaine','Cocamidopropyl Hydroxysultaine; COCAMIDOPROPYL HYDROXYSULTAINE',16,16),
  ('ING0281','Zinc PCA','Zinc PCA; ZINC PCA; zinc PCA; Zinc PCA(5.7%); Zinc Pca',16,16),
  ('ING0282','Tyrosine','Tyrosine',16,16),
  ('ING0283','Hydrolyzed Rice Protein','Hydrolyzed Rice Protein; Hydrolyzed Rice Protein**; hydrolyzed rice protein; HYDROLYZED RICE PROTEIN',16,16),
  ('ING0284','Quaternium-80','Quaternium-80; quaternium-80; QUATERNIUM-80',16,16),
  ('ING0285','YELLOW 5 (CI 19140)','YELLOW 5 (CI 19140); Yellow 5; Yellow 5 (Ci 19140); yellow 5 (ci19140); Yellow 5 (CI 19140); yellow 5',16,16),
  ('ING0286','Pyrus Malus (Apple) Fruit Extract','Pyrus Malus (Apple) Fruit Extract; Pyrus Malus (Apple) Fruit Extract*; pyrus malus (apple) fruit extract',16,16),
  ('ING0287','Glyceryl Stearate Citrate','Glyceryl Stearate Citrate; glyceryl stearate citrate',16,16),
  ('ING0288','Lavandula Angustifolia (Lavender) Oil','Lavandula Angustifolia (Lavender) Oil; Lavandula Angustifolia Oil; LAVANDULA ANGUSTIFOLIA (LAVENDER) OIL; Lavandula angustifolia oil; Lavandula Angustifolia (Lavender) Oil*',16,16),
  ('ING0289','Isopropyl Palmitate','Isopropyl Palmitate; ISOPROPYL PALMITATE; Isopropyl palmitate; isopropyl palmitate',16,16),
  ('ING0290','Phospholipids','Phospholipids; PHOSPHOLIPIDS',16,16),
  ('ING0291','Xylitylglucoside','Xylitylglucoside; XYLITYLGLUCOSIDE; Xylitylglucoside(4PPM)',16,16),
  ('ING0292','Ocimum Sanctum Leaf Extract','Ocimum Sanctum Leaf Extract; Ocimum Sanctum (Tulsi) Leaf Extract',16,16),
  ('ING0293','CAMELLIA JAPONICA SEED OIL','CAMELLIA JAPONICA SEED OIL; Camellia Japonica Seed Oil; Camellia Japonica (Tsubaki) Seed Oil; camellia japonica seed oil; Camellia japonica seed oil',16,17),
  ('ING0294','Caprylyl/Capryl Glucoside','Caprylyl/Capryl Glucoside; CAPRYLYL/CAPRYL GLUCOSIDE; Caprylyl/ Capryl Glucoside; Caprylyl/capryl Glucoside',16,16),
  ('ING0295','Bakuchiol','Bakuchiol; BAKUCHIOL; Bakuchiol(100ppm); Bakuchiol (1000 ppm); Bakuchiol (10000 ppm)',16,16),
  ('ING0296','Cyanocobalamin','Cyanocobalamin',16,16),
  ('ING0297','Ceramide EOP','Ceramide EOP; CERAMIDE EOP',16,16),
  ('ING0298','Dimethyl Isosorbide','Dimethyl Isosorbide; DIMETHYL ISOSORBIDE; Dimethyl isosorbide',16,16),
  ('ING0299','Disodium Cocoamphodiacetate','Disodium Cocoamphodiacetate; DISODIUM COCOAMPHODIACETATE; disodium cocoamphodiacetate; Disodium cocoamphodiacetate',15,15),
  ('ING0300','Cysteine','Cysteine',15,15),
  ('ING0301','Cetearyl Glucoside','Cetearyl Glucoside; CETEARYL GLUCOSIDE; cetearyl glucoside',15,15),
  ('ING0302','Octocrylene','Octocrylene; OCTOCRYLENE; octocrylene',15,15),
  ('ING0303','PVP','PVP',15,15),
  ('ING0304','Beta-Sitosterol','Beta-Sitosterol; BETA-SITOSTEROL; Beta-sitosterol; Beta Sitosterol',15,15),
  ('ING0305','Polyglyceryl-3 Methylglucose Distearate','Polyglyceryl-3 Methylglucose Distearate; POLYGLYCERYL-3 METHYLGLUCOSE DISTEARATE',15,15),
  ('ING0306','Ferulic Acid','Ferulic Acid; ferulic acid',15,15),
  ('ING0307','Hydroxypropyltrimonium Hyaluronate','Hydroxypropyltrimonium Hyaluronate; HYDROXYPROPYLTRIMONIUM HYALURONATE; hydroxypropyltrimonium hyaluronate; Hydroxypropyltrimonium Hyaluronate (30 ppm)',15,15),
  ('ING0308','Moringa Oleifera Seed Oil','Moringa Oleifera Seed Oil; Moringa oleifera seed oil; MORINGA OLEIFERA SEED OIL',14,14),
  ('ING0309','Hydroxypropyl Guar','Hydroxypropyl Guar; HYDROXYPROPYL GUAR',14,14),
  ('ING0310','Inulin','Inulin; INULIN; inulin',14,14),
  ('ING0311','Cetyl Ethylhexanoate','Cetyl Ethylhexanoate; cetyl ethylhexanoate',14,14),
  ('ING0312','Amyl Cinnamal','Amyl Cinnamal; amyl cinnamal; AMYL CINNAMAL',14,15),
  ('ING0313','COCO-BETAINE','COCO-BETAINE; coco-betaine; Coco betaine; Coco-Betaine; Coco-betaine',14,14),
  ('ING0314','Mica','Mica; mica; MICA (CI 77019); MICA; MICA (МИКРОНИЗИРОВАННАЯ СЛЮДА)',14,16),
  ('ING0315','Cellulose Gum','Cellulose Gum; CELLULOSE GUM',14,14),
  ('ING0316','Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer','Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer; SODIUM ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER; Sodium acrylate/Sodium Acryloyldimethyl Taurate Copolymer',14,14),
  ('ING0317','Sodium Salicylate','Sodium Salicylate; sodium salicylate; SODIUM SALICYLATE',13,13),
  ('ING0318','Acrylates Copolymer','Acrylates Copolymer; ACRYLATES COPOLYMER',13,13),
  ('ING0319','Tartaric Acid','Tartaric Acid; TARTARIC ACID; tartaric acid',13,13),
  ('ING0320','Pyridoxine Hcl','Pyridoxine Hcl; PYRIDOXINE HCl; Pyridoxine HCl; pyridoxine hcl; PYRIDOXINE HCL; Pyridoxine HCL; pyridoxine HCL',13,13),
  ('ING0321','Salvia Officinalis (Sage) Leaf Extract','Salvia Officinalis (Sage) Leaf Extract; Salvia Officinalis Leaf Extract; Salvia officinalis Leaf Extract; salvia officinalis leaf extract; salvia officinalis (sage) leaf extract',13,13),
  ('ING0322','Arctium Lappa Root Extract','Arctium Lappa Root Extract; Arctium lappa Root Extract; arctium lappa root extract',13,13),
  ('ING0323','Laureth-4','Laureth-4; LAURETH-4; laureth-4',13,13),
  ('ING0324','DICAPRYLYL ETHER','DICAPRYLYL ETHER; Dicaprylyl Ether',13,13),
  ('ING0325','Malic Acid','Malic Acid; MALIC ACID; malic acid; Malic acid',13,13),
  ('ING0326','Glyceryl Stearate SE','Glyceryl Stearate SE; GLYCERYL STEARATE SE; Glyceryl Stearate Se',13,13),
  ('ING0327','VP/VA Copolymer','VP/VA Copolymer; VP/VA COPOLYMER; Vp/Va Copolymer; VP/VA Сopolymer',13,13),
  ('ING0328','Cocamide MIPA','Cocamide MIPA; Cocamide Mipa; COCAMIDE MIPA; cocamide mipa',13,13),
  ('ING0329','Macadamia Integrifolia Seed Oil','Macadamia Integrifolia Seed Oil; Macadamia integrifolia seed oil; MACADAMIA INTEGRIFOLIA SEED OIL',13,13),
  ('ING0330','Homosalate','Homosalate; HOMOSALATE; homosalate',13,13),
  ('ING0331','Polysilicone-15','Polysilicone-15; Polysilicone- 15',13,13),
  ('ING0332','Chlorella Vulgaris Extract','Chlorella Vulgaris Extract; CHLORELLA VULGARIS EXTRACT; Chlorella Vulgaris (Plankton) Extract',13,14),
  ('ING0333','Hibiscus Sabdariffa Flower Extract','Hibiscus Sabdariffa Flower Extract; Hibiscus Sabdariffa (Hibiscus) Flower Extract; Hibiscus Sabdariffa (Hibiscus) Flower Extract*',13,13),
  ('ING0334','Scutellaria Baicalensis Root Extract','Scutellaria Baicalensis Root Extract; Scutellaria Baicalensis (Baikal Skullcap) Root Extract',13,13),
  ('ING0335','Palmitoyl Tripeptide-5','Palmitoyl Tripeptide-5; PALMITOYL TRIPEPTIDE-5; palmitoyl tripeptide-5; Palmitoyl Tripeptide-5(11ppb)',13,13),
  ('ING0336','Terephthalylidene Dicamphor Sulfonic Acid','Terephthalylidene Dicamphor Sulfonic Acid; TEREPHTHALYLIDENE DICAMPHOR SULFONIC ACID; terephthalylidene dicamphor sulfonic acid',13,13),
  ('ING0337','Methyl Methacrylate Crosspolymer','Methyl Methacrylate Crosspolymer; METHYL METHACRYLATE CROSSPOLYMER',13,13),
  ('ING0338','Polyglyceryl-3 Distearate','Polyglyceryl-3 Distearate; polyglyceryl-3 distearate',13,13),
  ('ING0339','Sodium Acrylates Copolymer','Sodium Acrylates Copolymer',13,13),
  ('ING0340','Citrus Aurantium Bergamia (Bergamot) Fruit Oil','Citrus Aurantium Bergamia (Bergamot) Fruit Oil; Citrus Aurantium Bergamia Fruit Oil; Citrus Aurantium Bergamia (Bergamot) fruit Oil',13,13),
  ('ING0341','Sodium Acetate','Sodium Acetate; SODIUM ACETATE; sodium acetate',12,12),
  ('ING0342','Distearoylethyl Hydroxyethylmonium Methosulfate','Distearoylethyl Hydroxyethylmonium Methosulfate; DISTEAROYLETHYL HYDROXYETHYLMONIUM METHOSULFATE; distearoylethyl hydroxyethylmonium methosulfate',12,12),
  ('ING0343','Oryza Sativa (Rice) Extract','Oryza Sativa (Rice) Extract; Oryza Sativa Extract; Oryza Sativa (Rice) Extract*; oryza sativa (rice) extract',12,14),
  ('ING0344','Cyclomethicone','Cyclomethicone; cyclomethicone; CYCLOMETHICONE',12,12),
  ('ING0345','Limnanthes Alba (Meadowfoam) Seed Oil','Limnanthes Alba (Meadowfoam) Seed Oil; LIMNANTHES ALBA (MEADOWFOAM) SEED OIL; Limnanthes Alba (Meadowfoam) Seed Oil*; Limnanthes Alba Seed Oil',12,12),
  ('ING0346','Sodium Lauroyl Methyl Isethionate','Sodium Lauroyl Methyl Isethionate; SODIUM LAUROYL METHYL ISETHIONATE; sodium lauroyl methyl isethionate; Sodium Lauroyl Methyl Isethionate**',12,12),
  ('ING0347','Palmitoyl Pentapeptide-4','Palmitoyl Pentapeptide-4; Palmitoyl Pentapeptide-4(1.1ppb)',12,12),
  ('ING0348','Lactobacillus Ferment Lysate','Lactobacillus Ferment Lysate; LACTOBACILLUS FERMENT LYSATE',12,12),
  ('ING0349','CI 19140','CI 19140; ci 19140; CI 19140 (Yellow 5)',12,12),
  ('ING0350','SODIUM DILAURAMIDOGLUTAMIDE LYSINE','SODIUM DILAURAMIDOGLUTAMIDE LYSINE; Sodium Dilauramidoglutamide Lysine',12,13),
  ('ING0351','Eclipta Prostrata Extract','Eclipta Prostrata Extract',12,12),
  ('ING0352','Ethylhexyl Olivate','Ethylhexyl Olivate; ETHYLHEXYL OLIVATE',12,12),
  ('ING0353','Laureth-2','Laureth-2; LAURETH-2',12,12),
  ('ING0354','Salix Alba (Willow) Bark Extract','Salix Alba (Willow) Bark Extract; Salix Alba Bark Extract; SALIX ALBA (WILLOW) BARK EXTRACT; Salix Alba (Willow) Bark Extract(10%)',12,12),
  ('ING0355','Panax Ginseng Root Extract','Panax Ginseng Root Extract; panax ginseng root extract',12,12),
  ('ING0356','Polyglyceryl-10 Myristate','Polyglyceryl-10 Myristate; Polyglyceryl-10 myristate',12,12),
  ('ING0357','Sodium Lauroyl Lactylate','Sodium Lauroyl Lactylate; SODIUM LAUROYL LACTYLATE',12,12),
  ('ING0358','ROYAL JELLY EXTRACT','ROYAL JELLY EXTRACT; Royal Jelly Extract',12,13),
  ('ING0359','GLYCINE SOJA (SOYBEAN) SEED EXTRACT','GLYCINE SOJA (SOYBEAN) SEED EXTRACT; Glycine Soja (Soybean) Seed Extract; Glycine Soja Seed Extract',12,13),
  ('ING0360','Sodium Lauroyl Glutamate','Sodium Lauroyl Glutamate; Sodium lauroyl glutamate',12,12),
  ('ING0361','Fructose','Fructose',12,12),
  ('ING0362','T-Butyl Alcohol','T-Butyl Alcohol; t-Butyl Alcohol; t-butyl Alcohol; t-butyl alcohol; T-BUTYL ALCOHOL',12,13),
  ('ING0363','Potassium Hyaluronate','Potassium Hyaluronate; POTASSIUM HYALURONATE; Potassium Hyaluronate (30 ppm)',12,12),
  ('ING0364','Hydrogenated Polydecene','Hydrogenated Polydecene; hydrogenated polydecene; hydrogenated Polydecene',12,12),
  ('ING0365','Quaternium-87','Quaternium-87; QUATERNIUM-87',11,11),
  ('ING0366','Centella Asiatica Leaf Extract','Centella Asiatica Leaf Extract; Centella Asiatica (Gotu Kola) Leaf Extract',11,11),
  ('ING0367','Diglycerin','Diglycerin; DIGLYCERIN',11,11),
  ('ING0368','Behenamidopropyl Dimethylamine','Behenamidopropyl Dimethylamine; BEHENAMIDOPROPYL DIMETHYLAMINE; behenamidopropyl dimethylamine',11,11),
  ('ING0369','Keratin Amino Acids','Keratin Amino Acids; Keratin amino acids; Keratin Amino Acids*; keratin amino acids',11,11),
  ('ING0370','PEG-60 HYDROGENATED CASTOR OIL','PEG-60 HYDROGENATED CASTOR OIL; PEG-60 Hydrogenated Castor Oil; peg-60 hydrogenated castor oil; PEG-60 hydrogenated castor oil',11,12),
  ('ING0371','PARAFFINUM LIQUIDUM','PARAFFINUM LIQUIDUM; Paraffinum Liquidum; PARAFFINUM LIQUIDUM (MINERAL OIL); paraffinum liquidum',11,11),
  ('ING0372','Sodium Lauryl Sulfate','Sodium Lauryl Sulfate; SODIUM LAURYL SULFATE; sodium lauryl sulfate',11,11),
  ('ING0373','Sodium Lauroyl Sarcosinate','Sodium Lauroyl Sarcosinate; sodium lauroyl sarcosinate; SODIUM LAUROYL SARCOSINATE',11,11),
  ('ING0374','Rosa Canina Fruit Oil','Rosa Canina Fruit Oil; ROSA CANINA FRUIT OIL; rosa canina fruit oil; Rosa Canina (Rose Hip) Fruit Oil (Organic)',11,11),
  ('ING0375','Sodium Cocoyl Glutamate','Sodium Cocoyl Glutamate; sodium cocoyl glutamate; SODIUM COCOYL GLUTAMATE',11,11),
  ('ING0376','PEG-8','PEG-8',11,11),
  ('ING0377','Glycolipids','Glycolipids; glycolipids; GLYCOLIPIDS',11,11),
  ('ING0378','Vaccinium Macrocarpon (Cranberry) Fruit Extract','Vaccinium Macrocarpon (Cranberry) Fruit Extract; Vaccinium Macrocarpon Fruit Extract; VACCINIUM MACROCARPON FRUIT EXTRACT',11,11),
  ('ING0379','Alpha-Glucan Oligosaccharide','Alpha-Glucan Oligosaccharide; ALPHA-GLUCAN OLIGOSACCHARIDE; Alpha-glucan Oligosaccharide; Alpha-glucan oligosaccharide',11,11),
  ('ING0380','Piroctone Olamine','Piroctone Olamine; PIROCTONE OLAMINE',11,11),
  ('ING0381','Ascorbyl Palmitate','Ascorbyl Palmitate; ASCORBYL PALMITATE; ascorbyl palmitate',11,11),
  ('ING0382','Riboflavin','Riboflavin; riboflavin; RIBOFLAVIN',11,11),
  ('ING0383','Sclerotium Gum','Sclerotium Gum; SCLEROTIUM GUM',11,11),
  ('ING0384','Ficus Carica (Fig) Fruit Extract','Ficus Carica (Fig) Fruit Extract; ficus carica (fig) fruit extract',11,11),
  ('ING0385','Lavandula Angustifolia (Lavender) Flower Extract','Lavandula Angustifolia (Lavender) Flower Extract; lavandula angustifolia (lavender) flower extract',11,11),
  ('ING0386','Palmitoyl Tetrapeptide-7','Palmitoyl Tetrapeptide-7; PALMITOYL TETRAPEPTIDE-7; Palmitoyl Tetrapeptide-7(0.5ppb)',11,12),
  ('ING0387','Glyceryl Glucoside','Glyceryl Glucoside; GLYCERYL GLUCOSIDE',11,11),
  ('ING0388','Lactococcus Ferment Lysate','Lactococcus Ferment Lysate; lactococcus ferment lysate',11,12),
  ('ING0389','C12-20 Alkyl Glucoside','C12-20 Alkyl Glucoside; C12-20 alkyl glucoside',11,11),
  ('ING0390','Butyloctyl Salicylate','Butyloctyl Salicylate; BUTYLOCTYL SALICYLATE',11,11),
  ('ING0391','Coccinia Indica Fruit Extract','Coccinia Indica Fruit Extract',11,11),
  ('ING0392','Solanum Melongena (Eggplant) Fruit Extract','Solanum Melongena (Eggplant) Fruit Extract; Solanum Melongena (eggplant) Fruit Extract; Solanum Melongena Fruit Extract; SOLANUM MELONGENA (EGGPLANT) FRUIT EXTRACT',11,11),
  ('ING0393','Papain','Papain',11,11),
  ('ING0394','Glyceryl Acrylate/Acrylic Acid Copolymer','Glyceryl Acrylate/Acrylic Acid Copolymer; Glyceryl Acrylate/ Acrylic Acid Copolymer',11,11),
  ('ING0395','Retinal','Retinal; Retinal (100 ppm); retinal (50 ppb); Retinal (0.1%); retinal; Retinal (Retinaldehyde)',11,11),
  ('ING0396','Sodium DNA','Sodium DNA; Sodium DNA (5 ppb); Sodium DNA (0.5 ppm); Sodium DNA (0,00001 ppm); Sodium DNA (100 ppm); Sodium DNA (1 ppm)',11,11),
  ('ING0397','Panthenyl Ethyl Ether','Panthenyl Ethyl Ether; panthenyl ethyl ether',10,10),
  ('ING0398','PPG-1 Trideceth-6','PPG-1 Trideceth-6; Ppg-1 Trideceth-6; PPG-1 TRIDECETH-6; ppg-1 trideceth-6',10,10),
  ('ING0399','Vitis Vinifera (Grape) Fruit Extract','Vitis Vinifera (Grape) Fruit Extract; Vitis Vinifera (Crape) Fruit Extract',10,10),
  ('ING0400','PEG-12 Dimethicone','PEG-12 Dimethicone; Peg-12 Dimethicone; peg-12 dimethicone',10,10),
  ('ING0401','Saccharum Officinarum (Sugar Cane) Extract','Saccharum Officinarum (Sugar Cane) Extract; Saccharum Officinarum Extract; Saccharum Officinarum (Sugarcane) Extract; SACCHARUM OFFICINARUM (SUGAR CANE) EXTRACT',10,10),
  ('ING0402','Silicone Quaternium-16','Silicone Quaternium-16',10,10),
  ('ING0403','Cetyl PEG/PPG-10/1 Dimethicone','Cetyl PEG/PPG-10/1 Dimethicone; CETYL PEG/PPG-10/1 DIMETHICONE; Cetyl PEG/ PPG-10/ 1 Dimethicone; cetyl peg/ppg-10/1 dimethicone',10,10),
  ('ING0404','Serenoa Serrulata Fruit Extract','Serenoa Serrulata Fruit Extract; SERENOA SERRULATA FRUIT EXTRACT; Serenoa Serrulata (Saw Palmetto) Fruit Extract; Serenoa Serrulata (Saw Palmetto) Fruit Extract*; SERENOA SERRULATA (SAW PALMETTO) FRUIT EXTRACT',10,10),
  ('ING0405','Calendula Officinalis Flower Extract','Calendula Officinalis Flower Extract; CALENDULA OFFICINALIS FLOWER EXTRACT; calendula officinalis flower extract; Calendula Officinalis (Pot Marigold) Flower Extract; Calendula Officinalis (Calendula) Flower Extract',10,10),
  ('ING0406','Perfume','Perfume; PERFUME',10,10),
  ('ING0407','fragrance/parfum','fragrance/parfum; Fragrance/Parfum; Fragrance/ Parfum; FRAGRANCE/PARFUM; FRAGRANCE / PARFUM',10,10),
  ('ING0408','Erythritol','Erythritol; ERYTHRITOL',10,10),
  ('ING0409','LAURTRIMONIUM CHLORIDE','LAURTRIMONIUM CHLORIDE; Laurtrimonium Chloride',10,11),
  ('ING0410','Hydrolyzed Glycosaminoglycans','Hydrolyzed Glycosaminoglycans; hydrolyzed glycosaminoglycans; Hydrolyzed glycosaminoglycans',10,10),
  ('ING0411','Anthemis Nobilis Flower Extract','Anthemis Nobilis Flower Extract; Anthemis Nobilis (Chamomile) Flower Extract; ANTHEMIS NOBILIS FLOWER EXTRACT',10,10),
  ('ING0412','Ricinus Communis (Castor) Seed Oil','Ricinus Communis (Castor) Seed Oil; RICINUS COMMUNIS (CASTOR) SEED OIL; Ricinus Communis Seed Oil',10,10),
  ('ING0413','PEG-120 Methyl Glucose Dioleate','PEG-120 Methyl Glucose Dioleate; PEG-120 METHYL GLUCOSE DIOLEATE; PEG -120 METHYL GLUCOSE DIOLEATE',10,10),
  ('ING0414','Sodium Dehydroacetate','Sodium Dehydroacetate; Sodium dehydroacetate; sodium dehydroacetate',10,11),
  ('ING0415','Aminopropyl Dimethicone','Aminopropyl Dimethicone; AMINOPROPYL DIMETHICONE',10,10),
  ('ING0416','Bis-Aminopropyl Diglycol Dimaleate','Bis-Aminopropyl Diglycol Dimaleate; Bis-aminopropyl Diglycol Dimaleate',10,10),
  ('ING0417','Hydroxypropyl Cyclodextrin','Hydroxypropyl Cyclodextrin; HYDROXYPROPYL CYCLODEXTRIN',10,10),
  ('ING0418','Carthamus Tinctorius (Safflower) Seed Oil','Carthamus Tinctorius (Safflower) Seed Oil; CARTHAMUS TINCTORIUS (SAFFLOWER) SEED OIL; carthamus tinctorius seed oil; CARTHAMUS TINCTORIUS SEED OIL',10,10),
  ('ING0419','Pentaerythrityl Tetraethylhexanoate','Pentaerythrityl Tetraethylhexanoate; PENTAERYTHRITYL TETRAETHYLHEXANOATE; pentaerythrityl tetraethylhexanoate',10,11),
  ('ING0420','Decolorized Aloe Barbadensis (Aloe Vera) Leaf Juice*','Decolorized Aloe Barbadensis (Aloe Vera) Leaf Juice*; Decolorized Aloe Barbadensis (Aloe Vera) Leaf Juice; DECOLORIZED ALOE BARBADENSIS (ALOE VERA) LEAF JUICE*',10,10),
  ('ING0421','Citrus Aurantium Dulcis (Orange) Peel Oil','Citrus Aurantium Dulcis (Orange) Peel Oil; Citrus Aurantium Dulcis Peel Oil',10,10),
  ('ING0422','Aminomethyl Propanol','Aminomethyl Propanol; AMINOMETHYL PROPANOL',10,10),
  ('ING0423','Propolis Extract','Propolis Extract; PROPOLIS EXTRACT; Propolis extract (87.99%); Propolis Extract(1%)',10,10),
  ('ING0424','Mandelic Acid','Mandelic Acid; mandelic acid',10,10),
  ('ING0425','Myristic Acid','Myristic Acid; myristic acid; MYRISTIC ACID',10,10),
  ('ING0426','Sodium Polyacryloyldimethyl Taurate','Sodium Polyacryloyldimethyl Taurate; sodium polyacryloyldimethyl taurate',10,11),
  ('ING0427','Sorbitan Sesquioleate','Sorbitan Sesquioleate; sorbitan sesquioleate; SORBITAN SESQUIOLEATE',10,10),
  ('ING0428','Hydrogenated Poly(C6-14 Olefin)','Hydrogenated Poly(C6-14 Olefin); Hydrogenated Poly(c6-14 Olefin); Hydrogenated Poly(C6 14 Olefin); Hydrogenated Poly; Hydrogenated Poly (c6-14 Olefin)',10,10),
  ('ING0429','Trideceth-5','Trideceth-5; TRIDECETH-5; trideceth-5',9,9),
  ('ING0430','Bis-Aminopropyl Dimethicone','Bis-Aminopropyl Dimethicone; bis-aminopropyl dimethicone; Bis-aminopropyl Dimethicone',9,9),
  ('ING0431','Citrus Limon (Lemon) Fruit Extract','Citrus Limon (Lemon) Fruit Extract; Citrus Limon Fruit Extract; CITRUS LIMON (LEMON) FRUIT EXTRACT; Citrus Limon (Lemon) Fruit Extract (560000 ppm)',9,9),
  ('ING0432','Polyquaternium-22','Polyquaternium-22; polyquaternium-22; POLYQUATERNIUM-22',9,9),
  ('ING0433','Trideceth-3','Trideceth-3; trideceth-3; TRIDECETH-3',9,9),
  ('ING0434','Linolenic Acid','Linolenic Acid; LINOLENIC ACID',9,9),
  ('ING0435','Dimethylsilanol Hyaluronate','Dimethylsilanol Hyaluronate; dimethylsilanol hyaluronate',9,9),
  ('ING0436','Polyquaternium-16','Polyquaternium-16; polyquaternium-16',9,9),
  ('ING0437','Camellia Oleifera Seed Oil','Camellia Oleifera Seed Oil; CAMELLIA OLEIFERA SEED OIL; camellia oleifera seed oil (масло семян камелии); camellia oleifera (sasanqua) seed oil; Camellia Oleifera (Green Tea) Seed Oil',9,9),
  ('ING0438','Caramel','Caramel; CARAMEL; caramel',9,9),
  ('ING0439','Undeceth-11','Undeceth-11',9,9),
  ('ING0440','Butyloctanol','Butyloctanol; BUTYLOCTANOL',9,9),
  ('ING0441','Undeceth-5','Undeceth-5',9,9),
  ('ING0442','Ammonium Lauryl Sulfate','Ammonium Lauryl Sulfate; Ammonium lauryl sulfate; AMMONIUM LAURYL SULFATE',9,9),
  ('ING0443','RED 33 (CI 17200)','RED 33 (CI 17200); Red 33; red 33 (ci17200); Red 33 (Ci 17200); red 33',9,9),
  ('ING0444','Phytosterols','Phytosterols; PHYTOSTEROLS',9,9),
  ('ING0445','Lauryl Alcohol','Lauryl Alcohol; LAURYL ALCOHOL',9,9),
  ('ING0446','Polyglyceryl-10 Oleate','Polyglyceryl-10 Oleate; polyglyceryl-10 oleate',9,9),
  ('ING0447','Resveratrol','Resveratrol; RESVERATROL; Resveratrol (ресвератрол)',9,9),
  ('ING0448','Oenothera Biennis (Evening Primrose) Oil','Oenothera Biennis (Evening Primrose) Oil; oenothera biennis (evening primrose) oil; Oenothera Biennis Oil; OENOTHERA BIENNIS (EVENING PRIMROSE) OIL (OENOTHERA BIENNIS OIL)',9,9),
  ('ING0449','Caprylhydroxamic Acid','Caprylhydroxamic Acid; caprylhydroxamic acid; CAPRYLHYDROXAMIC ACID',9,9),
  ('ING0450','PLUKENETIA VOLUBILIS SEED OIL','PLUKENETIA VOLUBILIS SEED OIL; Plukenetia Volubilis (Sacha Inchi) Seed Oil; Plukenetia Volubilis Seed Oil; Plukenetia volubilis seed oil; Plukenetia Volubilis (sacha Inchi) Seed Oil',9,9),
  ('ING0451','Hydrolyzed Oat Protein','Hydrolyzed Oat Protein; hydrolyzed oat protein; HYDROLYZED OAT PROTEIN',9,9),
  ('ING0452','dipalmitoylethyl hydroxyethylmonium methosulfate','dipalmitoylethyl hydroxyethylmonium methosulfate; Dipalmitoylethyl Hydroxyethylmonium Methosulfate; DIPALMITOYLETHYL HYDROXYETHYLMONIUM METHOSULFATE',9,9),
  ('ING0453','Disodium Phosphate','Disodium Phosphate; DISODIUM PHOSPHATE; Disodium phosphate',9,9),
  ('ING0454','ISOEUGENOL','ISOEUGENOL; isoeugenol; Isoeugenol',9,9),
  ('ING0455','Lauric Acid','Lauric Acid; LAURIC ACID; lauric acid',9,9),
  ('ING0456','Keratin','Keratin; keratin',9,9),
  ('ING0457','Glycine Soja Sterols','Glycine Soja Sterols; Glycine Soja (Soybean) Sterols; GLYCINE SOJA (SOYBEAN) STEROLS; Glycine soja Sterols; GLYCINE SOJA STEROLS',9,9),
  ('ING0458','Mentha Piperita (Peppermint) Leaf Extract','Mentha Piperita (Peppermint) Leaf Extract; Mentha piperita Leaf Extract; MENTHA PIPERITA (PEPPERMINT) LEAF EXTRACT',9,9),
  ('ING0459','CI 15985','CI 15985; ci 15985; CI 15985 (Yellow 6); Ci 15985',9,9),
  ('ING0460','Triethyl Citrate','Triethyl Citrate; triethyl citrate; Triethyl citrate; TRIETHYL CITRATE',9,9),
  ('ING0461','Eugenol','Eugenol; eugenol; EUGENOL',9,9),
  ('ING0462','Inositol','Inositol; INOSITOL; inositol',9,9),
  ('ING0463','Glutamine','Glutamine; GLUTAMINE',9,9),
  ('ING0464','glyceryl laurate','glyceryl laurate; Glyceryl Laurate; GLYCERYL LAURATE',9,9),
  ('ING0465','Melaleuca Alternifolia (Tea Tree) Extract','Melaleuca Alternifolia (Tea Tree) Extract; Melaleuca Alternifolia extract; Melaleuca Alternifolia (Tea Tree) Extract (630ppm)',9,9),
  ('ING0466','Malt Extract','Malt Extract; MALT EXTRACT; malt extract',9,9),
  ('ING0467','Sucrose','Sucrose; SUCROSE; SUCROSE (SUGAR)',9,9),
  ('ING0468','Coffea Arabica (Coffee) Seed Extract','Coffea Arabica (Coffee) Seed Extract; COFFEA ARABICA (COFEE) SEED EXTRACT; Coffea Arabica Seed Extract',9,9),
  ('ING0469','Laminaria Japonica Extract','Laminaria Japonica Extract; LAMINARIA JAPONICA EXTRACT',9,9),
  ('ING0470','Green Tea Extract','Green Tea Extract; Green Tea (Camellia Sinensis) (Leaf) Extract; GREEN TEA EXTRACT; green tea extract (121 ppm)',9,9),
  ('ING0471','Capryloyl Salicylic Acid','Capryloyl Salicylic Acid; CAPRYLOYL SALICYLIC ACID',9,9),
  ('ING0472','C14-22 Alcohols','C14-22 Alcohols',9,9),
  ('ING0473','Polyether-1','Polyether-1; polyether -1',9,9),
  ('ING0474','DIISOPROPYL SEBACATE','DIISOPROPYL SEBACATE; diisopropyl sebacate; Diisopropyl Sebacate',9,9),
  ('ING0475','Butylene Glycol Dicaprylate/Dicaprate','Butylene Glycol Dicaprylate/Dicaprate; Butylene Glycol Dicaprylate/dicaprate',9,9),
  ('ING0476','Ulmus Davidiana Root Extract','Ulmus Davidiana Root Extract',9,9),
  ('ING0477','PVM/MA Copolymer','PVM/MA Copolymer; Pvm/ Ma Copolymer',9,9),
  ('ING0478','Sorbitan Stearate','Sorbitan Stearate; SORBITAN STEARATE',9,9),
  ('ING0479','Polygonum Cuspidatum Root Extract','Polygonum Cuspidatum Root Extract',9,9),
  ('ING0480','Polyacrylate-13','Polyacrylate-13; POLYACRYLATE-13',9,9),
  ('ING0481','Sodium Xylenesulfonate','Sodium Xylenesulfonate; sodium xylenesulfonate',8,8),
  ('ING0482','Cocos Nucifera (Coconut) Fruit Extract','Cocos Nucifera (Coconut) Fruit Extract; Cocos Nucifera Fruit Extract; cocos nucifera (coconut) fruit extract',8,8),
  ('ING0483','Hydrolyzed Vegetable Protein PG-Propyl Silanetriol','Hydrolyzed Vegetable Protein PG-Propyl Silanetriol; Hydrolyzed Vegetable Protein Pg-Propyl Silanetriol; HYDROLYZED VEGETABLE PROTEIN PG-PROPYL SILANETRIOL',8,8),
  ('ING0484','Tripeptide-1','Tripeptide-1; Tripeptide -1',8,8),
  ('ING0485','Pyridoxine','Pyridoxine; pyridoxine',8,8),
  ('ING0486','Hydroxypropyl Starch Phosphate','Hydroxypropyl Starch Phosphate; HYDROXYPROPYL STARCH PHOSPHATE',8,8),
  ('ING0487','Propylene Glycol Dicaprylate/Dicaprate','Propylene Glycol Dicaprylate/Dicaprate; PROPYLENE GLYCOL DICAPRYLATE/DICAPRATE; propylene glycol dicaprylate/dicaprate; PROPYLENE GLYCOL DICAPRYLATE / DICAPRATE',8,8),
  ('ING0488','Polyquaternium-11','Polyquaternium-11; POLYQUATERNIUM-11',8,9),
  ('ING0489','Rosmarinus Officinalis (Rosemary) Extract','Rosmarinus Officinalis (Rosemary) Extract; rosmarinus officinalis extract; Rosmarinus Officinalis Extract; ROSMARINUS OFFICINALIS (ROSEMARY) ЕXTRACT',8,8),
  ('ING0490','Algin','Algin; ALGIN',8,8),
  ('ING0491','Sodium Phosphate','Sodium Phosphate; SODIUM PHOSPHATE',8,8),
  ('ING0492','Linum Usitatissimum Seed Oil','Linum Usitatissimum Seed Oil; Linum Usitatissimum (Linseed) Seed Oil; Linum usitatissimum (Linseed) seed oil; Linum usitatissimum seed oil; LINUM USITATISSIMUM SEED OIL; LINUM USITATISSIMUM (LINSEED) SEED OIL',8,8),
  ('ING0493','Hydrogenated Starch Hydrolysate','Hydrogenated Starch Hydrolysate; HYDROGENATED STARCH HYDROLYSATE',8,8),
  ('ING0494','Hydrolyzed Elastin','Hydrolyzed Elastin; Hydrolyzed elastin; HYDROLYZED ELASTIN',8,8),
  ('ING0495','Jojoba Esters','Jojoba Esters; JOJOBA ESTERS',8,8),
  ('ING0496','Chondrus Crispus (Carrageenan) Extract','Chondrus Crispus (Carrageenan) Extract; Chondrus Crispus Extract',8,8),
  ('ING0497','Alumina','Alumina',8,8),
  ('ING0498','Hydrogenated Castor Oil','Hydrogenated Castor Oil; HYDROGENATED CASTOR OIL',8,8),
  ('ING0499','Phyllanthus Emblica Fruit Extract','Phyllanthus Emblica Fruit Extract; PHYLLANTHUS EMBLICA FRUIT EXTRACT; Phyllanthus Emblica (Indian Gooseberry) Fruit Extract',8,8),
  ('ING0500','Kaolin','Kaolin; KAOLIN; kaolin; Kaolin(CI 77004)(10%)',8,8)
ON CONFLICT (ingredient_id) DO UPDATE SET canonical_name=EXCLUDED.canonical_name, aliases=EXCLUDED.aliases;