INSERT INTO ingredients_dictionary (ingredient_id,canonical_name,aliases,product_count,occurrence_count)
VALUES
  ('ING2501','Sunflower (Helianthus Annuus) (Seed) Extract','Sunflower (Helianthus Annuus) (Seed) Extract',1,1),
  ('ING2502','Italian Woodbine (Lonicera Caprifolium) (Flower) Extract','Italian Woodbine (Lonicera Caprifolium) (Flower) Extract',1,1),
  ('ING2503','Japanese Honeysuckle (Lonicera Japonica) (Flower) Extract','Japanese Honeysuckle (Lonicera Japonica) (Flower) Extract',1,1),
  ('ING2504','Cucumber (Cucumis Sativus) Extract','Cucumber (Cucumis Sativus) Extract',1,1),
  ('ING2505','Citrus Limon (Lemon) Oil*','Citrus Limon (Lemon) Oil*',1,1),
  ('ING2506','Fragrance Made With Natural Lavender','Fragrance Made With Natural Lavender',1,1),
  ('ING2507','Shea Butter Glycereth-8 Esters','Shea Butter Glycereth-8 Esters',1,1),
  ('ING2508','HEXAMETHYLINDANOPYRAN','HEXAMETHYLINDANOPYRAN',1,1),
  ('ING2509','POTASSIUM AZELOYL DIGLYCINATE','POTASSIUM AZELOYL DIGLYCINATE',1,1),
  ('ING2510','CARNOSINE','CARNOSINE',1,1),
  ('ING2511','AMARANTHUS SPINOSUS SEED OIL','AMARANTHUS SPINOSUS SEED OIL',1,1),
  ('ING2512','CORISPERMUM SIBIRICUM FLOWER/LEAF/STEM EXTRACT','CORISPERMUM SIBIRICUM FLOWER/LEAF/STEM EXTRACT',1,1),
  ('ING2513','ROSA DAVURICA LEAF EXTRACT','ROSA DAVURICA LEAF EXTRACT',1,1),
  ('ING2514','ANGELICA ARCHANGELICA RooT EXTRACT','ANGELICA ARCHANGELICA RooT EXTRACT',1,1),
  ('ING2515','ACTINIDIA POLYGAMA FRUIT EXTRACT','ACTINIDIA POLYGAMA FRUIT EXTRACT',1,1),
  ('ING2516','AGARUM CRIBROSUM EXTRACT','AGARUM CRIBROSUM EXTRACT',1,1),
  ('ING2517','AMBER ACID','AMBER ACID',1,1),
  ('ING2518','RHODODENDRON DAURICUM FLOWER/LEAF/STEM EXTRACT','RHODODENDRON DAURICUM FLOWER/LEAF/STEM EXTRACT',1,1),
  ('ING2519','FRAGARIA VESCA FRUIT EXTRACT','FRAGARIA VESCA FRUIT EXTRACT',1,1),
  ('ING2520','SOPHORA FLAVESCENS EXTRACT','SOPHORA FLAVESCENS EXTRACT',1,1),
  ('ING2521','Pinus Sibirica Needle Extract','Pinus Sibirica Needle Extract',1,1),
  ('ING2522','Iris Sibirica Root Water','Iris Sibirica Root Water',1,1),
  ('ING2523','Eurybia Sibirica Leaf Extract','Eurybia Sibirica Leaf Extract',1,1),
  ('ING2524','Vaccinium Vulcanorum Fruit Extract','Vaccinium Vulcanorum Fruit Extract',1,1),
  ('ING2525','Rhaponticum Carthamoides Root Extract','Rhaponticum Carthamoides Root Extract',1,1),
  ('ING2526','Acrylamidopropyltrimonium Chloride/Acrylamide Copolymer','Acrylamidopropyltrimonium Chloride/Acrylamide Copolymer',1,1),
  ('ING2527','Saponaria Officinalis Leaf Extract','Saponaria Officinalis Leaf Extract',1,1),
  ('ING2528','Sodium Lauryl Sarcosinate','Sodium Lauryl Sarcosinate',1,1),
  ('ING2529','HC Blue 2','HC Blue 2',1,1),
  ('ING2530','Lactobacillus/ Salix Purpurea Bark Ferment Extract','Lactobacillus/ Salix Purpurea Bark Ferment Extract',1,1),
  ('ING2531','Bambusa Arundinacea Stem Powder','Bambusa Arundinacea Stem Powder',1,1),
  ('ING2532','Ethyl Hydroxypyrone','Ethyl Hydroxypyrone',1,1),
  ('ING2533','Melaleuca Alternifolia (Teatree) Oil','Melaleuca Alternifolia (Teatree) Oil',1,1),
  ('ING2534','Capric/Caprylic Triglycerydes','Capric/Caprylic Triglycerydes',1,1),
  ('ING2535','Quercus infectoria gall extract','Quercus infectoria gall extract',1,1),
  ('ING2536','Juniperus Sibirica Needle Extract','Juniperus Sibirica Needle Extract',1,1),
  ('ING2537','Aralia Mandshurica Root Extract','Aralia Mandshurica Root Extract',1,1),
  ('ING2538','Inula Helenium Extract','Inula Helenium Extract',1,1),
  ('ING2539','Acrylic Polymer','Acrylic Polymer',1,1),
  ('ING2540','Quercus Robur Bark Extract','Quercus Robur Bark Extract',1,1),
  ('ING2541','Trideceth-9','Trideceth-9',1,1),
  ('ING2542','Silicone Quaterniuim-18','Silicone Quaterniuim-18',1,1),
  ('ING2543','ACETYL CEDRENE','ACETYL CEDRENE',1,1),
  ('ING2544','LINALYL ACETATE','LINALYL ACETATE',1,1),
  ('ING2545','PINENE','PINENE',1,1),
  ('ING2546','CITRUS AURANTIUM PEEL OIL','CITRUS AURANTIUM PEEL OIL',1,1),
  ('ING2547','ACRYLATES/BEHENETH-25 METHACRYLATE COPOLYMER','ACRYLATES/BEHENETH-25 METHACRYLATE COPOLYMER',1,1),
  ('ING2548','Macadamia Nut Oil','Macadamia Nut Oil',1,1),
  ('ING2549','behenoyl pg-trimonium chloride','behenoyl pg-trimonium chloride',1,1),
  ('ING2550','KOU-CHA EKISU','KOU-CHA EKISU',1,1),
  ('ING2551','Phenylalanine Persea Gratissima (Avocado) Oil','Phenylalanine Persea Gratissima (Avocado) Oil',1,1),
  ('ING2552','Guar HydroxypropyItrimonium Chloride','Guar HydroxypropyItrimonium Chloride',1,1),
  ('ING2553','Ethylhexyglycerin','Ethylhexyglycerin',1,1),
  ('ING2554','Grape Seed Extract','Grape Seed Extract',1,1),
  ('ING2555','PEG-10','PEG-10',1,1),
  ('ING2556','Ether Tregalosa','Ether Tregalosa',1,1),
  ('ING2557','Jojoba Butter','Jojoba Butter',1,1),
  ('ING2558','Silk Extract','Silk Extract',1,1),
  ('ING2559','Hydroxypropyltrimonium','Hydroxypropyltrimonium',1,1),
  ('ING2560','Hydroxypropyltrimonium Honey','Hydroxypropyltrimonium Honey',1,1),
  ('ING2561','Guar Hydroxypropyltrimonium Chloride Phenoxyethanol','Guar Hydroxypropyltrimonium Chloride Phenoxyethanol',1,1),
  ('ING2562','3-Butylene Glycol','3-Butylene Glycol',1,1),
  ('ING2563','Bis-Diisopropanolamino-PG-Propyl Disiloxane','Bis-Diisopropanolamino-PG-Propyl Disiloxane',1,1),
  ('ING2564','Bis-Vinyl Dimethicone Copolymer','Bis-Vinyl Dimethicone Copolymer',1,1),
  ('ING2565','Behenamidopropyl','Behenamidopropyl',1,1),
  ('ING2566','Dimethylamine Amodimethicone','Dimethylamine Amodimethicone',1,1),
  ('ING2567','Prunus Armeniaca Extract','Prunus Armeniaca Extract',1,1),
  ('ING2568','Persea americana Fruit Extract','Persea americana Fruit Extract',1,1),
  ('ING2569','Musa acuminata Fruit Extract','Musa acuminata Fruit Extract',1,1),
  ('ING2570','CI 19140/CI42090','CI 19140/CI42090',1,1),
  ('ING2571','CI 15510','CI 15510',1,1),
  ('ING2572','HYDROLYZED PEARL','HYDROLYZED PEARL',1,1),
  ('ING2573','CITRUS GRANDIS (GRAPEFRUIT) EXTRACT','CITRUS GRANDIS (GRAPEFRUIT) EXTRACT',1,1),
  ('ING2574','SALVIA SCLAREA EXTRACT (SALVIA SCLAREA (CLARY) EXTRACT)','SALVIA SCLAREA EXTRACT (SALVIA SCLAREA (CLARY) EXTRACT)',1,1),
  ('ING2575','SALVIA SCLAREA FLOWER OIL','SALVIA SCLAREA FLOWER OIL',1,1),
  ('ING2576','Экстракт зверобоя','Экстракт зверобоя',1,1),
  ('ING2577','Экстракт ромашки','Экстракт ромашки',1,1),
  ('ING2578','Sodium Laureth carboxilate','Sodium Laureth carboxilate',1,1),
  ('ING2579','Моноэтаноламид рапсового масла','Моноэтаноламид рапсового масла',1,1),
  ('ING2580','sodium salicilate','sodium salicilate',1,1),
  ('ING2581','Йодопропинил бутилкарбамат','Йодопропинил бутилкарбамат',1,1),
  ('ING2582','polyquaternium-76','polyquaternium-76',1,1),
  ('ING2583','hydrochloric acid','hydrochloric acid',1,1),
  ('ING2584','Hydrolyzed Quinoa protein','Hydrolyzed Quinoa protein',1,1),
  ('ING2585','Cymbopogon Citratus Oil','Cymbopogon Citratus Oil',1,1),
  ('ING2586','Eucalyptus Essential Oil','Eucalyptus Essential Oil',1,1),
  ('ING2587','OPUNTIA FICUS-INDICA SEED OIL','OPUNTIA FICUS-INDICA SEED OIL',1,1),
  ('ING2588','AVENA SATIVA LEAF/STALK EXTRACT (AVENA SATIVA OAT LEAF/STALK EXTRACT)','AVENA SATIVA LEAF/STALK EXTRACT (AVENA SATIVA OAT LEAF/STALK EXTRACT)',1,1),
  ('ING2589','mentha piperita flower/leaf/stem oil','mentha piperita flower/leaf/stem oil',1,1),
  ('ING2590','mentha arvensis leaf/stem oil','mentha arvensis leaf/stem oil',1,1),
  ('ING2591','glyoxal','glyoxal',1,1),
  ('ING2592','PRUNUS ARMENIACA SEED POWDER / APRICOT SEED POWDER','PRUNUS ARMENIACA SEED POWDER / APRICOT SEED POWDER',1,1),
  ('ING2593','глицерин/вода/ экстракт цветков календулы/сорбат калия','глицерин/вода/ экстракт цветков календулы/сорбат калия',1,1),
  ('ING2594','glicerin','glicerin',1,1),
  ('ING2595','глицерин/вода/ экстракт корня лопуха/сорбат калия','глицерин/вода/ экстракт корня лопуха/сорбат калия',1,1),
  ('ING2596','Klimazol','Klimazol',1,1),
  ('ING2597','эфирное масло чайного дерева','эфирное масло чайного дерева',1,1),
  ('ING2598','polysorbat-10','polysorbat-10',1,1),
  ('ING2599','Disodium Laureth Sullosuccinate','Disodium Laureth Sullosuccinate',1,1),
  ('ING2600','CapryIhydroxamic Acid','CapryIhydroxamic Acid',1,1),
  ('ING2601','Phenoxyethanol Citric Acid','Phenoxyethanol Citric Acid',1,1),
  ('ING2602','Sodium Acetate Isopropyl Alcohol','Sodium Acetate Isopropyl Alcohol',1,1),
  ('ING2603','Chlorophyllin-copper complex','Chlorophyllin-copper complex',1,1),
  ('ING2604','PEG-18 Glyceryl Oleate/Cocoate','PEG-18 Glyceryl Oleate/Cocoate',1,1),
  ('ING2605','Glyceria Emretrum Ngrum Fruit Juice','Glyceria Emretrum Ngrum Fruit Juice',1,1),
  ('ING2606','Sodium Dodecylbenzenesulphonate','Sodium Dodecylbenzenesulphonate',1,1),
  ('ING2607','Dextrose Monohydrate','Dextrose Monohydrate',1,1),
  ('ING2608','SODIUM LAURYL GLUCOSE CARBOXYLATE','SODIUM LAURYL GLUCOSE CARBOXYLATE',1,1),
  ('ING2609','PEACH KERNEL OIL GLYCERETH-8 ESTERS','PEACH KERNEL OIL GLYCERETH-8 ESTERS',1,1),
  ('ING2610','LAVANDULA INTERMEDIA FLOWER/LEAF/STEM EXTRACT','LAVANDULA INTERMEDIA FLOWER/LEAF/STEM EXTRACT',1,1),
  ('ING2611','PEG-200 GLYCERYL STEARATE','PEG-200 GLYCERYL STEARATE',1,1),
  ('ING2612','ARGANIA SPINOSA (ARGAN) NUT OIL','ARGANIA SPINOSA (ARGAN) NUT OIL',1,1),
  ('ING2613','Oleic/Linoleic/Linolenic Polyglycerides','Oleic/Linoleic/Linolenic Polyglycerides',1,1),
  ('ING2614','Theobroma Grandiflorum Seed Butter','Theobroma Grandiflorum Seed Butter',1,1),
  ('ING2615','Cetearyl Dimethicone Crosspolymer','Cetearyl Dimethicone Crosspolymer',1,1),
  ('ING2616','cetyl stearyl alcohol','cetyl stearyl alcohol',1,1),
  ('ING2617','capsicum annuum extract','capsicum annuum extract',1,1),
  ('ING2618','sodium cocoyl amino acids','sodium cocoyl amino acids',1,1),
  ('ING2619','potassium dimethicone peg-7 panthenyl phosphate','potassium dimethicone peg-7 panthenyl phosphate',1,1),
  ('ING2620','sodium salycilate','sodium salycilate',1,1),
  ('ING2621','prunus amygdalus dilcis (sweet almond) oil','prunus amygdalus dilcis (sweet almond) oil',1,1),
  ('ING2622','Lysine Na Dilauroylglutamate','Lysine Na Dilauroylglutamate',1,1),
  ('ING2623','Soybean Seed Extract','Soybean Seed Extract',1,1),
  ('ING2624','PPG-20-Decyltetradeceth-10','PPG-20-Decyltetradeceth-10',1,1),
  ('ING2625','Isopropanol','Isopropanol',1,1),
  ('ING2626','EDTA -2Na','EDTA -2Na',1,1),
  ('ING2627','BG','BG',1,1),
  ('ING2628','Dibutyladifate','Dibutyladifate',1,1),
  ('ING2629','Propandyol','Propandyol',1,1),
  ('ING2630','Polyglyceryl-3 Dystearate','Polyglyceryl-3 Dystearate',1,1),
  ('ING2631','1,2 Hexanthandyol','1,2 Hexanthandyol',1,1),
  ('ING2632','Setearyl Alcohol','Setearyl Alcohol',1,1),
  ('ING2633','Capryl Methicone','Capryl Methicone',1,1),
  ('ING2634','Polymethylcessesquioxein','Polymethylcessesquioxein',1,1),
  ('ING2635','Hydrolyzed Rye Pytoplasenta Extract','Hydrolyzed Rye Pytoplasenta Extract',1,1),
  ('ING2636','Sea Near-Padyl Extract','Sea Near-Padyl Extract',1,1),
  ('ING2637','Shiitake Mushroom Mycelia Extract','Shiitake Mushroom Mycelia Extract',1,1),
  ('ING2638','Dimethylcon/Vinyldimethiconcrosspolymer','Dimethylcon/Vinyldimethiconcrosspolymer',1,1),
  ('ING2639','Methylpropandyol','Methylpropandyol',1,1),
  ('ING2640','Ammonium Acryloyl Dimethyl Tarate Piccopolymer','Ammonium Acryloyl Dimethyl Tarate Piccopolymer',1,1),
  ('ING2641','Glyceryl Sterate Citrate','Glyceryl Sterate Citrate',1,1),
  ('ING2642','Polyester-1','Polyester-1',1,1),
  ('ING2643','Butyl Alcohol','Butyl Alcohol',1,1),
  ('ING2644','Bioscaride gum-1','Bioscaride gum-1',1,1),
  ('ING2645','Lauryl Methacrylate/Glycol Dimethacrylate Crosspolymer','Lauryl Methacrylate/Glycol Dimethacrylate Crosspolymer',1,1),
  ('ING2646','Sophora Japonica Fruit Extract','Sophora Japonica Fruit Extract',1,1),
  ('ING2647','Diethylamino Hydroxy Benzoyl Hexyl Benzoate','Diethylamino Hydroxy Benzoyl Hexyl Benzoate',1,1),
  ('ING2648','C 20-22 Alcohols','C 20-22 Alcohols',1,1),
  ('ING2649','Pentylene Gycol Behenyl Alcohol','Pentylene Gycol Behenyl Alcohol',1,1),
  ('ING2650','Gyceryl Stearate Polyacrylate Crosspolymer-6','Gyceryl Stearate Polyacrylate Crosspolymer-6',1,1),
  ('ING2651','Tromethamine Ammonium Aayloyi dimethytaurate Vp Copolymer','Tromethamine Ammonium Aayloyi dimethytaurate Vp Copolymer',1,1),
  ('ING2652','Sodium Aayloyldimethyl Taurate Copolymer','Sodium Aayloyldimethyl Taurate Copolymer',1,1),
  ('ING2653','Cucu mis Melo (melon) Fruit Extract','Cucu mis Melo (melon) Fruit Extract',1,1),
  ('ING2654','Capryly / Capryl Glucoside','Capryly / Capryl Glucoside',1,1),
  ('ING2655','Actinidia Arguta Fruit Extract','Actinidia Arguta Fruit Extract',1,1),
  ('ING2656','Dibutyl Adipate, Butyloctyl Salicylate','Dibutyl Adipate, Butyloctyl Salicylate',1,1),
  ('ING2657','Galactomyces fermentation filtrate (10%)','Galactomyces fermentation filtrate (10%)',1,1),
  ('ING2658','diethylamino hydroxy benzoylhexyl benzoate','diethylamino hydroxy benzoylhexyl benzoate',1,1),
  ('ING2659','phenethylbenzoate','phenethylbenzoate',1,1),
  ('ING2660','Manchurian birch sap','Manchurian birch sap',1,1),
  ('ING2661','xylitol glucoside','xylitol glucoside',1,1),
  ('ING2662','Oryza Sativa (Rice) Germ Extract','Oryza Sativa (Rice) Germ Extract',1,1),
  ('ING2663','Bacillus/Soybean Ferment Extract','Bacillus/Soybean Ferment Extract',1,1),
  ('ING2664','Saccharomyces/Rice Ferment Filtrate','Saccharomyces/Rice Ferment Filtrate',1,1),
  ('ING2665','C20-22 Alcohols','C20-22 Alcohols',1,1),
  ('ING2666','Sodium Acrylate/ Sodium Acryloyldimethyltaurate Copolymer','Sodium Acrylate/ Sodium Acryloyldimethyltaurate Copolymer',1,1),
  ('ING2667','Ethylhexyl Glycerine','Ethylhexyl Glycerine',1,1),
  ('ING2668','Peppermint Oil','Peppermint Oil',1,1),
  ('ING2669','Bp Multi-Fermented Seafood','Bp Multi-Fermented Seafood',1,1),
  ('ING2670','Cerulata Cherry Tree Flower Extract','Cerulata Cherry Tree Flower Extract',1,1),
  ('ING2671','Lavender Flower Extract','Lavender Flower Extract',1,1),
  ('ING2672','Portmari Gold Flower Extract','Portmari Gold Flower Extract',1,1),
  ('ING2673','Kakadu Plum Extract','Kakadu Plum Extract',1,1),
  ('ING2674','Broccoli Extract','Broccoli Extract',1,1),
  ('ING2675','DECYLGLUCOSIDE','DECYLGLUCOSIDE',1,1),
  ('ING2676','POLYGLYCERYL-5 POLYRICINOLEATE','POLYGLYCERYL-5 POLYRICINOLEATE',1,1),
  ('ING2677','MA GNESIUM SULFATE','MA GNESIUM SULFATE',1,1),
  ('ING2678','Caprylylmethicone','Caprylylmethicone',1,1),
  ('ING2679','Ascorbic Acid Polypeptide','Ascorbic Acid Polypeptide',1,1),
  ('ING2680','Ethylhexylg Lycerin','Ethylhexylg Lycerin',1,1),
  ('ING2681','Tocopherol T-butyl Alcohol','Tocopherol T-butyl Alcohol',1,1),
  ('ING2682','Anthemis Nobilis Flower Extract Propylene Glycol','Anthemis Nobilis Flower Extract Propylene Glycol',1,1),
  ('ING2683','Cardiospermum Halicacabum Flower / Leafvine Extract','Cardiospermum Halicacabum Flower / Leafvine Extract',1,1),
  ('ING2684','Unsaponifiables','Unsaponifiables',1,1),
  ('ING2685','Mung Bean Extract','Mung Bean Extract',1,1),
  ('ING2686','Cotton Extract','Cotton Extract',1,1),
  ('ING2687','Longleaf Rhubarb Root/stem Extract','Longleaf Rhubarb Root/stem Extract',1,1),
  ('ING2688','Hwangbark Bark Extract','Hwangbark Bark Extract',1,1),
  ('ING2689','Cotton Seed Oil','Cotton Seed Oil',1,1),
  ('ING2690','Polymethyl Silsesquioxane','Polymethyl Silsesquioxane',1,1),
  ('ING2691','Sodium Polyacryloyl Dimethyl Taurate','Sodium Polyacryloyl Dimethyl Taurate',1,1),
  ('ING2692','Ammonium Acryloyl Dimethyl Taurate/vpicopolymer','Ammonium Acryloyl Dimethyl Taurate/vpicopolymer',1,1),
  ('ING2693','Gossypium Herbaceum (cotton) Extract','Gossypium Herbaceum (cotton) Extract',1,1),
  ('ING2694','Rheum Palmatum Root/Stalk Extract','Rheum Palmatum Root/Stalk Extract',1,1),
  ('ING2695','Betula Platyphylla Japonica Juice','Betula Platyphylla Japonica Juice',1,1),
  ('ING2696','Artemisia Annua Extract','Artemisia Annua Extract',1,1),
  ('ING2697','Pinus Sylvestris Leaf Oil','Pinus Sylvestris Leaf Oil',1,1),
  ('ING2698','VP/Eicosene Copolymer','VP/Eicosene Copolymer',1,1),
  ('ING2699','Iron Oxide Yellow','Iron Oxide Yellow',1,1),
  ('ING2700','Iron Oxide Red','Iron Oxide Red',1,1),
  ('ING2701','t-Butyl','t-Butyl',1,1),
  ('ING2702','Ethyl Menthane Carboxamide','Ethyl Menthane Carboxamide',1,1),
  ('ING2703','Mesembryanthemum Crystallinum Extract','Mesembryanthemum Crystallinum Extract',1,1),
  ('ING2704','TRICONTANYL PVP','TRICONTANYL PVP',1,1),
  ('ING2705','PROPYLENE GLYCOL ISOSTEARATE','PROPYLENE GLYCOL ISOSTEARATE',1,1),
  ('ING2706','ETHYLCELLULOSE','ETHYLCELLULOSE',1,1),
  ('ING2707','methoxypropylamino cyclohexenylidene ethoxyethylcyanoacetate','methoxypropylamino cyclohexenylidene ethoxyethylcyanoacetate',1,1),
  ('ING2708','bis-ethyhexyloxyphenol methoxyphenyl triazine','bis-ethyhexyloxyphenol methoxyphenyl triazine',1,1),
  ('ING2709','capryl/capric triglyceride','capryl/capric triglyceride',1,1),
  ('ING2710','ηυρροχυαεετορηεμονε','ηυρροχυαεετορηεμονε',1,1),
  ('ING2711','thermus thermophilus ferment','thermus thermophilus ferment',1,1),
  ('ING2712','Camellia Oleifera (Green Tea) Leaf Extract','Camellia Oleifera (Green Tea) Leaf Extract',1,1),
  ('ING2713','Peucedanum Graveolens (Dill) Extract','Peucedanum Graveolens (Dill) Extract',1,1),
  ('ING2714','Magnesium Aluminum Silicate','Magnesium Aluminum Silicate',1,1),
  ('ING2715','Aluminum Hydride','Aluminum Hydride',1,1),
  ('ING2716','Oenothera Biennis (Evening Primrose) Extract','Oenothera Biennis (Evening Primrose) Extract',1,1),
  ('ING2717','Camelia Snensle Leaf Extract','Camelia Snensle Leaf Extract',1,1),
  ('ING2718','Frapranoe','Frapranoe',1,1),
  ('ING2719','Hydooycitronalat','Hydooycitronalat',1,1),
  ('ING2720','Butylootyl Salicylate','Butylootyl Salicylate',1,1),
  ('ING2721','Sodium Polya cryloyldimethyl Taurate','Sodium Polya cryloyldimethyl Taurate',1,1),
  ('ING2722','Polyacrylate Crosspolym er-6','Polyacrylate Crosspolym er-6',1,1),
  ('ING2723','Fruotose','Fruotose',1,1),
  ('ING2724','Nelumbo Nucifera Seed Extract','Nelumbo Nucifera Seed Extract',1,1),
  ('ING2725','Nylon - 12. Polysilicone-15','Nylon - 12. Polysilicone-15',1,1),
  ('ING2726','Polyglyceryl 3 Distearate 1','Polyglyceryl 3 Distearate 1',1,1),
  ('ING2727','2- Hexanediol Tromethamine','2- Hexanediol Tromethamine',1,1),
  ('ING2728','Polyhydroxystanic Acid','Polyhydroxystanic Acid',1,1),
  ('ING2729','Hydroxyacanophenone Stearic Acid','Hydroxyacanophenone Stearic Acid',1,1),
  ('ING2730','Polar Sante Bom Polyacryloyldimthyl Tautate','Polar Sante Bom Polyacryloyldimthyl Tautate',1,1),
  ('ING2731','Polyglyceryl 2 Dipoli ydroxytearate','Polyglyceryl 2 Dipoli ydroxytearate',1,1),
  ('ING2732','Glybory Stearateit','Glybory Stearateit',1,1),
  ('ING2733','Bulylene Glycol','Bulylene Glycol',1,1),
  ('ING2734','Ocimum Basilicum (Basil) Oil','Ocimum Basilicum (Basil) Oil',1,1),
  ('ING2735','cetearyl olivate sorbitan olivate','cetearyl olivate sorbitan olivate',1,1),
  ('ING2736','vp/hexadecene copolymer','vp/hexadecene copolymer',1,1),
  ('ING2737','ammonium polyacrylate','ammonium polyacrylate',1,1),
  ('ING2738','Tannic Acid','Tannic Acid',1,1),
  ('ING2739','Solanum Lycopersicum (Tomato) Seed Oil','Solanum Lycopersicum (Tomato) Seed Oil',1,1),
  ('ING2740','Mangifera Indica (Mango) Seed Oil','Mangifera Indica (Mango) Seed Oil',1,1),
  ('ING2741','Citrus Paradisi (Grapefruit) Seed Oil','Citrus Paradisi (Grapefruit) Seed Oil',1,1),
  ('ING2742','4-Methylbenzylidene Camphor','4-Methylbenzylidene Camphor',1,1),
  ('ING2743','Butylene Glycol Dipotassium Glycyrrhizate','Butylene Glycol Dipotassium Glycyrrhizate',1,1),
  ('ING2744','Polysorbate 60 Stearic Acid','Polysorbate 60 Stearic Acid',1,1),
  ('ING2745','Triethanolamine Polymethyl Methacrylate','Triethanolamine Polymethyl Methacrylate',1,1),
  ('ING2746','Fragrance Tocopheryl Acetate','Fragrance Tocopheryl Acetate',1,1),
  ('ING2747','Origanum Vulgare Flower/ Leaf/Stem Extract','Origanum Vulgare Flower/ Leaf/Stem Extract',1,1),
  ('ING2748','Polyglyceryl-3 Polydimethyl siloxyethyl Dimethicone','Polyglyceryl-3 Polydimethyl siloxyethyl Dimethicone',1,1),
  ('ING2749','Polygl yceryl-2 Dipolyhydroxystearate','Polygl yceryl-2 Dipolyhydroxystearate',1,1),
  ('ING2750','Citrus Aur antium Bergamia (Bergamot) Fruit Oil','Citrus Aur antium Bergamia (Bergamot) Fruit Oil',1,1),
  ('ING2751','Pelargonium Grave olens Flower Oil','Pelargonium Grave olens Flower Oil',1,1),
  ('ING2752','Rosa Damascena Flower Oil','Rosa Damascena Flower Oil',1,1),
  ('ING2753','Echium Plan tagineum Seed Oil','Echium Plan tagineum Seed Oil',1,1),
  ('ING2754','Cardiospemum Halicacabum Flower/Leaf/Vine Ex tract','Cardiospemum Halicacabum Flower/Leaf/Vine Ex tract',1,1),
  ('ING2755','Alanine Arginine','Alanine Arginine',1,1),
  ('ING2756','Tuber Magnatum Extract','Tuber Magnatum Extract',1,1),
  ('ING2757','Wine Extract','Wine Extract',1,1),
  ('ING2758','Caprylic/Capric/Succinic Triglyceride','Caprylic/Capric/Succinic Triglyceride',1,1),
  ('ING2759','Amygdalus Dulcis (Sweet Almond) Oil','Amygdalus Dulcis (Sweet Almond) Oil',1,1),
  ('ING2760','Calendula Officinalis Oil','Calendula Officinalis Oil',1,1),
  ('ING2761','Glyceryl Monostearate','Glyceryl Monostearate',1,1),
  ('ING2762','Emulsifying Wax','Emulsifying Wax',1,1),
  ('ING2763','Butanepropane','Butanepropane',1,1),
  ('ING2764','dimethicone / inyl dimethicone crosspolymer','dimethicone / inyl dimethicone crosspolymer',1,1),
  ('ING2765','moringa pterygosperma seed extract','moringa pterygosperma seed extract',1,1),
  ('ING2766','palmitoyl tripetide-1','palmitoyl tripetide-1',1,1),
  ('ING2767','palmitoyl treopeptide-7','palmitoyl treopeptide-7',1,1),
  ('ING2768','Isobutylamido Thiazolyl Resorcinol','Isobutylamido Thiazolyl Resorcinol',1,1),
  ('ING2769','Glycyrrhiza Inflata Root Extract','Glycyrrhiza Inflata Root Extract',1,1),
  ('ING2770','Glucosylrutin','Glucosylrutin',1,1),
  ('ING2771','Isoquercitrin','Isoquercitrin',1,1),
  ('ING2772','Cyclopenlasiloxane','Cyclopenlasiloxane',1,1),
  ('ING2773','Mentha Piperita (Peppermint) Ieaf extract','Mentha Piperita (Peppermint) Ieaf extract',1,1),
  ('ING2774','Thymus Vulgaris (Thyme) Leaf Extract','Thymus Vulgaris (Thyme) Leaf Extract',1,1),
  ('ING2775','Triethoxyca prylylsilane','Triethoxyca prylylsilane',1,1),
  ('ING2776','pentaerythritol','pentaerythritol',1,1),
  ('ING2777','Distearmonium hectorite','Distearmonium hectorite',1,1),
  ('ING2778','Chia Seed extract','Chia Seed extract',1,1),
  ('ING2779','Ginger extract','Ginger extract',1,1),
  ('ING2780','hydrogenated dimethicone','hydrogenated dimethicone',1,1),
  ('ING2781','saccharide hydrolizates','saccharide hydrolizates',1,1),
  ('ING2782','Karen dili oil','Karen dili oil',1,1),
  ('ING2783','macaques root extract','macaques root extract',1,1),
  ('ING2784','chamomile flower','chamomile flower',1,1),
  ('ING2785','Damask rose bloom','Damask rose bloom',1,1),
  ('ING2786','blue weed seed oil','blue weed seed oil',1,1),
  ('ING2787','Pink foliage / leaf / stem extract','Pink foliage / leaf / stem extract',1,1),
  ('ING2788','inflorescence flower / leaf / vine extract','inflorescence flower / leaf / vine extract',1,1),
  ('ING2789','Sunflower seed oil unsound','Sunflower seed oil unsound',1,1),
  ('ING2790','Madecasoides','Madecasoides',1,1),
  ('ING2791','Carambola fruit extract','Carambola fruit extract',1,1),
  ('ING2792','Chamomile extract','Chamomile extract',1,1),
  ('ING2793','drum stick tree seed extract','drum stick tree seed extract',1,1),
  ('ING2794','Hydrogenated Rapeseed Oil','Hydrogenated Rapeseed Oil',1,1),
  ('ING2795','Copernicia Cerifera Cera','Copernicia Cerifera Cera',1,1),
  ('ING2796','Caprylic/Acpric Triglyceride','Caprylic/Acpric Triglyceride',1,1),
  ('ING2797','Sodium Hyaluronat','Sodium Hyaluronat',1,1),
  ('ING2798','Aloe Barbadenis Leaf Extract','Aloe Barbadenis Leaf Extract',1,1),
  ('ING2799','Rosa Centifolia Flower Water','Rosa Centifolia Flower Water',1,1),
  ('ING2800','MUSA SAPIENTUM (BANANA) FLOWER EXTRACT','MUSA SAPIENTUM (BANANA) FLOWER EXTRACT',1,1),
  ('ING2801','Xanthium Strumarium Fruit Extract','Xanthium Strumarium Fruit Extract',1,1),
  ('ING2802','Sophora Angustifolia Root Extract','Sophora Angustifolia Root Extract',1,1),
  ('ING2803','Benzophenone-3','Benzophenone-3',1,1),
  ('ING2804','Hippophae Rhamnoides Extract (Экстракт облепихи)','Hippophae Rhamnoides Extract (Экстракт облепихи)',1,1),
  ('ING2805','Sodium Acryloyldimethyl','Sodium Acryloyldimethyl',1,1),
  ('ING2806','Taurate Copolymer','Taurate Copolymer',1,1),
  ('ING2807','Ascorbyl','Ascorbyl',1,1),
  ('ING2808','Palmitate','Palmitate',1,1),
  ('ING2809','2-HYDROXY-4-METHOXY BENZOPHENONE','2-HYDROXY-4-METHOXY BENZOPHENONE',1,1),
  ('ING2810','disopropyl sebacate','disopropyl sebacate',1,1),
  ('ING2811','lauryl lactate','lauryl lactate',1,1),
  ('ING2812','c 12-15 alkyl benzonate','c 12-15 alkyl benzonate',1,1),
  ('ING2813','polymethyl methacrylate','polymethyl methacrylate',1,1),
  ('ING2814','Tris-biphenyl triazine (nano)','Tris-biphenyl triazine (nano)',1,1),
  ('ING2815','polyester-5','polyester-5',1,1),
  ('ING2816','и еще половина состава.','и еще половина состава.',1,1),
  ('ING2817','Panax Ginseng Extract','Panax Ginseng Extract',1,1),
  ('ING2818','Panax Ginseng Leaf/Stem Extract','Panax Ginseng Leaf/Stem Extract',1,1),
  ('ING2819','Angelica Archangelica Root Oil','Angelica Archangelica Root Oil',1,1),
  ('ING2820','Citrus Aurantium','Citrus Aurantium',1,1),
  ('ING2821','Amara (Bitter Orange) Leaf/Twig Oil','Amara (Bitter Orange) Leaf/Twig Oil',1,1),
  ('ING2822','Jasminum Officinale (Jasmine) Oil','Jasminum Officinale (Jasmine) Oil',1,1),
  ('ING2823','Panax Ginseng Root','Panax Ginseng Root',1,1),
  ('ING2824','Extract','Extract',1,1),
  ('ING2825','C30-45 Alkyldimethylsilyl Polypropylsilsesquioxane','C30-45 Alkyldimethylsilyl Polypropylsilsesquioxane',1,1),
  ('ING2826','Centella Asiatica Extract (9','Centella Asiatica Extract (9',1,1),
  ('ING2827','Betula Platyphylla Japonica Bark Extract','Betula Platyphylla Japonica Bark Extract',1,1),
  ('ING2828','Medicago Sativa (Alfalfa) Leaf Extract','Medicago Sativa (Alfalfa) Leaf Extract',1,1),
  ('ING2829','Brassica Oleracea Italica (Broccoli) Sprout Extract','Brassica Oleracea Italica (Broccoli) Sprout Extract',1,1),
  ('ING2830','Eruca Sativa Leaf Extract','Eruca Sativa Leaf Extract',1,1),
  ('ING2831','Centella Asiatica Extract (29','Centella Asiatica Extract (29',1,1),
  ('ING2832','Diethylhexyl 2','Diethylhexyl 2',1,1),
  ('ING2833','6-Naphthalate','6-Naphthalate',1,1),
  ('ING2834','Agave Tequiiana Leaf Extract','Agave Tequiiana Leaf Extract',1,1),
  ('ING2835','CERAMID AP','CERAMID AP',1,1),
  ('ING2836','CERAMID EOP','CERAMID EOP',1,1),
  ('ING2837','Olive Glycerides','Olive Glycerides',1,1),
  ('ING2838','Carota Sativa (Wild Carrot) Seed Oil','Carota Sativa (Wild Carrot) Seed Oil',1,1),
  ('ING2839','Prunus Cerasus (Bitter Cherry) Fruit Extract','Prunus Cerasus (Bitter Cherry) Fruit Extract',1,1),
  ('ING2840','Monarda Didyma (Scarlet Beebalm) Extract','Monarda Didyma (Scarlet Beebalm) Extract',1,1),
  ('ING2841','Chamomilla Recutita (Matricaria) Oil','Chamomilla Recutita (Matricaria) Oil',1,1),
  ('ING2842','п','п',1,1),
  ('ING2843','Laureth-12','Laureth-12',1,1),
  ('ING2844','Dihydroxypropyl Arginine HCl','Dihydroxypropyl Arginine HCl',1,1),
  ('ING2845','Avena Sativa Kernel Flour','Avena Sativa Kernel Flour',1,1),
  ('ING2846','Potassium Myristate','Potassium Myristate',1,1),
  ('ING2847','Potassium Laurate','Potassium Laurate',1,1),
  ('ING2848','Potassium Stearate','Potassium Stearate',1,1),
  ('ING2849','PEG-80 GLYCERYL COCOATE','PEG-80 GLYCERYL COCOATE',1,1),
  ('ING2850','PPG-2 HYDROXYETHYL COCAMIDE','PPG-2 HYDROXYETHYL COCAMIDE',1,1),
  ('ING2851','PPG-2 HYDROXYETHYL COCO/ISOSTEARAMIDE','PPG-2 HYDROXYETHYL COCO/ISOSTEARAMIDE',1,1),
  ('ING2852','MAGNESIUM LAURETH SULFATE','MAGNESIUM LAURETH SULFATE',1,1),
  ('ING2853','MAGNESIUM LAURETH-8 SULFATE','MAGNESIUM LAURETH-8 SULFATE',1,1),
  ('ING2854','MAGNESIUM OLETH SULFATE','MAGNESIUM OLETH SULFATE',1,1),
  ('ING2855','ASCORBYL PALMITATE. [BI 722]','ASCORBYL PALMITATE. [BI 722]',1,1),
  ('ING2856','CAPRYL/CAPRAMIDOPROPYL BETAINE','CAPRYL/CAPRAMIDOPROPYL BETAINE',1,1),
  ('ING2857','Sodium Laureth-6 Carboxylate','Sodium Laureth-6 Carboxylate',1,1),
  ('ING2858','Hamamelis Virginiana (Witch Hazel) Leaf Water','Hamamelis Virginiana (Witch Hazel) Leaf Water',1,1),
  ('ING2859','Saponaria Officinalis Root Extract','Saponaria Officinalis Root Extract',1,1),
  ('ING2860','Viscum Album (Mistletoe) Leaf Extract','Viscum Album (Mistletoe) Leaf Extract',1,1),
  ('ING2861','Hydroxycinnamic Acid','Hydroxycinnamic Acid',1,1),
  ('ING2862','Mentha Rotundifolia Leaf Extract','Mentha Rotundifolia Leaf Extract',1,1),
  ('ING2863','Ceramide 4','Ceramide 4',1,1),
  ('ING2864','Ceramide 1','Ceramide 1',1,1),
  ('ING2865','Ceramide 6 II','Ceramide 6 II',1,1),
  ('ING2866','TURMERIC EXTRACT','TURMERIC EXTRACT',1,1),
  ('ING2867','SODIUM EDTA','SODIUM EDTA',1,1),
  ('ING2868','CL15985','CL15985',1,1),
  ('ING2869','Chamomilla Recutita (Matricaria) Leaf Extract','Chamomilla Recutita (Matricaria) Leaf Extract',1,1),
  ('ING2870','PEG-200 HYDROGENATED GLYCERYLPALMATE','PEG-200 HYDROGENATED GLYCERYLPALMATE',1,1),
  ('ING2871','SODIUM GLYCOLATE','SODIUM GLYCOLATE',1,1),
  ('ING2872','BUTYROSPERMUMPARKII SEEDCAKE EXTRACT','BUTYROSPERMUMPARKII SEEDCAKE EXTRACT',1,1),
  ('ING2873','SHEA BUTTER SEED EXTRACT','SHEA BUTTER SEED EXTRACT',1,1),
  ('ING2874','Aqua with infusions of Pinus Sylvestris Trunk Water (вытяжка «золотой» сосны)','Aqua with infusions of Pinus Sylvestris Trunk Water (вытяжка «золотой» сосны)',1,1),
  ('ING2875','Organic Prunus Persica Kernel Oil (органическое масло персика)','Organic Prunus Persica Kernel Oil (органическое масло персика)',1,1),
  ('ING2876','elettaria cardamomum (cardamom) seed extract','elettaria cardamomum (cardamom) seed extract',1,1),
  ('ING2877','cupressus sempervirens leaf extract','cupressus sempervirens leaf extract',1,1),
  ('ING2878','coffea arabica (coffee) leaf/seed extract','coffea arabica (coffee) leaf/seed extract',1,1),
  ('ING2879','cananga odorata flower extract','cananga odorata flower extract',1,1),
  ('ING2880','citrus auranitum bergamia (bergamot) fruit extract','citrus auranitum bergamia (bergamot) fruit extract',1,1),
  ('ING2881','santalum album (sandalwood) wood extract','santalum album (sandalwood) wood extract',1,1),
  ('ING2882','CITRUS AURANTIUM AMARA (BITTER ORANGE) FLOWER WATER','CITRUS AURANTIUM AMARA (BITTER ORANGE) FLOWER WATER',1,1),
  ('ING2883','LEPIDIUM SATIVUM SPROUT EXTRACT','LEPIDIUM SATIVUM SPROUT EXTRACT',1,1),
  ('ING2884','SODIUM BENZOATE POTASSIUM SORBATE','SODIUM BENZOATE POTASSIUM SORBATE',1,1),
  ('ING2885','AVENE AQUA','AVENE AQUA',1,1),
  ('ING2886','ISOCETYL STEAROYL STEARATE','ISOCETYL STEAROYL STEARATE',1,1),
  ('ING2887','SILYBUM MARIANUM (LADY''S THISTLE) EXTRACT','SILYBUM MARIANUM (LADY''S THISTLE) EXTRACT',1,1),
  ('ING2888','BETULA ALBA (BIRCH) BARK EXTRACT','BETULA ALBA (BIRCH) BARK EXTRACT',1,1),
  ('ING2889','SACCHAROMYCES LYSATE EXTRACT','SACCHAROMYCES LYSATE EXTRACT',1,1),
  ('ING2890','THERMUS THERMOPHILLUS FERMENT','THERMUS THERMOPHILLUS FERMENT',1,1),
  ('ING2891','OLETH-10','OLETH-10',1,1),
  ('ING2892','ALOE BARBADENSIS LEAF POLYSACCHARIDES','ALOE BARBADENSIS LEAF POLYSACCHARIDES',1,1),
  ('ING2893','RED 4 (CI 14700)','RED 4 (CI 14700)',1,1),
  ('ING2894','OLEA EUROPAEA (OLIVE) FRUIT EXTRACT','OLEA EUROPAEA (OLIVE) FRUIT EXTRACT',1,1),
  ('ING2895','TRITICUM VULGARE (WHEAT) BRAN EXTRACT','TRITICUM VULGARE (WHEAT) BRAN EXTRACT',1,1),
  ('ING2896','WHEY PROTEIN\LACTIS PROTEIN\PROTEINE DU PETIT-LAIT','WHEY PROTEIN\LACTIS PROTEIN\PROTEINE DU PETIT-LAIT',1,1),
  ('ING2897','PYRIDOXINE DIPALMITATE','PYRIDOXINE DIPALMITATE',1,1),
  ('ING2898','PEG-150','PEG-150',1,1),
  ('ING2899','SODIUM HEXAMETAPHOSPHATE','SODIUM HEXAMETAPHOSPHATE',1,1),
  ('ING2900','ceramide IO','ceramide IO',1,1),
  ('ING2901','ceramide ACE','ceramide ACE',1,1),
  ('ING2902','heptasodium hexa Carboxymethyl dipeptide-12','heptasodium hexa Carboxymethyl dipeptide-12',1,1),
  ('ING2903','Peg-40 Stearate','Peg-40 Stearate',1,1),
  ('ING2904','Lactobacillus/Rice Ferment Filtrate','Lactobacillus/Rice Ferment Filtrate',1,1),
  ('ING2905','Hydroxypropyl Bispalmitamide Mea','Hydroxypropyl Bispalmitamide Mea',1,1),
  ('ING2906','Hydroxypropyl Bislauramide Mea','Hydroxypropyl Bislauramide Mea',1,1),
  ('ING2907','Acrylates/Ammonium Methacrylate Copolymer','Acrylates/Ammonium Methacrylate Copolymer',1,1),
  ('ING2908','Citrullus Lanatus (Watermelon) Fruit Extract','Citrullus Lanatus (Watermelon) Fruit Extract',1,1),
  ('ING2909','Lens Esculenta (Lentil) Fruit Extract','Lens Esculenta (Lentil) Fruit Extract',1,1),
  ('ING2910','Vitis Vinifera (Grape) Juice Extract','Vitis Vinifera (Grape) Juice Extract',1,1),
  ('ING2911','Glutamylamidoethyl Imidazole','Glutamylamidoethyl Imidazole',1,1),
  ('ING2912','Tetrahydrobisdemethoxydiferuloylmethane','Tetrahydrobisdemethoxydiferuloylmethane',1,1),
  ('ING2913','Tetrahydrodemethoxydiferuloylmethane','Tetrahydrodemethoxydiferuloylmethane',1,1),
  ('ING2914','Tetrahydrodiferuloylmethane','Tetrahydrodiferuloylmethane',1,1),
  ('ING2915','MELIA AZADIRACHTA LEAF/FLOWER EXTRACT','MELIA AZADIRACHTA LEAF/FLOWER EXTRACT',1,1),
  ('ING2916','LAWSONIA INERMIS (HENNA) FLOWER/FRUIT/LEAF EXTRACT','LAWSONIA INERMIS (HENNA) FLOWER/FRUIT/LEAF EXTRACT',1,1),
  ('ING2917','OCIMUM SANCTUM LEAF EXTRACT/OCIMUM BASILCUM FLOWER/LEAF EXTRACT','OCIMUM SANCTUM LEAF EXTRACT/OCIMUM BASILCUM FLOWER/LEAF EXTRACT',1,1),
  ('ING2918','NEEM FLOWERS AMINO ACIDS','NEEM FLOWERS AMINO ACIDS',1,1),
  ('ING2919','Ribes Nigrum Oil','Ribes Nigrum Oil',1,1),
  ('ING2920','Cyclopentosiloxane','Cyclopentosiloxane',1,1),
  ('ING2921','Hamamelis Virginiana (Witch Hazel) Bark / Leaf / Twig Extract','Hamamelis Virginiana (Witch Hazel) Bark / Leaf / Twig Extract',1,1),
  ('ING2922','Aloe Barbodenis Leaf Juice','Aloe Barbodenis Leaf Juice',1,1),
  ('ING2923','Saccharomyces Cerevisioe Extract','Saccharomyces Cerevisioe Extract',1,1),
  ('ING2924','Trificum Vulgare (Wheat) Germ Extract','Trificum Vulgare (Wheat) Germ Extract',1,1),
  ('ING2925','Sesamum Indicum (Sesame) Seed Extract','Sesamum Indicum (Sesame) Seed Extract',1,1),
  ('ING2926','Cordyceps Sinensis Extract','Cordyceps Sinensis Extract',1,1),
  ('ING2927','Ganoderma Lucidum (Mushroom) Extract','Ganoderma Lucidum (Mushroom) Extract',1,1),
  ('ING2928','Sodium Hyoluronate','Sodium Hyoluronate',1,1),
  ('ING2929','Sodium Acrylatle/Sodium Acryloyldimethyl Tourate Copolymer','Sodium Acrylatle/Sodium Acryloyldimethyl Tourate Copolymer',1,1),
  ('ING2930','Isohexodecane','Isohexodecane',1,1),
  ('ING2931','Celearyl Glucoside','Celearyl Glucoside',1,1),
  ('ING2932','Tocopheryl Acelate','Tocopheryl Acelate',1,1),
  ('ING2933','Dipotassium Glycymhizate','Dipotassium Glycymhizate',1,1),
  ('ING2934','Nordihydroguaiarefic Acid','Nordihydroguaiarefic Acid',1,1),
  ('ING2935','1,2-Hexonediol','1,2-Hexonediol',1,1),
  ('ING2936','Hydroxyocelophenone','Hydroxyocelophenone',1,1),
  ('ING2937','Cera Microcristallina','Cera Microcristallina',1,1),
  ('ING2938','Lanolin Alcohol (Eucerit®)','Lanolin Alcohol (Eucerit®)',1,1),
  ('ING2939','Stearyl Stearate','Stearyl Stearate',1,1),
  ('ING2940','Rhus Verniciflua Peel Cera','Rhus Verniciflua Peel Cera',1,1),
  ('ING2941','Rhododendron Ferrugineum Extract','Rhododendron Ferrugineum Extract',1,1),
  ('ING2942','Lithothamnion Calcareum Extract','Lithothamnion Calcareum Extract',1,1),
  ('ING2943','Bis-Peg/Ppg-14/14 Dimethicone','Bis-Peg/Ppg-14/14 Dimethicone',1,1),
  ('ING2944','Dipentaerythrityl Tetrahydroxystearate/Tetraisostearate','Dipentaerythrityl Tetrahydroxystearate/Tetraisostearate',1,1),
  ('ING2945','Empetrum Nigrum Fruit Juice','Empetrum Nigrum Fruit Juice',1,1),
  ('ING2946','Ci 77007 / Ultramarines','Ci 77007 / Ultramarines',1,1),
  ('ING2947','Pentaerythrityl Stearate/caprate/caprylate/adipate','Pentaerythrityl Stearate/caprate/caprylate/adipate',1,1),
  ('ING2948','Polyglyceryl-5 Stearate','Polyglyceryl-5 Stearate',1,1),
  ('ING2949','Palmitoyl Palmitamide Mea','Palmitoyl Palmitamide Mea',1,1),
  ('ING2950','N-decanoyl Serinol','N-decanoyl Serinol',1,1),
  ('ING2951','Olea Europaea (Olive) Fruitoil','Olea Europaea (Olive) Fruitoil',1,1),
  ('ING2952','Viscum Album (Mistletoe) Fruit Extract','Viscum Album (Mistletoe) Fruit Extract',1,1),
  ('ING2953','Sunflower Oil Decyl Esters','Sunflower Oil Decyl Esters',1,1),
  ('ING2954','Juniperus Communis Fruit Oil','Juniperus Communis Fruit Oil',1,1),
  ('ING2955','hydrolysed lechitin','hydrolysed lechitin',1,1),
  ('ING2956','Myristoylpalmitoyl Oxostearamide/Arachamide Mea','Myristoylpalmitoyl Oxostearamide/Arachamide Mea',1,1),
  ('ING2957','Polyglyceryl-10 Distearate','Polyglyceryl-10 Distearate',1,1),
  ('ING2958','Sodium Levulinate','Sodium Levulinate',1,1),
  ('ING2959','OCTYLDODECYL MYRISTATE','OCTYLDODECYL MYRISTATE',1,1),
  ('ING2960','PRUNUS AMYGDALUS DULCIS OIL / PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL','PRUNUS AMYGDALUS DULCIS OIL / PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL',1,1),
  ('ING2961','TRIHEPTANOIN','TRIHEPTANOIN',1,1),
  ('ING2962','DILINOLEIC ACID/BUTANEDIOL COPOLYMER','DILINOLEIC ACID/BUTANEDIOL COPOLYMER',1,1),
  ('ING2963','SUCROSE COCOATE','SUCROSE COCOATE',1,1),
  ('ING2964','CASTOR OIL/IPDI COPOLYMER','CASTOR OIL/IPDI COPOLYMER',1,1),
  ('ING2965','Lauryl Polyglyceryl-3 Polydimethylsiloxyethyl Dimethicone','Lauryl Polyglyceryl-3 Polydimethylsiloxyethyl Dimethicone',1,1),
  ('ING2966','PARAFFINUM LIQUIDUM/MINERAL OIL/HUILE MINERALE','PARAFFINUM LIQUIDUM/MINERAL OIL/HUILE MINERALE',1,1),
  ('ING2967','BRASSICA CAMPESTRIS (RAPESEED) SEED OIL','BRASSICA CAMPESTRIS (RAPESEED) SEED OIL',1,1),
  ('ING2968','LAMINARIA OCHROLEUCA EXTRACT.','LAMINARIA OCHROLEUCA EXTRACT.',1,1),
  ('ING2969','LAURYL PEG-18/18 METHICONE','LAURYL PEG-18/18 METHICONE',1,1),
  ('ING2970','TRIETHOXYCAPRYLSILANE','TRIETHOXYCAPRYLSILANE',1,1),
  ('ING2971','ALUMINIUM HYDROXIDE','ALUMINIUM HYDROXIDE',1,1),
  ('ING2972','FAGUS SYLVATICA BUD EXTRACT','FAGUS SYLVATICA BUD EXTRACT',1,1),
  ('ING2973','AVENE THERMALE SPRING WATER (AVENE AQUA)','AVENE THERMALE SPRING WATER (AVENE AQUA)',1,1),
  ('ING2974','CETERARYL GLUCOSIDE','CETERARYL GLUCOSIDE',1,1),
  ('ING2975','AQUAPHILUS DOLOMIAE EXTRACT','AQUAPHILUS DOLOMIAE EXTRACT',1,1),
  ('ING2976','PALM OIL AMINOPROPANEDIOL ESTERS','PALM OIL AMINOPROPANEDIOL ESTERS',1,1),
  ('ING2977','SODIUM ACRYLATE/ ACRYLOYLDIMETHYLTAURATE/ DIMETHYLACRYLAMIDE CROSSPOLYMER','SODIUM ACRYLATE/ ACRYLOYLDIMETHYLTAURATE/ DIMETHYLACRYLAMIDE CROSSPOLYMER',1,1),
  ('ING2978','DIATOMACEOUS EARTH','DIATOMACEOUS EARTH',1,1),
  ('ING2979','CALCIUM SULFATE','CALCIUM SULFATE',1,1),
  ('ING2980','TETRASODIUM PYROPHOSPHATE','TETRASODIUM PYROPHOSPHATE',1,1),
  ('ING2981','CI 77007','CI 77007',1,1),
  ('ING2982','SWEET ORANGE (CITRUS SINENSIS) EXTRACT','SWEET ORANGE (CITRUS SINENSIS) EXTRACT',1,1),
  ('ING2983','Trimethylsiloxyphenyl Dimethicone','Trimethylsiloxyphenyl Dimethicone',1,1),
  ('ING2984','Ethylene /acrylic Acid Copolymer','Ethylene /acrylic Acid Copolymer',1,1),
  ('ING2985','Cetyl Dimethicone','Cetyl Dimethicone',1,1),
  ('ING2986','Aroma / Flavor','Aroma / Flavor',1,1),
  ('ING2987','Poloxamer 338','Poloxamer 338',1,1),
  ('ING2988','Nylon-6','Nylon-6',1,1),
  ('ING2989','Ethylene/Va Copolymer','Ethylene/Va Copolymer',1,1),
  ('ING2990','CIRSIUM ERIOPHORUM CALLUS EXTRACT','CIRSIUM ERIOPHORUM CALLUS EXTRACT',1,1),
  ('ING2991','RUBUS IDAEUS (RASPBERRY) LEAF EXTRACT','RUBUS IDAEUS (RASPBERRY) LEAF EXTRACT',1,1),
  ('ING2992','Camellia Japonica seed Extract','Camellia Japonica seed Extract',1,1),
  ('ING2993','Cymbopogon Citratus Extract','Cymbopogon Citratus Extract',1,1),
  ('ING2994','Chamomilla Recutita Flower Water','Chamomilla Recutita Flower Water',1,1),
  ('ING2995','CYCLOHEXANE SILOXANE','CYCLOHEXANE SILOXANE',1,1),
  ('ING2996','POLOXAMER-33','POLOXAMER-33',1,1),
  ('ING2997','DISODIUM EDTA HYDROLYZED HYALURONIC ACID','DISODIUM EDTA HYDROLYZED HYALURONIC ACID',1,1),
  ('ING2998','TOLUENESULFONIC SULFONIC ACID','TOLUENESULFONIC SULFONIC ACID',1,1),
  ('ING2999','Chrysanthemum Indicum Flower Extract','Chrysanthemum Indicum Flower Extract',1,1),
  ('ING3000','BIS-DIISOPROPANOLAMINO-PG-PROPYL DIMETHICONE/BIS-ISOBUTYL PEG-14 COPOLYMER','BIS-DIISOPROPANOLAMINO-PG-PROPYL DIMETHICONE/BIS-ISOBUTYL PEG-14 COPOLYMER',1,1)
ON CONFLICT (ingredient_id) DO UPDATE SET canonical_name=EXCLUDED.canonical_name, aliases=EXCLUDED.aliases;