INSERT INTO ingredients_dictionary (ingredient_id,canonical_name,aliases,product_count,occurrence_count)
VALUES
  ('ING0501','Sodium Sulfate','Sodium Sulfate; SODIUM SULFATE',8,9),
  ('ING0502','Mineral Oil','Mineral Oil; MINERAL OIL; MINERAL OIL (PARAFFINUM LIQUIDUM)',8,8),
  ('ING0503','Climbazole','Climbazole; climbazole',8,8),
  ('ING0504','Ammonium Polyacryloyldimethyl Taurate','Ammonium Polyacryloyldimethyl Taurate; AMMONIUM POLYACRYLOYLDIMETHYL TAURATE; ammonium polyacryloyldimethyl taurate',8,8),
  ('ING0505','Polyquaternium-51','Polyquaternium-51',8,8),
  ('ING0506','Diethylhexyl Butamido Triazone','Diethylhexyl Butamido Triazone; DIETHYLHEXYL BUTAMIDO TRIAZONE',8,8),
  ('ING0507','Poly C10-30 Alkyl Acrylate','Poly C10-30 Alkyl Acrylate; POLY C10-30 ALKYL ACRYLATE',8,8),
  ('ING0508','Ceramide NS','Ceramide NS; ceramide NS',8,8),
  ('ING0509','Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer','Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer; VINYL DIMETHICONE/METHICONE SILSESQUIOXANE CROSSPOLYMER',8,8),
  ('ING0510','Phenethyl Alcohol','Phenethyl Alcohol; PHENETHYL ALCOHOL',8,8),
  ('ING0511','Agar','Agar; AGAR',8,8),
  ('ING0512','Methyl Trimethicone','Methyl Trimethicone; METHYL TRIMETHICONE; methyl trimethicone',8,8),
  ('ING0513','Tranexamic Acid','Tranexamic Acid',8,8),
  ('ING0514','CI 77492','CI 77492; Ci 77492; CI 77492 (IRON OXIDES); CI 77492 (IRON OXIDE); ci 77492',8,8),
  ('ING0515','Ascorbyl Glucoside','Ascorbyl Glucoside; ASCORBYL GLUCOSIDE; ascorbyl glucoside (2.00%)',8,8),
  ('ING0516','Mannitol','Mannitol; MANNITOL',8,8),
  ('ING0517','Melaleuca Alternifolia (Tea Tree) Leaf Extract','Melaleuca Alternifolia (Tea Tree) Leaf Extract; Melaleuca Alternifolia Leaf Extract; Melaleuca Alternifolia (Tea Tree) Leaf Extract (9800ppm)',8,8),
  ('ING0518','Glyceryl Polymethacrylate','Glyceryl Polymethacrylate; GLYCERYL POLYMETHACRYLATE',8,8),
  ('ING0519','Polyglyceryl-10 Stearate','Polyglyceryl-10 Stearate; POLYGLYCERYL-10 STEARATE',8,8),
  ('ING0520','Ubiquinone','Ubiquinone; UBIQUINONE',8,8),
  ('ING0521','CI 77491','CI 77491; Ci 77491; CI 77491 (IRON OXIDES); CI 77491 (IRON OXIDE); ci 77491',8,8),
  ('ING0522','Hexapeptide-9','Hexapeptide-9',8,8),
  ('ING0523','sh-Oligopeptide-1','sh-Oligopeptide-1; SH-Oligopeptide-1; Sh-oligopeptide-1',8,8),
  ('ING0524','Benzyl Glycol','Benzyl Glycol; benzyl glycol',8,8),
  ('ING0525','Olive Oil PEG-7 Esters','Olive Oil PEG-7 Esters; Olive Oil Peg-7 Esters',7,7),
  ('ING0526','Sodium C14-16 Olefin Sulfonate','Sodium C14-16 Olefin Sulfonate; SODIUM C14-16 OLEFIN SULFONATE',7,7),
  ('ING0527','Ananas Sativus (Pineapple) Fruit Extract','Ananas Sativus (Pineapple) Fruit Extract; ananas sativus (pineapple) fruit extract; Ananas Sativus Fruit Extract; Ananas sativus (pineapple) fruit Extract',7,7),
  ('ING0528','Pisum Sativum (Pea) Peptide','Pisum Sativum (Pea) Peptide; Pisum sativum (pea) peptide; Pisum Sativum (pea) Peptide; pisum sativum (pea) peptide; PISUM SATIVUM (PEA) PEPTIDE',7,7),
  ('ING0529','D-Panthenol','D-Panthenol; d-panthenol; D-PANTHENOL',7,7),
  ('ING0530','Ginkgo Biloba Leaf Extract','Ginkgo Biloba Leaf Extract; GINKGO BILOBA LEAF EXTRACT',7,7),
  ('ING0531','Lavandula Angustifolia (Lavender) Extract','Lavandula Angustifolia (Lavender) Extract; Lavandula Angustifolia Extract; lavandula angustifolia extract; lavandula angustifolia (lavender) extract',7,7),
  ('ING0532','Laminaria Saccharina Extract','Laminaria Saccharina Extract; Laminaria saccharina extract',7,7),
  ('ING0533','Betula alba Leaf Extract','Betula alba Leaf Extract; Betula Alba Leaf Extract; BETULA ALBA LEAF EXTRACT; betula alba leaf extract; Betula alba leaf extract',7,7),
  ('ING0534','C11-15 Pareth-7','C11-15 Pareth-7; c11-15 pareth-7; C11-15 PARETH-7',7,7),
  ('ING0535','Laureth-9','Laureth-9; LAURETH-9',7,7),
  ('ING0536','DMDM Hydantoin','DMDM Hydantoin; DMDM HYDANTOIN; Dmdm Hydantoin',7,7),
  ('ING0537','Pullulan','Pullulan; pullulan; PULLULAN',7,7),
  ('ING0538','Distearoylethyl Dimonium Chloride','Distearoylethyl Dimonium Chloride; DISTEAROYLETHYL DIMONIUM CHLORIDE',7,7),
  ('ING0539','Disiloxane','Disiloxane; DISILOXANE; disiloxane',7,7),
  ('ING0540','CAPRYLOYL GLYCINE','CAPRYLOYL GLYCINE; Capryloyl Glycine; capryloyl glycine',7,7),
  ('ING0541','Hydrolyzed Vegetable Protein','Hydrolyzed Vegetable Protein',7,7),
  ('ING0542','Camellia Sinensis Seed Oil','Camellia Sinensis Seed Oil; camellia sinensis seed oil; Camellia Sinensis (Green Tea) Seed Oil',7,7),
  ('ING0543','Coco-Caprylate','Coco-Caprylate; COCO-CAPRYLATE; coco-caprylate',7,7),
  ('ING0544','Beta-Carotene','Beta-Carotene',7,7),
  ('ING0545','Thioctic Acid','Thioctic Acid; thioctic acid',7,8),
  ('ING0546','Laureth-23','Laureth-23; LAURETH-23',7,7),
  ('ING0547','Sesamum Indicum (Sesame) Seed Oil','Sesamum Indicum (Sesame) Seed Oil; sesamum indicum seed oil; SESAMUM INDICUM (SESAME) SEED OIL',7,7),
  ('ING0548','Vitis Vinifera (Grape) Seed Extract','Vitis Vinifera (Grape) Seed Extract; VITIS VINIFERA (GRAPE) SEED EXTRACT; Vitis Vinifera Seed Extract',7,7),
  ('ING0549','Sphingolipids','Sphingolipids; SPHINGOLIPIDS',7,7),
  ('ING0550','Citrus Limon (Lemon) Peel Oil','Citrus Limon (Lemon) Peel Oil; Citrus Limon (Lemon) Peel Oil*; CITRUS LIMON (LEMON) PEEL OIL*; Citrus Limon (Lemon) Peel Oil.; Citrus Limon(Lemon) Peel Oil',7,7),
  ('ING0551','CI 77891 (Titanium Dioxide)','CI 77891 (Titanium Dioxide); CI 77891 (TITANIUM DIOXIDE); CI 77891; ci 77891; Ci 77891',7,7),
  ('ING0552','PEG-7 PROPYLHEPTYL ETHER','PEG-7 PROPYLHEPTYL ETHER; PEG-7 Propylheptyl Ether',7,7),
  ('ING0553','Cellulose','Cellulose; CELLULOSE',7,7),
  ('ING0554','Oryza Sativa (Rice) Bran Extract','Oryza Sativa (Rice) Bran Extract; Oryza Sativa (Rice) Bran Extract*; Oryza sativa Bran Extract',7,7),
  ('ING0555','Persea Gratissima (Avocado) Fruit Extract','Persea Gratissima (Avocado) Fruit Extract; Persea Gratissima (avocado) Fruit Extract; Persea Gratissima Fruit Extract; PERSEA GRATISSIMA (AVOCADO) FRUIT EXTRACT',7,7),
  ('ING0556','Thiamine HCl','Thiamine HCl; Thiamine HCL; THIAMINE HCl; thiamine HCL',7,7),
  ('ING0557','Menthyl Lactate','Menthyl Lactate; MENTHYL LACTATE',7,8),
  ('ING0558','Dextran','Dextran',7,7),
  ('ING0559','PEG-2 LAURATE','PEG-2 LAURATE; Peg-2 Laurate',7,8),
  ('ING0560','Melissa Officinalis Leaf Extract','Melissa Officinalis Leaf Extract; *Melissa Officinalis Leaf Extract',7,7),
  ('ING0561','Hippophae Rhamnoides Fruit Extract','Hippophae Rhamnoides Fruit Extract; Hippophae rhamnoides Fruit Extract; HIPPOPHAE RHAMNOIDES FRUIT EXTRACT; Hippophae Rhamnoides Fruit Extract (3863ppm)',7,7),
  ('ING0562','SQUALENE','SQUALENE; Squalene',7,7),
  ('ING0563','Sorbitan Caprylate','Sorbitan Caprylate',7,7),
  ('ING0564','Ethylhexyl Glycerin','Ethylhexyl Glycerin; Ethylhexyl glycerin; ETHYLHEXYL GLYCERIN',7,7),
  ('ING0565','Butyrospermum Parkii (Shea Butter) Oil','Butyrospermum Parkii (Shea Butter) Oil; Butyrospermum Parkii (Shea) Oil; Butyrospermum Parkii Oil (Масло Ши); Butyrospermum Parkii Oil (масло Ши); Butyrospermum Parkii Oil; Butyrospermum Parkii (shea) Oil',7,7),
  ('ING0566','Trihydroxystearin','Trihydroxystearin; TRIHYDROXYSTEARIN',7,7),
  ('ING0567','Ethylhexyl Stearate','Ethylhexyl Stearate; Ethylhexyl stearate; ETHYLHEXYL STEARATE',7,7),
  ('ING0568','Polygonum Multiflorum (He Shou Wu) Root Extract','Polygonum Multiflorum (He Shou Wu) Root Extract; Polygonum Multiflorum (He Shou Wu) Root Extract*; Polygonum Multiflorum Root Extract; POLYGONUM MULTIFLORUM ROOT EXTRACT',7,7),
  ('ING0569','Salvia Sclarea (Clary) Oil','Salvia Sclarea (Clary) Oil; Salvia Sclarea (Clary Sage) Oil*; Salvia Sclarea (Clary) Oil*',7,7),
  ('ING0570','Polyglyceryl-3 Polydimethylsiloxyethyl Dimethicone','Polyglyceryl-3 Polydimethylsiloxyethyl Dimethicone; POLYGLYCERYL-3 POLYDIMETHYLSILOXYETHYL DIMETHICONE',7,7),
  ('ING0571','Nylon-12','Nylon-12; nylon-12; NYLON-12',7,7),
  ('ING0572','Phenylbenzimidazole Sulfonic Acid','Phenylbenzimidazole Sulfonic Acid; PHENYLBENZIMIDAZOLE SULFONIC ACID',7,7),
  ('ING0573','Anthemis Nobilis Flower Oil','Anthemis Nobilis Flower Oil; ANTHEMIS NOBILIS FLOWER OIL; Anthemis Nobilis (Chamomile) Flower Oil',7,7),
  ('ING0574','Tetrahexyldecyl Ascorbate','Tetrahexyldecyl Ascorbate; TETRAHEXYLDECYL ASCORBATE; Tetrahexyldecyl Ascorbate (Vitamin C)',7,7),
  ('ING0575','Microcrystalline Cellulose','Microcrystalline Cellulose; MICROCRYSTALLINE CELLULOSE',7,7),
  ('ING0576','Arachidyl Alcohol','Arachidyl Alcohol',7,7),
  ('ING0577','Arachidyl Glucoside','Arachidyl Glucoside',7,7),
  ('ING0578','Propylene Carbonate','Propylene Carbonate; PROPYLENE CARBONATE',7,7),
  ('ING0579','Talc','Talc; TALC; talc',7,7),
  ('ING0580','Polyglycerin-3','Polyglycerin-3',7,7),
  ('ING0581','Protease','Protease; Protease (0 07ppm); Protease (1000 ppm)',7,8),
  ('ING0582','Rosa Canina Fruit Extract','Rosa Canina Fruit Extract; ROSA CANINA FRUIT EXTRACT',6,6),
  ('ING0583','PPG-3 Caprylyl Ether','PPG-3 Caprylyl Ether; PPG-3 caprylyl ether',6,6),
  ('ING0584','RICINUS COMMUNIS SEED OIL / CASTOR SEED OIL','RICINUS COMMUNIS SEED OIL / CASTOR SEED OIL; Ricinus Communis Seed Oil / Castor Seed Oil; ricinus communis seed oil / castor seed oil',6,6),
  ('ING0585','Steareth-6','Steareth-6; STEARETH-6; steareth-6',6,6),
  ('ING0586','Chlorhexidine Digluconate','Chlorhexidine Digluconate; CHLORHEXIDINE DIGLUCONATE',6,6),
  ('ING0587','C10-40 Isoalkylamidopropylethyldimonium Ethosulfate','C10-40 Isoalkylamidopropylethyldimonium Ethosulfate',6,6),
  ('ING0588','PEG/PPG-15/15 Dimethicone','PEG/PPG-15/15 Dimethicone; PEG/PPG-15/15 dimethicone; PEG/PPG- 15/15 Dimethicone; PEG / PPG-15/15 Dimethicone',6,6),
  ('ING0589','GOSSYPIUM HERBACEUM (COTTON) SEED OIL','GOSSYPIUM HERBACEUM (COTTON) SEED OIL; Gossypium Herbaceum (Cotton) Seed Oil; Gossypium Herbaceum (Cotton) Seed OIl; Gossypium herbaceum (cotton) seed oil; Gossypium Herbaceum Seed Oil',6,6),
  ('ING0590','Cocos Nucifera Oil / Coconut Oil','Cocos Nucifera Oil / Coconut Oil; COCOS NUCIFERA OIL / COCONUT OIL; cocos nucifera oil / coconut oil',6,6),
  ('ING0591','Hamamelis Virginiana (Witch Hazel) Leaf Extract','Hamamelis Virginiana (Witch Hazel) Leaf Extract; Hamamelis Virginiana Leaf Extract; HAMAMELIS VIRGINIANA LEAF EXTRACT',6,6),
  ('ING0592','Polyquaternium-70','Polyquaternium-70; POLYQUATERNIUM-70; Polyquaternium 70',6,6),
  ('ING0593','TEA-Dodecylbenzenesulfonate','TEA-Dodecylbenzenesulfonate; TEA-dodecylbenzenesulfonate',6,6),
  ('ING0594','Bis-Hydroxy/Methoxy Amodimethicone','Bis-Hydroxy/Methoxy Amodimethicone',6,6),
  ('ING0595','Sclerocarya Birrea Seed Oil','Sclerocarya Birrea Seed Oil; SCLEROCARYA BIRREA SEED OIL; sclerocarya birrea seed oil',6,6),
  ('ING0596','Cucumis Sativus (Cucumber) Fruit Extract','Cucumis Sativus (Cucumber) Fruit Extract; cucumis sativus fruit extract; CUCUMIS SATIVUS (CUCUMBER) FRUIT EXTRACT; cucumis sativus (cucumber) fruit extract',6,6),
  ('ING0597','CI 47005','CI 47005; CI 47005 (Acid Yellow 3); ci 47005; CI 47005 (YELLOW 10)',6,6),
  ('ING0598','2-OLEAMIDO-1','2-OLEAMIDO-1; 2-Oleamido-1',6,6),
  ('ING0599','3-OCTADECANEDIOL','3-OCTADECANEDIOL; 3-Octadecanediol',6,6),
  ('ING0600','Prunus Persica (Peach) Fruit Extract','Prunus Persica (Peach) Fruit Extract; PRUNUS PERSICA (PEACH) FRUIT EXTRACT; Prunus Persica Fruit Extract',6,6),
  ('ING0601','Bis (C13-15 Alkoxy) PG-Amodimethicone','Bis (C13-15 Alkoxy) PG-Amodimethicone; Bis (C13-15 Alkoxy) PG Amodimethicone; BIS (C13-15 ALKOXY) PG-AMODIMETHICONE',6,6),
  ('ING0602','EDTA','EDTA; Edta; edta',6,6),
  ('ING0603','Potassium Phosphate','Potassium Phosphate; POTASSIUM PHOSPHATE',6,6),
  ('ING0604','Salvia Sclarea (Clary) Extract','Salvia Sclarea (Clary) Extract',6,6),
  ('ING0605','Isodecyl Neopentanoate','Isodecyl Neopentanoate; isodecyl neopentanoate',6,6),
  ('ING0606','Hamamelis Virginiana (Witch Hazel) Water','Hamamelis Virginiana (Witch Hazel) Water',6,6),
  ('ING0607','Deionized Water','Deionized Water; deionized water; Deionized water',6,6),
  ('ING0608','Pueraria Lobata Root Extract','Pueraria Lobata Root Extract',6,6),
  ('ING0609','C12-13 Pareth-23','C12-13 Pareth-23; C12-13 PARETH-23',6,6),
  ('ING0610','C12-13 Pareth-3','C12-13 Pareth-3; C12-13 PARETH-3',6,6),
  ('ING0611','Divinyldimethicone/Dimethicone Copolymer','Divinyldimethicone/Dimethicone Copolymer; Divinyldimethicone/ Dimethicone Copolymer; DivinylDimethicone/Dimethicone Copolymer; DIVINYLDIMETHICONE/DIMETHICONE COPOLYMER',6,6),
  ('ING0612','Sodium Lauroyl Methylaminopropionate','Sodium Lauroyl Methylaminopropionate',6,6),
  ('ING0613','Coconut Acid','Coconut Acid',6,6),
  ('ING0614','sh-Oligopeptide-78','sh-Oligopeptide-78; SH-Oligopeptide-78 (K18Peptide™); SH-Oligopeptide-78; Sh-Oligopeptide-78',6,6),
  ('ING0615','Calcium Gluconate','Calcium Gluconate; CALCIUM GLUCONATE',6,6),
  ('ING0616','C13-15 Alkane','C13-15 Alkane',6,6),
  ('ING0617','Potassium Cocoyl Glycinate','Potassium Cocoyl Glycinate; Potassium Cocoyl glycinate',6,6),
  ('ING0618','Disodium Cocoyl Glutamate','Disodium Cocoyl Glutamate; DISODIUM COCOYL GLUTAMATE',6,6),
  ('ING0619','Euterpe Oleracea Fruit Extract','Euterpe Oleracea Fruit Extract; EUTERPE OLERACEA FRUIT EXTRACT',6,6),
  ('ING0620','Punica Granatum Extract','Punica Granatum Extract; Punica Granatum (Pomegranate) Extract',6,6),
  ('ING0621','Punica Granatum Seed Oil','Punica Granatum Seed Oil; Punica Granatum (Pomegranate) Seed Oil',6,6),
  ('ING0622','Hydrolyzed Jojoba Esters','Hydrolyzed Jojoba Esters; HYDROLYZED JOJOBA ESTERS',6,6),
  ('ING0623','Ethylparaben','Ethylparaben; ETHYLPARABEN; ethylparaben',6,6),
  ('ING0624','Hydrolyzed Silk Protein','Hydrolyzed Silk Protein; hydrolyzed silk protein; HYDROLYZED SILK PROTEIN',6,6),
  ('ING0625','hydroxyisohexyl 3-cyclohexene carboxaldehyde','hydroxyisohexyl 3-cyclohexene carboxaldehyde; Hydroxyisohexyl 3-Cyclohexene Carboxaldehyde; HYDROXYISOHEXYL-3-CYCLOHEXENE CARBOXALDEHYDE',6,6),
  ('ING0626','Rosa Damascena Flower Water','Rosa Damascena Flower Water; Rosa Damascena (Rose) Flower Water; rosa damascena flower water (3 ppb); ROSA DAMASCENA FLOWER WATER',6,6),
  ('ING0627','Yeast Extract','Yeast Extract',6,6),
  ('ING0628','Pantolactone','Pantolactone; pantolactone',6,6),
  ('ING0629','CI 42090','CI 42090',6,6),
  ('ING0630','Nigella Sativa (Black Cumin) Seed Oil*','Nigella Sativa (Black Cumin) Seed Oil*; NIGELLA SATIVA (BLACK CUMIN) SEED OIL*; Nigella Sativa Seed Oil',6,6),
  ('ING0631','Niacin','Niacin; niacin; NIACIN',6,6),
  ('ING0632','P-ANISIC ACID','P-ANISIC ACID; p-Anisic Acid; P-Anisic Acid',6,6),
  ('ING0633','Biosaccharide Gum-4','Biosaccharide Gum-4; BIOSACCHARIDE GUM-4; Biosaccharide Gum- 4',6,6),
  ('ING0634','Taurine','Taurine; TAURINE',6,7),
  ('ING0635','Hydrogenated Phosphatidylcholine','Hydrogenated Phosphatidylcholine; HYDROGENATED PHOSPHATIDYLCHOLINE',6,6),
  ('ING0636','Calcium Pantothenate','Calcium Pantothenate; calcium pantothenate; CALCIUM PANTOTHENATE; calcium pantotheNate',6,6),
  ('ING0637','Polyglyceryl-4 Caprate','Polyglyceryl-4 Caprate; POLYGLYCERYL-4 CAPRATE',6,6),
  ('ING0638','PALMITOYL HEXAPEPTIDE-12','PALMITOYL HEXAPEPTIDE-12; Palmitoyl Hexapeptide-12',6,6),
  ('ING0639','Ethyl Hexanediol','Ethyl Hexanediol',6,6),
  ('ING0640','Hippophae Rhamnoides Fruit Oil','Hippophae Rhamnoides Fruit Oil; HIPPOPHAE RHAMNOIDES FRUIT OIL',6,6),
  ('ING0641','Synthetic Fluorphlogopite','Synthetic Fluorphlogopite; SYNTHETIC FLUORPHLOGOPITE',6,6),
  ('ING0642','Dimethicone Crosspolymer','Dimethicone Crosspolymer; dimethicone crosspolymer; DIMETHICONE CROSSPOLYMER',6,6),
  ('ING0643','Carthamus Tinctorius (Safflower) Flower Extract','Carthamus Tinctorius (Safflower) Flower Extract',6,6),
  ('ING0644','Beeswax','Beeswax; BEESWAX (CERA ALBA)',6,6),
  ('ING0645','Coptis Japonica Root Extract','Coptis Japonica Root Extract',6,6),
  ('ING0646','Propylheptyl Caprylate','Propylheptyl Caprylate; PROPYLHEPTYL CAPRYLATE',6,6),
  ('ING0647','Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate','Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate; Polyglyceryl-4 Diisostearate/Polyhydroxystearate Sebacate; Polyglyceryl-4 Diisostearate/ Polyhydroxystearate/ Sebacate',6,6),
  ('ING0648','Bifida Ferment Filtrate','Bifida Ferment Filtrate; Bifida Ferment Filtrate (3.59%); Bifida Ferment Filtrate(2.5ppb); Bifida Ferment Filtrate (388.98 ppm)',6,6),
  ('ING0649','Saccharomyces Ferment Filtrate','Saccharomyces Ferment Filtrate',6,6),
  ('ING0650','Simethicone','Simethicone; simethicone',6,6),
  ('ING0651','Methylene Bis-benzotriazolyl Tetramethylbutylphenol','Methylene Bis-benzotriazolyl Tetramethylbutylphenol; Methylene Bis-Benzotriazolyl Tetramethylbutylphenol; METHYLENE BIS-BENZOTRIAZOLYL TETRAMETHYLBUTYLPHENOL; Methylene Bis-Benzotriazolyl Tetramethylbutylphenol (nano)',6,6),
  ('ING0652','Guaiazulene','Guaiazulene; Guaiazulene (500Ppm); Guaiazulene(0.1Ppm)',6,6),
  ('ING0653','Ceramide AS','Ceramide AS',6,6),
  ('ING0654','Oenothera Biennis (Evening Primrose) Flower Extract','Oenothera Biennis (Evening Primrose) Flower Extract; Oenothera Biennis (evening Primrose) Flower Extract',6,6),
  ('ING0655','Polyhydroxystearic Acid','Polyhydroxystearic Acid',6,6),
  ('ING0656','DROMETRIZOLE TRISILOXANE','DROMETRIZOLE TRISILOXANE; drometrizole trisiloxane',6,6),
  ('ING0657','Isoceteth-20','Isoceteth-20',6,6),
  ('ING0658','Polyvinyl Alcohol','Polyvinyl Alcohol',6,6),
  ('ING0659','PEG-10 DIMETHICONE','PEG-10 DIMETHICONE; PEG 10 Dimethicone; PEG-10 dimethicone; Peg-10 Dimethicone; PEG-10 Dimethicone',6,6),
  ('ING0660','Calamine','Calamine',6,6),
  ('ING0661','CI 77499','CI 77499; CI 77499 (IRON OXIDES); CI 77499 (IRON OXIDE); ci 77499',6,6),
  ('ING0662','Artemisia Princeps Leaf Extract','Artemisia Princeps Leaf Extract',6,6),
  ('ING0663','Ceteareth-12','Ceteareth-12',6,6),
  ('ING0664','Vinyl Dimethicone','Vinyl Dimethicone; Vinyl dimethicone',6,6),
  ('ING0665','Castanea Crenata (Chestnut) Shell Extract','Castanea Crenata (Chestnut) Shell Extract; Castanea Crenata Shell Extract',6,6),
  ('ING0666','Zanthoxylum Piperitum Fruit Extract','Zanthoxylum Piperitum Fruit Extract',6,6),
  ('ING0667','Bromelain','Bromelain',6,6),
  ('ING0668','Theobroma Cacao (Cocoa) Seed Extract','Theobroma Cacao (Cocoa) Seed Extract',6,6),
  ('ING0669','Triethylhexanoin','Triethylhexanoin; TRIETHYLHEXANOIN',6,6),
  ('ING0670','Trimethylsiloxysilicate','Trimethylsiloxysilicate; TRIMETHYLSILOXYSILICATE; trimethylsiloxysilicate',6,8),
  ('ING0671','Sodium Bicarbonate','Sodium Bicarbonate; SODIUM BICARBONATE',6,6),
  ('ING0672','Iron Oxides (CI 77499)','Iron Oxides (CI 77499); Iron Oxides (CI 77491); Iron Oxides (Cl 77492); IRON OXIDES (CI 77492); IRON OXIDES (CI 77491); IRON OXIDES (CI 77499); Iron Oxides',6,14),
  ('ING0673','Carica Papaya (Papaya) Fruit Extract','Carica Papaya (Papaya) Fruit Extract; CARICA PAPAYA FRUIT EXTRACT',6,6),
  ('ING0674','Nonapeptide-1','Nonapeptide-1',6,6),
  ('ING0675','Sucrose Palmitate','Sucrose Palmitate',6,6),
  ('ING0676','Hydroxypinacolone Retinoate','Hydroxypinacolone Retinoate; hydroxypinacolone retinoate (10 ppb); Hydroxypinacolone Retinoate (1000 ppm); Hydroxypinacolone retinoate; Hydroxypinacolone Retinoate (0.7%)',6,6),
  ('ING0677','Brassica Campestris (Rapeseed) Sterols','Brassica Campestris (Rapeseed) Sterols; brassica campestris (rapeseed) sterols; Brassica Campestris Sterols',6,6),
  ('ING0678','Decylene Glycol','Decylene Glycol; decylene glycol; DECYLENE GLYCOL',5,5),
  ('ING0679','VP/Dimethylaminoethylmethacrylate Copolymer','VP/Dimethylaminoethylmethacrylate Copolymer; Vp/ Dimethylaminoethylmethacrylate Copolymer; VP/dimethylaminoethylmethacrylate copolymer',5,5),
  ('ING0680','PEG-6 CAPRYLIC/CAPRIC GLYCERIDES','PEG-6 CAPRYLIC/CAPRIC GLYCERIDES; PEG-6 Caprylic/Capric Glycerides',5,5),
  ('ING0681','Hexapeptide-11','Hexapeptide-11; hexapeptide-11; HEXAPEPTIDE-11',5,5),
  ('ING0682','Triticum Vulgare (Wheat) Germ Extract','Triticum Vulgare (Wheat) Germ Extract; Triticum Vulgare Germ Extract',5,5),
  ('ING0683','Avocado Oil','Avocado Oil; avocado oil (фруктовые масла); avocado oil; Avocado (Persea Gratissima) Oil*',5,5),
  ('ING0684','Helianthus Annuus Seed Oil / Sunflower Seed Oil','Helianthus Annuus Seed Oil / Sunflower Seed Oil; HELIANTHUS ANNUUS SEED OIL / SUNFLOWER SEED OIL; helianthus annuus seed oil / sunflower seed oil',5,5),
  ('ING0685','Glycerine','Glycerine; GLYCERINE',5,5),
  ('ING0686','Aesculus Hippocastanum Seed Extract','Aesculus Hippocastanum Seed Extract; AESCULUS HIPPOCASTANUM (HORSE CHESTNUT) SEED EXTRACT; Аesculus Hippocastanum Seed Extract; Aesculus Hippocastanum (Horse Chestnut) Seed Extract',5,5),
  ('ING0687','Laurdimonium Hydroxypropyl Hydrolyzed Keratin','Laurdimonium Hydroxypropyl Hydrolyzed Keratin; laurdimonium hydroxypropyl hydrolyzed keratin; LAURDIMONIUM HYDROXYPROPYL HYDROLYZED KERATIN',5,5),
  ('ING0688','Hydrolyzed Wheat Starch','Hydrolyzed Wheat Starch',5,5),
  ('ING0689','Lawsonia inermis (Henna) Extract','Lawsonia inermis (Henna) Extract; Lawsonia Inermis (Henna) Extract; lawsonia inermis extract; Lawsonia Inermis extract',5,5),
  ('ING0690','hydroxypropyltrimonium hydrolyzed wheat protein','hydroxypropyltrimonium hydrolyzed wheat protein; Hydroxypropyltrimonium Hydrolyzed Wheat Protein; Hydroxypropyltrimonium hydrolyzed Wheat Protein',5,5),
  ('ING0691','Collagen','Collagen; Collagen(450ppm)',5,5),
  ('ING0692','Silkworm Cocoon Extract','Silkworm Cocoon Extract',5,5),
  ('ING0693','Imidazolidinyl urea','Imidazolidinyl urea; imidazolidinyl urea; IMIDAZOLIDINYL UREA; Imidazolidinyl Urea',5,5),
  ('ING0694','CHLORHEXIDINE DIHYDROCHLORIDE','CHLORHEXIDINE DIHYDROCHLORIDE; Chlorhexidine Dihydrochloride; Chlorhexidine dihydrochloride',5,5),
  ('ING0695','Hydrolyzed Quinoa','Hydrolyzed Quinoa; hydrolyzed quinoa; Hydrolyzed Quinoa*',5,5),
  ('ING0696','Shea Butter','Shea Butter; Shea butter; shea butter',5,5),
  ('ING0697','Iodopropynyl Butylcarbamate','Iodopropynyl Butylcarbamate; IODOPROPYNYL BUTYLCARBAMATE; iodopropynyl butylcarbamate',5,5),
  ('ING0698','PETROLATUM','PETROLATUM; Petrolatum',5,5),
  ('ING0699','Urtica Dioica Extract','Urtica Dioica Extract; urtica dioica extract; Urtica dioica extract',5,5),
  ('ING0700','Equisetum Arvense Extract','Equisetum Arvense Extract; equisetum arvense extract; Equisetum arvense extract',5,5),
  ('ING0701','Cinnamyl Alcohol','Cinnamyl Alcohol; cinnamyl alcohol',5,5),
  ('ING0702','Hydroxypropylgluconamide','Hydroxypropylgluconamide; HYDROXYPROPYLGLUCONAMIDE',5,5),
  ('ING0703','Hydroxypropyl Methylcellulose','Hydroxypropyl Methylcellulose; HYDROXYPROPYL METHYLCELLULOSE; hydroxypropyl methylcellulose',5,5),
  ('ING0704','Hydroxypropylammonium Gluconate','Hydroxypropylammonium Gluconate; HYDROXYPROPYLAMMONIUM GLUCONATE',5,5),
  ('ING0705','Polyquaternium-68','Polyquaternium-68; POLYQUATERNIUM-68',5,5),
  ('ING0706','PPG-5-CETETH-20','PPG-5-CETETH-20; ppg-5-ceteth-20; ppg- 5-ceteth-20',5,5),
  ('ING0707','PEG-55 PROPYLENE GLYCOL OLEATE','PEG-55 PROPYLENE GLYCOL OLEATE; peg-55 propylene glycol oleate',5,5),
  ('ING0708','Heptyl Glucoside','Heptyl Glucoside; HEPTYL GLUCOSIDE',5,5),
  ('ING0709','Ceramide NG','Ceramide NG; CERAMIDE NG',5,5),
  ('ING0710','Citrus Grandis (Grapefruit) Peel Oil','Citrus Grandis (Grapefruit) Peel Oil; Citrus Grandis Peel Oil',5,5),
  ('ING0711','Sodium Isethionate','Sodium Isethionate',5,5),
  ('ING0712','Hydrolyzed Keratin Pg-Propyl Methylsilanediol','Hydrolyzed Keratin Pg-Propyl Methylsilanediol; hydrolyzed keratin pg-propyl methylsilanediol; hydrolyzed keratin pg- propyl methylsilanediol',5,5),
  ('ING0713','Cinnamal','Cinnamal',5,5),
  ('ING0714','Morinda Citrifolia Fruit Extract','Morinda Citrifolia Fruit Extract',5,5),
  ('ING0715','C13-14 Isoparaffin','C13-14 Isoparaffin; C13-14 ISOPARAFFIN',5,5),
  ('ING0716','ORYZA SATIVA (RICE) BRAN OIL','ORYZA SATIVA (RICE) BRAN OIL; Oryza Sativa (Rice) Bran Oil',5,5),
  ('ING0717','Phosphatidylcholine','Phosphatidylcholine; phosphatidylcholine; PHOSPHATIDYLCHOLINE',5,5),
  ('ING0718','oleic acid','oleic acid; Oleic Acid; OLEIC ACID',5,5),
  ('ING0719','Aroma','Aroma; AROMA',5,6),
  ('ING0720','Ci 77891 / Titanium Dioxide','Ci 77891 / Titanium Dioxide; ci 77891 / titanium dioxide; CI 77891 / TITANIUM DIOXIDE; Ci 77891/ Titanium Dioxide',5,5),
  ('ING0721','fumaric acid','fumaric acid; FUMARIC ACID; Fumaric Acid',5,5),
  ('ING0722','Candida Bombicola/Glucose/Methyl Rapeseedate Ferment','Candida Bombicola/Glucose/Methyl Rapeseedate Ferment',5,5),
  ('ING0723','Phyllanthus Emblica (Amla) Fruit Oil','Phyllanthus Emblica (Amla) Fruit Oil; Phyllanthus Emblica (Amla) Fruit Oil*; PHYLLANTHUS EMBLICA (AMLA) FRUIT OIL',5,5),
  ('ING0724','hydroxyethyl cellulose','hydroxyethyl cellulose; Hydroxyethyl Cellulose; Hydroxyethyl cellulose; HYDROXYETHYL CELLULOSE',5,5),
  ('ING0725','Eucalyptus Globulus Leaf Oil','Eucalyptus Globulus Leaf Oil; EUCALYPTUS GLOBULUS LEAF OIL',5,5),
  ('ING0726','Citrus Paradisi (Grapefruit) Peel Oil','Citrus Paradisi (Grapefruit) Peel Oil; Citrus paradisi peel oil',5,5),
  ('ING0727','Polyacrylamide','Polyacrylamide; POLYACRYLAMIDE',5,5),
  ('ING0728','Laureth-7','Laureth-7; LAURETH 7; LAURETH-7',5,5),
  ('ING0729','PEG/PPG-18/18 DIMETHICONE','PEG/PPG-18/18 DIMETHICONE; PEG/PPG-18/18 Dimethicone; Peg/Ppg-18/18 Dimethicone',5,5),
  ('ING0730','Hydrogenated Vegetable Oil','Hydrogenated Vegetable Oil; HYDROGENATED VEGETABLE OIL',5,5),
  ('ING0731','Salvia Hispanica Seed Extract','Salvia Hispanica Seed Extract',5,5),
  ('ING0732','Pogostemon Cablin Oil','Pogostemon Cablin Oil; POGOSTEMON CABLIN (PATCHOULI) OIL; Pogostemon Cablin (Patchouli) Oil*',5,5),
  ('ING0733','Elettaria Cardamomum Seed Oil','Elettaria Cardamomum Seed Oil',5,5),
  ('ING0734','Lonicera Japonica (Honeysuckle) Flower Extract','Lonicera Japonica (Honeysuckle) Flower Extract; Lonicera Japonica Flower Extract',5,5),
  ('ING0735','Mangifera Indica (Mango) Seed Butter','Mangifera Indica (Mango) Seed Butter; MANGIFERA INDICA (MANGO) SEED BUTTER',5,5),
  ('ING0736','Avena Sativa (Oat) Bran Extract','Avena Sativa (Oat) Bran Extract; AVENA SATIVA BRAN EXTRACT',5,5),
  ('ING0737','Zingiber Officinale (Ginger) Root Extract','Zingiber Officinale (Ginger) Root Extract; ZINGIBER OFFICINALE ROOT EXTRACT; zingiber officinale root extract; Zingiber Officinale Root Extract',5,5),
  ('ING0738','POLYSILICONE-13','POLYSILICONE-13; Polysilicone-13',5,5),
  ('ING0739','Citrus Limon (Lemon) Peel Extract','Citrus Limon (Lemon) Peel Extract; Citrus Limon Peel Extract',5,5),
  ('ING0740','Cetyl Hydroxyethylcellulose','Cetyl Hydroxyethylcellulose; Cetyl hydroxyethylcellulose; CETYL HYDROXYETHYLCELLULOSE',5,5),
  ('ING0741','Mentha Arvensis Leaf Oil','Mentha Arvensis Leaf Oil; MENTHA ARVENSIS LEAF OIL',5,5),
  ('ING0742','Salvia Officinalis (Sage) Extract','Salvia Officinalis (Sage) Extract; Salvia officinalis extract; salvia officinalis extract',5,6),
  ('ING0743','Vegetable oil','Vegetable oil; vegetable oil; VEGETABLE OIL; Vegetable Oil',5,5),
  ('ING0744','Tryptophan','Tryptophan',5,5),
  ('ING0745','Tin Oxide','Tin Oxide; TIN OXIDE; tin oxide',5,6),
  ('ING0746','POTASSIUM CHLORIDE','POTASSIUM CHLORIDE; Potassium Chloride; Potassium chloride',5,5),
  ('ING0747','HYDRATED SILICA','HYDRATED SILICA; Hydrated Silica',5,5),
  ('ING0748','Cynanchum Atratum Extract','Cynanchum Atratum Extract',5,5),
  ('ING0749','Polyglutamic Acid','Polyglutamic Acid',5,5),
  ('ING0750','Sucrose Stearate','Sucrose Stearate; SUCROSE STEARATE',5,5),
  ('ING0751','Ppg-2-Deceth-12','Ppg-2-Deceth-12; PPG-2-DECETH-12; PPG-2-Deceth-12',5,5),
  ('ING0752','Troxerutin','Troxerutin',5,6),
  ('ING0753','Zinc Gluconate','Zinc Gluconate',5,5),
  ('ING0754','Mentha Piperita Oil','Mentha Piperita Oil; Mentha Piperita (Peppermint) Oil*; Mentha Piperita (Peppermint) Oil',5,5),
  ('ING0755','Lactobacillus','Lactobacillus',5,5),
  ('ING0756','Folic Acid','Folic Acid',5,5),
  ('ING0757','Azelaic Acid','Azelaic Acid; AZELAIC ACID',5,5),
  ('ING0758','Punica Granatum Fruit Extract','Punica Granatum Fruit Extract',5,5),
  ('ING0759','Ethanol','Ethanol; ethanol',5,5),
  ('ING0760','Myristyl Glucoside','Myristyl Glucoside',5,5),
  ('ING0761','Hexyl Laurate','Hexyl Laurate',5,5),
  ('ING0762','Isoamyl p-Methoxycinnamate','Isoamyl p-Methoxycinnamate; Isoamyl p- Methoxycinnamate; isoamyl p-methoxycinnamate',5,5),
  ('ING0763','Polyglyceryl-4 Oleate','Polyglyceryl-4 Oleate',5,5),
  ('ING0764','Lactobacillus/Pumpkin Ferment Extract','Lactobacillus/Pumpkin Ferment Extract',5,5),
  ('ING0765','Arbutin','Arbutin; ARBUTIN; arbutin',5,5),
  ('ING0766','Pinus Palustris Leaf Extract','Pinus Palustris Leaf Extract',5,5),
  ('ING0767','Camellia Sinensis Leaf Water','Camellia Sinensis Leaf Water; Camellia Sinensis Leaf Water (940 ppm)',5,5),
  ('ING0768','PERLITE','PERLITE; perlite',5,5),
  ('ING0769','Diethylhexyl Syringylidenemalonate','Diethylhexyl Syringylidenemalonate',5,5),
  ('ING0770','Polyglyceryl-2 Dipolyhydroxystearate','Polyglyceryl-2 Dipolyhydroxystearate; POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE',5,5),
  ('ING0771','Hamamelis Virginiana (Witch Hazel) Extract','Hamamelis Virginiana (Witch Hazel) Extract; Hamamelis Virginiana Extract',5,5),
  ('ING0772','Centaurea Cyanus Flower Extract','Centaurea Cyanus Flower Extract; Centaurea Cyanus (Cornflower) Flower Extract; CENTAUREA CYANUS (CORNFLOWER) FLOWER EXTRACT',5,5),
  ('ING0773','Gardenia Florida Fruit Extract','Gardenia Florida Fruit Extract',5,5),
  ('ING0774','Rubus Idaeus (Raspberry) Fruit Extract','Rubus Idaeus (Raspberry) Fruit Extract; rubus idaeus (raspberry) fruit extract; RUBUS IDAEUS (RASPBERRY) FRUIT EXTRACT',5,5),
  ('ING0775','Olive Oil','Olive Oil; olive oil; Olive Оil',5,5),
  ('ING0776','Chamaecyparis Obtusa Leaf Extract','Chamaecyparis Obtusa Leaf Extract',5,5),
  ('ING0777','Ectoin','Ectoin; Ectoin (5000 ppm); ECTOIN',5,5),
  ('ING0778','Aluminum Starch Octenylsuccinate','Aluminum Starch Octenylsuccinate; ALUMINUM STARCH OCTENYLSUCCINATE',5,5),
  ('ING0779','Acetyl Tetrapeptide-5','Acetyl Tetrapeptide-5',5,6),
  ('ING0780','BHA','BHA; Bha',5,5),
  ('ING0781','Sucrose Distearate','Sucrose Distearate',5,5),
  ('ING0782','DIISOPROPYL ADIPATE','DIISOPROPYL ADIPATE; diisopropyl adipate; Diisopropyl Adipate',5,5),
  ('ING0783','Soluble Collagen','Soluble Collagen; Soluble Collagen (2 ppm); Soluble Collagen (53%)',5,5),
  ('ING0784','sh-Oligopeptide-2','sh-Oligopeptide-2; SH-Oligopeptide-2',5,5),
  ('ING0785','SH-Polypeptide-1','SH-Polypeptide-1; sh-Polypeptide-1; Sh-polypeptide-1',5,5),
  ('ING0786','Betaine Salicylate','Betaine Salicylate',5,5),
  ('ING0787','Paeonia Lactiflora Root Extract','Paeonia Lactiflora Root Extract',4,4),
  ('ING0788','Orbignya Oleifera Seed Oil','Orbignya Oleifera Seed Oil; ORBIGNYA OLEIFERA SEED OIL; Orbignya Oleifera (Babassu) Seed Oil',4,4),
  ('ING0789','Dimethicone PEG-8 Meadowfoamate','Dimethicone PEG-8 Meadowfoamate; DIMETHICONE PEG-8 MEADOWFOAMATE',4,4),
  ('ING0790','Wheat Amino Acids','Wheat Amino Acids',4,4),
  ('ING0791','Sodium Laureth-5 Carboxylate','Sodium Laureth-5 Carboxylate; SODIUM LAURETH-5 CARBOXYLATE; Sodium laureth-5 carboxylate',4,4),
  ('ING0792','Lauryl Hydroxysultaine','Lauryl Hydroxysultaine; LAURYL HYDROXYSULTAINE',4,4),
  ('ING0793','Etidronic Acid','Etidronic Acid',4,4),
  ('ING0794','Rosa Centifolia (Rose) Flower Extract','Rosa Centifolia (Rose) Flower Extract; Rosa Centifolia Flower Extract',4,4),
  ('ING0795','Rosa Canina (Rose Hip) Extract','Rosa Canina (Rose Hip) Extract; Rosa Canina Extract',4,4),
  ('ING0796','Citrus Aurantium Dulcis (Orange) Fruit Extract','Citrus Aurantium Dulcis (Orange) Fruit Extract; CITRUS AURANTIUM DULCIS (ORANGE) FRUIT EXTRACT',4,4),
  ('ING0797','Coconut Oil','Coconut Oil; coconut oil (масло кокоса)',4,4),
  ('ING0798','sunflower seed oil','sunflower seed oil; Sunflower Seed Oil',4,4),
  ('ING0799','ROSMARINUS OFFICINALIS LEAF EXTRACT / ROSEMARY LEAF EXTRACT','ROSMARINUS OFFICINALIS LEAF EXTRACT / ROSEMARY LEAF EXTRACT; Rosmarinus Officinalis Leaf Extract / Rosemary Leaf Extract; rosmarinus officinalis leaf extract / rosemary leaf extract',4,4),
  ('ING0800','PERSEA GRATISSIMA OIL / AVOCADO OIL','PERSEA GRATISSIMA OIL / AVOCADO OIL; Persea Gratissima Oil / Avocado Oil; persea gratissima oil/ avocado oil',4,4),
  ('ING0801','Styrene/Acrylates Copolymer','Styrene/Acrylates Copolymer; STYRENE/ACRYLATES COPOLYMER',4,4),
  ('ING0802','PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE','PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE; Phytosteryl/Octyldodecyl Lauroyl Glutamate',4,4),
  ('ING0803','Helianthus Annuus (Sunflower) Seed Extract','Helianthus Annuus (Sunflower) Seed Extract; HELIANTHUS ANNUUS (SUNFLOWER) SEED EXTRACT; helianthus annuus (sunflower) seed extract',4,4),
  ('ING0804','Avena Sativa (Oat) Kernel Extract','Avena Sativa (Oat) Kernel Extract',4,4),
  ('ING0805','Acorus Calamus Root Extract','Acorus Calamus Root Extract; Acorus Calamus (Sweet Flag) Root Extract',4,5),
  ('ING0806','Polyquaternium-67','Polyquaternium-67; POLYQUATERNIUM-67',4,4),
  ('ING0807','SODIUM COCOYL GLYCINATE','SODIUM COCOYL GLYCINATE; Sodium Cocoyl Glycinate',4,4),
  ('ING0808','Myristyl Myristate','Myristyl Myristate; myristyl myristate; MYRISTYL MYRISTATE',4,4),
  ('ING0809','Oligopeptide-1','Oligopeptide-1',4,4),
  ('ING0810','ceteardimonium chloride','ceteardimonium chloride; Ceteardimonium chloride',4,4),
  ('ING0811','Elastin','Elastin; elastin',4,4),
  ('ING0812','BLUE 1 (CI 42090)','BLUE 1 (CI 42090); blue 1 (ci42090); Blue 1',4,4),
  ('ING0813','PLACENTAL PROTEIN','PLACENTAL PROTEIN; placental protein; Placental Protein',4,4),
  ('ING0814','Ceramide 3','Ceramide 3; Ceramide-3',4,4),
  ('ING0815','brassicamidopropyl dimethylamine','brassicamidopropyl dimethylamine; BRASSICAMIDOPROPYL DIMETHYLAMINE',4,4),
  ('ING0816','CI 17200 / RED 33','CI 17200 / RED 33; Ci 17200 / Red 33; CI 17200/RED 33',4,4),
  ('ING0817','Sodium Polystyrene Sulfonate','Sodium Polystyrene Sulfonate; SODIUM POLYSTYRENE SULFONATE',4,4),
  ('ING0818','PEG-14M','PEG-14M; peg-14m',4,4),
  ('ING0819','Phytantriol','Phytantriol',4,4),
  ('ING0820','argania spinosa oil','argania spinosa oil; ARGANIA SPINOSA OIL; Argania spinosa oil; Argania Spinosa Oil',4,4),
  ('ING0821','cl 42090','cl 42090; Cl 42090; CL 42090',4,4),
  ('ING0822','LAURDIMONIUM HYDROXYPROPYL HYDROLYZED WHEAT PROTEIN','LAURDIMONIUM HYDROXYPROPYL HYDROLYZED WHEAT PROTEIN; Laurdimonium Hydroxypropyl Hydrolyzed Wheat Protein; laurdimonium hydroxypropyl hydrolyzed wheat protein',4,4),
  ('ING0823','Melissa Officinalis Flower/Leaf/Stem Extract','Melissa Officinalis Flower/Leaf/Stem Extract; Melissa officinalis Flower/Leaf/Stem Extract',4,4),
  ('ING0824','Butyrospermum Parkii (Shea Butter)','Butyrospermum Parkii (Shea Butter)',4,4),
  ('ING0825','Hydrolyzed Rice Bran Protein','Hydrolyzed Rice Bran Protein',4,4),
  ('ING0826','Fullerenes [Nano]','Fullerenes [Nano]',4,4),
  ('ING0827','Sodium Stearoyl Lactylate','Sodium Stearoyl Lactylate',4,4),
  ('ING0828','Tea-Cocoyl Glutamate','Tea-Cocoyl Glutamate; Tea-cocoyl Glutamate; TEA-Cocoyl Glutamate',4,4),
  ('ING0829','Methyl Gluceth-20','Methyl Gluceth-20',4,4),
  ('ING0830','Palmitoyl Myristyl Serinate','Palmitoyl Myristyl Serinate; PALMITOYL MYRISTYL SERINATE',4,4),
  ('ING0831','PEG-45M','PEG-45M',4,4),
  ('ING0832','PEG-4 LAURATE','PEG-4 LAURATE; PEG-4 Laurate; peg-4 laurate',4,4),
  ('ING0833','PEG-4','PEG-4; peg-4; Peg-4',4,4),
  ('ING0834','Maltitol','Maltitol; MALTITOL',4,4),
  ('ING0835','PEG-150 Distearate','PEG-150 Distearate; PEG-150 DISTEARATE; PEG- 150 Distearate',4,4),
  ('ING0836','cocodimonium hydroxypropyl hydrolyzed keratin','cocodimonium hydroxypropyl hydrolyzed keratin',4,4),
  ('ING0837','psidium guajava fruit extract','psidium guajava fruit extract; psidium guajava (guava) fruit extract',4,4),
  ('ING0838','Sodium Methylparaben','Sodium Methylparaben; SODIUM METHYLPARABEN',4,4),
  ('ING0839','PEG/PPG-120/10 Trimethylolpropane Trioleate','PEG/PPG-120/10 Trimethylolpropane Trioleate; PEG/PPG-120/10 TRIMETHYLOLPROPANE TRIOLEATE',4,4),
  ('ING0840','nicotinamide','nicotinamide; Nicotinamide; NICOTINAMIDE',4,4),
  ('ING0841','Laminaria Digitata Extract','Laminaria Digitata Extract; LAMINARIA DIGITATA EXTRACT',4,4),
  ('ING0842','HYDROGENATED PALM GLYCERIDES CITRATE','HYDROGENATED PALM GLYCERIDES CITRATE',4,4),
  ('ING0843','TRISODIUM EDTA','TRISODIUM EDTA; Trisodium EDTA',4,4),
  ('ING0844','Sorbitan Oleate Decylglucoside Crosspolymer','Sorbitan Oleate Decylglucoside Crosspolymer; SORBITAN OLEATE DECYLGLUCOSIDE CROSSPOLYMER',4,4),
  ('ING0845','Nelumbo Nucifera (Lotus) Flower Water','Nelumbo Nucifera (Lotus) Flower Water',4,4),
  ('ING0846','Jasminum Officinale (Jasmine) Flower Extract','Jasminum Officinale (Jasmine) Flower Extract; Jasminum Officinale Flower Extract; jasminum officinale (jasmine) flower extract',4,4),
  ('ING0847','Farnesol','Farnesol',4,4),
  ('ING0848','RHAMNOSE','RHAMNOSE',4,4),
  ('ING0849','Cyclotetrasiloxane','Cyclotetrasiloxane; CYCLOTETRASILOXANE',4,4),
  ('ING0850','Citrus Aurantium Dulcis (Orange) Peel Extract','Citrus Aurantium Dulcis (Orange) Peel Extract',4,4),
  ('ING0851','Coconut Alkanes','Coconut Alkanes',4,4),
  ('ING0852','CETEARYL ETHYLHEXANOATE','CETEARYL ETHYLHEXANOATE; cetearyl ethylhexanoate; Cetearyl Ethylhexanoate',4,4),
  ('ING0853','Chitosan','Chitosan',4,4),
  ('ING0854','Helianthus Annuus (Sunflower) Extract','Helianthus Annuus (Sunflower) Extract; Helianthus Annuus (Sunflower) Extract*',4,4),
  ('ING0855','Lonicera Caprifolium (Honeysuckle) Flower Extract','Lonicera Caprifolium (Honeysuckle) Flower Extract; Lonicera Caprifolium Flower Extract',4,4),
  ('ING0856','Hydrolyzed Pea Protein','Hydrolyzed Pea Protein; hydrolyzed pea protein',4,4),
  ('ING0857','Leontopodium Alpinum Callus Culture Extract','Leontopodium Alpinum Callus Culture Extract; Leontopodium alpinum callus culture extract',4,4),
  ('ING0858','SODIUM METHYLTAURATE','SODIUM METHYLTAURATE; Sodium Methyltaurate',4,4),
  ('ING0859','Ethylpanthenol','Ethylpanthenol; ethylpanthenol',4,4),
  ('ING0860','Sodium Ascorbate','Sodium Ascorbate; sodium ascorbate',4,4),
  ('ING0861','L-Arginine','L-Arginine',4,5),
  ('ING0862','Polyquaternium-4','Polyquaternium-4; POLYQUATERNIUM-4',4,4),
  ('ING0863','Chondrus Crispus','Chondrus Crispus; Chondrus Crispus (Carrageenan)',4,4),
  ('ING0864','L-Ascorbic Acid','L-Ascorbic Acid',4,4),
  ('ING0865','Camphor','Camphor; CAMPHOR',4,4),
  ('ING0866','Lauramide DEA','Lauramide DEA; Lauramide Dea',4,4),
  ('ING0867','Gelatin','Gelatin; gelatin',4,4),
  ('ING0868','Adansonia Digitata Seed Oil','Adansonia Digitata Seed Oil',4,4),
  ('ING0869','Vaccinium Myrtillus Fruit Extract','Vaccinium Myrtillus Fruit Extract; Vaccinium Myrtillus Fruit Extract (Organic Bilberry Extract); VACCINIUM MYRTILLUS FRUIT EXTRACT',4,4),
  ('ING0870','saccharomyces ferment lysate filtrate','saccharomyces ferment lysate filtrate; SACCHAROMYCES FERMENT LYSATE FILTRATE',4,4),
  ('ING0871','Mentha Piperita (Peppermint) Extract','Mentha Piperita (Peppermint) Extract; Mentha Piperita Extract',4,4),
  ('ING0872','Asparagine','Asparagine',4,4),
  ('ING0873','Hydrolyzed Barley Protein','Hydrolyzed Barley Protein; HYDROLYZED BARLEY PROTEIN',4,4),
  ('ING0874','Glycyrrhiza Uralensis (Licorice) Root Extract','Glycyrrhiza Uralensis (Licorice) Root Extract; Glycyrrhiza Uralensis Root Extract',4,4),
  ('ING0875','Phellodendron Amurense Bark Extract','Phellodendron Amurense Bark Extract; phellodendron Amurense Bark Extract',4,4),
  ('ING0876','Dioscorea Japonica Root Extract','Dioscorea Japonica Root Extract',4,4),
  ('ING0877','Paeonia Suffruticosa Root Extract','Paeonia Suffruticosa Root Extract',4,4),
  ('ING0878','Freesia Refracta Extract','Freesia Refracta Extract',4,4),
  ('ING0879','phenyltrimethicone','phenyltrimethicone; Phenyltrimethicone',4,4),
  ('ING0880','Pinus Sibirica Seed Oil','Pinus Sibirica Seed Oil; PINUS SIBIRICA SEED OIL',4,4),
  ('ING0881','Althaea Rosea Flower Extract','Althaea Rosea Flower Extract',4,4),
  ('ING0882','Magnesium Aspartate','Magnesium Aspartate; MAGNESIUM ASPARTATE',4,4),
  ('ING0883','Thymus Vulgaris (Thyme) Extract','Thymus Vulgaris (Thyme) Extract; THYMUS VULGARIS (THYME) EXTRACT',4,4),
  ('ING0884','Cedrus Atlantica (Cedarwood) Bark Oil*','Cedrus Atlantica (Cedarwood) Bark Oil*',4,4),
  ('ING0885','Cucurbita Pepo (Pumpkin) Seed Oil','Cucurbita Pepo (Pumpkin) Seed Oil; Cucurbita Pepo (Pumpkin) Seed Oil*; Cucurbita Pepo Seed (Pumpkin) Oil',4,4),
  ('ING0886','Polyquaternium-73','Polyquaternium-73',4,4),
  ('ING0887','RUBUS CHAMAEMORUS FRUIT EXTRACT','RUBUS CHAMAEMORUS FRUIT EXTRACT; Rubus Chamaemorus (Cloudberry) Fruit Extract; RUBUS CHAMAEMORUS (CLOUDBERRY) FRUIT EXTRACT',4,4),
  ('ING0888','Acetyl Hexapeptide-1','Acetyl Hexapeptide-1; ACETYL HEXAPEPTIDE-1.',4,4),
  ('ING0889','Sodium Acrylates Crosspolymer-2','Sodium Acrylates Crosspolymer-2; Sodium Acrylates Crosspolymer- 2',4,4),
  ('ING0890','Fructan','Fructan; fructan',4,4),
  ('ING0891','Aspergillus Ferment','Aspergillus Ferment',4,4),
  ('ING0892','Inulin Lauryl Carbamate','Inulin Lauryl Carbamate; INULIN LAURYL CARBAMATE',4,4),
  ('ING0893','Synthetic Wax','Synthetic Wax',4,4),
  ('ING0894','Ozokerite','Ozokerite',4,4),
  ('ING0895','Aloe Barbadensis Flower Extract','Aloe Barbadensis Flower Extract',4,4),
  ('ING0896','Sodium Carbomer','Sodium Carbomer',4,4),
  ('ING0897','Polyglyceryl-6 Stearate','Polyglyceryl-6 Stearate',4,4),
  ('ING0898','Litsea Cubeba Fruit Oil','Litsea Cubeba Fruit Oil',4,4),
  ('ING0899','Polyglyceryl-2 Stearate','Polyglyceryl-2 Stearate; POLYGLYCERYL-2 STEARATE',4,4),
  ('ING0900','Citrus Nobilis (Mandarin Orange) Peel Oil','Citrus Nobilis (Mandarin Orange) Peel Oil',4,4),
  ('ING0901','Collagen Extract','Collagen Extract',4,4),
  ('ING0902','Diisostearyl Malate','Diisostearyl Malate',4,6),
  ('ING0903','Diospyros Kaki Leaf Extract','Diospyros Kaki Leaf Extract',4,4),
  ('ING0904','C12-16 Alcohols','C12-16 Alcohols; C12-16 alcohols; C12-16 ALCOHOLS',4,4),
  ('ING0905','Dimethyl Sulfone','Dimethyl Sulfone; DIMETHYL SULFONE',4,4),
  ('ING0906','Cyclodextrin','Cyclodextrin; cyclodextrin',4,4),
  ('ING0907','Pentaerythrityl Tetraisostearate','Pentaerythrityl Tetraisostearate; Pentaerythrityl tetraisostearate',4,4),
  ('ING0908','HDI/Trimethylol Hexyllactone Crosspolymer','HDI/Trimethylol Hexyllactone Crosspolymer; Hdi/Trimethylol Hexyllactone Crosspolymer; Hdi / trimethylol Hexyllactone Crosspolymer',4,4),
  ('ING0909','Borago Officinalis Extract','Borago Officinalis Extract; borago officinalis extract',4,4),
  ('ING0910','Lactobacillus/Soybean Ferment Extract','Lactobacillus/Soybean Ferment Extract; Lactobacillus/Soybean Ferment-Extract',4,4),
  ('ING0911','Diethoxyethyl Succinate','Diethoxyethyl Succinate; DIETHOXYETHYL SUCCINATE',4,4),
  ('ING0912','Superoxide Dismutase','Superoxide Dismutase; SUPEROXIDE DISMUTASE',4,4),
  ('ING0913','Palmitoyl Tripeptide-38','Palmitoyl Tripeptide-38; PALMITOYL TRIPEPTIDE-38',4,5),
  ('ING0914','PHYTIC ACID','PHYTIC ACID; phytic acid; Phytic Acid',4,4),
  ('ING0915','Bis-Diglyceryl Polyacyladipate-2','Bis-Diglyceryl Polyacyladipate-2',4,4),
  ('ING0916','Isopropyl Lauroyl Sarcosinate','Isopropyl Lauroyl Sarcosinate; ISOPROPYL LAUROYL SARCOSINATE',4,4),
  ('ING0917','Silica Silylate','Silica Silylate; SILICA SILYLATE',4,4),
  ('ING0918','Corn Starch','Corn Starch; Corn (zea Mays) Starch',4,4),
  ('ING0919','Acetyl Dipeptide-1 Cetyl Ester','Acetyl Dipeptide-1 Cetyl Ester; ACETYL DIPEPTIDE-1 CETYL ESTER',4,4),
  ('ING0920','Polyethylene','Polyethylene; POLYETHYLENE',4,4),
  ('ING0921','Polyglyceryl-4 Isostearate','Polyglyceryl-4 Isostearate',4,4),
  ('ING0922','Rubus Fruticosus (Blackberry) Fruit Extract','Rubus Fruticosus (Blackberry) Fruit Extract',4,4),
  ('ING0923','Gaultheria Procumbens (Wintergreen) Leaf Extract','Gaultheria Procumbens (Wintergreen) Leaf Extract; GAULTHERIA PROCUMBENS (WINTERGREEN) LEAF EXTRACT',4,4),
  ('ING0924','Boron Nitride','Boron Nitride; boron nitride',4,6),
  ('ING0925','Sh-Polypeptide-82','Sh-Polypeptide-82; sh-Polypeptide-82',4,5),
  ('ING0926','Ergothioneine','Ergothioneine',4,4),
  ('ING0927','Eclipta Prostrata Leaf Extract','Eclipta Prostrata Leaf Extract',4,4),
  ('ING0928','Diphenyl Dimethicone','Diphenyl Dimethicone',4,4),
  ('ING0929','Hydroxydecyl Ubiquinone','Hydroxydecyl Ubiquinone',4,4),
  ('ING0930','Tris(Tetramethylhydroxypiperidinol) Citrate','Tris(Tetramethylhydroxypiperidinol) Citrate',4,4),
  ('ING0931','Polyglyceryl-6 Laurate','Polyglyceryl-6 Laurate',4,4),
  ('ING0932','Aluminum/Magnesium Hydroxide Stearate','Aluminum/Magnesium Hydroxide Stearate; aluminum/magnesium hydroxide stearate',4,4),
  ('ING0933','Lipase','Lipase; Lipase (1000 ppm)',4,4),
  ('ING0934','Sodium Sulfite','Sodium Sulfite; sodium sulfite',3,3),
  ('ING0935','PPG-9','PPG-9',3,3),
  ('ING0936','CI 17200','CI 17200',3,3),
  ('ING0937','Bisamino PEG/ PPG-41/ 3 Aminoethyl Pg-Propyl Dimethicone','Bisamino PEG/ PPG-41/ 3 Aminoethyl Pg-Propyl Dimethicone; Bisamino PEG/PPG-41/3 Aminoethyl PG-Propyl Dimethicone; BISAMINO PEG / PPG-41 / 3 AMINOETHYL PG-PROPYL DIMETHICONE',3,3),
  ('ING0938','Sodium Lauroamphoacetate','Sodium Lauroamphoacetate',3,3),
  ('ING0939','SILK AMINO ACIDS','SILK AMINO ACIDS',3,3),
  ('ING0940','Dicetyldimonium Chloride','Dicetyldimonium Chloride',3,3),
  ('ING0941','Silicone Quaternium-18','Silicone Quaternium-18',3,3),
  ('ING0942','Carboxymethyl Chitin','Carboxymethyl Chitin; Carboxymethyl Сhitin',3,3),
  ('ING0943','Hydrolyzed Rye Proteins','Hydrolyzed Rye Proteins',3,3),
  ('ING0944','Hydrolyzed Ceratonia Siliqua (Caroubier) Seed Extract','Hydrolyzed Ceratonia Siliqua (Caroubier) Seed Extract; Hydrolyzed Ceratonia Siliqua Seed Extract',3,3),
  ('ING0945','steardimonium hydroxypropyl hydrolyzed keratin','steardimonium hydroxypropyl hydrolyzed keratin; Steardimonium Hydroxypropyl Hydrolyzed Keratin',3,3),
  ('ING0946','Citrus Limon Fruit Extract / Lemon Fruit Extract','Citrus Limon Fruit Extract / Lemon Fruit Extract; CITRUS LIMON FRUIT EXTRACT / LEMON FRUIT EXTRACT; citrus limon fruit extract / lemon fruit extract',3,3),
  ('ING0947','Pyrus Malus Fruit Extract / Apple Fruit Extract','Pyrus Malus Fruit Extract / Apple Fruit Extract; pyrus malus fruit extract / apple fruit extract; PYRUS MALUS FRUIT EXTRACT / APPLE FRUIT EXTRACT',3,3),
  ('ING0948','Hydroxypropyltrimonium Lemon Protein','Hydroxypropyltrimonium Lemon Protein; hydroxypropyltrimonium lemon protein; HYDROXYPROPYLTRIMONIUM LEMON PROTEIN',3,3),
  ('ING0949','CI 19140 / YELLOW 5','CI 19140 / YELLOW 5; Ci 19140 / Yellow 5',3,3),
  ('ING0950','PVP/VA Copolymer','PVP/VA Copolymer',3,3),
  ('ING0951','Laureth-10','Laureth-10; LAURETH-10; laureth-10',3,3),
  ('ING0952','Peg-120 Methyl Glucose Trioleate','Peg-120 Methyl Glucose Trioleate; PEG-120 Methyl Glucose Trioleate; PEG-120 METHYL GLUCOSE TRIOLEATE',3,3),
  ('ING0953','Distearyldimonium Chloride','Distearyldimonium Chloride; DISTEARYLDIMONIUM CHLORIDE',3,3),
  ('ING0954','Spirulina Platensis Extract','Spirulina Platensis Extract; SPIRULINA PLATENSIS EXTRACT',3,3),
  ('ING0955','Perilla Frutescens Leaf Extract','Perilla Frutescens Leaf Extract',3,3),
  ('ING0956','SODIUM LAURYL SULFOACETATE','SODIUM LAURYL SULFOACETATE; Sodium Lauryl Sulfoacetate',3,3),
  ('ING0957','Polyquaternium-44','Polyquaternium-44',3,3),
  ('ING0958','glycoproteins','glycoproteins; GLYCOPROTEINS; Glycoproteins',3,3),
  ('ING0959','Ornithine','Ornithine; ornithine',3,3),
  ('ING0960','Avena sativa kernel oil','Avena sativa kernel oil; AVENA SATIVA KERNEL OIL; Avena Sativa Kernel Oil',3,3),
  ('ING0961','CANDELILLA CERA / CANDELILLA WAX / CIRE DE CANDELILLA','CANDELILLA CERA / CANDELILLA WAX / CIRE DE CANDELILLA; Candelilla Cera / Candelilla Wax / Cire De Candelilla',3,3),
  ('ING0962','Xylose','Xylose; XYLOSE',3,3),
  ('ING0963','Trideceth-15','Trideceth-15; trideceth-15',3,3),
  ('ING0964','Polyquaternium-39','Polyquaternium-39',3,3),
  ('ING0965','Magnesium Ascorbyl Phosphate','Magnesium Ascorbyl Phosphate; MAGNESIUM ASCORBYL PHOSPHATE',3,3),
  ('ING0966','Crambe Abyssinica Seed Oil','Crambe Abyssinica Seed Oil',3,3),
  ('ING0967','Quaternium-91','Quaternium-91',3,3),
  ('ING0968','Achillea Millefolium Extract','Achillea Millefolium Extract; Achillea Millefolium (Common Yarrow) Extract',3,3),
  ('ING0969','Lysine HCL','Lysine HCL; Lysine HCl',3,3),
  ('ING0970','Vitamin E (Tocopheryl Acetate)','Vitamin E (Tocopheryl Acetate); VITAMIN E',3,3),
  ('ING0971','Glyceryl Polyacrylate','Glyceryl Polyacrylate; GLYCERYL POLYACRYLATE',3,3),
  ('ING0972','Sodium laneth-40 maleate/styrene sulfonate copolymer','Sodium laneth-40 maleate/styrene sulfonate copolymer; Sodium Laneth-40 Maleate/Styrene Sulfonate Copolymer',3,3),
  ('ING0973','CI 15510 / ORANGE 4','CI 15510 / ORANGE 4; Ci 15510 / Orange 4',3,3),
  ('ING0974','Olus Oil','Olus Oil',3,3),
  ('ING0975','Sweet Almond Oil Polyglyceryl-4 Esters','Sweet Almond Oil Polyglyceryl-4 Esters',3,3),
  ('ING0976','Parfume','Parfume; parfume',3,3),
  ('ING0977','Tapioca Starch','Tapioca Starch',3,3),
  ('ING0978','Isoamyl Laurate','Isoamyl Laurate; Isoamyl laurate',3,3),
  ('ING0979','Phenylpropanol','Phenylpropanol; PHENYLPROPANOL',3,3),
  ('ING0980','Sunflower Oil','Sunflower Oil; sunflower oil',3,3),
  ('ING0981','lanolin','lanolin; Lanolin',3,3),
  ('ING0982','Arnica Montana Flower Extract','Arnica Montana Flower Extract; Arnica Montana (Arnica) Flower Extract',3,3),
  ('ING0983','Meadowfoam Delta-Lactone','Meadowfoam Delta-Lactone',3,3),
  ('ING0984','Neopentyl Glycol Diheptanoate','Neopentyl Glycol Diheptanoate',3,3),
  ('ING0985','Tamarindus Indica Seed Polysaccharide','Tamarindus Indica Seed Polysaccharide',3,3),
  ('ING0986','Desamido Collagen','Desamido Collagen; DESAMIDO COLLAGEN',3,3),
  ('ING0987','Charcoal Powder','Charcoal Powder',3,3),
  ('ING0988','Stearalkonium Chloride','Stearalkonium Chloride',3,3),
  ('ING0989','Undecane','Undecane',3,3),
  ('ING0990','Potassium Cocoate','Potassium Cocoate',3,3),
  ('ING0991','Pseudozyma Epicola/Camellia Sinensis Seed Oil Ferment Extract Filtrate','Pseudozyma Epicola/Camellia Sinensis Seed Oil Ferment Extract Filtrate',3,3),
  ('ING0992','Origanum Vulgare Leaf Extract','Origanum Vulgare Leaf Extract',3,3),
  ('ING0993','PEG-8/SMDI Copolymer','PEG-8/SMDI Copolymer; PEG-8/SMDI COPOLYMER',3,3),
  ('ING0994','SODIUM POLYASPARTATE','SODIUM POLYASPARTATE; Sodium Polyaspartate',3,3),
  ('ING0995','PEG-4 Dilaurate','PEG-4 Dilaurate; PEG-4 DILAURATE; peg-4 dilaurate',3,3),
  ('ING0996','Cetrimonium Bromide','Cetrimonium Bromide; CETRIMONIUM BROMIDE',3,3),
  ('ING0997','Pelvetia Canaliculata Extract','Pelvetia Canaliculata Extract',3,3),
  ('ING0998','peg-3 distearate','peg-3 distearate; PEG-3 Distearate',3,3),
  ('ING0999','PEG-60 Almond Glycerides','PEG-60 Almond Glycerides; Peg-60 Almond Glycerides',3,3),
  ('ING1000','aleurites moluccana seed oil','aleurites moluccana seed oil; Aleurites Moluccana Seed Oil',3,3)
ON CONFLICT (ingredient_id) DO UPDATE SET canonical_name=EXCLUDED.canonical_name, aliases=EXCLUDED.aliases;