INSERT INTO ingredients_dictionary (ingredient_id,canonical_name,aliases,product_count,occurrence_count)
VALUES
  ('ING1501','terephthalylidene dicamphorsulfonic acid','terephthalylidene dicamphorsulfonic acid; Terephthalylidene Dicamphorsulfonic Acid',2,2),
  ('ING1502','ammonium acryloyldimethyltaurate/ Vpicopolymer','ammonium acryloyldimethyltaurate/ Vpicopolymer; Ammonium Acryloyldimethyltaurate/Vpicopolymer',2,2),
  ('ING1503','Monascus/Rice Ferment','Monascus/Rice Ferment',2,2),
  ('ING1504','Sodium Hyaluronate Dimethylsilanol','Sodium Hyaluronate Dimethylsilanol',2,2),
  ('ING1505','Drumstick Seed Extract','Drumstick Seed Extract',2,2),
  ('ING1506','Lauryl PEG-10 Tris(Trimethylsiloxy)silylethyl Dimethicone','Lauryl PEG-10 Tris(Trimethylsiloxy)silylethyl Dimethicone; Lauryl PEG-10 Tris (Trimethyisitoxy) Silylethyl Dimethicone',2,2),
  ('ING1507','Yellow Iron Oxide','Yellow Iron Oxide; Yellow Iron oxide (CI 77492)',2,2),
  ('ING1508','Decyl Glucoside Tromethamine','Decyl Glucoside Tromethamine',2,2),
  ('ING1509','Diethylaminohydroxybenzoylhexylbenzoate','Diethylaminohydroxybenzoylhexylbenzoate; DiethylaminoHydroxybenzoylHexylBenzoate',2,2),
  ('ING1510','Golden Extract','Golden Extract',2,2),
  ('ING1511','Evening Primrose Flower Extract','Evening Primrose Flower Extract',2,2),
  ('ING1512','Elm Root Extract','Elm Root Extract',2,2),
  ('ING1513','Arrowroot Extract','Arrowroot Extract',2,2),
  ('ING1514','Cardiospermum Halicacabum Flower/Leaf/Vine Extract','Cardiospermum Halicacabum Flower/Leaf/Vine Extract',2,2),
  ('ING1515','Polyglyceryl-2 Triisostearate','Polyglyceryl-2 Triisostearate',2,2),
  ('ING1516','Methyl Diisopropyl Propionamide','Methyl Diisopropyl Propionamide; METHYL DIISOPROPYL PROPIONAMIDE',2,2),
  ('ING1517','BIS-ETHYLHEXYL HYDROXYDIMETHOXY BENZYLMALONATE','BIS-ETHYLHEXYL HYDROXYDIMETHOXY BENZYLMALONATE; Bis-Ethylhexyl Hydroxydimethoxy Benzylmalonate',2,2),
  ('ING1518','Lauryl Methacrylate/Sodium Methacrylate Crosspolymer','Lauryl Methacrylate/Sodium Methacrylate Crosspolymer',2,2),
  ('ING1519','Glyceryl Behenate','Glyceryl Behenate',2,2),
  ('ING1520','Sorbitan Distearate','Sorbitan Distearate',2,2),
  ('ING1521','Stearoyl Glutamic Acid','Stearoyl Glutamic Acid',2,2),
  ('ING1522','Phenethyl Benzoate','Phenethyl Benzoate',2,2),
  ('ING1523','Diphenylsiloxy Phenyl Trimethicone','Diphenylsiloxy Phenyl Trimethicone',2,2),
  ('ING1524','C30-45 Alkyl Cetearyl Dimethicone Crosspolymer','C30-45 Alkyl Cetearyl Dimethicone Crosspolymer',2,2),
  ('ING1525','Origanum Majorana Leaf Extract','Origanum Majorana Leaf Extract',2,2),
  ('ING1526','Trimethoxycaprylylsilane','Trimethoxycaprylylsilane',2,2),
  ('ING1527','Bees Wax','Bees Wax',2,2),
  ('ING1528','Dibutyl Ethylhexanoyl Glutamide','Dibutyl Ethylhexanoyl Glutamide',2,2),
  ('ING1529','Dibutyl Lauroyl Glutamide','Dibutyl Lauroyl Glutamide',2,2),
  ('ING1530','Acrylates/Dimethicone Copolymer','Acrylates/Dimethicone Copolymer',2,2),
  ('ING1531','Salicornia Herbacea Extract','Salicornia Herbacea Extract',2,2),
  ('ING1532','Poncirus Trifoliata Fruit Extract','Poncirus Trifoliata Fruit Extract',2,2),
  ('ING1533','Allium Sativum (Garlic) Bulb Extract','Allium Sativum (Garlic) Bulb Extract',2,2),
  ('ING1534','Hydroxyethyl Acrylate','Hydroxyethyl Acrylate; HYDROXYETHYL ACRYLATE',2,2),
  ('ING1535','Panax Ginseng Berry Extract','Panax Ginseng Berry Extract',2,2),
  ('ING1536','Triticum Vulgare (Wheat) Sprout Extract','Triticum Vulgare (Wheat) Sprout Extract',2,2),
  ('ING1537','Heptasodium Hexacarboxymethyl Dipeptide-12','Heptasodium Hexacarboxymethyl Dipeptide-12',2,2),
  ('ING1538','Ascorbyl Tetraisopalmitate','Ascorbyl Tetraisopalmitate',2,2),
  ('ING1539','Citrus Sinensis (Orange) Peel Extract','Citrus Sinensis (Orange) Peel Extract; CITRUS SINENSIS (ORANGE) PEEL EXTRACT',2,2),
  ('ING1540','PEG-7 CAPRYLIC/CAPRIC GLYCERIDES','PEG-7 CAPRYLIC/CAPRIC GLYCERIDES',2,2),
  ('ING1541','MYRTRIMONIUM BROMIDE','MYRTRIMONIUM BROMIDE',2,2),
  ('ING1542','Avena Sativa (Oat) Meal Extract','Avena Sativa (Oat) Meal Extract',2,2),
  ('ING1543','Glycine Max (Soybean) Seed Extract','Glycine Max (Soybean) Seed Extract',2,2),
  ('ING1544','medicago sativa (alfalfa) extract','medicago sativa (alfalfa) extract; Medicago Sativa (Alfalfa) Extract',2,2),
  ('ING1545','Pyruvic Acid','Pyruvic Acid',2,2),
  ('ING1546','Juniperus Communis Fruit Extract','Juniperus Communis Fruit Extract',2,2),
  ('ING1547','Rutin','Rutin',2,2),
  ('ING1548','Artemisia Vulgaris Extract','Artemisia Vulgaris Extract',2,2),
  ('ING1549','PEG-20','PEG-20',2,2),
  ('ING1550','LEMON (CITRUS LIMON) EXTRACT','LEMON (CITRUS LIMON) EXTRACT; lemon extract',2,2),
  ('ING1551','PUNICA GRANATUM PERICARP EXTRACT','PUNICA GRANATUM PERICARP EXTRACT; Punica Granatum Pericarp Extract',2,2),
  ('ING1552','Alchemilla Vulgaris Extract','Alchemilla Vulgaris Extract',2,2),
  ('ING1553','PEG-30 GLYCERYL COCOATE','PEG-30 GLYCERYL COCOATE',2,2),
  ('ING1554','Sapindus Trifoliatus Fruit Extract (экстракт индийского мыльного ореха)','Sapindus Trifoliatus Fruit Extract (экстракт индийского мыльного ореха); Sapindus Trifoliatus Fruit Extract',2,2),
  ('ING1555','citrus aurantium amara (bitter orange) flower extract','citrus aurantium amara (bitter orange) flower extract; Citrus Aurantium Amara (Bitter Orange) Flower Extract',2,2),
  ('ING1556','C12-16 alcohol','C12-16 alcohol; C12-16 Alcohol',2,2),
  ('ING1557','Tamarindus Indica Seed Gum','Tamarindus Indica Seed Gum',2,2),
  ('ING1558','Illicium Verum (Anise) Fruit Extract','Illicium Verum (Anise) Fruit Extract',2,2),
  ('ING1559','Berberis Vulgaris Root Extract','Berberis Vulgaris Root Extract',2,2),
  ('ING1560','HYDROXYETHYLPIPERAZINE ETHANE SULFONIC ACID','HYDROXYETHYLPIPERAZINE ETHANE SULFONIC ACID; hydroxyethylpiperazine ethane sulfonic acid',2,2),
  ('ING1561','Phellinus Linteus Extract','Phellinus Linteus Extract',2,2),
  ('ING1562','Oleanolic Acid','Oleanolic Acid',2,2),
  ('ING1563','Paraffin','Paraffin',2,2),
  ('ING1564','Decyl Oleate','Decyl Oleate',2,2),
  ('ING1565','Polyglyceryl-3 Polyricinoleate','Polyglyceryl-3 Polyricinoleate',2,2),
  ('ING1566','Stearalkonium Hectorite','Stearalkonium Hectorite; STEARALKONIUM HECTORITE',2,2),
  ('ING1567','Copernicia Cerifera Wax','Copernicia Cerifera Wax',2,2),
  ('ING1568','Disodium Stearoyl Glutamate','Disodium Stearoyl Glutamate',2,2),
  ('ING1569','Ci 77499 / Iron Oxides','Ci 77499 / Iron Oxides; Ci 77499/ Iron Oxides',2,2),
  ('ING1570','Salvia Officinalis (Sage) Oil','Salvia Officinalis (Sage) Oil',2,2),
  ('ING1571','Palmitoyl Tripeptide-8','Palmitoyl Tripeptide-8',2,2),
  ('ING1572','Silver (ci 77820)','Silver (ci 77820); Silver',2,2),
  ('ING1573','Acetyl Glucosamine','Acetyl Glucosamine',2,2),
  ('ING1574','Hydroxyphenyl Propamidobenzoic Acid','Hydroxyphenyl Propamidobenzoic Acid',2,2),
  ('ING1575','Dihydroxyisopropyl Palmoylpalmamide','Dihydroxyisopropyl Palmoylpalmamide; DIHYDROXYISOPROPYL PALMOYLPALMAMIDE',2,2),
  ('ING1576','Acetyl Heptapeptide-4','Acetyl Heptapeptide-4; ACETYL HEPTAPEPTIDE-4',2,2),
  ('ING1577','CERA ALBA (BEESWAX)','CERA ALBA (BEESWAX)',2,2),
  ('ING1578','HIZIKIA FUSIFORME EXTRACT','HIZIKIA FUSIFORME EXTRACT; Hizikia Fusiforme Extract',2,2),
  ('ING1579','TROPOLONE','TROPOLONE; Tropolone',2,2),
  ('ING1580','Peg-9 Polydimethylsiloxyethyl Dimethicone','Peg-9 Polydimethylsiloxyethyl Dimethicone',2,2),
  ('ING1581','Tribehenin','Tribehenin',2,2),
  ('ING1582','MAGNESIUM OXIDE','MAGNESIUM OXIDE; Magnesium Oxide',2,2),
  ('ING1583','SPIRAEA ULMARIA EXTRACT','SPIRAEA ULMARIA EXTRACT; Spiraea Ulmaria Extract',2,2),
  ('ING1584','Opuntia Coccinellifera Fruit Extract','Opuntia Coccinellifera Fruit Extract',2,2),
  ('ING1585','Citrus Unshiu Peel Extract','Citrus Unshiu Peel Extract',2,2),
  ('ING1586','Polyglyceryl-10 Diisostearate','Polyglyceryl-10 Diisostearate',2,2),
  ('ING1587','KOJIC ACID','KOJIC ACID; kojic acid',2,2),
  ('ING1588','Galactomyces Ferment Filtrate (93.69%)','Galactomyces Ferment Filtrate (93.69%); Galactomyces Ferment Filtrate',2,2),
  ('ING1589','STEARYL DIMETHICONE','STEARYL DIMETHICONE; Stearyl Dimethicone',2,2),
  ('ING1590','OCTADECENE','OCTADECENE; Octadecene',2,2),
  ('ING1591','Laminaria Extract','Laminaria Extract; LAMINARIA EXTRACT',2,3),
  ('ING1592','CRYPTOMERIA JAPONICA LEAF EXTRACT','CRYPTOMERIA JAPONICA LEAF EXTRACT; Cryptomeria Japonica Leaf Extract',2,2),
  ('ING1593','Gossypium Herbaceum Seed Extract','Gossypium Herbaceum Seed Extract; Gossypium Herbaceum (Cotton) Seed Extract',2,2),
  ('ING1594','Fragaria Chiloensis (Strawberry) Fruit Extract','Fragaria Chiloensis (Strawberry) Fruit Extract',2,2),
  ('ING1595','Malpighia Glabra (Acerola) Fruit Extract','Malpighia Glabra (Acerola) Fruit Extract',2,2),
  ('ING1596','Jasminum Officinale (Jasmine) Flower Water','Jasminum Officinale (Jasmine) Flower Water',2,2),
  ('ING1597','Raphanus Sativus (Radish) Seed Extract','Raphanus Sativus (Radish) Seed Extract',2,2),
  ('ING1598','Carmine (Cl 75470)','Carmine (Cl 75470); Carmine (CI 75470)',2,2),
  ('ING1599','Commiphora Myrrha Oil','Commiphora Myrrha Oil',2,2),
  ('ING1600','Lauroyl Lysine','Lauroyl Lysine',2,4),
  ('ING1601','Camellia Sinensis Leaf Powder','Camellia Sinensis Leaf Powder',2,2),
  ('ING1602','Carnitine','Carnitine',2,2),
  ('ING1603','Sd Alcohol 40b','Sd Alcohol 40b; sd alcohol 40b',2,2),
  ('ING1604','Dipeptide-2','Dipeptide-2',2,2),
  ('ING1605','Sorbitan Palmitate','Sorbitan Palmitate; sorbitan palmitate',2,2),
  ('ING1606','RESVERATROL DIMETHYL ETHER','RESVERATROL DIMETHYL ETHER; Resveratrol Dimethyl Ether',2,2),
  ('ING1607','QUERCETIN','QUERCETIN; Quercetin',2,2),
  ('ING1608','Calophyllum Inophyllum Seed Oil','Calophyllum Inophyllum Seed Oil',2,2),
  ('ING1609','Microcitrus Australasica Fruit Extract','Microcitrus Australasica Fruit Extract; microcitrus australasica fruit extract.',2,2),
  ('ING1610','Citrus Junos Peel Extract','Citrus Junos Peel Extract',2,2),
  ('ING1611','Indian Mulberry Flower Extract','Indian Mulberry Flower Extract',2,2),
  ('ING1612','Indian Mulberry Leaf Extract','Indian Mulberry Leaf Extract',2,2),
  ('ING1613','Elaeis Guineensis (Palm) Oil','Elaeis Guineensis (Palm) Oil',2,2),
  ('ING1614','C12-14 Alketh-12','C12-14 Alketh-12',2,2),
  ('ING1615','camellia flower extract','camellia flower extract; Camellia Flower Extract',2,2),
  ('ING1616','macadamia seed oil','macadamia seed oil; Macadamia Seed Oil',2,2),
  ('ING1617','dipotassium glycyrhizate','dipotassium glycyrhizate; Dipotassium Glycyrhizate',2,2),
  ('ING1618','retinyl retinoate (30 ppb)','retinyl retinoate (30 ppb); Retinyl Retinoate',2,2),
  ('ING1619','Polypropylsilsesquioxane','Polypropylsilsesquioxane',2,2),
  ('ING1620','Glyceryl Stearates','Glyceryl Stearates',2,2),
  ('ING1621','Betula Alba Juice','Betula Alba Juice',2,2),
  ('ING1622','Olea Europaea (Olive) Oil','Olea Europaea (Olive) Oil; OLEA EUROPAEA (OLIVE) OIL',2,2),
  ('ING1623','Sodium Alginate','Sodium Alginate',2,2),
  ('ING1624','Epigallocatechin Gallate','Epigallocatechin Gallate',2,2),
  ('ING1625','Trifluoroacetyl Tripeptide-2','Trifluoroacetyl Tripeptide-2',2,2),
  ('ING1626','SH-Polypeptide-11','SH-Polypeptide-11',2,2),
  ('ING1627','SH-Polypeptide-9','SH-Polypeptide-9',2,2),
  ('ING1628','Bacillus/Folic Acid Ferment Filtrate Extract','Bacillus/Folic Acid Ferment Filtrate Extract',2,2),
  ('ING1629','Acetyl Glutamine','Acetyl Glutamine',2,2),
  ('ING1630','SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER','SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER; Sodium Acryloyldimethyl Taurate Copolymer',2,2),
  ('ING1631','Brassica Oleracea Italica (Broccoli) Extract','Brassica Oleracea Italica (Broccoli) Extract',2,2),
  ('ING1632','Oligopeptide-32(0.5 ppb)','Oligopeptide-32(0.5 ppb); Oligopeptide-32',2,2),
  ('ING1633','Oligopeptide-29(0.5ppb)','Oligopeptide-29(0.5ppb); Oligopeptide-29',2,2),
  ('ING1634','rh-oligopeptide-1(0.01ppb)','rh-oligopeptide-1(0.01ppb); rh-Oligopeptide-1',2,2),
  ('ING1635','Spanish Licorice Root Extract','Spanish Licorice Root Extract',2,2),
  ('ING1636','Polyglyceryl-3 Diisostearate','Polyglyceryl-3 Diisostearate',2,2),
  ('ING1637','Hydroxyapatite','Hydroxyapatite',2,2),
  ('ING1638','Hydroxystearic Acid','Hydroxystearic Acid',2,2),
  ('ING1639','Strawberry Dry Extract','Strawberry Dry Extract',2,2),
  ('ING1640','ORYZA SATIVA (RICE) STARCH','ORYZA SATIVA (RICE) STARCH; Oryza Sativa (Rice) Starch',2,2),
  ('ING1641','Nelumbo Nucifera Leaf Extract','Nelumbo Nucifera Leaf Extract; Nelumbo Nucifera Leaf Extract(8.7%)',2,2),
  ('ING1642','Propionibacterium Ferment Lysate','Propionibacterium Ferment Lysate',2,2),
  ('ING1643','Myristoyl/palmitoyl Oxostearamide/Arachamide MEA','Myristoyl/palmitoyl Oxostearamide/Arachamide MEA; MYRISTOYL PALMITOYL OXOSTEARAMIDE/ARACHAMIDE MEA',2,2),
  ('ING1644','Sodium Lauroyl Aspartate','Sodium Lauroyl Aspartate',2,2),
  ('ING1645','Polyglyceryl-4 Laurate','Polyglyceryl-4 Laurate',2,2),
  ('ING1646','Drumstick Seed Oil','Drumstick Seed Oil',2,2),
  ('ING1647','Rosa Damascena Extract','Rosa Damascena Extract',2,2),
  ('ING1648','Hibiscus Esculentus Fruit Extract','Hibiscus Esculentus Fruit Extract',2,2),
  ('ING1649','Polygonum Fagopyrum Seed Extract','Polygonum Fagopyrum Seed Extract; Polygonum Fagopyrum (Buckwheat) Seed Extract',2,2),
  ('ING1650','Chamomilla Recutita (Matricaria) Flower Oil','Chamomilla Recutita (Matricaria) Flower Oil',2,2),
  ('ING1651','Thuja Orientalis Extract','Thuja Orientalis Extract',2,2),
  ('ING1652','Bacuchiol (0.1%)','Bacuchiol (0.1%); Bacuchiol (1 000 ppm)',2,2),
  ('ING1653','Sodium Salt Of Salmon DNA (0.1%)','Sodium Salt Of Salmon DNA (0.1%); Sodium Salt Of Salmon DNA (1 000 ppm)',2,2),
  ('ING1654','Astaxanthin','Astaxanthin',2,2),
  ('ING1655','Anemarrhena Asphodeloides Root Extract','Anemarrhena Asphodeloides Root Extract',2,2),
  ('ING1656','3-Butanediol','3-Butanediol',2,2),
  ('ING1657','Prunus Persica (Peach) Flower Extract','Prunus Persica (Peach) Flower Extract',2,2),
  ('ING1658','Gellan Gum','Gellan Gum',2,2),
  ('ING1659','Salvia Hispanica Seed Oil','Salvia Hispanica Seed Oil; Salvia Hispanica (Chia) Seed Oil',2,2),
  ('ING1660','Lactobionic Acid','Lactobionic Acid',2,2),
  ('ING1661','Centaurea Cyanus Flower Water(9%)','Centaurea Cyanus Flower Water(9%); Centaurea Cyanus Flower Water',2,2),
  ('ING1662','Saccharomyces/Xylinum/Black Tea Ferment','Saccharomyces/Xylinum/Black Tea Ferment',2,2),
  ('ING1663','Tasmannia Lanceolata Fruit/Leaf Extract','Tasmannia Lanceolata Fruit/Leaf Extract',2,2),
  ('ING1664','Acacia Senegal Gum','Acacia Senegal Gum',2,2),
  ('ING1665','Boswellia serrata Extract','Boswellia serrata Extract; BOSWELLIA SERRATA EXTRACT',2,2),
  ('ING1666','Ceresin','Ceresin',2,2),
  ('ING1667','Octisalate','Octisalate',2,2),
  ('ING1668','Hedera Helix Extract','Hedera Helix Extract; Hedera Helix (Ivy) Extract',2,2),
  ('ING1669','MONASCUS EXTRACT','MONASCUS EXTRACT; Monascus Extract',2,2),
  ('ING1670','Angelica Elm Root Extract','Angelica Elm Root Extract',2,2),
  ('ING1671','Sorghum Bicolor Leaf/Stem Extract','Sorghum Bicolor Leaf/Stem Extract',2,2),
  ('ING1672','Anastatica Hierochuntica Extract','Anastatica Hierochuntica Extract',2,2),
  ('ING1673','Cynara Scolymus Leaf Extract','Cynara Scolymus Leaf Extract; Cynara Scolymus (Artichoke) Leaf Extract',2,2),
  ('ING1674','pencil juniper oil','pencil juniper oil; Pencil Juniper Oil',2,2),
  ('ING1675','holy basil leaf extract','holy basil leaf extract; Holy Basil Leaf Extract',2,2),
  ('ING1676','true coral extract','true coral extract; True Coral Extract',2,2),
  ('ING1677','fragrant violet petal extract','fragrant violet petal extract; Fragrant Violet Petal Extract',2,2),
  ('ING1678','chamomile flower oil','chamomile flower oil; Chamomile Flower Oil',2,2),
  ('ING1679','Paeonia Albiflora Flower Extract','Paeonia Albiflora Flower Extract',2,2),
  ('ING1680','Gardenia Extract','Gardenia Extract',2,2),
  ('ING1681','Pinus Densiflora Leaf Extract','Pinus Densiflora Leaf Extract',2,2),
  ('ING1682','Citrus Aurantium Bergamia (Bergamot) Leaf Extract','Citrus Aurantium Bergamia (Bergamot) Leaf Extract',2,2),
  ('ING1683','Cladosiphon Okamuranus Extract','Cladosiphon Okamuranus Extract',2,2),
  ('ING1684','4-t-Butylcyclohexanol','4-t-Butylcyclohexanol',2,2),
  ('ING1685','Sodium Hyaloronate','Sodium Hyaloronate',2,2),
  ('ING1686','Rosewood Oil','Rosewood Oil',2,2),
  ('ING1687','Lavender Oil','Lavender Oil',2,2),
  ('ING1688','Bergamot Oil','Bergamot Oil',2,2),
  ('ING1689','Scented Geranium Flower Oil','Scented Geranium Flower Oil',2,2),
  ('ING1690','Ribose','Ribose',2,2),
  ('ING1691','alpha-bisabolol','alpha-bisabolol; Alpha-Bisabolol',2,2),
  ('ING1692','Polyglyceryl-6 Dicaprate','Polyglyceryl-6 Dicaprate',2,2),
  ('ING1693','Prunus Mume Fruit Extract','Prunus Mume Fruit Extract',2,2),
  ('ING1694','Sorbeth-30 Tetraoleate','Sorbeth-30 Tetraoleate',2,2),
  ('ING1695','Asparagopsis Armata Extract','Asparagopsis Armata Extract',2,2),
  ('ING1696','Nonfat Dry Milk','Nonfat Dry Milk',1,1),
  ('ING1697','Quaternium-70','Quaternium-70',1,1),
  ('ING1698','Dicaprylate/Dicaprate','Dicaprylate/Dicaprate',1,1),
  ('ING1699','Santalum Acuminatum Fruit Extract','Santalum Acuminatum Fruit Extract',1,1),
  ('ING1700','Leptospermum Scoparium Leaf Extract','Leptospermum Scoparium Leaf Extract',1,1),
  ('ING1701','Morpholinomethyl Silsesquioxane Copolymer','Morpholinomethyl Silsesquioxane Copolymer',1,1),
  ('ING1702','Magnesium Citrate','Magnesium Citrate',1,1),
  ('ING1703','Cocodimonium Hydroxypropyl','Cocodimonium Hydroxypropyl',1,1),
  ('ING1704','Argana Spinosa Kernel Oil','Argana Spinosa Kernel Oil',1,1),
  ('ING1705','Dimethicone/Silsesquioxane Copolymer','Dimethicone/Silsesquioxane Copolymer',1,1),
  ('ING1706','Polyoxyethylene Cetyl Steryl Ether','Polyoxyethylene Cetyl Steryl Ether',1,1),
  ('ING1707','Butyrosperum Parkii (Shea Butter) Oil','Butyrosperum Parkii (Shea Butter) Oil',1,1),
  ('ING1708','Opuntia Tuna Extract','Opuntia Tuna Extract',1,1),
  ('ING1709','Boswella Carterii Oil','Boswella Carterii Oil',1,1),
  ('ING1710','Peg-4 Sorbitan Stearate','Peg-4 Sorbitan Stearate',1,1),
  ('ING1711','OAT MILK PROTEIN','OAT MILK PROTEIN',1,1),
  ('ING1712','Hydroxy-Propyltrimonium Hydrolyzed Wheat Protein','Hydroxy-Propyltrimonium Hydrolyzed Wheat Protein',1,1),
  ('ING1713','Trisodium Hedta','Trisodium Hedta',1,1),
  ('ING1714','Fragrance Citric Acid','Fragrance Citric Acid',1,1),
  ('ING1715','Creatin','Creatin',1,1),
  ('ING1716','olive fruit oil (масло оливы)','olive fruit oil (масло оливы)',1,1),
  ('ING1717','Olea Europaea Fruit Oil / Olive Fruit Oil','Olea Europaea Fruit Oil / Olive Fruit Oil',1,1),
  ('ING1718','Prunus Amygdalus Dulcis Oil / Sweet Almond Oil','Prunus Amygdalus Dulcis Oil / Sweet Almond Oil',1,1),
  ('ING1719','Dilauryl Thiodipropionate','Dilauryl Thiodipropionate',1,1),
  ('ING1720','PEG-150/ Decyl Alcohol/ Smdi Copolymer','PEG-150/ Decyl Alcohol/ Smdi Copolymer',1,1),
  ('ING1721','Ecklonia Radiata Extract','Ecklonia Radiata Extract',1,1),
  ('ING1722','Laurdimonium Hydroxypropyl Hydrolyzed Collagen','Laurdimonium Hydroxypropyl Hydrolyzed Collagen',1,1),
  ('ING1723','Zinc Pyrition','Zinc Pyrition',1,1),
  ('ING1724','Acrylates/Vinyl Neodecanoate Crosspolymer','Acrylates/Vinyl Neodecanoate Crosspolymer',1,1),
  ('ING1725','Phenyllalanine','Phenyllalanine',1,1),
  ('ING1726','Magnesium PCA','Magnesium PCA',1,1),
  ('ING1727','Manganese PCA','Manganese PCA',1,1),
  ('ING1728','Buthylene Glycol','Buthylene Glycol',1,1),
  ('ING1729','PPG-26-Buteht-26','PPG-26-Buteht-26',1,1),
  ('ING1730','Apigenin','Apigenin',1,1),
  ('ING1731','Olealonic Acid','Olealonic Acid',1,1),
  ('ING1732','Biotinoyl Tripeptide-1','Biotinoyl Tripeptide-1',1,1),
  ('ING1733','Hydolyzed Corn Protein','Hydolyzed Corn Protein',1,1),
  ('ING1734','Pyrus Malus Stem Extract','Pyrus Malus Stem Extract',1,1),
  ('ING1735','Chamomile Recutita Flower','Chamomile Recutita Flower',1,1),
  ('ING1736','Argania Spinosa Fruit Extract','Argania Spinosa Fruit Extract',1,1),
  ('ING1737','Equisetum Arvense Leaf Extract','Equisetum Arvense Leaf Extract',1,1),
  ('ING1738','Methylcholoisothiazolinone','Methylcholoisothiazolinone',1,1),
  ('ING1739','BUTYROSPERMUM PARK 11 (SHEA BUTTER)','BUTYROSPERMUM PARK 11 (SHEA BUTTER)',1,1),
  ('ING1740','OLETH-2','OLETH-2',1,1),
  ('ING1741','CHOLESTERYL LANOLATE','CHOLESTERYL LANOLATE',1,1),
  ('ING1742','MACADAM IA TERNIFOLIA SEED OIL','MACADAM IA TERNIFOLIA SEED OIL',1,1),
  ('ING1743','HAZEL (CORYLUS AMERICANA) NUT OIL','HAZEL (CORYLUS AMERICANA) NUT OIL',1,1),
  ('ING1744','CAMELLIA JAPONICA OIL','CAMELLIA JAPONICA OIL',1,1),
  ('ING1745','DOG ROSE (ROSA CAN IN A) HIPS OIL','DOG ROSE (ROSA CAN IN A) HIPS OIL',1,1),
  ('ING1746','DIPENTAERYTHRITYL','DIPENTAERYTHRITYL',1,1),
  ('ING1747','HEXAHYDROXYSTEARATE/ HEXASTEARATE/HEXAROSINATE','HEXAHYDROXYSTEARATE/ HEXASTEARATE/HEXAROSINATE',1,1),
  ('ING1748','CETEARETH-7','CETEARETH-7',1,1),
  ('ING1749','CETEARETH-13','CETEARETH-13',1,1),
  ('ING1750','Hydrolyzed Glycerin','Hydrolyzed Glycerin',1,1),
  ('ING1751','Carum Petroselinum (Parsley) Extract','Carum Petroselinum (Parsley) Extract',1,1),
  ('ING1752','Ory za Sativa (Rice) Bran Extract','Ory za Sativa (Rice) Bran Extract',1,1),
  ('ING1753','Trideceth‐12','Trideceth‐12',1,1),
  ('ING1754','SODIUM METHYL 2-SULFOLAURATE','SODIUM METHYL 2-SULFOLAURATE',1,1),
  ('ING1755','DISODIUM 2-SULFOLAURATE','DISODIUM 2-SULFOLAURATE',1,1),
  ('ING1756','PRUNUS AMYGDALUS DULCIS SEED EXTRACT / PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) SEED EXTRACT','PRUNUS AMYGDALUS DULCIS SEED EXTRACT / PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) SEED EXTRACT',1,1),
  ('ING1757','Vegetable Amino Acids','Vegetable Amino Acids',1,1),
  ('ING1758','Oligopeptide1','Oligopeptide1',1,1),
  ('ING1759','ethyl ether','ethyl ether',1,1),
  ('ING1760','Disodium Cocoampodieteacetate','Disodium Cocoampodieteacetate',1,1),
  ('ING1761','Acetyl Nucleopeptide-8','Acetyl Nucleopeptide-8',1,1),
  ('ING1762','C12-15 Pares-3','C12-15 Pares-3',1,1),
  ('ING1763','Methylpolysiloxane Emulsion','Methylpolysiloxane Emulsion',1,1),
  ('ING1764','octyldodecyl pca','octyldodecyl pca',1,1),
  ('ING1765','butylphenyl','butylphenyl',1,1),
  ('ING1766','methylpropional','methylpropional',1,1),
  ('ING1767','orange 4 (ci15510)','orange 4 (ci15510)',1,1),
  ('ING1768','Hydrolyzed Hemp Seed Extract','Hydrolyzed Hemp Seed Extract',1,1),
  ('ING1769','Alpha-Isomethyl lonone','Alpha-Isomethyl lonone',1,1),
  ('ING1770','Trimethylsilylamodimethicone','Trimethylsilylamodimethicone',1,1),
  ('ING1771','Methoxy Peg/ppg-7/3 Aminopropyl Dimethicone','Methoxy Peg/ppg-7/3 Aminopropyl Dimethicone',1,1),
  ('ING1772','C11-15 Pareth-5','C11-15 Pareth-5',1,1),
  ('ING1773','C11-15 Pareth-9','C11-15 Pareth-9',1,1),
  ('ING1774','Camellia Oelifera Seed Oil','Camellia Oelifera Seed Oil',1,1),
  ('ING1775','polyurethane-48','polyurethane-48',1,1),
  ('ING1776','hydrolized keratin','hydrolized keratin',1,1),
  ('ING1777','C262059/1','C262059/1',1,1),
  ('ING1778','Dimethicone Peg-7 Phosphate','Dimethicone Peg-7 Phosphate',1,1),
  ('ING1779','pp','pp',1,1),
  ('ING1780','ethylhexy| methoxycinnamate','ethylhexy| methoxycinnamate',1,1),
  ('ING1781','methy! gluceth-20','methy! gluceth-20',1,1),
  ('ING1782','potossium sorbate','potossium sorbate',1,1),
  ('ING1783','Vincetoxicum Atratum Root Extract','Vincetoxicum Atratum Root Extract',1,1),
  ('ING1784','Behentrimonium Methosulfat','Behentrimonium Methosulfat',1,1),
  ('ING1785','Lemon acid','Lemon acid',1,1),
  ('ING1786','Lotus Japonicus Extract','Lotus Japonicus Extract',1,1),
  ('ING1787','Celandine Extract','Celandine Extract',1,1),
  ('ING1788','Juniper Extract','Juniper Extract',1,1),
  ('ING1789','Lemongrass Extract','Lemongrass Extract',1,1),
  ('ING1790','Vitamin B3 (Niacinamide)','Vitamin B3 (Niacinamide)',1,1),
  ('ING1791','Vitamin Е (Tocopherols)','Vitamin Е (Tocopherols)',1,1),
  ('ING1792','DIPENTAERYTHRITYLHEXA C5-9 ACID ESTERS','DIPENTAERYTHRITYLHEXA C5-9 ACID ESTERS',1,1),
  ('ING1793','BIS-METHOXYPROPYLAMIDOISODOCOSANE','BIS-METHOXYPROPYLAMIDOISODOCOSANE',1,1),
  ('ING1794','GARDENIA TAITENSIS FLOWER EXTRACT','GARDENIA TAITENSIS FLOWER EXTRACT',1,1),
  ('ING1795','Stearoxypropyl Dimethylamine','Stearoxypropyl Dimethylamine',1,1),
  ('ING1796','C14-28 Isoalkyl Acid','C14-28 Isoalkyl Acid',1,1),
  ('ING1797','C14-28 Alkyl Acid','C14-28 Alkyl Acid',1,1),
  ('ING1798','Bis(C13-15 Alkoxy) PGAmodimethicone','Bis(C13-15 Alkoxy) PGAmodimethicone',1,1),
  ('ING1799','Cocodimonium Hydroxypropyl Hydrolyzed Wheat Protein','Cocodimonium Hydroxypropyl Hydrolyzed Wheat Protein',1,1),
  ('ING1800','Glycerin Stearate','Glycerin Stearate',1,1),
  ('ING1801','Sodium Stearate','Sodium Stearate',1,1),
  ('ING1802','Dht','Dht',1,1),
  ('ING1803','Tilia Cordata Flower Extract','Tilia Cordata Flower Extract',1,1),
  ('ING1804','Mentha piperita water','Mentha piperita water',1,1),
  ('ING1805','astrocaryum tucuma seed butter','astrocaryum tucuma seed butter',1,1),
  ('ING1806','hydrolyzsed chestnut extract','hydrolyzsed chestnut extract',1,1),
  ('ING1807','vitis vinifera (grape) fruit cell extract','vitis vinifera (grape) fruit cell extract',1,1),
  ('ING1808','hydrolyzed eruca sativa leaf','hydrolyzed eruca sativa leaf',1,1),
  ('ING1809','hydrolyzed walnut extract','hydrolyzed walnut extract',1,1),
  ('ING1810','Hydrogenated Vegetable Glycerides','Hydrogenated Vegetable Glycerides',1,1),
  ('ING1811','Acrylates/ Stearyl Methacrylate Copolymer','Acrylates/ Stearyl Methacrylate Copolymer',1,1),
  ('ING1812','HEXADIMETHRINE CHLORIDE','HEXADIMETHRINE CHLORIDE',1,1),
  ('ING1813','aloe barbadensis / aloe barbadensis leaf juice','aloe barbadensis / aloe barbadensis leaf juice',1,1),
  ('ING1814','methyl cocoate','methyl cocoate',1,1),
  ('ING1815','passiflora edulis fruit juice','passiflora edulis fruit juice',1,1),
  ('ING1816','Ppg-5-Ceteth-10 Phosphate','Ppg-5-Ceteth-10 Phosphate',1,1),
  ('ING1817','Agave Tequilana Leaf Extract','Agave Tequilana Leaf Extract',1,1),
  ('ING1818','Orchis Mascula Extract','Orchis Mascula Extract',1,1),
  ('ING1819','ITRONELLOL','ITRONELLOL',1,1),
  ('ING1820','Elaeis Guineensis Oil / Palm Oil','Elaeis Guineensis Oil / Palm Oil',1,1),
  ('ING1821','Aminopropyl Triethoxysilane','Aminopropyl Triethoxysilane',1,1),
  ('ING1822','benzyl alcohol methylchloroisothiazolinone','benzyl alcohol methylchloroisothiazolinone',1,1),
  ('ING1823','CI9140','CI9140',1,1),
  ('ING1824','CI42090','CI42090',1,1),
  ('ING1825','Sodium Dilaureth-7 Citrate','Sodium Dilaureth-7 Citrate',1,1),
  ('ING1826','Сaprylic Triglyceride','Сaprylic Triglyceride',1,1),
  ('ING1827','Lycopene','Lycopene',1,1),
  ('ING1828','PUFA BOOSTER','PUFA BOOSTER',1,1),
  ('ING1829','NATURAL PUMPKIN SEED OIL','NATURAL PUMPKIN SEED OIL',1,1),
  ('ING1830','COUMARIN ALPHA-ISOMETHYL','COUMARIN ALPHA-ISOMETHYL',1,1),
  ('ING1831','IONONE','IONONE',1,1),
  ('ING1832','Sea Salt (Maris Sal/Dead Sea Salt)','Sea Salt (Maris Sal/Dead Sea Salt)',1,1),
  ('ING1833','Cocoamid Dea','Cocoamid Dea',1,1),
  ('ING1834','Polyimide-1','Polyimide-1',1,1),
  ('ING1835','Sodium Cocoyl Sarcosinate','Sodium Cocoyl Sarcosinate',1,1),
  ('ING1836','PEG-4 Rapeseedamide','PEG-4 Rapeseedamide',1,1),
  ('ING1837','ammonium hydroxide','ammonium hydroxide',1,1),
  ('ING1838','saccharum officinarum extract / sugar cane extract','saccharum officinarum extract / sugar cane extract',1,1),
  ('ING1839','cocos nucifera fruit extract / coconut fruit extract','cocos nucifera fruit extract / coconut fruit extract',1,1),
  ('ING1840','citrus limon peel extract / lemon peel extract','citrus limon peel extract / lemon peel extract',1,1),
  ('ING1841','vitamine e','vitamine e',1,1),
  ('ING1842','hydroxyethlcellulose','hydroxyethlcellulose',1,1),
  ('ING1843','Escalol HP-610','Escalol HP-610',1,1),
  ('ING1844','Lanolinum anhydricum','Lanolinum anhydricum',1,1),
  ('ING1845','Rose Oil','Rose Oil',1,1),
  ('ING1846','Daucus carota extract','Daucus carota extract',1,1),
  ('ING1847','Zea mays germ oil','Zea mays germ oil',1,1),
  ('ING1848','Aqua with infusions of Rubus Idaeus Fruit Extract','Aqua with infusions of Rubus Idaeus Fruit Extract',1,1),
  ('ING1849','PEG-PPG-15/15 Acetate Dimethicone','PEG-PPG-15/15 Acetate Dimethicone',1,1),
  ('ING1850','PEG-PPG 15/15 Allyl Ether Acetate','PEG-PPG 15/15 Allyl Ether Acetate',1,1),
  ('ING1851','PEG/PPG-15/15 Acetate','PEG/PPG-15/15 Acetate',1,1),
  ('ING1852','Glycidoxy Dimethicone Crosspolymer','Glycidoxy Dimethicone Crosspolymer',1,1),
  ('ING1853','Silk Protein','Silk Protein',1,1),
  ('ING1854','Dipropylene Glycol Trideceth-12','Dipropylene Glycol Trideceth-12',1,1),
  ('ING1855','Macadamia Ternifolia Seed Extract','Macadamia Ternifolia Seed Extract',1,1),
  ('ING1856','C10-40 Isoalkylamidopropylet hyldimonium Ethosulfate','C10-40 Isoalkylamidopropylet hyldimonium Ethosulfate',1,1),
  ('ING1857','Jojoba Oil','Jojoba Oil',1,1),
  ('ING1858','Lactobacillus/ Milk Ferment Filtrate','Lactobacillus/ Milk Ferment Filtrate',1,1),
  ('ING1859','Perilla Ocymoides Leaf Extract','Perilla Ocymoides Leaf Extract',1,1),
  ('ING1860','Nasturtium Officinale','Nasturtium Officinale',1,1),
  ('ING1861','Leaf/ Stem Extract','Leaf/ Stem Extract',1,1),
  ('ING1862','Allium Sativum (Garlic) Extract','Allium Sativum (Garlic) Extract',1,1),
  ('ING1863','Hedera Helix (Ivy)','Hedera Helix (Ivy)',1,1),
  ('ING1864','Leaf/ Stem Extract Lamium','Leaf/ Stem Extract Lamium',1,1),
  ('ING1865','Albumen','Albumen',1,1),
  ('ING1866','Flower Extract','Flower Extract',1,1),
  ('ING1867','Pinus Sylvestris Cone Extract','Pinus Sylvestris Cone Extract',1,1),
  ('ING1868','Hydroxypropylcellulose','Hydroxypropylcellulose',1,1),
  ('ING1869','PPG-2 Cocamide','PPG-2 Cocamide',1,1),
  ('ING1870','Potassium Cocoyl Hydrolyzed Keratin','Potassium Cocoyl Hydrolyzed Keratin',1,1),
  ('ING1871','Polyquaternium-48','Polyquaternium-48',1,1),
  ('ING1872','Fullerenes〔Nano〕','Fullerenes〔Nano〕',1,1),
  ('ING1873','Sorbeth-60 Tetraoleate','Sorbeth-60 Tetraoleate',1,1),
  ('ING1874','Sodium removed comma Cocoyl Isethionate','Sodium removed comma Cocoyl Isethionate',1,1),
  ('ING1875','Calcium Sodium Borosilicate','Calcium Sodium Borosilicate',1,1),
  ('ING1876','Silver Oxide','Silver Oxide',1,1),
  ('ING1877','PPG-51/ Smdi Copolymer','PPG-51/ Smdi Copolymer',1,1),
  ('ING1878','PEG-2 Oleammonium Chloride','PEG-2 Oleammonium Chloride',1,1),
  ('ING1879','Dicocodimonium Chloride','Dicocodimonium Chloride',1,1),
  ('ING1880','Ceteth-20','Ceteth-20',1,1),
  ('ING1881','Isostearamidopropyl Betaine','Isostearamidopropyl Betaine',1,1),
  ('ING1882','PEG-20 Sorbitan Cocoate','PEG-20 Sorbitan Cocoate',1,1),
  ('ING1883','Potassium Cocoyl Hydrolyzed Collagen','Potassium Cocoyl Hydrolyzed Collagen',1,1),
  ('ING1884','Sodium Lauroyl Hydrolyzed Silk','Sodium Lauroyl Hydrolyzed Silk',1,1),
  ('ING1885','Hydrolyzed Coix Lacryma-Jobi Ma-Yuen Seed','Hydrolyzed Coix Lacryma-Jobi Ma-Yuen Seed',1,1),
  ('ING1886','Isodonis Japonicus Leaf/ Stalk Extract','Isodonis Japonicus Leaf/ Stalk Extract',1,1),
  ('ING1887','Hydrolyzed Silk Pg-Propyl Methylsilanediol Crosspolymer','Hydrolyzed Silk Pg-Propyl Methylsilanediol Crosspolymer',1,1),
  ('ING1888','Hydrolyzed Sesame Protein Pg-Propyl Methylsilanediol','Hydrolyzed Sesame Protein Pg-Propyl Methylsilanediol',1,1),
  ('ING1889','Aminopropyl Phenyl Trimethicone','Aminopropyl Phenyl Trimethicone',1,1),
  ('ING1890','Paraffinum Liquidum / Mineral Oil','Paraffinum Liquidum / Mineral Oil',1,1),
  ('ING1891','Safflower Glucoside','Safflower Glucoside',1,1),
  ('ING1892','Methyl Lactate','Methyl Lactate',1,1),
  ('ING1893','TEA-dodecylbenzene-sulfonate','TEA-dodecylbenzene-sulfonate',1,1),
  ('ING1894','PPG-3','PPG-3',1,1),
  ('ING1895','Caprilic Ether','Caprilic Ether',1,1),
  ('ING1896','Shea Oil','Shea Oil',1,1),
  ('ING1897','Quinoa Extract','Quinoa Extract',1,1),
  ('ING1898','Butylhydrooctanol','Butylhydrooctanol',1,1),
  ('ING1899','Alteromonas Ferment Extract','Alteromonas Ferment Extract',1,1),
  ('ING1900','Phytosteryl/ Isostearyl/ Cetyl/ Stearyl/ Behenyl Dimer Dilinoleate','Phytosteryl/ Isostearyl/ Cetyl/ Stearyl/ Behenyl Dimer Dilinoleate',1,1),
  ('ING1901','Caprylyl Caprylate/Caprate','Caprylyl Caprylate/Caprate',1,1),
  ('ING1902','Castor Isostearate Succinate','Castor Isostearate Succinate',1,1),
  ('ING1903','Hydroxyethyl Ethylcellulose','Hydroxyethyl Ethylcellulose',1,1),
  ('ING1904','Cocamidopropylamine Oxide','Cocamidopropylamine Oxide',1,1),
  ('ING1905','Pentasodium Triphosphate','Pentasodium Triphosphate',1,1),
  ('ING1906','Potassium','Potassium',1,1),
  ('ING1907','PPG-3 Benzyl Ether Myristate','PPG-3 Benzyl Ether Myristate',1,1),
  ('ING1908','Octyldodecyl Ricinoleate','Octyldodecyl Ricinoleate',1,1),
  ('ING1909','Dimethicone PEG-7 Isostearate','Dimethicone PEG-7 Isostearate',1,1),
  ('ING1910','Glycine Soya (Soybean) Oil','Glycine Soya (Soybean) Oil',1,1),
  ('ING1911','PEG-7 Amodimethicone','PEG-7 Amodimethicone',1,1),
  ('ING1912','Ahnfeltiopsis Concinna Extract','Ahnfeltiopsis Concinna Extract',1,1),
  ('ING1913','Tocopheryl Linoleate/Oleate','Tocopheryl Linoleate/Oleate',1,1),
  ('ING1914','Iodpropynyl Butylcarbamate','Iodpropynyl Butylcarbamate',1,1),
  ('ING1915','Gigartina Stellata Extract','Gigartina Stellata Extract',1,1),
  ('ING1916','Pseudozyma Epicola/Camellia','Pseudozyma Epicola/Camellia',1,1),
  ('ING1917','Sinensis Seed Oil Ferment Extract Filtrate','Sinensis Seed Oil Ferment Extract Filtrate',1,1),
  ('ING1918','Zea Mays (Corn) Oil','Zea Mays (Corn) Oil',1,1),
  ('ING1919','Morinda Citrifolia Fruit Powder','Morinda Citrifolia Fruit Powder',1,1),
  ('ING1920','Rosa Canina (Rose Hip) Seed Extract','Rosa Canina (Rose Hip) Seed Extract',1,1),
  ('ING1921','Cannabis Sativa (Hemp) Seed Oil','Cannabis Sativa (Hemp) Seed Oil',1,1),
  ('ING1922','Bis-Cetearyl Amodimethicone','Bis-Cetearyl Amodimethicone',1,1),
  ('ING1923','Sodium Nitrate','Sodium Nitrate',1,1),
  ('ING1924','Tocopherol Fragrance (Parfum)','Tocopherol Fragrance (Parfum)',1,1),
  ('ING1925','Quaternium-22','Quaternium-22',1,1),
  ('ING1926','Furcellaria Lumbricalis Extract','Furcellaria Lumbricalis Extract',1,1),
  ('ING1927','Cocos Nucifera Seed Oil','Cocos Nucifera Seed Oil',1,1),
  ('ING1928','C14-15 Alcohols','C14-15 Alcohols',1,1),
  ('ING1929','Isotridecyl Alcohol','Isotridecyl Alcohol',1,1),
  ('ING1930','Laureth Sulfate','Laureth Sulfate',1,1),
  ('ING1931','хлорид гуаргидроксипропилтримония','хлорид гуаргидроксипропилтримония',1,1),
  ('ING1932','экстракт белой крапивы','экстракт белой крапивы',1,1),
  ('ING1933','сосны','сосны',1,1),
  ('ING1934','лопуха','лопуха',1,1),
  ('ING1935','ромашки','ромашки',1,1),
  ('ING1936','розмарина','розмарина',1,1),
  ('ING1937','плюща','плюща',1,1),
  ('ING1938','арники','арники',1,1),
  ('ING1939','водяного креса','водяного креса',1,1),
  ('ING1940','чеснока','чеснока',1,1),
  ('ING1941','глицерет-8 эфиры оливкового масла','глицерет-8 эфиры оливкового масла',1,1),
  ('ING1942','ЭДТА динатрия','ЭДТА динатрия',1,1),
  ('ING1943','бензиловый спирт','бензиловый спирт',1,1),
  ('ING1944','метилхлоризотиазолинон','метилхлоризотиазолинон',1,1),
  ('ING1945','метилизотиазолинон','метилизотиазолинон',1,1),
  ('ING1946','кислота лимонная','кислота лимонная',1,1),
  ('ING1947','экстрак семян Brassica Juncea (горчицы)','экстрак семян Brassica Juncea (горчицы)',1,1),
  ('ING1948','краситель оранжевый','краситель оранжевый',1,1),
  ('ING1949','Guar Hydroxypropy trimonium Chloride','Guar Hydroxypropy trimonium Chloride',1,1),
  ('ING1950','Ceteareth-33','Ceteareth-33',1,1),
  ('ING1951','Padin Pavonica Extract','Padin Pavonica Extract',1,1),
  ('ING1952','Cl42090','Cl42090',1,1),
  ('ING1953','Symphytum Officinale Leaf Extract','Symphytum Officinale Leaf Extract',1,1),
  ('ING1954','Red 40 (CI 16035)','Red 40 (CI 16035)',1,1),
  ('ING1955','Tilia Platyphyllos (Linden) Flower Water','Tilia Platyphyllos (Linden) Flower Water',1,1),
  ('ING1956','Dwarf Nettle (Urtica Urens) Leaf Water','Dwarf Nettle (Urtica Urens) Leaf Water',1,1),
  ('ING1957','Salix Nigra (Willow) Bark Extract','Salix Nigra (Willow) Bark Extract',1,1),
  ('ING1958','Dihydroxypropyl PEG-5 Linoleammonium Chloride','Dihydroxypropyl PEG-5 Linoleammonium Chloride',1,1),
  ('ING1959','Tuber Melanosporum (Black Truffle) Extract','Tuber Melanosporum (Black Truffle) Extract',1,1),
  ('ING1960','Sodium C14-16 Alpha Olefin Sulfonate','Sodium C14-16 Alpha Olefin Sulfonate',1,1),
  ('ING1961','Vinegar','Vinegar',1,1),
  ('ING1962','Lauroyl Methyl Glucamide','Lauroyl Methyl Glucamide',1,1),
  ('ING1963','Silicone Quaternium-17','Silicone Quaternium-17',1,1),
  ('ING1964','C12-14 sec-Pareth-5','C12-14 sec-Pareth-5',1,1),
  ('ING1965','C12-14 sec-Pareth-9','C12-14 sec-Pareth-9',1,1),
  ('ING1966','Na-PCA','Na-PCA',1,1),
  ('ING1967','Dimethylsilanol hyaluronic acid ester','Dimethylsilanol hyaluronic acid ester',1,1),
  ('ING1968','guar hydroxypropyl-trimonium chloride','guar hydroxypropyl-trimonium chloride',1,1),
  ('ING1969','Parfum / Fragrance. C261695/1','Parfum / Fragrance. C261695/1',1,1),
  ('ING1970','Betain','Betain',1,1),
  ('ING1971','Olive Oil Polyglyceryl-4 Ester','Olive Oil Polyglyceryl-4 Ester',1,1),
  ('ING1972','Hydrolyzed Elastine','Hydrolyzed Elastine',1,1),
  ('ING1973','TEA-Sulfate','TEA-Sulfate',1,1),
  ('ING1974','Pistacia Vera Seed Extract','Pistacia Vera Seed Extract',1,1),
  ('ING1975','PPG-12','PPG-12',1,1),
  ('ING1976','Cl 42051','Cl 42051',1,1),
  ('ING1977','Cl47005','Cl47005',1,1),
  ('ING1978','Cl 77891','Cl 77891',1,1),
  ('ING1979','PEG-35 Castor Oil','PEG-35 Castor Oil',1,1),
  ('ING1980','Sulfurized TEA-Ricinoleate','Sulfurized TEA-Ricinoleate',1,1),
  ('ING1981','Soyamidopropylamine Oxide','Soyamidopropylamine Oxide',1,1),
  ('ING1982','POLYSORBATE 21','POLYSORBATE 21',1,1),
  ('ING1983','nettle leaf extract','nettle leaf extract',1,1),
  ('ING1984','cayenne pepper extract','cayenne pepper extract',1,1),
  ('ING1985','European olive leaf extract','European olive leaf extract',1,1),
  ('ING1986','placental extract','placental extract',1,1),
  ('ING1987','tocopherol acetate','tocopherol acetate',1,1),
  ('ING1988','horse chestnut extract','horse chestnut extract',1,1),
  ('ING1989','extract yeast','extract yeast',1,1),
  ('ING1990','hawthorn extract','hawthorn extract',1,1),
  ('ING1991','dwarf palm fruit extract','dwarf palm fruit extract',1,1),
  ('ING1992','methyl chloroisothiazolinone','methyl chloroisothiazolinone',1,1),
  ('ING1993','hexyl cinnamaldehyde','hexyl cinnamaldehyde',1,1),
  ('ING1994','ISOSTEARYL ISOSTEARATE','ISOSTEARYL ISOSTEARATE',1,1),
  ('ING1995','PEG-5 COCOMONIUM METHOSULFATE','PEG-5 COCOMONIUM METHOSULFATE',1,1),
  ('ING1996','TETRASODIUM DISUCCINOYL CYSTINE','TETRASODIUM DISUCCINOYL CYSTINE',1,1),
  ('ING1997','PUERARIA MIRIFICA ROOT EXTRACT SODIUM GLUTAMATE HYDROLYZED RICE PROTEIN ERIOBOTRYA JAPONICA LEAF EXTRACT','PUERARIA MIRIFICA ROOT EXTRACT SODIUM GLUTAMATE HYDROLYZED RICE PROTEIN ERIOBOTRYA JAPONICA LEAF EXTRACT',1,1),
  ('ING1998','ARTEMIA EXTRACT','ARTEMIA EXTRACT',1,1),
  ('ING1999','Lysine carboxymethyl cysteinate','Lysine carboxymethyl cysteinate',1,1),
  ('ING2000','Lysine thiazolidine carboxylate','Lysine thiazolidine carboxylate',1,1)
ON CONFLICT (ingredient_id) DO UPDATE SET canonical_name=EXCLUDED.canonical_name, aliases=EXCLUDED.aliases;