INSERT INTO ingredients_dictionary (ingredient_id,canonical_name,aliases,product_count,occurrence_count)
VALUES
  ('ING3501','Acetylated Sodium Hyaluronate','Acetylated Sodium Hyaluronate',1,1),
  ('ING3502','Polyglyceryl-3 Methyl Glucose Distearate','Polyglyceryl-3 Methyl Glucose Distearate',1,1),
  ('ING3503','Saccharomyces/Barley Seed Ferment Filtrate','Saccharomyces/Barley Seed Ferment Filtrate',1,1),
  ('ING3504','Lactobacillus/Pear Juice Ferment Filtrate','Lactobacillus/Pear Juice Ferment Filtrate',1,1),
  ('ING3505','Alanine/Histidine/Lysine Polypeptide Copper HCl','Alanine/Histidine/Lysine Polypeptide Copper HCl',1,1),
  ('ING3506','Hydrogenated Lecitin','Hydrogenated Lecitin',1,1),
  ('ING3507','Ehyhexylglycerin Sodum Hyaluronale','Ehyhexylglycerin Sodum Hyaluronale',1,1),
  ('ING3508','Viscum Abum (Mistletoe) Extract','Viscum Abum (Mistletoe) Extract',1,1),
  ('ING3509','Terephthalylidene Di-camphor Sulfonic Acid','Terephthalylidene Di-camphor Sulfonic Acid',1,1),
  ('ING3510','C11-13 Isoalkane','C11-13 Isoalkane',1,1),
  ('ING3511','Polymethylsilses-quioxane','Polymethylsilses-quioxane',1,1),
  ('ING3512','Dehydroxanthan Gum','Dehydroxanthan Gum',1,1),
  ('ING3513','Octadecane','Octadecane',1,1),
  ('ING3514','Lactic Acid/Glycolic Acid Copolymer','Lactic Acid/Glycolic Acid Copolymer',1,1),
  ('ING3515','Hydroxyinapcinolone Retinoate','Hydroxyinapcinolone Retinoate',1,1),
  ('ING3516','Sodium Carboxymethyl Cellulose','Sodium Carboxymethyl Cellulose',1,1),
  ('ING3517','L-Carnosine','L-Carnosine',1,1),
  ('ING3518','Aloe Vera Leaf Juice','Aloe Vera Leaf Juice',1,1),
  ('ING3519','Glycyrrhiza echinata Root Extract','Glycyrrhiza echinata Root Extract',1,1),
  ('ING3520','Enantia Chlorantha Bark Extract','Enantia Chlorantha Bark Extract',1,1),
  ('ING3521','Sodium','Sodium',1,1),
  ('ING3522','Polyacrylate','Polyacrylate',1,1),
  ('ING3523','Acrylate/ C10-30 Alkyl Acrylate Latex Crosspolymer','Acrylate/ C10-30 Alkyl Acrylate Latex Crosspolymer',1,1),
  ('ING3524','Yeast/Xylinum/Black Tea Fermentation','Yeast/Xylinum/Black Tea Fermentation',1,1),
  ('ING3525','Lemon Peel Oil','Lemon Peel Oil',1,1),
  ('ING3526','Chicory Root Extract','Chicory Root Extract',1,1),
  ('ING3527','Lactobacillus Fermentation Lysate','Lactobacillus Fermentation Lysate',1,2),
  ('ING3528','Lactococcus Fermentation Lysate','Lactococcus Fermentation Lysate',1,1),
  ('ING3529','Lactococco Kuss Fermented Product','Lactococco Kuss Fermented Product',1,1),
  ('ING3530','Blue Agave Leaf Extract','Blue Agave Leaf Extract',1,1),
  ('ING3531','Artichoke Leaf Extract','Artichoke Leaf Extract',1,1),
  ('ING3532','Azelamide MEA','Azelamide MEA',1,1),
  ('ING3533','Sodium Hyaluronate Crosspolymer-3','Sodium Hyaluronate Crosspolymer-3',1,1),
  ('ING3534','Lysophosphatidic Acid','Lysophosphatidic Acid',1,1),
  ('ING3535','Lysolecithin','Lysolecithin',1,1),
  ('ING3536','Disodium Adenosine Triphosphate','Disodium Adenosine Triphosphate',1,1),
  ('ING3537','Pichia/Resveratrol Ferment Extract','Pichia/Resveratrol Ferment Extract',1,1),
  ('ING3538','cetylethylhexanoate','cetylethylhexanoate',1,1),
  ('ING3539','phytosteride Lil/octyldodecyllauroyl glutamate','phytosteride Lil/octyldodecyllauroyl glutamate',1,1),
  ('ING3540','sodium starch octenyl succinate','sodium starch octenyl succinate',1,1),
  ('ING3541','Mildew extract','Mildew extract',1,1),
  ('ING3542','port marigold extract','port marigold extract',1,1),
  ('ING3543','wormwood extract','wormwood extract',1,1),
  ('ING3544','2-hexanedol','2-hexanedol',1,1),
  ('ING3545','Polygly','Polygly',1,1),
  ('ING3546','Cheryl-10 Laurate','Cheryl-10 Laurate',1,1),
  ('ING3547','Disodium ETDA','Disodium ETDA',1,1),
  ('ING3548','Rosmarinus Officinals (rosemary) Leaf Oil','Rosmarinus Officinals (rosemary) Leaf Oil',1,1),
  ('ING3549','Vito''s Vinifera (grape) Seed Extract','Vito''s Vinifera (grape) Seed Extract',1,1),
  ('ING3550','Saururus Chinensis Extract','Saururus Chinensis Extract',1,1),
  ('ING3551','Rice Ferment Filtrate (sake)','Rice Ferment Filtrate (sake)',1,1),
  ('ING3552','Cyclohasiloxane','Cyclohasiloxane',1,1),
  ('ING3553','12-14 Alketh-12','12-14 Alketh-12',1,1),
  ('ING3554','Dimethicon/Vinyldimethicon Crosspolymer','Dimethicon/Vinyldimethicon Crosspolymer',1,1),
  ('ING3555','Citrus Aurantium Dulcis (Orange) Flower Oil','Citrus Aurantium Dulcis (Orange) Flower Oil',1,1),
  ('ING3556','Barosma Betulina Leaf Extract','Barosma Betulina Leaf Extract',1,1),
  ('ING3557','Lycopodium Clavatum Extract','Lycopodium Clavatum Extract',1,2),
  ('ING3558','Hesperidin','Hesperidin',1,1),
  ('ING3559','Pyrus Malus (Apple) Fruit Extract⁠','Pyrus Malus (Apple) Fruit Extract⁠',1,1),
  ('ING3560','Hydrogenated Lecithin⁠','Hydrogenated Lecithin⁠',1,1),
  ('ING3561','Polyglyceryl-6 Polyricinoleate⁠','Polyglyceryl-6 Polyricinoleate⁠',1,1),
  ('ING3562','Acrylates/C10-30 Alkyl Acrylate Crosspolymer⁠','Acrylates/C10-30 Alkyl Acrylate Crosspolymer⁠',1,1),
  ('ING3563','Xanthan Gum⁠','Xanthan Gum⁠',1,1),
  ('ING3564','Oryza Sativa (Rice) Bran Extract⁠','Oryza Sativa (Rice) Bran Extract⁠',1,1),
  ('ING3565','Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer⁠','Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer⁠',1,1),
  ('ING3566','Cetyl Alcohol⁠','Cetyl Alcohol⁠',1,1),
  ('ING3567','Caprylyl Glycol⁠','Caprylyl Glycol⁠',1,1),
  ('ING3568','Lysine Carboxymethyl Cysteinate⁠','Lysine Carboxymethyl Cysteinate⁠',1,1),
  ('ING3569','Coco Caprylate/Caprate⁠','Coco Caprylate/Caprate⁠',1,1),
  ('ING3570','Tocopherol⁠','Tocopherol⁠',1,1),
  ('ING3571','Glutathione⁠','Glutathione⁠',1,1),
  ('ING3572','Sodium Citrate⁠','Sodium Citrate⁠',1,1),
  ('ING3573','Sodium Phytate⁠','Sodium Phytate⁠',1,1),
  ('ING3574','Hexylene Glycol⁠','Hexylene Glycol⁠',1,1),
  ('ING3575','Ethylhexylglycerin⁠','Ethylhexylglycerin⁠',1,1),
  ('ING3576','Helianthus Annuus Sunflower Seed Extract⁠','Helianthus Annuus Sunflower Seed Extract⁠',1,1),
  ('ING3577','Urea⁠','Urea⁠',1,1),
  ('ING3578','Mannitol⁠','Mannitol⁠',1,1),
  ('ING3579','Caprylic/Capric Triglyceride⁠','Caprylic/Capric Triglyceride⁠',1,1),
  ('ING3580','Sodium PCA⁠','Sodium PCA⁠',1,1),
  ('ING3581','Rosmarinus Officinalis (Rosemary) Leaf Extract⁠','Rosmarinus Officinalis (Rosemary) Leaf Extract⁠',1,1),
  ('ING3582','Polysorbate 60⁠','Polysorbate 60⁠',1,1),
  ('ING3583','Sorbitan Isostearate⁠','Sorbitan Isostearate⁠',1,1),
  ('ING3584','Trehalose⁠','Trehalose⁠',1,1),
  ('ING3585','Ascorbic Acid⁠','Ascorbic Acid⁠',1,1),
  ('ING3586','Glucose⁠','Glucose⁠',1,1),
  ('ING3587','Vanilla','Vanilla',1,1),
  ('ING3588','Melaleuca Alternifolia (Tea Tree) Leaf Water','Melaleuca Alternifolia (Tea Tree) Leaf Water',1,1),
  ('ING3589','Pulsatilla Koreana Extract','Pulsatilla Koreana Extract',1,1),
  ('ING3590','Usnea Barbata (Lichen) Extract','Usnea Barbata (Lichen) Extract',1,1),
  ('ING3591','Glycine Max (Soybean) Oil','Glycine Max (Soybean) Oil',1,1),
  ('ING3592','Cymbopogon Martini Oil','Cymbopogon Martini Oil',1,1),
  ('ING3593','Phytosterol','Phytosterol',1,1),
  ('ING3594','Pueraria Thunbergiana Root Extract','Pueraria Thunbergiana Root Extract',1,1),
  ('ING3595','Lavandula Angustifolia (Lavender) Flower Water','Lavandula Angustifolia (Lavender) Flower Water',1,1),
  ('ING3596','Chrysanthemum Zawadskii Extract','Chrysanthemum Zawadskii Extract',1,1),
  ('ING3597','Cyperus Rotundus Root Extract','Cyperus Rotundus Root Extract',1,1),
  ('ING3598','Leonurus Sibiricus Extract','Leonurus Sibiricus Extract',1,1),
  ('ING3599','Polydecene','Polydecene',1,1),
  ('ING3600','Hwangpyeong Tree Bark Extract','Hwangpyeong Tree Bark Extract',1,1),
  ('ING3601','Palmarosa Oil','Palmarosa Oil',1,1),
  ('ING3602','White Champaca Flower Oil','White Champaca Flower Oil',1,1),
  ('ING3603','Mexican Juniper Oil','Mexican Juniper Oil',1,1),
  ('ING3604','Orange Flower Oil','Orange Flower Oil',1,1),
  ('ING3605','Hydrangea Rolled Collagen (1 000 ppm)','Hydrangea Rolled Collagen (1 000 ppm)',1,1),
  ('ING3606','Hydroxyethyl Acrylate/sodium Acryloyl Dimethyl Taurate Copolymer','Hydroxyethyl Acrylate/sodium Acryloyl Dimethyl Taurate Copolymer',1,1),
  ('ING3607','Jojoba Ester','Jojoba Ester',1,1),
  ('ING3608','Dika Prillyl Ether','Dika Prillyl Ether',1,1),
  ('ING3609','Sodium Laurate','Sodium Laurate',1,1),
  ('ING3610','Hydroxyethyl','Hydroxyethyl',1,1),
  ('ING3611','Dipeptide Diaminobutyroylbenzylamide Diacetate','Dipeptide Diaminobutyroylbenzylamide Diacetate',1,1),
  ('ING3612','Acetylhexapeptide-8','Acetylhexapeptide-8',1,1),
  ('ING3613','Palmitoylpentapeptide-4','Palmitoylpentapeptide-4',1,1),
  ('ING3614','Palmitoyltetrapeptide-7','Palmitoyltetrapeptide-7',1,1),
  ('ING3615','Palmitoyltripeptide-1','Palmitoyltripeptide-1',1,1),
  ('ING3616','PPG-13-Decyltetradeceth-24','PPG-13-Decyltetradeceth-24',1,1),
  ('ING3617','Retinyl Linoleate','Retinyl Linoleate',1,1),
  ('ING3618','Ecklonia Cava Extract','Ecklonia Cava Extract',1,1),
  ('ING3619','Chlorella Minutissima Extract','Chlorella Minutissima Extract',1,1),
  ('ING3620','Gelidium Cartilagineum Extract','Gelidium Cartilagineum Extract',1,1),
  ('ING3621','Sargassum Fulvellum Extract','Sargassum Fulvellum Extract',1,1),
  ('ING3622','Hydroxyacetophe-none','Hydroxyacetophe-none',1,1),
  ('ING3623','Coptis Japonica Extract','Coptis Japonica Extract',1,1),
  ('ING3624','Theobroma Cacao (Cocoa Seed Extract','Theobroma Cacao (Cocoa Seed Extract',1,1),
  ('ING3625','Phytostery /Behenyl/ Octyldodecyl Lauroyl Glutamate','Phytostery /Behenyl/ Octyldodecyl Lauroyl Glutamate',1,1),
  ('ING3626','Hydroxymethoxyphenyl Decanone','Hydroxymethoxyphenyl Decanone',1,1),
  ('ING3627','Hydrangea Macrophylla Leaf Extract','Hydrangea Macrophylla Leaf Extract',1,1),
  ('ING3628','Vitis Vinifera (Grape) Vine Extract','Vitis Vinifera (Grape) Vine Extract',1,1),
  ('ING3629','C13-14 Alkane','C13-14 Alkane',1,1),
  ('ING3630','Sodium Acrylic Acid/MA Copolymer','Sodium Acrylic Acid/MA Copolymer',1,1),
  ('ING3631','C15-23 Alkane','C15-23 Alkane',1,1),
  ('ING3632','sh-Decapeptide-7','sh-Decapeptide-7',1,1),
  ('ING3633','sh-Octapeptide-4','sh-Octapeptide-4',1,1),
  ('ING3634','sh-Polypeptide-22','sh-Polypeptide-22',1,1),
  ('ING3635','sh-Polypeptide-3','sh-Polypeptide-3',1,1),
  ('ING3636','Potentilla Anserina Extract','Potentilla Anserina Extract',1,1),
  ('ING3637','Hydrolyzed Extensin','Hydrolyzed Extensin',1,1),
  ('ING3638','Lupinus Albus Seed Extract','Lupinus Albus Seed Extract',1,1),
  ('ING3639','Hydrolyzed Lupine Protein','Hydrolyzed Lupine Protein',1,1),
  ('ING3640','Glyceryl Acrylate/AcrylicAcid Copolymer','Glyceryl Acrylate/AcrylicAcid Copolymer',1,1),
  ('ING3641','Sphingomonas Fermentation Extract','Sphingomonas Fermentation Extract',1,1),
  ('ING3642','C13-14 Isoalkane','C13-14 Isoalkane',1,1),
  ('ING3643','phenyltrimethicon','phenyltrimethicon',1,1),
  ('ING3644','polysolbate-20','polysolbate-20',1,1),
  ('ING3645','polysilicon-11','polysilicon-11',1,1),
  ('ING3646','PCAidymethicon','PCAidymethicon',1,1),
  ('ING3647','thromethamine','thromethamine',1,1),
  ('ING3648','sodium polyacryloyldimethyltaurate','sodium polyacryloyldimethyltaurate',1,1),
  ('ING3649','dimethanol','dimethanol',1,1),
  ('ING3650','synthetic fluorofluorophosphate','synthetic fluorofluorophosphate',1,1),
  ('ING3651','sodium hexylglycerin','sodium hexylglycerin',1,1),
  ('ING3652','alginine','alginine',1,1),
  ('ING3653','hydroxypropylcyclodextrin','hydroxypropylcyclodextrin',1,1),
  ('ING3654','hydrolide hyaluronate crosspolymer (2 ppm)','hydrolide hyaluronate crosspolymer (2 ppm)',1,1),
  ('ING3655','hyaluronate (1 ppm)','hyaluronate (1 ppm)',1,1),
  ('ING3656','tocoperol','tocoperol',1,1),
  ('ING3657','OLEA EUROPAEA (OLIVE) OIL UNSAPONIFIABLES','OLEA EUROPAEA (OLIVE) OIL UNSAPONIFIABLES',1,1),
  ('ING3658','DIMETHYLAMINOETHANOL','DIMETHYLAMINOETHANOL',1,1),
  ('ING3659','TRIGLYCERIDES LINOLEIC AND LINOLENIC ACIDS','TRIGLYCERIDES LINOLEIC AND LINOLENIC ACIDS',1,1),
  ('ING3660','Lauryl PEG-8 Dimethicone','Lauryl PEG-8 Dimethicone',1,1),
  ('ING3661','Theobroma Cacao (Cocoa) Shell Extract','Theobroma Cacao (Cocoa) Shell Extract',1,1),
  ('ING3662','Akebia Quinata Extract','Akebia Quinata Extract',1,1),
  ('ING3663','Vanilla Planifolia Fruit Extract','Vanilla Planifolia Fruit Extract',1,1),
  ('ING3664','Eugenia Caryophyllus (Clove) Flower Extract','Eugenia Caryophyllus (Clove) Flower Extract',1,1),
  ('ING3665','Sodium Palmitate','Sodium Palmitate',1,1),
  ('ING3666','Green Tea Powder (20000 ppm)','Green Tea Powder (20000 ppm)',1,1),
  ('ING3667','Oat Flour Extract (0.3 ppm)','Oat Flour Extract (0.3 ppm)',1,1),
  ('ING3668','Kudzu Root Extract','Kudzu Root Extract',1,1),
  ('ING3669','Biiberry Fruit Extract','Biiberry Fruit Extract',1,1),
  ('ING3670','Lactobacillus/Soy Milk Ferment Filtrate (9.8 ppm)','Lactobacillus/Soy Milk Ferment Filtrate (9.8 ppm)',1,1),
  ('ING3671','PEG-8 BEESWAX','PEG-8 BEESWAX',1,1),
  ('ING3672','CITRUS SINESIS (SWEET ORANGE) OIL','CITRUS SINESIS (SWEET ORANGE) OIL',1,1),
  ('ING3673','PPG-12/SMDI COPOLYMER','PPG-12/SMDI COPOLYMER',1,1),
  ('ING3674','CHLORPHENESIN GLYCERIN','CHLORPHENESIN GLYCERIN',1,1),
  ('ING3675','Octyldodecyl Stearoyl Stearate','Octyldodecyl Stearoyl Stearate',1,1),
  ('ING3676','Ammonium AaryloyldimethyltaurateMP Copolymer','Ammonium AaryloyldimethyltaurateMP Copolymer',1,1),
  ('ING3677','Fructooligosacchardes','Fructooligosacchardes',1,1),
  ('ING3678','Ethylhexylgycerin','Ethylhexylgycerin',1,1),
  ('ING3679','Citrofortunella Microcarpa Fruit Extract','Citrofortunella Microcarpa Fruit Extract',1,1),
  ('ING3680','Jasminum Officinale (Jasmine) Flower/Leaf Extract','Jasminum Officinale (Jasmine) Flower/Leaf Extract',1,1),
  ('ING3681','Iris Versicolor Extract','Iris Versicolor Extract',1,1),
  ('ING3682','Leontopodium Alpinum Flower/Leaf Extract','Leontopodium Alpinum Flower/Leaf Extract',1,1),
  ('ING3683','Narcissus Pseudonarcissus (Daffodil) Flower Extract','Narcissus Pseudonarcissus (Daffodil) Flower Extract',1,1),
  ('ING3684','Rosa Damascena Flower Extract','Rosa Damascena Flower Extract',1,1),
  ('ING3685','PEG-240/HDI Copolymer Bis-Decyltetradeceth-20 Ether','PEG-240/HDI Copolymer Bis-Decyltetradeceth-20 Ether',1,1),
  ('ING3686','PEG-2M','PEG-2M',1,1),
  ('ING3687','Actinidia Chinensis (Kiwi) Fruit Extract','Actinidia Chinensis (Kiwi) Fruit Extract',1,1),
  ('ING3688','Isotridecyl Isononanoate','Isotridecyl Isononanoate',1,1),
  ('ING3689','Rhus Semialata Gall Extract','Rhus Semialata Gall Extract',1,1),
  ('ING3690','Salix Purpurea Bark Extract','Salix Purpurea Bark Extract',1,1),
  ('ING3691','carrageenan','carrageenan',1,1),
  ('ING3692','Scenedesmus Rubescens Extract','Scenedesmus Rubescens Extract',1,1),
  ('ING3693','Pentapeptide-18','Pentapeptide-18',1,2),
  ('ING3694','Acetylarginyltryptophyl Diphenylglycine','Acetylarginyltryptophyl Diphenylglycine',1,2),
  ('ING3695','Chlorphenesin.Aqua (Water)','Chlorphenesin.Aqua (Water)',1,1),
  ('ING3696','Nicotiana Benthamiana Hexapeptide-40 sh-Oligopeptide-1','Nicotiana Benthamiana Hexapeptide-40 sh-Oligopeptide-1',1,1),
  ('ING3697','Nicotiana Benthamiana Hexapeptide-40 sh-Polypeptide-76','Nicotiana Benthamiana Hexapeptide-40 sh-Polypeptide-76',1,1),
  ('ING3698','Nicotiana Benthamiana Octapeptide-30 sh-Oligopeptide-2','Nicotiana Benthamiana Octapeptide-30 sh-Oligopeptide-2',1,1),
  ('ING3699','Diutan Gum','Diutan Gum',1,1),
  ('ING3700','Arnica Montana Extract','Arnica Montana Extract',1,1),
  ('ING3701','Kojic Dipalmitate','Kojic Dipalmitate',1,1),
  ('ING3702','Silybum Marianum Fruit Extract','Silybum Marianum Fruit Extract',1,1),
  ('ING3703','Trideceth-6 Phosphate','Trideceth-6 Phosphate',1,1),
  ('ING3704','STEVIOSIDE','STEVIOSIDE',1,1),
  ('ING3705','MARIS AQUA','MARIS AQUA',1,1),
  ('ING3706','Euphorbia Cerifera (Candelilla) Wax','Euphorbia Cerifera (Candelilla) Wax',1,1),
  ('ING3707','Alteromonas Ferment Filtrate','Alteromonas Ferment Filtrate',1,1),
  ('ING3708','Diisostearylmalate','Diisostearylmalate',1,1),
  ('ING3709','bis-diglycerylpolyacyl adipate-2','bis-diglycerylpolyacyl adipate-2',1,1),
  ('ING3710','synthetic beeswax','synthetic beeswax',1,1),
  ('ING3711','palm seed butter','palm seed butter',1,1),
  ('ING3712','hydrogenated castor oil dimer dilinoleate','hydrogenated castor oil dimer dilinoleate',1,1),
  ('ING3713','hydrogenated castor oil hydroxystea Rate','hydrogenated castor oil hydroxystea Rate',1,1),
  ('ING3714','Methyl Hydrogenated Loginate','Methyl Hydrogenated Loginate',1,1),
  ('ING3715','Dimerdilinoleyl Dimerdilinoleate','Dimerdilinoleyl Dimerdilinoleate',1,1),
  ('ING3716','Phytosteryl/Behenyl/Octyldodecyllauroyl Glutamate','Phytosteryl/Behenyl/Octyldodecyllauroyl Glutamate',1,1),
  ('ING3717','silica dimethicone silylate','silica dimethicone silylate',1,1),
  ('ING3718','myristoyl/palmitoyl oxostearamide/aracamide MAE','myristoyl/palmitoyl oxostearamide/aracamide MAE',1,1),
  ('ING3719','butylilen glycol','butylilen glycol',1,1),
  ('ING3720','centella extract','centella extract',1,1),
  ('ING3721','Ibuprofen piconol (IPPN) 3.0%','Ibuprofen piconol (IPPN) 3.0%',1,1),
  ('ING3722','Isopropyl methylphenol (IPMP) 0.3%','Isopropyl methylphenol (IPMP) 0.3%',1,1),
  ('ING3723','disodium edetate','disodium edetate',1,1),
  ('ING3724','paraben','paraben',1,1),
  ('ING3725','diisopropanolamine','diisopropanolamine',1,1),
  ('ING3726','carboxyvinyl polymer','carboxyvinyl polymer',1,1),
  ('ING3727','Triethylhexyl Trimellitate','Triethylhexyl Trimellitate',1,1),
  ('ING3728','Glycol','Glycol',1,1),
  ('ING3729','Polyglyceryl-10 Pentaisostearate','Polyglyceryl-10 Pentaisostearate',1,1),
  ('ING3730','Polystyrene','Polystyrene',1,1),
  ('ING3731','Triethanol Amine','Triethanol Amine',1,1),
  ('ING3732','Sodium Cocoamphodiacetate','Sodium Cocoamphodiacetate',1,1),
  ('ING3733','Disodium Acetyl Glucosamine Phosphate','Disodium Acetyl Glucosamine Phosphate',1,1),
  ('ING3734','Organic Fractionated Coconut Oil','Organic Fractionated Coconut Oil',1,1),
  ('ING3735','Organic and Fair Trade Coconut Oil','Organic and Fair Trade Coconut Oil',1,1),
  ('ING3736','Organic Aloe Vera Juice','Organic Aloe Vera Juice',1,1),
  ('ING3737','Organic Olive Oil','Organic Olive Oil',1,1),
  ('ING3738','Vanilla Extract','Vanilla Extract',1,1),
  ('ING3739','Organic Almond Extract','Organic Almond Extract',1,1),
  ('ING3740','Organic Sunflower Oil','Organic Sunflower Oil',1,1),
  ('ING3741','Organic Shea Butter','Organic Shea Butter',1,1),
  ('ING3742','Tonka Bean Essential Oil','Tonka Bean Essential Oil',1,1),
  ('ING3743','Organic Rosemary Extract','Organic Rosemary Extract',1,1),
  ('ING3744','Non-gmo Vitamin E','Non-gmo Vitamin E',1,1)
ON CONFLICT (ingredient_id) DO UPDATE SET canonical_name=EXCLUDED.canonical_name, aliases=EXCLUDED.aliases;