INSERT INTO ingredients_dictionary (ingredient_id,canonical_name,aliases,product_count,occurrence_count)
VALUES
  ('ING3001','CAULERPA LENTILLIFERA EXTRACT','CAULERPA LENTILLIFERA EXTRACT',1,1),
  ('ING3002','Rosa Rugosa Leaf Extract','Rosa Rugosa Leaf Extract',1,1),
  ('ING3003','Verbena Officinalis Extract','Verbena Officinalis Extract',1,1),
  ('ING3004','Sodium Azulene Sulfonate','Sodium Azulene Sulfonate',1,1),
  ('ING3005','AMP-Ac rylates Copolymer','AMP-Ac rylates Copolymer',1,1),
  ('ING3006','Lithum Magnesium Sodium Silicate','Lithum Magnesium Sodium Silicate',1,1),
  ('ING3007','Synthetic Fluorphogopite','Synthetic Fluorphogopite',1,1),
  ('ING3008','lllicium Verum (Anise) Fruit Extract','lllicium Verum (Anise) Fruit Extract',1,1),
  ('ING3009','Aluminum Hydro xide','Aluminum Hydro xide',1,1),
  ('ING3010','Gold (4 ppm)','Gold (4 ppm)',1,1),
  ('ING3011','Methyl Propanediol','Methyl Propanediol',1,1),
  ('ING3012','Evening Primrose Extract','Evening Primrose Extract',1,1),
  ('ING3013','Dong Elm Root Extract','Dong Elm Root Extract',1,1),
  ('ING3014','Persimmon Leaf Extract','Persimmon Leaf Extract',1,1),
  ('ING3015','Chestnut Bark Extract','Chestnut Bark Extract',1,1),
  ('ING3016','Safflower Flower Extract','Safflower Flower Extract',1,1),
  ('ING3017','Fruit Extract','Fruit Extract',1,1),
  ('ING3018','Coffee Bean Extract','Coffee Bean Extract',1,1),
  ('ING3019','Grape Extract','Grape Extract',1,1),
  ('ING3020','Knotweed Root Extract','Knotweed Root Extract',1,1),
  ('ING3021','Disteardimonium Hectolite','Disteardimonium Hectolite',1,1),
  ('ING3022','Lactobacillus Fermentation (1000 Ppm)','Lactobacillus Fermentation (1000 Ppm)',1,1),
  ('ING3023','Tylosine','Tylosine',1,1),
  ('ING3024','Agave Americana Stem Extract','Agave Americana Stem Extract',1,1),
  ('ING3025','Pancratium Maritimum Extract','Pancratium Maritimum Extract',1,1),
  ('ING3026','VIGNA ACONITIFOLIA SEED EXTRACT','VIGNA ACONITIFOLIA SEED EXTRACT',1,1),
  ('ING3027','INONOTUS OBLIQUUS EXTRACT','INONOTUS OBLIQUUS EXTRACT',1,1),
  ('ING3028','BETULA VERRUCOSA LEAF EXTRACT','BETULA VERRUCOSA LEAF EXTRACT',1,1),
  ('ING3029','Isopropylbenzyl Salicylate','Isopropylbenzyl Salicylate',1,1),
  ('ING3030','Isodecyl Salicylate','Isodecyl Salicylate',1,1),
  ('ING3031','Cetearyl Methicone','Cetearyl Methicone',1,1),
  ('ING3032','SALI- CYLIC ACID','SALI- CYLIC ACID',1,1),
  ('ING3033','SULFUR','SULFUR',1,1),
  ('ING3034','CHROMIUM OXIDE GREENS','CHROMIUM OXIDE GREENS',1,1),
  ('ING3035','NE- LUMBO NUCIFERA LEAF EXTRACT','NE- LUMBO NUCIFERA LEAF EXTRACT',1,1),
  ('ING3036','MELALEUCA ALTER- NIFOLIA (TEA TREE) EXTRACT','MELALEUCA ALTER- NIFOLIA (TEA TREE) EXTRACT',1,1),
  ('ING3037','Hibiscus Flower water','Hibiscus Flower water',1,1),
  ('ING3038','Ascobyl glucoside','Ascobyl glucoside',1,1),
  ('ING3039','Konjac Root Extract','Konjac Root Extract',1,1),
  ('ING3040','Alginin','Alginin',1,1),
  ('ING3041','Undecylenamidopropyltrimonium Methosulfate','Undecylenamidopropyltrimonium Methosulfate',1,1),
  ('ING3042','Termal Water','Termal Water',1,1),
  ('ING3043','Colloidal Silver','Colloidal Silver',1,1),
  ('ING3044','Cetyl Stearyl','Cetyl Stearyl',1,1),
  ('ING3045','Recutita Calendula','Recutita Calendula',1,1),
  ('ING3046','Chamomilla Recutita','Chamomilla Recutita',1,1),
  ('ING3047','PEG-40','PEG-40',1,1),
  ('ING3048','castor oil','castor oil',1,1),
  ('ING3049','PPG-2','PPG-2',1,1),
  ('ING3050','2-bromo','2-bromo',1,1),
  ('ING3051','Momordica Charantia Fruit Extract','Momordica Charantia Fruit Extract',1,1),
  ('ING3052','Sambucus Nigra Flower Extract','Sambucus Nigra Flower Extract',1,1),
  ('ING3053','Leontopodium Alpinum Extract','Leontopodium Alpinum Extract',1,1),
  ('ING3054','Diethylhexyl Carbonate','Diethylhexyl Carbonate',1,1),
  ('ING3055','Vaccinium VitisIdaea Fruit Extract','Vaccinium VitisIdaea Fruit Extract',1,1),
  ('ING3056','Cymbopogon Nardus (Citronella) Oil','Cymbopogon Nardus (Citronella) Oil',1,1),
  ('ING3057','Artemisia Vulgaris Oil','Artemisia Vulgaris Oil',1,1),
  ('ING3058','Magnesium Myristate','Magnesium Myristate',1,3),
  ('ING3059','Bronze Powder (CI 77400)','Bronze Powder (CI 77400)',1,1),
  ('ING3060','Copper Powder (CI 77400)','Copper Powder (CI 77400)',1,1),
  ('ING3061','Ferric Ferrocyanide (CI 77510)','Ferric Ferrocyanide (CI 77510)',1,2),
  ('ING3062','Ultramarines (CI 77007)','Ultramarines (CI 77007)',1,1),
  ('ING3063','Manganese Violet (CI 77742)','Manganese Violet (CI 77742)',1,1),
  ('ING3064','Prunus Serotina Fruit Extract','Prunus Serotina Fruit Extract',1,1),
  ('ING3065','Acetyl Methionine','Acetyl Methionine',1,1),
  ('ING3066','VEGETABLE COLLAGEN','VEGETABLE COLLAGEN',1,1),
  ('ING3067','Black Iron oxide (CI 77499)','Black Iron oxide (CI 77499)',1,1),
  ('ING3068','cholesteryl stearate','cholesteryl stearate',1,1),
  ('ING3069','bht diethylhexyl succinate ethylhexyl hydroxystearate','bht diethylhexyl succinate ethylhexyl hydroxystearate',1,1),
  ('ING3070','MALUS PUMILA (APPLE) FRUIT EXTRACT','MALUS PUMILA (APPLE) FRUIT EXTRACT',1,1),
  ('ING3071','PUNICA GRANATUM (POMEGRANATE) SEED EXTRACT','PUNICA GRANATUM (POMEGRANATE) SEED EXTRACT',1,1),
  ('ING3072','VIBURNUM PRUNIFOLIUM (STAGBERRY) EXTRACT','VIBURNUM PRUNIFOLIUM (STAGBERRY) EXTRACT',1,1),
  ('ING3073','COFFEA (COFFEE) SEED POWDER','COFFEA (COFFEE) SEED POWDER',1,1),
  ('ING3074','CETEARYL WHEAT STRAW GLYCOSIDES','CETEARYL WHEAT STRAW GLYCOSIDES',1,1),
  ('ING3075','HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX','HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX',1,1),
  ('ING3076','JUGLANS REGIA (WALNUT) SHELL POWDER','JUGLANS REGIA (WALNUT) SHELL POWDER',1,1),
  ('ING3077','SODIUM SACCHARIN','SODIUM SACCHARIN',1,1),
  ('ING3078','Ethyl Ascorbyl Ether','Ethyl Ascorbyl Ether',1,1),
  ('ING3079','Ascorby! Methylsilanol Pectinate','Ascorby! Methylsilanol Pectinate',1,1),
  ('ING3080','Tetrahydropiperine','Tetrahydropiperine',1,1),
  ('ING3081','EVODIA RUTAECARPA FRUIT EXTRACT','EVODIA RUTAECARPA FRUIT EXTRACT',1,1),
  ('ING3082','Anthemis Nobilis (Chamomile) Extract','Anthemis Nobilis (Chamomile) Extract',1,1),
  ('ING3083','Malva Silvestris (Mallow) Extract','Malva Silvestris (Mallow) Extract',1,1),
  ('ING3084','Plantain (Plantago Major) Extract','Plantain (Plantago Major) Extract',1,1),
  ('ING3085','Olea Europaea (Olive) Oit','Olea Europaea (Olive) Oit',1,1),
  ('ING3086','Butyrospermumparkii(Shea Butter)','Butyrospermumparkii(Shea Butter)',1,1),
  ('ING3087','Clyceryl Stearate','Clyceryl Stearate',1,1),
  ('ING3088','imidazodinyl Urea','imidazodinyl Urea',1,1),
  ('ING3089','Solidago Virgaurea (Goldenrod) Extract','Solidago Virgaurea (Goldenrod) Extract',1,1),
  ('ING3090','Polyacrilate Crosspolymer-6','Polyacrilate Crosspolymer-6',1,2),
  ('ING3091','Paullinia Cupana Fruit Extract','Paullinia Cupana Fruit Extract',1,2),
  ('ING3092','Аesculus Hippocastanum Fruit Extract','Аesculus Hippocastanum Fruit Extract',1,2),
  ('ING3093','Chrysanthellum Indicum Extract','Chrysanthellum Indicum Extract',1,2),
  ('ING3094','Taraxacum Officinale Root Extract','Taraxacum Officinale Root Extract',1,2),
  ('ING3095','Menthyl PolylactateAqua','Menthyl PolylactateAqua',1,1),
  ('ING3096','Menthyl Polylactate','Menthyl Polylactate',1,1),
  ('ING3097','Diosmine','Diosmine',1,1),
  ('ING3098','Coleus Forskohlii Root Extract','Coleus Forskohlii Root Extract',1,1),
  ('ING3099','Dicetyl Phospate','Dicetyl Phospate',1,1),
  ('ING3100','Peramigan','Peramigan',1,1),
  ('ING3101','Hesperidin Methyl Chalcone','Hesperidin Methyl Chalcone',1,1),
  ('ING3102','Coffea Arabica Fruit Extract','Coffea Arabica Fruit Extract',1,1),
  ('ING3103','Foeniculum Vulgare (Fennel) Oil','Foeniculum Vulgare (Fennel) Oil',1,1),
  ('ING3104','Pimenta Racemosa (Bay Rum Essential Oil)','Pimenta Racemosa (Bay Rum Essential Oil)',1,1),
  ('ING3105','NEOHESPERIDIN DIHYDROCHALCONE','NEOHESPERIDIN DIHYDROCHALCONE',1,1),
  ('ING3106','PINUS PINASTER BARK/BUD EXTRACT','PINUS PINASTER BARK/BUD EXTRACT',1,1),
  ('ING3107','bis-peg-18 methyl ether dimethyl silane','bis-peg-18 methyl ether dimethyl silane',1,1),
  ('ING3108','phenylethyl resorcinol','phenylethyl resorcinol',1,1),
  ('ING3109','oxothiazolidine-carboxylic acid','oxothiazolidine-carboxylic acid',1,1),
  ('ING3110','MORUS ALBA ROOT EXTRACT','MORUS ALBA ROOT EXTRACT',1,1),
  ('ING3111','SODIUM CHOLATE','SODIUM CHOLATE',1,1),
  ('ING3112','CITRONELLYL METHYLCROTONATE','CITRONELLYL METHYLCROTONATE',1,1),
  ('ING3113','Ascorbic Acid 82%','Ascorbic Acid 82%',1,1),
  ('ING3114','Silica Silylate 8.6%','Silica Silylate 8.6%',1,1),
  ('ING3115','Dimethicone 8.3%','Dimethicone 8.3%',1,1),
  ('ING3116','Dimethiconol 1.1%','Dimethiconol 1.1%',1,1),
  ('ING3117','Ethylene/Propylene/Styrene Copolymer','Ethylene/Propylene/Styrene Copolymer',1,1),
  ('ING3118','Glucomannan','Glucomannan',1,1),
  ('ING3119','Butylene/Ethylene/Styrene Copolymer','Butylene/Ethylene/Styrene Copolymer',1,1),
  ('ING3120','Acrylates/Ethylhexyl Acrylate Crosspolymer','Acrylates/Ethylhexyl Acrylate Crosspolymer',1,1),
  ('ING3121','C12-14 Pareth-12','C12-14 Pareth-12',1,1),
  ('ING3122','Hydroxyethyl Ubiquinone','Hydroxyethyl Ubiquinone',1,1),
  ('ING3123','Hydrogenated C 6-20 Polyolefin','Hydrogenated C 6-20 Polyolefin',1,1),
  ('ING3124','Natural Fragrance Oil','Natural Fragrance Oil',1,1),
  ('ING3125','Citrus Grandis (Grapefruit) Water','Citrus Grandis (Grapefruit) Water',1,1),
  ('ING3126','Microcitrus Australis Fruit Extract','Microcitrus Australis Fruit Extract',1,1),
  ('ING3127','Citrus Glauca Fruit Extract','Citrus Glauca Fruit Extract',1,1),
  ('ING3128','Melaleuca Alternifolia (Tea Tree) Flower/Leaf/Stem Extract','Melaleuca Alternifolia (Tea Tree) Flower/Leaf/Stem Extract',1,1),
  ('ING3129','Tetradecyl Aminobutyroylvalylaminobutyric Urea Trifluoroacetate','Tetradecyl Aminobutyroylvalylaminobutyric Urea Trifluoroacetate',1,1),
  ('ING3130','Palmitoyl Dipeptide-5 Diaminobutyroyl Hydroxythreonine','Palmitoyl Dipeptide-5 Diaminobutyroyl Hydroxythreonine',1,1),
  ('ING3131','Acer Rubrum Extract','Acer Rubrum Extract',1,1),
  ('ING3132','Acetylated Glycol Stearate','Acetylated Glycol Stearate',1,1),
  ('ING3133','Acrylonitrile/ Methyl Methacrylate/ Vinylidene Chloride Copolymer','Acrylonitrile/ Methyl Methacrylate/ Vinylidene Chloride Copolymer',1,1),
  ('ING3134','Pseudoalteromonas Exopolysaccharides','Pseudoalteromonas Exopolysaccharides',1,1),
  ('ING3135','Mirabilis Jalapa Extract Mirabilis Jalapa Extract','Mirabilis Jalapa Extract Mirabilis Jalapa Extract',1,1),
  ('ING3136','Glyceryl Srearate SE','Glyceryl Srearate SE',1,1),
  ('ING3137','Actylates/C10-30 Alkyl Acrylate Crosspolymer','Actylates/C10-30 Alkyl Acrylate Crosspolymer',1,1),
  ('ING3138','Capryloyl Glycerine/Sebacic Acid Copolymer','Capryloyl Glycerine/Sebacic Acid Copolymer',1,1),
  ('ING3139','Pentaerythyl Tetra-di-t-bytil Hydroxyhydrocinnamate','Pentaerythyl Tetra-di-t-bytil Hydroxyhydrocinnamate',1,1),
  ('ING3140','Octoxynol-12','Octoxynol-12',1,1),
  ('ING3141','Ci 75470','Ci 75470',1,1),
  ('ING3142','Bioflavonoids','Bioflavonoids',1,1),
  ('ING3143','Tremella Fuciformis (Mushroom) Extract','Tremella Fuciformis (Mushroom) Extract',1,1),
  ('ING3144','Sea Buckthorn Water','Sea Buckthorn Water',1,1),
  ('ING3145','Filtrate Fermented Yeast Galactomisis','Filtrate Fermented Yeast Galactomisis',1,1),
  ('ING3146','Damascus Rose Flowers Water','Damascus Rose Flowers Water',1,1),
  ('ING3147','Glyceres-26','Glyceres-26',1,1),
  ('ING3148','Polyacid','Polyacid',1,1),
  ('ING3149','Caprylic / Capric Acid Triglyceride','Caprylic / Capric Acid Triglyceride',1,1),
  ('ING3150','Ethylhexylglycerol','Ethylhexylglycerol',1,1),
  ('ING3151','Acetylphitosphingosine','Acetylphitosphingosine',1,1),
  ('ING3152','Basil Leaf Extract','Basil Leaf Extract',1,1),
  ('ING3153','Perdil Seed Extract','Perdil Seed Extract',1,1),
  ('ING3154','Real Coral Horse Extract','Real Coral Horse Extract',1,1),
  ('ING3155','Goth Ivy Fruit Extract','Goth Ivy Fruit Extract',1,1),
  ('ING3156','Honey','Honey',1,1),
  ('ING3157','Matrixyl® 3000','Matrixyl® 3000',1,1),
  ('ING3158','Aloe Barbadensis','Aloe Barbadensis',1,1),
  ('ING3159','Benzylalcohol','Benzylalcohol',1,1),
  ('ING3160','Canavalia Gladiata Seed Extract','Canavalia Gladiata Seed Extract',1,1),
  ('ING3161','Diamond Powder','Diamond Powder',1,1),
  ('ING3162','Lotus Flower Extract','Lotus Flower Extract',1,1),
  ('ING3163','Cutibacterium Avidum Ferment Extract Filtrate','Cutibacterium Avidum Ferment Extract Filtrate',1,1),
  ('ING3164','Tocotrienols','Tocotrienols',1,1),
  ('ING3165','Octadecyl Di-T-Butyl-4-Hydroxyhydrocinnamate','Octadecyl Di-T-Butyl-4-Hydroxyhydrocinnamate',1,1),
  ('ING3166','Buteth-3','Buteth-3',1,1),
  ('ING3167','Sodium Benzotriazolyl Butylphenol Sulfonate','Sodium Benzotriazolyl Butylphenol Sulfonate',1,1),
  ('ING3168','Tributyl Citrate','Tributyl Citrate',1,1),
  ('ING3169','Piper Methysticum Leaf/Root/Stem Extract','Piper Methysticum Leaf/Root/Stem Extract',1,1),
  ('ING3170','Glycine Soja (Soybean) Peptide','Glycine Soja (Soybean) Peptide',1,1),
  ('ING3171','Hippophae Rhamnoides Oil','Hippophae Rhamnoides Oil',1,1),
  ('ING3172','meadowform seed oil','meadowform seed oil',1,1),
  ('ING3173','true rose of jerico extract','true rose of jerico extract',1,1),
  ('ING3174','tomato extract','tomato extract',1,1),
  ('ING3175','SH-Polypeptide-121 (9900 ppb)','SH-Polypeptide-121 (9900 ppb)',1,1),
  ('ING3176','water-soluble collagen (0.01 ppb)','water-soluble collagen (0.01 ppb)',1,1),
  ('ING3177','silybin','silybin',1,1),
  ('ING3178','yellow lotus root extract','yellow lotus root extract',1,1),
  ('ING3179','C14-22 alcohol','C14-22 alcohol',1,1),
  ('ING3180','isopropyllauroyl sacosinate','isopropyllauroyl sacosinate',1,1),
  ('ING3181','benzotriazoyldodecyl p-cresol','benzotriazoyldodecyl p-cresol',1,1),
  ('ING3182','diethylhexyloxide silidene malonate','diethylhexyloxide silidene malonate',1,1),
  ('ING3183','peanut oil','peanut oil',1,1),
  ('ING3184','ppg-13-decyl tetradesces-24','ppg-13-decyl tetradesces-24',1,1),
  ('ING3185','Pentaerythrityl Distearate','Pentaerythrityl Distearate',1,1),
  ('ING3186','caprylic/caprictriglyceride','caprylic/caprictriglyceride',1,1),
  ('ING3187','butyleneglycol dicaprylate/dicaprate','butyleneglycol dicaprylate/dicaprate',1,1),
  ('ING3188','palmitoyltripeptide-5','palmitoyltripeptide-5',1,1),
  ('ING3189','Sodium Acrylates/Sodium Acryloyldimethyl Taurate Copolymer','Sodium Acrylates/Sodium Acryloyldimethyl Taurate Copolymer',1,1),
  ('ING3190','Dipropylheptyl Carbonate','Dipropylheptyl Carbonate',1,1),
  ('ING3191','Titanium Dioxide CI77891','Titanium Dioxide CI77891',1,1),
  ('ING3192','Alkyl Malate','Alkyl Malate',1,1),
  ('ING3193','Polydimetylsiloxan','Polydimetylsiloxan',1,1),
  ('ING3194','Cetearyl Glucoside/Cetearyl Alcohol','Cetearyl Glucoside/Cetearyl Alcohol',1,1),
  ('ING3195','Cyclopentasiloxane/Dimethicone/Vinyl Dimethicone Crosspolymer','Cyclopentasiloxane/Dimethicone/Vinyl Dimethicone Crosspolymer',1,1),
  ('ING3196','Red Iron Oxide CI 77491','Red Iron Oxide CI 77491',1,1),
  ('ING3197','Ethyl Cellulose','Ethyl Cellulose',1,1),
  ('ING3198','Hydroxypropyl Methyl Cellulose','Hydroxypropyl Methyl Cellulose',1,1),
  ('ING3199','Pottassium Cetyl Phoshate','Pottassium Cetyl Phoshate',1,1),
  ('ING3200','Phytosteryl Macadamiate','Phytosteryl Macadamiate',1,1),
  ('ING3201','Rubus Chamaemorus Seed Oil','Rubus Chamaemorus Seed Oil',1,1),
  ('ING3202','Rumex Occidentalis Extract','Rumex Occidentalis Extract',1,1),
  ('ING3203','Acetyl Tetrapeptide-40','Acetyl Tetrapeptide-40',1,1),
  ('ING3204','Aureobasidium Pullulans Ferment','Aureobasidium Pullulans Ferment',1,1),
  ('ING3205','Physalis Alkekengi Calyx Extract','Physalis Alkekengi Calyx Extract',1,1),
  ('ING3206','Sodium choride','Sodium choride',1,1),
  ('ING3207','Ammonium Acryloyldime thyltaurate/VP Copolymer','Ammonium Acryloyldime thyltaurate/VP Copolymer',1,1),
  ('ING3208','Silkworm Cocoon (10000ppm)','Silkworm Cocoon (10000ppm)',1,1),
  ('ING3209','Brassica Oleracea Capitata (Cabbage) Leaf Extract','Brassica Oleracea Capitata (Cabbage) Leaf Extract',1,1),
  ('ING3210','Brassica Campestris (Rapeseed) Extract','Brassica Campestris (Rapeseed) Extract',1,1),
  ('ING3211','Saccharomy ces Ferment Filtrate','Saccharomy ces Ferment Filtrate',1,1),
  ('ING3212','Glycosyl Trehalose','Glycosyl Trehalose',1,1),
  ('ING3213','Bifida Fermentation Lysate','Bifida Fermentation Lysate',1,1),
  ('ING3214','Lactobacillus / Pumpkin Fermentation Extract','Lactobacillus / Pumpkin Fermentation Extract',1,1),
  ('ING3215','Black Yeast Fermentation','Black Yeast Fermentation',1,1),
  ('ING3216','Black Soybean Extract','Black Soybean Extract',1,1),
  ('ING3217','Kelp Extract','Kelp Extract',1,1),
  ('ING3218','Iris Root Extract','Iris Root Extract',1,1),
  ('ING3219','Black Sesame Extract','Black Sesame Extract',1,1),
  ('ING3220','Hydrolyzed Keratin Extract','Hydrolyzed Keratin Extract',1,1),
  ('ING3221','Sewage Root Extract','Sewage Root Extract',1,1),
  ('ING3222','Barley Wheat Extract','Barley Wheat Extract',1,1),
  ('ING3223','Seaweed Extract','Seaweed Extract',1,1),
  ('ING3224','Red Ginseng Extract','Red Ginseng Extract',1,1),
  ('ING3225','Red Ginseng Root Extract','Red Ginseng Root Extract',1,1),
  ('ING3226','Chalcedony Root Extract','Chalcedony Root Extract',1,1),
  ('ING3227','Rakemosa Horse Root Extract','Rakemosa Horse Root Extract',1,1),
  ('ING3228','Mulberry Bark Extract','Mulberry Bark Extract',1,1),
  ('ING3229','H-polypeptide-1','H-polypeptide-1',1,1),
  ('ING3230','H-polypeptide-2','H-polypeptide-2',1,1),
  ('ING3231','H-oligopeptide-2','H-oligopeptide-2',1,1),
  ('ING3232','H-oligopeptide-1','H-oligopeptide-1',1,1),
  ('ING3233','Ussian Extract','Ussian Extract',1,1),
  ('ING3234','Choco Fruit Extract','Choco Fruit Extract',1,1),
  ('ING3235','Pasqueflower Extract','Pasqueflower Extract',1,1),
  ('ING3236','Mud Mushroom Extract','Mud Mushroom Extract',1,1),
  ('ING3237','Star Anise Extract','Star Anise Extract',1,1),
  ('ING3238','Capryl Glycol','Capryl Glycol',1,1),
  ('ING3239','Citron Extract','Citron Extract',1,1),
  ('ING3240','Mugwort Extract','Mugwort Extract',1,1),
  ('ING3241','C9-12 Alkane','C9-12 Alkane',1,1),
  ('ING3242','Etylhexyl Salicylate','Etylhexyl Salicylate',1,1),
  ('ING3243','Caprylic/ Capric Triglycende','Caprylic/ Capric Triglycende',1,1),
  ('ING3244','Disostearate Malate','Disostearate Malate',1,1),
  ('ING3245','Sodium Carbonate','Sodium Carbonate',1,1),
  ('ING3246','Tripeptide-46','Tripeptide-46',1,1),
  ('ING3247','Hexapeptide-40','Hexapeptide-40',1,1),
  ('ING3248','Decapeptide-27','Decapeptide-27',1,1),
  ('ING3249','Methionyl Oligopeptide-91','Methionyl Oligopeptide-91',1,1),
  ('ING3250','Tetrapeptide-38','Tetrapeptide-38',1,1),
  ('ING3251','Oleyl Adapalenate','Oleyl Adapalenate',1,1),
  ('ING3252','Albatrellus Confluens (Mushroom) Extract','Albatrellus Confluens (Mushroom) Extract',1,1),
  ('ING3253','Cetyl Glyceryl Ether','Cetyl Glyceryl Ether',1,1),
  ('ING3254','Naringin','Naringin',1,1),
  ('ING3255','Prunus Armeniaca (Apricot) Fruite Extract','Prunus Armeniaca (Apricot) Fruite Extract',1,1),
  ('ING3256','Ficus Carica (Fig) Fruit Water','Ficus Carica (Fig) Fruit Water',1,1),
  ('ING3257','Triticum Aestivum (Wheat) Seed Extract','Triticum Aestivum (Wheat) Seed Extract',1,1),
  ('ING3258','Ficin','Ficin',1,1),
  ('ING3259','Sodium carboxymethyl starch','Sodium carboxymethyl starch',1,1),
  ('ING3260','Sutilains','Sutilains',1,1),
  ('ING3261','AVEENA SATIVA (OAT) KERNEL POWDER','AVEENA SATIVA (OAT) KERNEL POWDER',1,1),
  ('ING3262','PROPOLIS DRY EXTRACT','PROPOLIS DRY EXTRACT',1,1),
  ('ING3263','SORBIT','SORBIT',1,1),
  ('ING3264','SOAPNUT (ARITHA) POWDER','SOAPNUT (ARITHA) POWDER',1,1),
  ('ING3265','TANACETUM ANNUUM (BLUE TANSY) OIL','TANACETUM ANNUUM (BLUE TANSY) OIL',1,1),
  ('ING3266','PINEAPPLE JUICE CONCENTRATE','PINEAPPLE JUICE CONCENTRATE',1,1),
  ('ING3267','BLACK CARROT EXTRACT','BLACK CARROT EXTRACT',1,1),
  ('ING3268','LACTOBACILLUS/PUMPKIN FRUIT FERMENT','LACTOBACILLUS/PUMPKIN FRUIT FERMENT',1,1),
  ('ING3269','Gardenia Jasminoides (Gardenia) Fruit Extract','Gardenia Jasminoides (Gardenia) Fruit Extract',1,1),
  ('ING3270','BI','BI',1,1),
  ('ING3271','Centella Asiatica Centella Asiatica Root Extract','Centella Asiatica Centella Asiatica Root Extract',1,1),
  ('ING3272','Stear','Stear',1,1),
  ('ING3273','cauu','cauu',1,1),
  ('ING3274','srycerin','srycerin',1,1),
  ('ING3275','Color Clay Olea','Color Clay Olea',1,1),
  ('ING3276','Licorice Roots Extract','Licorice Roots Extract',1,1),
  ('ING3277','Keratinase','Keratinase',1,1),
  ('ING3278','Citrus Auranfium Dulcis (Orange) Oil','Citrus Auranfium Dulcis (Orange) Oil',1,1),
  ('ING3279','BiFida Ferment Filirate','BiFida Ferment Filirate',1,1),
  ('ING3280','Bifida Fermenf Lysate','Bifida Fermenf Lysate',1,1),
  ('ING3281','Tropolone Saccharomyces Ferment Filtrate','Tropolone Saccharomyces Ferment Filtrate',1,1),
  ('ING3282','Illite','Illite',1,1),
  ('ING3283','Pineapple Dry Extract','Pineapple Dry Extract',1,1),
  ('ING3284','CI 77288','CI 77288',1,1),
  ('ING3285','Nelumbo Nucifera Extract','Nelumbo Nucifera Extract',1,1),
  ('ING3286','Subtilisin','Subtilisin',1,1),
  ('ING3287','Methyl Benzoate','Methyl Benzoate',1,1),
  ('ING3288','TBHQ','TBHQ',1,1),
  ('ING3289','Sodium Acrylate/sodium Acryloyldimethyl Taurate Polymer','Sodium Acrylate/sodium Acryloyldimethyl Taurate Polymer',1,1),
  ('ING3290','Hydrolyzed DNA','Hydrolyzed DNA',1,1),
  ('ING3291','Glutathione Glyceryl Stearate','Glutathione Glyceryl Stearate',1,1),
  ('ING3292','Centella Asiatica Leaf Vesicles','Centella Asiatica Leaf Vesicles',1,1),
  ('ING3293','Citrus Limon (Lemon) Fruit Oil','Citrus Limon (Lemon) Fruit Oil',1,1),
  ('ING3294','Rheum Palmatum Root Extract','Rheum Palmatum Root Extract',1,1),
  ('ING3295','Polygonum','Polygonum',1,1),
  ('ING3296','Cuspidatum Root Extract','Cuspidatum Root Extract',1,1),
  ('ING3297','Galloyl Pentapeptide-74','Galloyl Pentapeptide-74',1,1),
  ('ING3298','Caffeoyl Tetrapeptide-80','Caffeoyl Tetrapeptide-80',1,1),
  ('ING3299','Galloyl Tetrapeptide-80','Galloyl Tetrapeptide-80',1,1),
  ('ING3300','Feruloyl Tetrapeptide-80','Feruloyl Tetrapeptide-80',1,1),
  ('ING3301','Caffeoyl Hexapeptide-82','Caffeoyl Hexapeptide-82',1,1),
  ('ING3302','Meadowfoam Seed Oil','Meadowfoam Seed Oil',1,1),
  ('ING3303','Polyglucuronic Acid','Polyglucuronic Acid',1,1),
  ('ING3304','Ceramide AOS','Ceramide AOS',1,1),
  ('ING3305','Ceramide EP','Ceramide EP',1,1),
  ('ING3306','Methyl Hydrogenated Rosinate','Methyl Hydrogenated Rosinate',1,1),
  ('ING3307','Sodium Guaiazulene Sulfonate','Sodium Guaiazulene Sulfonate',1,1),
  ('ING3308','Lotus Flower Water (10,088 ppm)','Lotus Flower Water (10,088 ppm)',1,1),
  ('ING3309','Nasturtium Herb Extract','Nasturtium Herb Extract',1,1),
  ('ING3310','Neem Leaf Extract','Neem Leaf Extract',1,1),
  ('ING3311','White Rice Flower Extract','White Rice Flower Extract',1,1),
  ('ING3312','Acetyl Octapeptide-3','Acetyl Octapeptide-3',1,1),
  ('ING3313','Apple Cell Culture Extract (0,001 ppm)','Apple Cell Culture Extract (0,001 ppm)',1,1),
  ('ING3314','Yam Root Extract','Yam Root Extract',1,1),
  ('ING3315','Lotus Leaf Extract (0,0001 ppm)','Lotus Leaf Extract (0,0001 ppm)',1,1),
  ('ING3316','Hydrolyzed Spongilla Spicules','Hydrolyzed Spongilla Spicules',1,1),
  ('ING3317','Glycerin Acrylate/Acrylic Acid Copolymer','Glycerin Acrylate/Acrylic Acid Copolymer',1,1),
  ('ING3318','Lactobacillus Extracellular Vesicles','Lactobacillus Extracellular Vesicles',1,1),
  ('ING3319','Milk Exosome','Milk Exosome',1,1),
  ('ING3320','Brassicasterol','Brassicasterol',1,1),
  ('ING3321','Ceteareth-3','Ceteareth-3',1,1),
  ('ING3322','Ceteareth-5','Ceteareth-5',1,1),
  ('ING3323','Morus Bombycis Leaf Extract','Morus Bombycis Leaf Extract',1,1),
  ('ING3324','Fragaria Ananassa Fruit Extract','Fragaria Ananassa Fruit Extract',1,1),
  ('ING3325','Hydrolyzed Sclerotium Gum','Hydrolyzed Sclerotium Gum',1,1),
  ('ING3326','Salmon Egg Extract','Salmon Egg Extract',1,1),
  ('ING3327','Allium Cepa (Onion) Bulb Extract','Allium Cepa (Onion) Bulb Extract',1,1),
  ('ING3328','Matricaria Recutita (Chamomile) Extract','Matricaria Recutita (Chamomile) Extract',1,1),
  ('ING3329','Abelmoschus Esculentus (Okra) Fruit Extract','Abelmoschus Esculentus (Okra) Fruit Extract',1,1),
  ('ING3330','Petroselinum Crispum (Parsley) Extract','Petroselinum Crispum (Parsley) Extract',1,1),
  ('ING3331','Corchorus Olitorius Leaf Extract','Corchorus Olitorius Leaf Extract',1,1),
  ('ING3332','Bifidoenzyme Lysate','Bifidoenzyme Lysate',1,1),
  ('ING3333','Acrylates/c10-30 Alkylacrylate Crosspolymer','Acrylates/c10-30 Alkylacrylate Crosspolymer',1,1),
  ('ING3334','Dipentaerythritylhex C5-9 Acid Esters','Dipentaerythritylhex C5-9 Acid Esters',1,1),
  ('ING3335','Hyaluronate Sodium','Hyaluronate Sodium',1,1),
  ('ING3336','Rehmannia Chinensis Root Extract','Rehmannia Chinensis Root Extract',1,1),
  ('ING3337','Rice Bran Extract (50 ppm)','Rice Bran Extract (50 ppm)',1,1),
  ('ING3338','Julmandrami Seed Extract','Julmandrami Seed Extract',1,1),
  ('ING3339','2-Hexandediol','2-Hexandediol',1,1),
  ('ING3340','Citrus Reticulata (Tangerine) Peel Extract','Citrus Reticulata (Tangerine) Peel Extract',1,1),
  ('ING3341','Haematococcus Pluvialis Oil','Haematococcus Pluvialis Oil',1,1),
  ('ING3342','Thuja Orientalis Leaf Extract','Thuja Orientalis Leaf Extract',1,1),
  ('ING3343','C12-13 Pareth-9','C12-13 Pareth-9',1,1),
  ('ING3344','Raspberry Ketone','Raspberry Ketone',1,1),
  ('ING3345','Morus Nigra Fruit Extract','Morus Nigra Fruit Extract',1,1),
  ('ING3346','Lycium Chinense Fruit Extract','Lycium Chinense Fruit Extract',1,1),
  ('ING3347','Stearatrimonium Chloride','Stearatrimonium Chloride',1,1),
  ('ING3348','Hydrogenated Didecene','Hydrogenated Didecene',1,1),
  ('ING3349','Sphingomonas Ferment Extract','Sphingomonas Ferment Extract',1,1),
  ('ING3350','Vitex Agnus-Castus Extract','Vitex Agnus-Castus Extract',1,1),
  ('ING3351','triethanolamin','triethanolamin',1,1),
  ('ING3352','Palmitoyl Decapeptide-21','Palmitoyl Decapeptide-21',1,1),
  ('ING3353','Zinc Palmitoyl Nonapeptide-14','Zinc Palmitoyl Nonapeptide-14',1,1),
  ('ING3354','Decapeptide-22','Decapeptide-22',1,1),
  ('ING3355','Oligopeptide-78','Oligopeptide-78',1,1),
  ('ING3356','pyridoxine hydrochloride (500PPM)','pyridoxine hydrochloride (500PPM)',1,1),
  ('ING3357','Konjac Mannan Root Extract','Konjac Mannan Root Extract',1,1),
  ('ING3358','Anise Fruit Extract','Anise Fruit Extract',1,1),
  ('ING3359','Vanilla Fruit Extract','Vanilla Fruit Extract',1,1),
  ('ING3360','Provence Rose Flower Extract','Provence Rose Flower Extract',1,1),
  ('ING3361','Pear Extract','Pear Extract',1,1),
  ('ING3362','Coconut Extract','Coconut Extract',1,1),
  ('ING3363','Damask Rose Flower Hydrolate','Damask Rose Flower Hydrolate',1,1),
  ('ING3364','Strawberry Extract','Strawberry Extract',1,1),
  ('ING3365','Saccharomyces/Honey Ferment Filtrate','Saccharomyces/Honey Ferment Filtrate',1,1),
  ('ING3366','Alcohol sd 40b','Alcohol sd 40b',1,1),
  ('ING3367','Hexyl Nicotinate','Hexyl Nicotinate',1,1),
  ('ING3368','Croton Lechleri Resin Powder','Croton Lechleri Resin Powder',1,1),
  ('ING3369','Palmitoyl Hydroxypropyltrimonium Amylopectin/Glycerin Crosspolymer','Palmitoyl Hydroxypropyltrimonium Amylopectin/Glycerin Crosspolymer',1,1),
  ('ING3370','Oligopeptide-10','Oligopeptide-10',1,1),
  ('ING3371','Disodium Laureth Sulphosuccinate','Disodium Laureth Sulphosuccinate',1,1),
  ('ING3372','Natto Gum','Natto Gum',1,1),
  ('ING3373','Dimethicone/Bis-Isobutyl PPG-20 Crosspolymer','Dimethicone/Bis-Isobutyl PPG-20 Crosspolymer',1,1),
  ('ING3374','Tridecyl Salicylate','Tridecyl Salicylate',1,1),
  ('ING3375','Citrullus Lanatus (Watermelon) Extract','Citrullus Lanatus (Watermelon) Extract',1,1),
  ('ING3376','Daucus Carota Sativa (Carrot) Extract','Daucus Carota Sativa (Carrot) Extract',1,1),
  ('ING3377','Glycyrrhiza Glabra (Licorice) Extract','Glycyrrhiza Glabra (Licorice) Extract',1,1),
  ('ING3378','Rubus Idaeus (Raspberry) Oil','Rubus Idaeus (Raspberry) Oil',1,1),
  ('ING3379','Isododecane 5.0%','Isododecane 5.0%',1,1),
  ('ING3380','Methyl Propanediol 3.0%','Methyl Propanediol 3.0%',1,1),
  ('ING3381','Butylene Glycol 2.0%','Butylene Glycol 2.0%',1,1),
  ('ING3382','1.2-Hexanediol 2.0%','1.2-Hexanediol 2.0%',1,1),
  ('ING3383','Calamine 2.0%','Calamine 2.0%',1,1),
  ('ING3384','Polyacrylate Crosspolymer-6 Polyester-1','Polyacrylate Crosspolymer-6 Polyester-1',1,1),
  ('ING3385','Sucrose Laurate','Sucrose Laurate',1,1),
  ('ING3386','Caprylyl/Caprylyl Glucoside','Caprylyl/Caprylyl Glucoside',1,1),
  ('ING3387','PEG-30 DIPOLYHYDROXYSTEARATE-RATE','PEG-30 DIPOLYHYDROXYSTEARATE-RATE',1,1),
  ('ING3388','SODIUM DODECYLBENZENESULFONATE','SODIUM DODECYLBENZENESULFONATE',1,1),
  ('ING3389','PEG-8 LAURATE','PEG-8 LAURATE',1,1),
  ('ING3390','ETHYLHEXYL TRIAZINE','ETHYLHEXYL TRIAZINE',1,1),
  ('ING3391','LAURYL PEG / PPG-18 / 18 METHICONE (E.L.L Z70014795/1).','LAURYL PEG / PPG-18 / 18 METHICONE (E.L.L Z70014795/1).',1,1),
  ('ING3392','Citrus Japonica Fruit Extract','Citrus Japonica Fruit Extract',1,1),
  ('ING3393','Oxybenzone','Oxybenzone',1,1),
  ('ING3394','Picea Abies Wood Extract','Picea Abies Wood Extract',1,1),
  ('ING3395','Bentonite','Bentonite',1,1),
  ('ING3396','Octinoxate','Octinoxate',1,1),
  ('ING3397','Acetyl Zingerone','Acetyl Zingerone',1,1),
  ('ING3398','Porphyra Umbilicalis Extract','Porphyra Umbilicalis Extract',1,1),
  ('ING3399','Entada Phaseoloides Bark/Seed Extract','Entada Phaseoloides Bark/Seed Extract',1,1),
  ('ING3400','Sunflower Oil refined','Sunflower Oil refined',1,1),
  ('ING3401','Rapeseed Oil refined','Rapeseed Oil refined',1,1),
  ('ING3402','Linseed Oil refined Food Grade','Linseed Oil refined Food Grade',1,1),
  ('ING3403','Hexylcinnamal','Hexylcinnamal',1,1),
  ('ING3404','PEG-400','PEG-400',1,1),
  ('ING3405','Vitis Vinifera Leaf Extract','Vitis Vinifera Leaf Extract',1,1),
  ('ING3406','Polygonum Fagopyrum Leaf Extract','Polygonum Fagopyrum Leaf Extract',1,1),
  ('ING3407','Iodized Hydrolyzed Zein','Iodized Hydrolyzed Zein',1,1),
  ('ING3408','Paullinia Cupana Seed Extract','Paullinia Cupana Seed Extract',1,1),
  ('ING3409','Sodium Propylparaben','Sodium Propylparaben',1,1),
  ('ING3410','Polyglyceryl-3 Methylglycose Distearate','Polyglyceryl-3 Methylglycose Distearate',1,1),
  ('ING3411','1.3-Butylene Glycol','1.3-Butylene Glycol',1,1),
  ('ING3412','Phytosteryl Canola Glycerides','Phytosteryl Canola Glycerides',1,1),
  ('ING3413','Triolein','Triolein',1,1),
  ('ING3414','TREHALOSE HIPPOPHAE RHAMNOIDES EXTRACT','TREHALOSE HIPPOPHAE RHAMNOIDES EXTRACT',1,1),
  ('ING3415','MELISSA OFFICINALIS EXTRACT','MELISSA OFFICINALIS EXTRACT',1,1),
  ('ING3416','Hydrolyzed Malt Extract','Hydrolyzed Malt Extract',1,1),
  ('ING3417','Hydrolyzed Viola Tricolor Extract','Hydrolyzed Viola Tricolor Extract',1,1),
  ('ING3418','Cutibacterium Avidum Fermentation Extract Filtrate (24.4%)','Cutibacterium Avidum Fermentation Extract Filtrate (24.4%)',1,1),
  ('ING3419','Juulmandrami Seed Extract','Juulmandrami Seed Extract',1,1),
  ('ING3420','Candelilla Cera','Candelilla Cera',1,1),
  ('ING3421','Phragmites Communis Extract','Phragmites Communis Extract',1,1),
  ('ING3422','Artemisia Princeps Extract','Artemisia Princeps Extract',1,1),
  ('ING3423','Aniba Rosodora (Rosewood) Wood Oil','Aniba Rosodora (Rosewood) Wood Oil',1,1),
  ('ING3424','Houttuynia Cordata Powder','Houttuynia Cordata Powder',1,1),
  ('ING3425','Octanediol','Octanediol',1,1),
  ('ING3426','Herbal Wheat Extract (100%) Houttuynia Cordata Extract','Herbal Wheat Extract (100%) Houttuynia Cordata Extract',1,1),
  ('ING3427','Mentha Aquatica Extract','Mentha Aquatica Extract',1,1),
  ('ING3428','Succinic Acid','Succinic Acid',1,1),
  ('ING3429','Yellow Wall Bark Extract','Yellow Wall Bark Extract',1,1),
  ('ING3430','Sugar Elm Root Extract','Sugar Elm Root Extract',1,1),
  ('ING3431','Zulmandrami Seed Extract','Zulmandrami Seed Extract',1,1),
  ('ING3432','Hydrolyzed Gardenia Extract','Hydrolyzed Gardenia Extract',1,1),
  ('ING3433','Aloe Ferox Leaf Extract','Aloe Ferox Leaf Extract',1,1),
  ('ING3434','Octyldodecyl-16','Octyldodecyl-16',1,1),
  ('ING3435','Noni fruit extract (84.91479441%)','Noni fruit extract (84.91479441%)',1,1),
  ('ING3436','indomul bead tree flower extract','indomul bead tree flower extract',1,1),
  ('ING3437','indomal Bead tree leaf extract','indomal Bead tree leaf extract',1,1),
  ('ING3438','castor seed oil','castor seed oil',1,1),
  ('ING3439','balsamic fiber resin','balsamic fiber resin',1,1),
  ('ING3440','gwanggwanghyang oil','gwanggwanghyang oil',1,1),
  ('ING3441','noni seed oil (10ppm)','noni seed oil (10ppm)',1,1),
  ('ING3442','cypress water','cypress water',1,1),
  ('ING3443','octyldodeses-16','octyldodeses-16',1,1),
  ('ING3444','acetylglucosamine','acetylglucosamine',1,1),
  ('ING3445','hydrolyzed glycosaminoglycan','hydrolyzed glycosaminoglycan',1,1),
  ('ING3446','Queensland Nut Oil','Queensland Nut Oil',1,1),
  ('ING3447','Seawater','Seawater',1,1),
  ('ING3448','Hydrogenated Olive Oil Lauryl Ester','Hydrogenated Olive Oil Lauryl Ester',1,1),
  ('ING3449','Hydrogenated Rice Bran Oil','Hydrogenated Rice Bran Oil',1,1),
  ('ING3450','Cacao Seed Extract','Cacao Seed Extract',1,1),
  ('ING3451','Polyglyceryl-3methyl Glucose Distearate','Polyglyceryl-3methyl Glucose Distearate',1,1),
  ('ING3452','Polyglyceryl-10 Stearate Late','Polyglyceryl-10 Stearate Late',1,1),
  ('ING3453','Behenic Acid','Behenic Acid',1,1),
  ('ING3454','Xanthophylls','Xanthophylls',1,1),
  ('ING3455','Polydimethylsiloxane','Polydimethylsiloxane',1,1),
  ('ING3456','Brassica Oleracea Acephala Leaf Extract','Brassica Oleracea Acephala Leaf Extract',1,1),
  ('ING3457','Hydrogenated Lecthin','Hydrogenated Lecthin',1,1),
  ('ING3458','Hydroxypropyitrimonium Hyaluronate','Hydroxypropyitrimonium Hyaluronate',1,1),
  ('ING3459','Sodium Hyaluronate Dimetbyslarol','Sodium Hyaluronate Dimetbyslarol',1,1),
  ('ING3460','Glycerin Sodium Cocoylalaninate','Glycerin Sodium Cocoylalaninate',1,1),
  ('ING3461','Dicodium Cocoampodiacetate','Dicodium Cocoampodiacetate',1,1),
  ('ING3462','Sodium Methyl Cocoyl taurate Acrylate','Sodium Methyl Cocoyl taurate Acrylate',1,1),
  ('ING3463','C10-30 Alkyl Acrylate Crospolymer','C10-30 Alkyl Acrylate Crospolymer',1,1),
  ('ING3464','Birch Sap','Birch Sap',1,1),
  ('ING3465','Quilla Peel Extract','Quilla Peel Extract',1,1),
  ('ING3466','White Rice Extract','White Rice Extract',1,1),
  ('ING3467','Medicinal Wheat Extract','Medicinal Wheat Extract',1,1),
  ('ING3468','Lauryl hydroxysultain','Lauryl hydroxysultain',1,1),
  ('ING3469','Caprilyl Glycol','Caprilyl Glycol',1,1),
  ('ING3470','Sodium Cocoylisethionate','Sodium Cocoylisethionate',1,1),
  ('ING3471','Hydrogenated Decitin','Hydrogenated Decitin',1,1),
  ('ING3472','PEG-20 Glyceryl Triisostearate','PEG-20 Glyceryl Triisostearate',1,1),
  ('ING3473','PEG-10 Isostearate','PEG-10 Isostearate',1,1),
  ('ING3474','Mineral Salts','Mineral Salts',1,1),
  ('ING3475','Geranium Maculatum Oil','Geranium Maculatum Oil',1,1),
  ('ING3476','Rose Flower Oil','Rose Flower Oil',1,1),
  ('ING3477','Styrax Benzoin Gum','Styrax Benzoin Gum',1,1),
  ('ING3478','Candida/Garcinia Cambogia Ferment','Candida/Garcinia Cambogia Ferment',1,1),
  ('ING3479','BUTYL AVOCADATE','BUTYL AVOCADATE',1,1),
  ('ING3480','Quillaja Saponaria Bark Extract','Quillaja Saponaria Bark Extract',1,1),
  ('ING3481','Ceramide 5','Ceramide 5',1,1),
  ('ING3482','Hydrogenated Rice Bran Wax','Hydrogenated Rice Bran Wax',1,1),
  ('ING3483','4-Terpineol','4-Terpineol',1,1),
  ('ING3484','Escin','Escin',1,1),
  ('ING3485','Ceramide','Ceramide',1,1),
  ('ING3486','Nelumbo Nucifera Root Extract','Nelumbo Nucifera Root Extract',1,1),
  ('ING3487','Borago Officinalis (Borage) Seed Oil','Borago Officinalis (Borage) Seed Oil',1,1),
  ('ING3488','Dicaprilyl Carbonate','Dicaprilyl Carbonate',1,1),
  ('ING3489','Caprylic/caprine/amber Triglyceride','Caprylic/caprine/amber Triglyceride',1,1),
  ('ING3490','Caprylic/caprine Triglyceride','Caprylic/caprine Triglyceride',1,1),
  ('ING3491','Pentaerythritol Tetraethylhexanoate','Pentaerythritol Tetraethylhexanoate',1,1),
  ('ING3492','Seed Oil Macadamia Ternifolia','Seed Oil Macadamia Ternifolia',1,1),
  ('ING3493','Bifidа Enzyme Lysate','Bifidа Enzyme Lysate',1,1),
  ('ING3494','Dimethicone/Vinyldimethicone Crosspolymer','Dimethicone/Vinyldimethicone Crosspolymer',1,1),
  ('ING3495','Flavor','Flavor',1,1),
  ('ING3496','Dicalium Glycyrhizate','Dicalium Glycyrhizate',1,1),
  ('ING3497','Chinese Remania Root Extract','Chinese Remania Root Extract',1,1),
  ('ING3498','Drometrizole Siloxane','Drometrizole Siloxane',1,1),
  ('ING3499','Acrylates Alkyl Acrylate/C10-30 Crosspolymer','Acrylates Alkyl Acrylate/C10-30 Crosspolymer',1,1),
  ('ING3500','Perfumery Water','Perfumery Water',1,1)
ON CONFLICT (ingredient_id) DO UPDATE SET canonical_name=EXCLUDED.canonical_name, aliases=EXCLUDED.aliases;