INSERT INTO ingredients_dictionary (ingredient_id,canonical_name,aliases,product_count,occurrence_count)
VALUES
  ('ING1001','propoxytetramethyl piperidinyl dimethicone','propoxytetramethyl piperidinyl dimethicone; Propoxytetramethyl Piperidinyl Dimethicone',3,3),
  ('ING1002','Glycereth-90 Isostearate','Glycereth-90 Isostearate',3,3),
  ('ING1003','Brassica Oleracea Italica (Broccoli) Seed Oil','Brassica Oleracea Italica (Broccoli) Seed Oil; Brassica oleracea italica seed oil; BRASSICA OLERACEA ITALICA (BROCCOLI) SEED OIL',3,3),
  ('ING1004','eucalyptol','eucalyptol; EUCALYPTOL',3,3),
  ('ING1005','IRIS FLORENTINA ROOT EXTRACT','IRIS FLORENTINA ROOT EXTRACT; iris florentina root extract; Iris Florentina Root Extract',3,3),
  ('ING1006','Sodium Oleate','Sodium Oleate; SODIUM OLEATE',3,3),
  ('ING1007','POLYQUATERNIUM-80','POLYQUATERNIUM-80; polyquaternium-80; Polyquaternium-80',3,3),
  ('ING1008','DISODIUM LAURYL SULFOSUCCINATE','DISODIUM LAURYL SULFOSUCCINATE; Disodium Lauryl Sulfosuccinate',3,3),
  ('ING1009','Cymbopogon Flexuosus (Lemongrass) Oil','Cymbopogon Flexuosus (Lemongrass) Oil; CYMBOPOGON FLEXUOSUS (LEMONGRASS) OIL',3,3),
  ('ING1010','Xylityl Sesquicaprylate','Xylityl Sesquicaprylate; XYLITYL SESQUICAPRYLATE',3,3),
  ('ING1011','CI 16035 / RED 40','CI 16035 / RED 40; CI 16035 [Red 40]',3,3),
  ('ING1012','HYDROXYPROPYL BIS-HYDROXYETHYLDIMONIUM CHLORIDE','HYDROXYPROPYL BIS-HYDROXYETHYLDIMONIUM CHLORIDE; Hydroxypropyl Bis-hydroxyethyldimonium Chloride; Hydroxypropyl Bis-Hydroxyethyldimonium Chloride',3,3),
  ('ING1013','Withania Somnifera (Ashwagandha) Root Extract','Withania Somnifera (Ashwagandha) Root Extract; Withania Somnifera Root Extract',3,3),
  ('ING1014','Phyllanthus Emblica (Amla) Extract','Phyllanthus Emblica (Amla) Extract; Phyllanthus Emblica Extract',3,3),
  ('ING1015','CI 42090 / BLUE 1','CI 42090 / BLUE 1; ci 42090/blue 1',3,3),
  ('ING1016','Hexyldecanol','Hexyldecanol',3,3),
  ('ING1017','Glycereth-2 Cocoate','Glycereth-2 Cocoate; GLYCERETH-2 COCOATE',3,3),
  ('ING1018','CAPRYLIC/CAPRIC GLYCERIDES','CAPRYLIC/CAPRIC GLYCERIDES; Caprylic/capric Glycerides; Caprylic/Capric Glycerides',3,3),
  ('ING1019','LAURETH-5 CARBOXYLIC ACID','LAURETH-5 CARBOXYLIC ACID',3,3),
  ('ING1020','Moringa Oleifera Leaf Extract','Moringa Oleifera Leaf Extract; MORINGA OLEIFERA LEAF EXTRACT; Moringa Oleifera (Moringa Tree) Leaf Extract',3,3),
  ('ING1021','Lens Esculenta (Lentil) Seed Extract','Lens Esculenta (Lentil) Seed Extract; LENS ESCULENTA (LENTIL) SEED EXTRACT',3,3),
  ('ING1022','SODIUM SUCCINATE','SODIUM SUCCINATE; Sodium Succinate',3,3),
  ('ING1023','MACROCYSTIS PYRIFERA (KELP) EXTRACT','MACROCYSTIS PYRIFERA (KELP) EXTRACT; Macrocystis Pyrifera (Kelp) Extract',3,3),
  ('ING1024','Diheptyl Succinate','Diheptyl Succinate; DIHEPTYL SUCCINATE',3,3),
  ('ING1025','HYDROLYZED ADANSONIA DIGITATA SEED EXTRACT','HYDROLYZED ADANSONIA DIGITATA SEED EXTRACT; Hydrolyzed Adansonia Digitata Seed Extract',3,3),
  ('ING1026','Ethyl Linoleate','Ethyl Linoleate',3,3),
  ('ING1027','FAEX (YEAST) EXTRACT','FAEX (YEAST) EXTRACT; faex extract',3,3),
  ('ING1028','Cymbopogon Schoenanthus Extract','Cymbopogon Schoenanthus Extract; Cymbopogon Schoenanthus (Lemongrass) Extract',3,3),
  ('ING1029','Vegetable Glycerin','Vegetable Glycerin',3,3),
  ('ING1030','Cucurbita Pepo (Pumpkin) Seed Extract','Cucurbita Pepo (Pumpkin) Seed Extract',3,3),
  ('ING1031','Glycine Soja Oil / Soybean Oil','Glycine Soja Oil / Soybean Oil; glycine soja oil / soybean oil; GLYCINE SOJA OIL / SOYBEAN OIL',3,3),
  ('ING1032','ZINGIBER OFFICINALE ROOT EXTRACT / GINGER ROOT EXTRACT','ZINGIBER OFFICINALE ROOT EXTRACT / GINGER ROOT EXTRACT; Zingiber officinale root extract / ginger root extract',3,3),
  ('ING1033','Dipeptide Diaminobutyroyl Benzylamide Diacetate','Dipeptide Diaminobutyroyl Benzylamide Diacetate; Dipeptide diaminobutyroyl benzylamide diacetate; Dipeptide Diaminobutyroyl Benzylamide Diacetate(100ppb)',3,4),
  ('ING1034','Heptyl Undecylenate','Heptyl Undecylenate',3,3),
  ('ING1035','Bis-Ethyl(Isostearylimidazoline) Isostearamide','Bis-Ethyl(Isostearylimidazoline) Isostearamide; BIS-ETHYL (ISOSTEARYLIMIDAZOLINE) ISOSTEARAMIDE; Bis-Ethyl(isostearylimidazoline) Isostearamide',3,3),
  ('ING1036','Capsicum Frutescens (Cayenne) Fruit Extract','Capsicum Frutescens (Cayenne) Fruit Extract; CAPSICUM FRUTESCENS FRUIT EXTRACT',3,3),
  ('ING1037','OLEA EUROPAEA (OLIVE) LEAF EXTRACT','OLEA EUROPAEA (OLIVE) LEAF EXTRACT; Olea Europaea (Olive) Leaf Extract',3,3),
  ('ING1038','Sodium Myristoyl Glutamate','Sodium Myristoyl Glutamate; Sodium myristoyl glutamate',3,3),
  ('ING1039','Acetyl Tetrapeptide-3','Acetyl Tetrapeptide-3',3,3),
  ('ING1040','Trifolium Pratense Flower Extract','Trifolium Pratense Flower Extract; Trifolium Pratense (Clover) Flower Extract; TRIFOLIUM PRATENSE (CLOVER) FLOWER EXTRACT',3,3),
  ('ING1041','Hydrolyzed Yeast Protein','Hydrolyzed Yeast Protein',3,3),
  ('ING1042','Rice oil glycereth-8 esters','Rice oil glycereth-8 esters; Rice Oil Glycereth-8 Esters',3,3),
  ('ING1043','Sodium Metabisulfite','Sodium Metabisulfite; SODIUM METABISULFITE',3,3),
  ('ING1044','Citrus Junos Fruit Extract','Citrus Junos Fruit Extract; citrus junos fruit extract',3,3),
  ('ING1045','Ethyl Lauroyl Arginate Hcl','Ethyl Lauroyl Arginate Hcl; Ethyl Lauroyl Arginate HCL',3,3),
  ('ING1046','Citrus Paradisi (Grapefruit) Peel Extract','Citrus Paradisi (Grapefruit) Peel Extract',3,3),
  ('ING1047','Citrus Aurantium Fruit Extract','Citrus Aurantium Fruit Extract',3,3),
  ('ING1048','Aloe Barbadensis Leaf Juice Extract','Aloe Barbadensis Leaf Juice Extract',3,3),
  ('ING1049','Humulus Lupulus Extract','Humulus Lupulus Extract; humulus lupulus extract; Humulus lupulus extract',3,3),
  ('ING1050','LINUM USITATISSIMUM SEED EXTRACT','LINUM USITATISSIMUM SEED EXTRACT; LINUM USITATISSIMUM (LINSEED) SEED EXTRACT',3,3),
  ('ING1051','Retinyl Acetate','Retinyl Acetate; RETINYL ACETATE',3,3),
  ('ING1052','Hydrolyzed Soy and Rice Protein','Hydrolyzed Soy and Rice Protein',3,3),
  ('ING1053','Hydroxyproline','Hydroxyproline',3,3),
  ('ING1054','Silicone Quaternium-22','Silicone Quaternium-22',3,3),
  ('ING1055','Snail Secretion Filtrate','Snail Secretion Filtrate',3,3),
  ('ING1056','Camellia Japonica Leaf Extract','Camellia Japonica Leaf Extract',3,3),
  ('ING1057','aloe barbadensis gel','aloe barbadensis gel; Aloe Barbadensis Gel',3,3),
  ('ING1058','chamomilla recutita extract','chamomilla recutita extract; Chamomilla recutita extract; Chamomilla Recutita (Matricaria) Extract',3,3),
  ('ING1059','camelia sinensis extract','camelia sinensis extract; Camelia sinensis extract; Camelia Sinensis Extract',3,3),
  ('ING1060','Shikimic Acid','Shikimic Acid; Shikimic acid',3,3),
  ('ING1061','Sodium Laureth-8 Sulfate','Sodium Laureth-8 Sulfate; SODIUM LAURETH-8 SULFATE',3,3),
  ('ING1062','Sodium Oleth Sulfate','Sodium Oleth Sulfate; SODIUM OLETH SULFATE',3,3),
  ('ING1063','d-limonene','d-limonene; D-LIMONENE; D-Limonene',3,3),
  ('ING1064','GLUCONIC ACID','GLUCONIC ACID; Gluconic Acid',3,3),
  ('ING1065','CYSTOSEIRA COMPRESSA EXTRACT','CYSTOSEIRA COMPRESSA EXTRACT; Cystoseira Compressa Extract',3,3),
  ('ING1066','Argan Kernel Oil','Argan Kernel Oil; argan kernel oil',3,3),
  ('ING1067','Camellia Seed Oil','Camellia Seed Oil; camellia seed oil',3,3),
  ('ING1068','Jojoba Seed Oil','Jojoba Seed Oil',3,3),
  ('ING1069','lactobacillus/rice ferment','lactobacillus/rice ferment; Lactobacillus/Rice Ferment; LACTOBACILLUS/RICE FERMENT',3,3),
  ('ING1070','Milk Protein Extract','Milk Protein Extract',3,3),
  ('ING1071','Silk Powder','Silk Powder',3,3),
  ('ING1072','Isobutane','Isobutane',3,3),
  ('ING1073','Butane','Butane; BUTANE',3,3),
  ('ING1074','Eucalyptus Globulus Leaf Extract','Eucalyptus Globulus Leaf Extract',3,3),
  ('ING1075','Cystine','Cystine',3,3),
  ('ING1076','Hydrolyzed Potato Protein','Hydrolyzed Potato Protein',3,3),
  ('ING1077','Hydrolyzed Sweet Almond Protein','Hydrolyzed Sweet Almond Protein',3,3),
  ('ING1078','Hydrogenated Olive Oil Unsaponifiables','Hydrogenated Olive Oil Unsaponifiables',3,3),
  ('ING1079','Camellia Japonica Flower Extract','Camellia Japonica Flower Extract',3,3),
  ('ING1080','Malpighia Emarginata (Acerola) Fruit Extract','Malpighia Emarginata (Acerola) Fruit Extract',3,3),
  ('ING1081','Prunus Serrulata Flower Extract','Prunus Serrulata Flower Extract; prunus serrulata flower extract',3,3),
  ('ING1082','YELLOW 6 (CI 15985)','YELLOW 6 (CI 15985); Yellow 6 (Ci 15985)',3,3),
  ('ING1083','ROSA CANINA SEED OIL','ROSA CANINA SEED OIL; Rosa Canina (Rose Hip) Seed Oil*; Rosa Canina Seed Oil',3,3),
  ('ING1084','SILICA DIMETHYL SILYLATE','SILICA DIMETHYL SILYLATE; Silica Dimethyl Silylate',3,3),
  ('ING1085','Sophora Flavescens Root Extract','Sophora Flavescens Root Extract',3,3),
  ('ING1086','Morus Alba Bark Extract','Morus Alba Bark Extract; Morus Alba Bark Extract(8.7%)',3,3),
  ('ING1087','Rose Extract','Rose Extract; rose extract',3,3),
  ('ING1088','Red Iron Oxide','Red Iron Oxide; Red Iron oxide (CI 77491)',3,3),
  ('ING1089','Monarda Didyma Leaf Extract','Monarda Didyma Leaf Extract',3,3),
  ('ING1090','Mauritia Flexuosa Fruit Oil','Mauritia Flexuosa Fruit Oil; Mauritia Flexuosa (Morete) Fruit Oil; Mauritia Flexuosa (Buriti) Fruit Oil',3,3),
  ('ING1091','Hydrolyzed Conchiolin Protein','Hydrolyzed Conchiolin Protein; HYDROLYZED CONCHIOLIN PROTEIN',3,3),
  ('ING1092','Ribes Nigrum Fruit Extract','Ribes Nigrum Fruit Extract; Ribes Nigrum (Black Currant) Fruit Extract; RIBES NIGRUM (BLACK CURRANT) FRUIT EXTRACT',3,3),
  ('ING1093','Amylopectin','Amylopectin',3,3),
  ('ING1094','Calendula Officinalis Extract','Calendula Officinalis Extract; calendula officinalis extract',3,3),
  ('ING1095','PEG-20 Stearate','PEG-20 Stearate; peg-20 stearate; PEG-20 STEARATE',3,3),
  ('ING1096','Citrus Nobilis (Mandarin Orange) Fruit Extract','Citrus Nobilis (Mandarin Orange) Fruit Extract; Citrus Nobilis Fruit Extract',3,3),
  ('ING1097','Polyglyceryl-6 Oleate','Polyglyceryl-6 Oleate; POLYGLYCERYL-6 OLEATE',3,3),
  ('ING1098','Arginine HCl','Arginine HCl; arginine hcl; ARGININE HCL',3,3),
  ('ING1099','Sodium Surfactin','Sodium Surfactin; SODIUM SURFACTIN',3,3),
  ('ING1100','Hydrolyzed Algin','Hydrolyzed Algin; HYDROLYZED ALGIN',3,3),
  ('ING1101','Bellis Perennis (Daisy) Flower Extract','Bellis Perennis (Daisy) Flower Extract; bellis perennis (daisy) flower extract',3,3),
  ('ING1102','Juniperus Mexicana Oil','Juniperus Mexicana Oil',3,3),
  ('ING1103','Copper Gluconate','Copper Gluconate; Copper gluconate',3,3),
  ('ING1104','Prunus Amygdalus Dulcis (Sweet Almond) Fruit Extract','Prunus Amygdalus Dulcis (Sweet Almond) Fruit Extract; prunus amygdalus dulcis fruit extract',3,3),
  ('ING1105','Glycine Soja (Soybean) Germ Extract','Glycine Soja (Soybean) Germ Extract; Glycine Soja Germ Extract',3,3),
  ('ING1106','Camelia Sinensis Leaf Extract','Camelia Sinensis Leaf Extract',3,3),
  ('ING1107','Prunus Africana (Pygeum) Bark Extract','Prunus Africana (Pygeum) Bark Extract; Prunus Africana (Pygeum) Bark Extract*',3,3),
  ('ING1108','Soy Isoflavones','Soy Isoflavones',3,3),
  ('ING1109','Nicotinic Acid (Niacin)*','Nicotinic Acid (Niacin)*',3,3),
  ('ING1110','Micrococcus Lysate','Micrococcus Lysate; MICROCOCCUS LYSATE',3,3),
  ('ING1111','Caesalpinia Spinosa Gum','Caesalpinia Spinosa Gum; CAESALPINIA SPINOSA GUM',3,3),
  ('ING1112','Methyl Glucose Sesquistearate','Methyl Glucose Sesquistearate; Methyl glucose sesquistearate',3,3),
  ('ING1113','Undaria Pinnatifida Extract','Undaria Pinnatifida Extract',3,3),
  ('ING1114','Ceteareth-6','Ceteareth-6',3,3),
  ('ING1115','Lycium barbarum fruit extract','Lycium barbarum fruit extract; Lycium Barbarum (Goij) Fruit Extract; Lycium Barbarum Fruit Extract',3,3),
  ('ING1116','Sericin','Sericin; SERICIN',3,3),
  ('ING1117','MYRISTYL LACTATE','MYRISTYL LACTATE; Myristyl Lactate',3,3),
  ('ING1118','Lauramidopropyl Betaine','Lauramidopropyl Betaine; lauramidopropyl betaine',3,3),
  ('ING1119','Polysilicon-15','Polysilicon-15; polysilicon-15',3,3),
  ('ING1120','Theanine','Theanine',3,3),
  ('ING1121','Ethyl Ascorbic Acid','Ethyl Ascorbic Acid',3,3),
  ('ING1122','Hedera helix (Ivy) Leaf / Stem Extract','Hedera helix (Ivy) Leaf / Stem Extract; HEDERA HELIX (IVY) LEAF/STEM EXTRACT; Hedera Helix (Ivy) Leaf/Stem Extract',3,3),
  ('ING1123','Beta Vulgaris (Beet) Root Extract','Beta Vulgaris (Beet) Root Extract',3,3),
  ('ING1124','ethylhexyltriazone','ethylhexyltriazone; Ethylhexyltriazone; EthylhexylTriazone',3,3),
  ('ING1125','arachidic acid','arachidic acid; Arachidic Acid',3,3),
  ('ING1126','Purslane Extract','Purslane Extract; purslane extract',3,3),
  ('ING1127','Calcium Aluminum Borosilicate','Calcium Aluminum Borosilicate; CALCIUM ALUMINUM BOROSILICATE',3,4),
  ('ING1128','Dimethicone/PEG-10/15 Crosspolymer','Dimethicone/PEG-10/15 Crosspolymer; Dimethicone/Peg-10/15 Crosspolymer',3,3),
  ('ING1129','Trisiloxane','Trisiloxane; TRISILOXANE',3,3),
  ('ING1130','Echium Plantagineum Seed Oil','Echium Plantagineum Seed Oil',3,3),
  ('ING1131','Giant Pine Leaf Extract','Giant Pine Leaf Extract',3,3),
  ('ING1132','Helianthus Annuus (Sunflower) Seed Oil Unsaponifiables','Helianthus Annuus (Sunflower) Seed Oil Unsaponifiables; Helianthus Annuus (sunflower) Seed Oil Unsaponifiables',3,3),
  ('ING1133','Hydroxypropyl Methylcellulose Stearoxy Ether','Hydroxypropyl Methylcellulose Stearoxy Ether',3,3),
  ('ING1134','Pelargonium Graveolens Flower Oil','Pelargonium Graveolens Flower Oil; Pelargonium Graveolens (Geranium) Flower Oil',3,3),
  ('ING1135','c12-22 alkyl acrylate/hydroxyethylacrylate copolymer','c12-22 alkyl acrylate/hydroxyethylacrylate copolymer; c12-22 alkyl acrylate/ hydroxyethylacrylate copolymer; C12-22 ALKYL ACRYLATE / HYDROXYETHYLACRYLATE COPOLYMER',3,3),
  ('ING1136','Dextrin Palmitate','Dextrin Palmitate',3,3),
  ('ING1137','Hydrogen Dimethicone','Hydrogen Dimethicone; hydrogen dimethicone',3,3),
  ('ING1138','Camellia Sinensis (Green Tea) Extract','Camellia Sinensis (Green Tea) Extract; Camellia Sinensis Extract',3,3),
  ('ING1139','Methicone','Methicone; methicone',3,3),
  ('ING1140','Saccharide Hydrolysate','Saccharide Hydrolysate; SACCHARIDE HYDROLYSATE',3,3),
  ('ING1141','Benzotriazolyl Dodecyl p-Cresol','Benzotriazolyl Dodecyl p-Cresol',3,3),
  ('ING1142','Citrus Aurantium Dulcis (Orange) Oil','Citrus Aurantium Dulcis (Orange) Oil',3,3),
  ('ING1143','Microcrystalline Wax','Microcrystalline Wax',3,3),
  ('ING1144','CUCUMIS MELO (MELON) FRUIT EXTRACT','CUCUMIS MELO (MELON) FRUIT EXTRACT; cucumis melo (melon) fruit extract; Cucumis Melo (Melon) Fruit Extract',3,3),
  ('ING1145','Caprylic Capric Triglycerides','Caprylic Capric Triglycerides; Caprylic /Capric Triglycerides; Caprylic/Capric Triglycerides',3,3),
  ('ING1146','Avobenzone','Avobenzone; AVOBENZONE',3,3),
  ('ING1147','Polymnia Sonchifolia Root Juice','Polymnia Sonchifolia Root Juice',3,3),
  ('ING1148','POLYSILICONE-11','POLYSILICONE-11; Polysilicone-11',3,3),
  ('ING1149','POLOXAMER 124','POLOXAMER 124',3,3),
  ('ING1150','POLOXAMER 184','POLOXAMER 184',3,3),
  ('ING1151','3-0-Ethyl Ascorbic Acid','3-0-Ethyl Ascorbic Acid; 3-0-ETHYL ASCORBIC ACID',3,3),
  ('ING1152','Honey Extract','Honey Extract; HONEY EXTRACT',3,3),
  ('ING1153','ALOE BARBADENSIS LEAF WATER','ALOE BARBADENSIS LEAF WATER; Aloe Barbadensis Leaf Water',3,3),
  ('ING1154','ISOPROPYL ISOSTEARATE','ISOPROPYL ISOSTEARATE',3,3),
  ('ING1155','ZEA MAYS STARCH / CORN STARCH','ZEA MAYS STARCH / CORN STARCH; ZEA MAYS STARCH/CORN STARCH',3,3),
  ('ING1156','DIPOTASSIUM PHOSPHATE','DIPOTASSIUM PHOSPHATE; Dipotassium Phosphate',3,3),
  ('ING1157','Cinnamomum Cassia Bark Extract','Cinnamomum Cassia Bark Extract',3,3),
  ('ING1158','Lactobacillus/Punica Granatum Fruit Ferment Extract','Lactobacillus/Punica Granatum Fruit Ferment Extract',3,3),
  ('ING1159','Sarcosine','Sarcosine',3,3),
  ('ING1160','Cinnamomum Zeylanicum Bark Extract','Cinnamomum Zeylanicum Bark Extract',3,3),
  ('ING1161','Magnesium Stearate','Magnesium Stearate',3,3),
  ('ING1162','Water/Aqua','Water/Aqua; Water/aqua; WATER/AQUA',3,3),
  ('ING1163','Bis-capryloyloxypalmitamido Isopropanol','Bis-capryloyloxypalmitamido Isopropanol; Bis-Capryloyloxypalmitamido Isopropanol; BIS-CAPRYLOYLOXYPALMITAMIDO ISOPROPANOL',3,3),
  ('ING1164','Yeast Ferment Extract','Yeast Ferment Extract',3,3),
  ('ING1165','Sorbitan Laurate','Sorbitan Laurate; SORBITAN LAURATE',3,3),
  ('ING1166','Sea Water','Sea Water',3,3),
  ('ING1167','Vaccinium Angustifolium (Blueberry) Fruit Extract','Vaccinium Angustifolium (Blueberry) Fruit Extract',3,3),
  ('ING1168','Menadione','Menadione',3,3),
  ('ING1169','PPG-26-Buteth-26','PPG-26-Buteth-26',3,3),
  ('ING1170','Hydrolyzed Collagen Extract','Hydrolyzed Collagen Extract; Hydrolyzed Collagen Extract (70.2%)',3,3),
  ('ING1171','Saccharomyces Ferment','Saccharomyces Ferment; SACCHAROMYCES FERMENT',3,3),
  ('ING1172','Cetearyl Isononanoate','Cetearyl Isononanoate',3,3),
  ('ING1173','Daucus Carota Sativa (Carrot) Root Extract','Daucus Carota Sativa (Carrot) Root Extract',3,3),
  ('ING1174','Ruscus Aculeatus Root Extract','Ruscus Aculeatus Root Extract',3,3),
  ('ING1175','Fucus Vesiculosus Extract','Fucus Vesiculosus Extract',3,4),
  ('ING1176','Hippophae Rhamnoides Water','Hippophae Rhamnoides Water; Hippophae Rhamnoides Water (733873ppm)',3,3),
  ('ING1177','Centella Asiatica Leaf Water','Centella Asiatica Leaf Water',3,3),
  ('ING1178','Alpha-Arbutin','Alpha-Arbutin',3,3),
  ('ING1179','Lactobacillus/Pumpkin Fruit Ferment Filtrate','Lactobacillus/Pumpkin Fruit Ferment Filtrate',3,3),
  ('ING1180','Alpha Tocopherol','Alpha Tocopherol',3,3),
  ('ING1181','Turmeric Root Extract','Turmeric Root Extract; turmeric root extract',3,3),
  ('ING1182','acrylate/C10-30 alkyl acrylate crosspolymer','acrylate/C10-30 alkyl acrylate crosspolymer; Acrylate / C10-30-Alkyl Acrylate Crosspolymer',3,3),
  ('ING1183','Guar Gum','Guar Gum',3,3),
  ('ING1184','Orange Peel Oil','Orange Peel Oil',3,3),
  ('ING1185','Phaseolus Radiatus Seed Extract','Phaseolus Radiatus Seed Extract',3,3),
  ('ING1186','Nelumbo Nucifera Flower Extract','Nelumbo Nucifera Flower Extract; nelumbo nucifera flower extract',3,3),
  ('ING1187','Centella Asiatica Root Extract','Centella Asiatica Root Extract',3,3),
  ('ING1188','Artemisia Capillaris Extract','Artemisia Capillaris Extract',3,3),
  ('ING1189','Octyldodeceth-16','Octyldodeceth-16',3,3),
  ('ING1190','Hydrolyzed Sponge','Hydrolyzed Sponge',3,3),
  ('ING1191','Polyglyceryl-6 Behenate','Polyglyceryl-6 Behenate',3,3),
  ('ING1192','Theobroma Cacao (Cocoa) Extract','Theobroma Cacao (Cocoa) Extract; theobroma cacao (cocoa) extract',3,3),
  ('ING1193','Phytosteryl/Behenyl/Octyldodecyl Lauroyl Glutamate','Phytosteryl/Behenyl/Octyldodecyl Lauroyl Glutamate; phytosteryl/behenyl/octyldodecyl lauroyl glutamate',3,3),
  ('ING1194','Hyacinthus Orientalis (Hyacinth) Extract','Hyacinthus Orientalis (Hyacinth) Extract',3,3),
  ('ING1195','Acetyl Tetrapeptide-2','Acetyl Tetrapeptide-2',3,3),
  ('ING1196','Ascophyllum Nodosum Extract','Ascophyllum Nodosum Extract',3,3),
  ('ING1197','O-cymen-5-OL','O-cymen-5-OL; O-CYMEN-5-OL',3,3),
  ('ING1198','Cutibacterium Granulosum Ferment Extract Filtrate (5.115 ppm)','Cutibacterium Granulosum Ferment Extract Filtrate (5.115 ppm); Cutibacterium Granulosum Ferment Extract Filtrate(10 ppb); Cutibacterium Granulosum Ferment Extract Filtrate (10.05 ppm)',3,3),
  ('ING1199','Bacillus Ferment','Bacillus Ferment',3,3),
  ('ING1200','Maltose','Maltose',3,3),
  ('ING1201','Amaranthus Caudatus Seed Extract','Amaranthus Caudatus Seed Extract',3,3),
  ('ING1202','Amber Powder','Amber Powder',3,3),
  ('ING1203','Cyamopsis Tetragonoloba (Guar) Gum','Cyamopsis Tetragonoloba (Guar) Gum',3,3),
  ('ING1204','Morinda Citrifolia Seed Oil','Morinda Citrifolia Seed Oil',3,3),
  ('ING1205','Solanum Lycopersicum (Tomato) Fruit Extract','Solanum Lycopersicum (Tomato) Fruit Extract',3,3),
  ('ING1206','Malachite Extract','Malachite Extract',3,3),
  ('ING1207','Cetylhydroxyproline Palmitamide','Cetylhydroxyproline Palmitamide; CETYLHYDROXYPROLINE PALMITAMIDE',3,3),
  ('ING1208','Hydrolyzed Gardenia Florida Extract','Hydrolyzed Gardenia Florida Extract',3,3),
  ('ING1209','Fig Extract','Fig Extract; fig extract',3,3),
  ('ING1210','Acmella Oleracea Extract','Acmella Oleracea Extract',3,3),
  ('ING1211','Polyglyceryl-6 Distearate','Polyglyceryl-6 Distearate; POLYGLYCERYL-6 DISTEARATE',3,3),
  ('ING1212','Polyglyceryl-3 Beeswax','Polyglyceryl-3 Beeswax; POLYGLYCERYL-3 BEESWAX',3,3),
  ('ING1213','Amodimethicone/ Silsesquioxane Copolymer','Amodimethicone/ Silsesquioxane Copolymer; Amodimethicone/Silsesquioxane Copolymer',2,2),
  ('ING1214','Alcohol Denatured.','Alcohol Denatured.; alcohol denatured',2,2),
  ('ING1215','Guar Hydroxypro pyltrimonium Chloride','Guar Hydroxypro pyltrimonium Chloride; Guar Hydroxypro-pyltrimonium Chloride',2,2),
  ('ING1216','Polyquaternium-59','Polyquaternium-59',2,2),
  ('ING1217','Chelidonium Majus Extract','Chelidonium Majus Extract',2,2),
  ('ING1218','Passiflora Edulis Fruit Extract','Passiflora Edulis Fruit Extract',2,2),
  ('ING1219','Lauryl Methyl Gluceth-10 Hydroxypropyldimonium Chloride','Lauryl Methyl Gluceth-10 Hydroxypropyldimonium Chloride',2,2),
  ('ING1220','PEG-150 Pentaerythrityl Tetrastearate','PEG-150 Pentaerythrityl Tetrastearate',2,2),
  ('ING1221','Steareth-4','Steareth-4',2,2),
  ('ING1222','SILICONE QUATERNIUM','SILICONE QUATERNIUM; Silicone Quaternium',2,2),
  ('ING1223','Acetamidoethoxyethanol','Acetamidoethoxyethanol; ACETAMIDOETHOXYETHANOL',2,2),
  ('ING1224','Glycine Soya Protein','Glycine Soya Protein',2,2),
  ('ING1225','CI 60730','CI 60730',2,2),
  ('ING1226','Bis-Diisopropanolamino-PG-Propyl Disiloxane/Bis-Vinyl Dimethicone Copolymer','Bis-Diisopropanolamino-PG-Propyl Disiloxane/Bis-Vinyl Dimethicone Copolymer',2,2),
  ('ING1227','Hydrolyzed Wheat Proteins','Hydrolyzed Wheat Proteins',2,2),
  ('ING1228','Hydrolyzed Oats Proteins','Hydrolyzed Oats Proteins',2,2),
  ('ING1229','Vaccinium Myrtillus Fruit Leaf (Bilberry) Extract','Vaccinium Myrtillus Fruit Leaf (Bilberry) Extract; VACCINIUM MYRTILLUS FRUIT/LEAF EXTRACT',2,2),
  ('ING1230','Acer Saccharum (Sugar Maple) Extract','Acer Saccharum (Sugar Maple) Extract; ACER SACCHARUM (SUGAR MAPLE) EXTRACT',2,2),
  ('ING1231','argania spinosa oil/argania spinosa kernel oil','argania spinosa oil/argania spinosa kernel oil; ARGANIA SPINOSA OIL/ARGANIA SPINOSA KERNEL OIL',2,2),
  ('ING1232','Saccharum Officinarum Extract / Sugarcane Extract','Saccharum Officinarum Extract / Sugarcane Extract; SACCHARUM OFFICINARUM EXTRACT / SUGARCANE EXTRACT',2,2),
  ('ING1233','Butyrospermum Parkii Butter / Shea Butter','Butyrospermum Parkii Butter / Shea Butter; butyrospermum parkii butter / shea butter',2,2),
  ('ING1234','Ci 15985 / Yellow 6','Ci 15985 / Yellow 6; CI 15985 / YELLOW 6',2,2),
  ('ING1235','Distarch Phosphate','Distarch Phosphate',2,2),
  ('ING1236','Ci 60730/ Ext. Violet 2','Ci 60730/ Ext. Violet 2; CI 60730 / EXT. VIOLET 2',2,2),
  ('ING1237','LANOLIN ACID','LANOLIN ACID; Lanolin Acid',2,2),
  ('ING1238','ORYZA SATIVA (RICE) GERM OIL','ORYZA SATIVA (RICE) GERM OIL; Oryza Sativa (Rice) Germ Oil',2,2),
  ('ING1239','GRAPE (VITIS VINIFERA) SEED OIL','GRAPE (VITIS VINIFERA) SEED OIL; Grape Seed Oil',2,2),
  ('ING1240','EVENING PRIMROSE (OENOTHERA BIENNIS) OIL','EVENING PRIMROSE (OENOTHERA BIENNIS) OIL; Evening Primrose (Oenothera Biennis) Oil',2,2),
  ('ING1241','Panicum miliaceum Seed Extract','Panicum miliaceum Seed Extract',2,2),
  ('ING1242','Equisetum arvense Herb Extract','Equisetum arvense Herb Extract',2,2),
  ('ING1243','Humulus lupulus Cone Extract','Humulus lupulus Cone Extract',2,2),
  ('ING1244','Creatine','Creatine; CREATINE',2,2),
  ('ING1245','Arctium Lappa (Burdock) Oil','Arctium Lappa (Burdock) Oil',2,2),
  ('ING1246','Gardenia Tahitensis Flower Extract','Gardenia Tahitensis Flower Extract; Gardenia tahitensis flower extract',2,2),
  ('ING1247','Lilium candidum bulb extract','Lilium candidum bulb extract; Lilium Candidum Bulb Extract',2,2),
  ('ING1248','Aphanothece Sacrum Polysaccharides','Aphanothece Sacrum Polysaccharides',2,2),
  ('ING1249','glucosamine HCL','glucosamine HCL; Glucosamine HCl',2,2),
  ('ING1250','citrulline','citrulline; Citrulline',2,2),
  ('ING1251','Ceramide-2','Ceramide-2; Ceramide 2',2,2),
  ('ING1252','sodium benzoat','sodium benzoat; SODIUM BENZOAT',2,2),
  ('ING1253','TRAMETES VERSICOLOR EXTRACT','TRAMETES VERSICOLOR EXTRACT; Trametes Versicolor Extract',2,2),
  ('ING1254','bis-isobutyl peg/ppg-20/35/amodimethicone copolymer','bis-isobutyl peg/ppg-20/35/amodimethicone copolymer; Bis-Isobutyl Peg/Ppg-20/35/ Amodimethicone Copolymer',2,2),
  ('ING1255','vp/dmapa acrylates copolymer','vp/dmapa acrylates copolymer',2,2),
  ('ING1256','benzalkonium chloride','benzalkonium chloride',2,2),
  ('ING1257','Rice Amino Acids','Rice Amino Acids',2,2),
  ('ING1258','Bambusa Arundinacea Leaf Extract','Bambusa Arundinacea Leaf Extract',2,2),
  ('ING1259','Cetrimonium Methosulfate','Cetrimonium Methosulfate',2,2),
  ('ING1260','astrocaryum murumuru seed butter','astrocaryum murumuru seed butter',2,2),
  ('ING1261','butylphenyl methylpropinal','butylphenyl methylpropinal',2,2),
  ('ING1262','CI 77288 / CHROMIUM OXIDE GREENS','CI 77288 / CHROMIUM OXIDE GREENS; Ci 77288 / Chromium Oxide Greens',2,2),
  ('ING1263','sodium cocoate','sodium cocoate; Sodium Cocoate',2,2),
  ('ING1264','Hydroxypropyltrimonium hydrolyzed corn starch','Hydroxypropyltrimonium hydrolyzed corn starch',2,2),
  ('ING1265','Hypnea musciformis extract','Hypnea musciformis extract',2,2),
  ('ING1266','CI 42051','CI 42051',2,2),
  ('ING1267','Polyquaternium-6','Polyquaternium-6',2,2),
  ('ING1268','Capsicum Annuum Fruit Extract','Capsicum Annuum Fruit Extract',2,2),
  ('ING1269','CI 40800','CI 40800',2,2),
  ('ING1270','Kappaphycus Alvarezii Extract','Kappaphycus Alvarezii Extract',2,2),
  ('ING1271','C14-16 Olefin Sulfonate','C14-16 Olefin Sulfonate',2,2),
  ('ING1272','Prunus Persica (Peach) Kernel Oil','Prunus Persica (Peach) Kernel Oil; PRUNUS PERSICA (PEACH) KERNEL OIL',2,2),
  ('ING1273','Punica Granatum (Pomegranate) Peel Extract','Punica Granatum (Pomegranate) Peel Extract',2,2),
  ('ING1274','cucumis sativus fruit extract /cucumber fruit extract','cucumis sativus fruit extract /cucumber fruit extract; CUCUMIS SATIVUS FRUIT EXTRACT / CUCUMBER FRUIT EXTRACT',2,2),
  ('ING1275','marine collagen','marine collagen; Marine Collagen',2,2),
  ('ING1276','Wheat Germ Oil','Wheat Germ Oil; Wheat Germ Oil*',2,2),
  ('ING1277','Didecyldimonium Chloride','Didecyldimonium Chloride; didecyldimonium chloride',2,2),
  ('ING1278','Polyglyceryl-10 Pentastearate','Polyglyceryl-10 Pentastearate',2,2),
  ('ING1279','PEG-40 Hydrogenated Castor Oil Pca Isostearate','PEG-40 Hydrogenated Castor Oil Pca Isostearate',2,2),
  ('ING1280','Propylene Glycol Laurate','Propylene Glycol Laurate; PROPYLENE GLYCOL LAURATE',2,2),
  ('ING1281','Ceteareth-60 Myristyl Glycol','Ceteareth-60 Myristyl Glycol',2,2),
  ('ING1282','Cymbopogon Schoenanthus Oil','Cymbopogon Schoenanthus Oil',2,2),
  ('ING1283','PEG/ PPG/ Polybutylene Glycol-8/ 5/ 3 Glycerin','PEG/ PPG/ Polybutylene Glycol-8/ 5/ 3 Glycerin; peg/ppg/polybutylene glycol-8/5/3 glycerin',2,2),
  ('ING1284','Polyglyceryl-6 Polyricinoleate','Polyglyceryl-6 Polyricinoleate; POLYGLYCERYL-6 POLYRICINOLEATE',2,2),
  ('ING1285','PEG-30 Phytosterol','PEG-30 Phytosterol',2,2),
  ('ING1286','Myrothamnus Flabellifolia Leaf Extract','Myrothamnus Flabellifolia Leaf Extract',2,2),
  ('ING1287','Helianthus Annuus (Sunflower) Oil','Helianthus Annuus (Sunflower) Oil',2,2),
  ('ING1288','Tridecane','Tridecane',2,2),
  ('ING1289','Pseudozyma Epicola/Argania Spinosa Kernel Oil Ferment Filtrate','Pseudozyma Epicola/Argania Spinosa Kernel Oil Ferment Filtrate',2,2),
  ('ING1290','Quaternium 95','Quaternium 95; Quaternium-95',2,2),
  ('ING1291','Musa Sapientum (Banana) Fruit Extract','Musa Sapientum (Banana) Fruit Extract; Musa Sapientum (banana) Fruit Extract',2,2),
  ('ING1292','pentapeptide-29 cysteinamide','pentapeptide-29 cysteinamide',2,2),
  ('ING1293','pentapeptide-30 cysteinamide','pentapeptide-30 cysteinamide',2,2),
  ('ING1294','tetrapeptide-28 argininamide','tetrapeptide-28 argininamide',2,2),
  ('ING1295','tetrapeptide-29 argininamide','tetrapeptide-29 argininamide',2,2),
  ('ING1296','tricetylmonium chloride','tricetylmonium chloride',2,2),
  ('ING1297','trisodium sulfosuccinate','trisodium sulfosuccinate',2,2),
  ('ING1298','Cl19140','Cl19140; CL19140',2,2),
  ('ING1299','Sodium Cocoyl Hydrolyzed Amaranth Protein','Sodium Cocoyl Hydrolyzed Amaranth Protein',2,2),
  ('ING1300','Cucumis Melo Cantalupensis (Melon) Fruit Extract','Cucumis Melo Cantalupensis (Melon) Fruit Extract; cucumis melo cantalupensis (cantaloupe) fruit extract',2,2),
  ('ING1301','Linoleamidopropyl PG-Dimonium Chloride Phosphate','Linoleamidopropyl PG-Dimonium Chloride Phosphate; Linoleamidopropyl Pg-dimonium Chloride Phosphate',2,2),
  ('ING1302','PEG-8 Dimethicone','PEG-8 Dimethicone',2,2),
  ('ING1303','Bis-PEG-12 Dimethicone','Bis-PEG-12 Dimethicone',2,2),
  ('ING1304','Coffea arabica (coffee) seed oil*','Coffea arabica (coffee) seed oil*; COFFEA ARABICA (COFFEE) SEED OIL',2,2),
  ('ING1305','Lauroyl/Myristoyl Methyl Glucamide','Lauroyl/Myristoyl Methyl Glucamide',2,2),
  ('ING1306','Citrus Aurantium Bergamia Fruit Extract','Citrus Aurantium Bergamia Fruit Extract; Citrus Aurantium Bergamia (Bergamot) Fruit Extract',2,2),
  ('ING1307','Triticum Vulgare (Wheat) Protein)','Triticum Vulgare (Wheat) Protein); Triticum Vulgare (Wheat) Protein',2,2),
  ('ING1308','Opuntia Ficus-Indica Stem Extract','Opuntia Ficus-Indica Stem Extract',2,2),
  ('ING1309','Sodium Glutamate','Sodium Glutamate; SODIUM GLUTAMATE',2,2),
  ('ING1310','Hydrolized Wheat Protein','Hydrolized Wheat Protein',2,2),
  ('ING1311','LAURETH-7 CITRATE','LAURETH-7 CITRATE',2,2),
  ('ING1312','Cocos Nucifera Fruit Juice','Cocos Nucifera Fruit Juice; Cocos Nucifera (Coconut) Fruit Juice',2,2),
  ('ING1313','thiamine chloride','thiamine chloride; thiaminе chloride',2,2),
  ('ING1314','HYDROLYZED PEA','HYDROLYZED PEA; Hydrolyzed Pea',2,2),
  ('ING1315','PENTAPEPTIDE-31','PENTAPEPTIDE-31; Pentapeptide-31',2,2),
  ('ING1316','POLYQUATERNIUM-71','POLYQUATERNIUM-71; Polyquaternium-71',2,2),
  ('ING1317','GRATELOUPIA ELLIPTICA (RED KOREAN SEAWEED) EXTRACT','GRATELOUPIA ELLIPTICA (RED KOREAN SEAWEED) EXTRACT; Grateloupia Elliptica (Red Korean Seaweed) Extract',2,2),
  ('ING1318','CITRUS GRANDIS (GRAPEFRUIT) SEED EXTRACT','CITRUS GRANDIS (GRAPEFRUIT) SEED EXTRACT; Citrus Grandis (Grapefruit) Seed Extract',2,2),
  ('ING1319','SODIUM METHYL OLEOYL TAURATE','SODIUM METHYL OLEOYL TAURATE; Sodium Methyl Oleoyl Taurate',2,2),
  ('ING1320','Citrus Aurantifolia Fruit Extract','Citrus Aurantifolia Fruit Extract',2,2),
  ('ING1321','Sodium Myreth Sulfate','Sodium Myreth Sulfate; SODIUM MYRETH SULFATE',2,2),
  ('ING1322','Withania Somnifera (Ashwagandha) Herb Extract','Withania Somnifera (Ashwagandha) Herb Extract',2,2),
  ('ING1323','Emblica Officinalis (Amla) Fruit Extract','Emblica Officinalis (Amla) Fruit Extract; Emblica Officinalis Fruit Extract',2,2),
  ('ING1324','Acacia Concinna (Shikakai) Fruit Extract','Acacia Concinna (Shikakai) Fruit Extract; Acacia Concinna Fruit Extract',2,2),
  ('ING1325','Levulinic Acid**','Levulinic Acid**; Levulinic Acid',2,2),
  ('ING1326','Potassium laureth-4 carboxylate','Potassium laureth-4 carboxylate; Potassium Laureth-4 Carboxylate',2,2),
  ('ING1327','ANISE ALCOHOL','ANISE ALCOHOL; Anise Alcohol',2,2),
  ('ING1328','Yogurt Powder','Yogurt Powder',2,2),
  ('ING1329','PEG-90 Glyceryl Isostearate','PEG-90 Glyceryl Isostearate; PEG-90 GLYCERYL ISOSTEARATE',2,2),
  ('ING1330','Bamboo Charcoal Powder','Bamboo Charcoal Powder',2,2),
  ('ING1331','Coconut Alcohol','Coconut Alcohol',2,2),
  ('ING1332','CALCIUM GLYCEROPHOSPHATE','CALCIUM GLYCEROPHOSPHATE',2,2),
  ('ING1333','Propylene Glycol Dicaprylate','Propylene Glycol Dicaprylate',2,2),
  ('ING1334','Citrus Tangerina (Tangerine) Peel Oil','Citrus Tangerina (Tangerine) Peel Oil; CITRUS TANGERINA PEEL OIL',2,2),
  ('ING1335','CAPRYLOYL GLYCERIN/SEBACIC ACID COPOLYMER','CAPRYLOYL GLYCERIN/SEBACIC ACID COPOLYMER; Capryloyl Glycerin/Sebacic Acid Copolymer',2,2),
  ('ING1336','Aloe Barbadensis Leaf Juice Powder','Aloe Barbadensis Leaf Juice Powder; ALOE BARBADENSIS LEAF JUICE POWDER',2,2),
  ('ING1337','THIAMINE','THIAMINE; Thiamine',2,2),
  ('ING1338','PHOSPHORIC ACID','PHOSPHORIC ACID; phosphoric acid',2,2),
  ('ING1339','CI 28440','CI 28440',2,2),
  ('ING1340','Oenocarpus Bataua (Rahua Ungurahua) Oil','Oenocarpus Bataua (Rahua Ungurahua) Oil',2,2),
  ('ING1341','Santalum Album (Sandalwood) Oil','Santalum Album (Sandalwood) Oil',2,2),
  ('ING1342','Amyris Balsamifera Bark Oil','Amyris Balsamifera Bark Oil',2,2),
  ('ING1343','Ferula Galbaniflua (Galbanum) Resin Oil','Ferula Galbaniflua (Galbanum) Resin Oil',2,2),
  ('ING1344','Cucumis Sativus (Cucumber) Extract','Cucumis Sativus (Cucumber) Extract',2,2),
  ('ING1345','Hydrolyzed Adansonia Digitata Extract','Hydrolyzed Adansonia Digitata Extract',2,2),
  ('ING1346','Behenyl/Octyldodecyl Propanediol Citrate Crosspolymer','Behenyl/Octyldodecyl Propanediol Citrate Crosspolymer',2,2),
  ('ING1347','Euphorbia Cerifera (Candelilla) Wax\Candelilla Cera\Cire De Candelilla','Euphorbia Cerifera (Candelilla) Wax\Candelilla Cera\Cire De Candelilla',2,2),
  ('ING1348','Polyglyceryl-10 Pentaoleate','Polyglyceryl-10 Pentaoleate',2,2),
  ('ING1349','SODIUM LAUROYL OAT AMINO ACIDS','SODIUM LAUROYL OAT AMINO ACIDS; sodium lauroyl oat amino acids',2,2),
  ('ING1350','Calcium Chloride','Calcium Chloride',2,2),
  ('ING1351','Hypericum Perforatum Flower/Leaf/Stem Extract','Hypericum Perforatum Flower/Leaf/Stem Extract',2,2),
  ('ING1352','Methylsilanol Hydroxyproline Aspartate','Methylsilanol Hydroxyproline Aspartate',2,2),
  ('ING1353','Larix Europaea Wood Extract','Larix Europaea Wood Extract; Larix Europaea (European Larch) Wood Extract',2,2),
  ('ING1354','Isopropanolamine','Isopropanolamine',2,2),
  ('ING1355','Zinc Chloride','Zinc Chloride',2,2),
  ('ING1356','Glycol Stearate','Glycol Stearate',2,2),
  ('ING1357','Hydrogenated Rapeseed Alcohol','Hydrogenated Rapeseed Alcohol; HYDROGENATED RAPESEED ALCOHOL',2,2),
  ('ING1358','Ananas Sativus (Pineapple) Powder','Ananas Sativus (Pineapple) Powder',2,2),
  ('ING1359','Aesculus hippocastanum extract','Aesculus hippocastanum extract; Aesculus Hippocastanum Extract',2,2),
  ('ING1360','Citrus Paradisi Fruit Extract','Citrus Paradisi Fruit Extract',2,2),
  ('ING1361','CROTON LECHLERI RESIN EXTRACT','CROTON LECHLERI RESIN EXTRACT; Croton Lechleri Resin Extract',2,2),
  ('ING1362','HYDROLYZED RYE PROTEIN','HYDROLYZED RYE PROTEIN; Hydrolyzed Rye Protein',2,2),
  ('ING1363','SODIUM STARCH OCTENYLSUCCINATE','SODIUM STARCH OCTENYLSUCCINATE; Sodium Starch Octenylsuccinate',2,2),
  ('ING1364','olea europaea oil / olive fruit oil','olea europaea oil / olive fruit oil',2,2),
  ('ING1365','Ceratonia Siliqua Seed Extract','Ceratonia Siliqua Seed Extract; Ceratonia Siliqua (Carob) Seed Extract',2,2),
  ('ING1366','Tocopherols Blend','Tocopherols Blend',2,2),
  ('ING1367','CANANGA ODORATA FLOWER OIL','CANANGA ODORATA FLOWER OIL; Cananga Odorata Flower Oil',2,2),
  ('ING1368','PANTENOL','PANTENOL',2,2),
  ('ING1369','Potato Starch Modified','Potato Starch Modified',2,2),
  ('ING1370','Frankincense Extract','Frankincense Extract',2,2),
  ('ING1371','Aloe Barbadensis Extract','Aloe Barbadensis Extract',2,2),
  ('ING1372','Polyglyceryl-3 Caprate','Polyglyceryl-3 Caprate',2,2),
  ('ING1373','Ammonium Laureth Sulfate','Ammonium Laureth Sulfate',2,2),
  ('ING1374','Sodium Lauryl Methylaminopropionate','Sodium Lauryl Methylaminopropionate',2,2),
  ('ING1375','Ammonium Sulfate','Ammonium Sulfate',2,2),
  ('ING1376','Anacardium Occidentale (Cashew) Extract','Anacardium Occidentale (Cashew) Extract; Anacardium Occidentale Extract',2,2),
  ('ING1377','Citrus Grandis (Grapefruit) Fruit Extract','Citrus Grandis (Grapefruit) Fruit Extract',2,2),
  ('ING1378','Citrus Clementina Peel Oil','Citrus Clementina Peel Oil',2,2),
  ('ING1379','Gaultheria Procumbens Leaf Oil','Gaultheria Procumbens Leaf Oil',2,2),
  ('ING1380','panicum miliaceum extract','panicum miliaceum extract; Panicum miliaceum extract',2,2),
  ('ING1381','glyceryl cocoate','glyceryl cocoate',2,2),
  ('ING1382','nature aroma','nature aroma',2,2),
  ('ING1383','Ceteareth-23','Ceteareth-23',2,2),
  ('ING1384','Aqua with infusions of Organic Robina Pseudoacacia Flower Extract','Aqua with infusions of Organic Robina Pseudoacacia Flower Extract',2,2),
  ('ING1385','xantan gum','xantan gum; XANTAN GUM',2,2),
  ('ING1386','ARGANIA SPINOSA EXTRACT','ARGANIA SPINOSA EXTRACT; Argania Spinosa Extract',2,2),
  ('ING1387','Glycerin Vegetable','Glycerin Vegetable; Glycerin Vegetable*',2,2),
  ('ING1388','Theobroma cacao (cocoa) seed butter','Theobroma cacao (cocoa) seed butter; THEOBROMA CACAO (COCOA) SEED BUTTER',2,2),
  ('ING1389','Hydrogenated coconut oil','Hydrogenated coconut oil; Hydrogenated Coconut Oil',2,2),
  ('ING1390','Dichlorobenzyl alcohol','Dichlorobenzyl alcohol; dichlorobenzyl alcohol',2,2),
  ('ING1391','Polyquaternium-47','Polyquaternium-47',2,2),
  ('ING1392','Avena Sativa (Oat) Protein Extract','Avena Sativa (Oat) Protein Extract',2,2),
  ('ING1393','Fucoidan','Fucoidan',2,2),
  ('ING1394','Malva Sylvestris Flower Extract (Organic Mallow Extract)','Malva Sylvestris Flower Extract (Organic Mallow Extract); Malva Sylvestris (Mallow) Flower Extract',2,2),
  ('ING1395','Arginine/Lysine Polypeptide','Arginine/Lysine Polypeptide; Arginine / Lysine Polypeptide',2,2),
  ('ING1396','Deionised water','Deionised water',2,2),
  ('ING1397','PG-HYDROXYETHYLCELLULOSE COCODIMONIUM CHLORIDE','PG-HYDROXYETHYLCELLULOSE COCODIMONIUM CHLORIDE',2,2),
  ('ING1398','MANGIFERA INDICA (MANGO) FRUIT EXTRACT','MANGIFERA INDICA (MANGO) FRUIT EXTRACT',2,2),
  ('ING1399','3-DIOL','3-DIOL; 3-diol',2,2),
  ('ING1400','Tetrahydroxypropyl Ethylenediamine','Tetrahydroxypropyl Ethylenediamine',2,2),
  ('ING1401','Propane','Propane',2,2),
  ('ING1402','Disperse Violet 1','Disperse Violet 1; Disperse Violet-1',2,2),
  ('ING1403','Nelumbium Speciosum Flower Extract','Nelumbium Speciosum Flower Extract',2,2),
  ('ING1404','Angelica Gigas Root Extract','Angelica Gigas Root Extract',2,2),
  ('ING1405','Swertia Japonica Extract','Swertia Japonica Extract',2,2),
  ('ING1406','Plantago Asiatica Extract','Plantago Asiatica Extract',2,2),
  ('ING1407','Opuntia Ficus-Indica Fruit Extract','Opuntia Ficus-Indica Fruit Extract',2,2),
  ('ING1408','Cornus Officinalis Fruit Extract','Cornus Officinalis Fruit Extract',2,2),
  ('ING1409','Poria Cocos Sclerotium Extract','Poria Cocos Sclerotium Extract',2,2),
  ('ING1410','Polyvinylpyrrolidone','Polyvinylpyrrolidone',2,2),
  ('ING1411','Benzophenone-5','Benzophenone-5',2,2),
  ('ING1412','Helianthus Annuus Seed Oil / Helianthus Annuus (Sunflower) Seed Oil','Helianthus Annuus Seed Oil / Helianthus Annuus (Sunflower) Seed Oil',2,2),
  ('ING1413','Bixa Orellana Seed Extract','Bixa Orellana Seed Extract',2,2),
  ('ING1414','dimethicon','dimethicon',2,2),
  ('ING1415','phospholipides','phospholipides; Phospholipides',2,2),
  ('ING1416','AMMONIUM LACTATE','AMMONIUM LACTATE; Ammonium Lactate',2,2),
  ('ING1417','Propyltrimoniumchloride Acrylamide/Dimethylacrylamide Copolymer','Propyltrimoniumchloride Acrylamide/Dimethylacrylamide Copolymer; PROPYLTRIMONIUMCHLORIDE ACRYLAMIDE/DIMETHYLACRYLAMIDE COPOLYMER',2,2),
  ('ING1418','ISOSTEARYL ALCOHOL','ISOSTEARYL ALCOHOL',2,3),
  ('ING1419','Sambucus Nigra Fruit Extract','Sambucus Nigra Fruit Extract; Sambucus Nigra (Black Elderberry) Fruit Extract',2,2),
  ('ING1420','Polydextrose','Polydextrose',2,2),
  ('ING1421','Ecklonia Kurome Extract','Ecklonia Kurome Extract',2,2),
  ('ING1422','Caprylic/Capric/Myristic/Stearic Triglyceride','Caprylic/Capric/Myristic/Stearic Triglyceride',2,2),
  ('ING1423','Dimethyl Palmitamine','Dimethyl Palmitamine',2,2),
  ('ING1424','Polysilicone-19','Polysilicone-19',2,2),
  ('ING1425','Hydrolysed Silk','Hydrolysed Silk',2,2),
  ('ING1426','schinziophyton rautanenii kernel oil','schinziophyton rautanenii kernel oil; Schinziophyton Rautanenii Kernel Oil',2,2),
  ('ING1427','hydrogenated castor oil/sebacic acid copolymer','hydrogenated castor oil/sebacic acid copolymer; Hydrogenated Castor Oil/Sebacic Acid Copolymer',2,2),
  ('ING1428','polyquaternium-55','polyquaternium-55; Polyquaternium-55',2,2),
  ('ING1429','myristoyl/palmistoyl oxostearamide/arachamide mea','myristoyl/palmistoyl oxostearamide/arachamide mea',2,2),
  ('ING1430','glyceryl linoleate','glyceryl linoleate',2,2),
  ('ING1431','ocimum basilicum (basil) flower/leaf extract','ocimum basilicum (basil) flower/leaf extract; Ocimum Basilicum (Basil) Flower/Leaf Extract',2,2),
  ('ING1432','Lauryl Betaine','Lauryl Betaine',2,2),
  ('ING1433','Prunus Amygdalus Dulcis Seed Extract','Prunus Amygdalus Dulcis Seed Extract; Prunus Amygdalus Dulcis (Sweet Almond) Seed Extract',2,2),
  ('ING1434','Bis-(Isostearoyl/Oleoyl Isopropyl) Dimonium Methosulfate','Bis-(Isostearoyl/Oleoyl Isopropyl) Dimonium Methosulfate',2,2),
  ('ING1435','Epilobium Angustifolium Flower/Leaf/Stem Extract','Epilobium Angustifolium Flower/Leaf/Stem Extract; EPILOBIUM ANGUSTIFOLIUM FLOWER/LEAF/STEM EXTRACT',2,2),
  ('ING1436','Chamomilla Recutita (Matricaria) Flower/Leaf Extract','Chamomilla Recutita (Matricaria) Flower/Leaf Extract',2,2),
  ('ING1437','Sophora Root Extract','Sophora Root Extract',2,2),
  ('ING1438','Peony Root Extract','Peony Root Extract',2,2),
  ('ING1439','Zingiber officinale Rhizome Extract','Zingiber officinale Rhizome Extract',2,2),
  ('ING1440','Melissa officinalis Herb Extract','Melissa officinalis Herb Extract',2,2),
  ('ING1441','Artemisia Dracunculus Herb Extract','Artemisia Dracunculus Herb Extract',2,2),
  ('ING1442','Zinc Pyrithione','Zinc Pyrithione',2,2),
  ('ING1443','Malus Domestica (Apple) Fruit Cell Culture Extract','Malus Domestica (Apple) Fruit Cell Culture Extract',2,2),
  ('ING1444','Dipotassium Glycyrrhizinate','Dipotassium Glycyrrhizinate; Dipotassium glycyrrhizinate',2,2),
  ('ING1445','Soy Isoflavone**','Soy Isoflavone**',2,2),
  ('ING1446','Plankton Extract','Plankton Extract',2,2),
  ('ING1447','Silicone Quaternium-8','Silicone Quaternium-8',2,2),
  ('ING1448','Pelargonium Graveolens (Geranium) Oil*','Pelargonium Graveolens (Geranium) Oil*; Pelargonium Graveolens Oil',2,2),
  ('ING1449','Decolorized Aloe Vera (Aloe Barbadensis) (Leaf) Juice','Decolorized Aloe Vera (Aloe Barbadensis) (Leaf) Juice; Decolorized Aloe Vera (Aloe Barbadensis) (Leaf) Juice*',2,2),
  ('ING1450','Argan (Argania Spinosa) (Kernel) Oil*','Argan (Argania Spinosa) (Kernel) Oil*',2,2),
  ('ING1451','Rosemary (Rosmarinus Officinalis) (Leaf) Oil*','Rosemary (Rosmarinus Officinalis) (Leaf) Oil*',2,2),
  ('ING1452','Lemon (Citrus Limon) (Peel) Oil*','Lemon (Citrus Limon) (Peel) Oil*; Lemon (Citrus Medica Limonum) Oil',2,2),
  ('ING1453','Pumpkin (Cucurbita Pepo) (Seed) Oil*','Pumpkin (Cucurbita Pepo) (Seed) Oil*',2,2),
  ('ING1454','Rice (Oryza Sativa) (Bran) Extract','Rice (Oryza Sativa) (Bran) Extract; Rice Extract (7,778 ppm)',2,2),
  ('ING1455','Pantothenic Acid','Pantothenic Acid',2,2),
  ('ING1456','Saponins','Saponins; saponins',2,2),
  ('ING1457','Geranium Oil','Geranium Oil',2,2),
  ('ING1458','Aloe Barbadensis (Aloe Vera) Leaf Gel','Aloe Barbadensis (Aloe Vera) Leaf Gel',2,2),
  ('ING1459','TETRAMETHYL ACETYLOCTAHYDRONAPHTHALENES','TETRAMETHYL ACETYLOCTAHYDRONAPHTHALENES',2,2),
  ('ING1460','BAMBUSA VULGARIS EXTRACT','BAMBUSA VULGARIS EXTRACT; Bambusa Vulgaris (Bamboo) Extract',2,2),
  ('ING1461','Schisandra Chinensis Fruit Extract','Schisandra Chinensis Fruit Extract; Schisandra Chinensis Fruit Extract(9%)',2,2),
  ('ING1462','Amodimethicone/Morpholinomethyl Silsesquioxane Copolymer','Amodimethicone/Morpholinomethyl Silsesquioxane Copolymer',2,2),
  ('ING1463','Carvone','Carvone; CARVONE',2,2),
  ('ING1464','Mentha Viridis (Spearmint) Leaf Oil','Mentha Viridis (Spearmint) Leaf Oil',2,2),
  ('ING1465','PEG-20 methyl glucose sesquistearate','PEG-20 methyl glucose sesquistearate; PEG-20 METHYL GLUCOSE SESQUISTEARATE',2,2),
  ('ING1466','Hamamelis virginiana bark/leaf extract','Hamamelis virginiana bark/leaf extract; Hamamelis Virginiana (Witch Hazel) Bark/leaf Extract',2,2),
  ('ING1467','Terminalia Ferdinandiana Fruit Extract','Terminalia Ferdinandiana Fruit Extract',2,2),
  ('ING1468','DIAMINOPYRIMIDINE OXIDE','DIAMINOPYRIMIDINE OXIDE',2,2),
  ('ING1469','PHYTOSTERYL OLEATE','PHYTOSTERYL OLEATE; Phytosteryl Oleate',2,2),
  ('ING1470','C13-16 Isoalkane','C13-16 Isoalkane',2,2),
  ('ING1471','AMORPHOPHALLUS KONJAC ROOT POWDER','AMORPHOPHALLUS KONJAC ROOT POWDER; Amorphophallus Konjac Root Powder',2,2),
  ('ING1472','SODIUM OLIVAMPHOACETATE','SODIUM OLIVAMPHOACETATE',2,2),
  ('ING1473','SODIUM COCOYL HYDROLYZED WHEAT PROTEIN','SODIUM COCOYL HYDROLYZED WHEAT PROTEIN',2,2),
  ('ING1474','MORINGA OLEIFERA SEED EXTRACT','MORINGA OLEIFERA SEED EXTRACT; Moringa Oleifera Seed Extract',2,2),
  ('ING1475','Polyglyceryl-3 Ricinoleate','Polyglyceryl-3 Ricinoleate',2,2),
  ('ING1476','Menthyl Ethylamido Oxalate','Menthyl Ethylamido Oxalate',2,2),
  ('ING1477','Trometamine','Trometamine',2,2),
  ('ING1478','Milk Lipids','Milk Lipids',2,2),
  ('ING1479','Disodium Phenyl Dibenzimidazole Tetrasulfonate','Disodium Phenyl Dibenzimidazole Tetrasulfonate',2,2),
  ('ING1480','Dipropylene Glycol Dibenzoate','Dipropylene Glycol Dibenzoate',2,2),
  ('ING1481','Polypodium Leucotomos Leaf Extract','Polypodium Leucotomos Leaf Extract',2,2),
  ('ING1482','Ethylhexyl Ferulate','Ethylhexyl Ferulate',2,2),
  ('ING1483','Caffeic Acid','Caffeic Acid',2,2),
  ('ING1484','Physalis Angulata Extract','Physalis Angulata Extract',2,2),
  ('ING1485','Ceteareth-25','Ceteareth-25',2,2),
  ('ING1486','Melanin','Melanin',2,2),
  ('ING1487','Hydrolyzed Wheat Protein/PVP Crosspolymer','Hydrolyzed Wheat Protein/PVP Crosspolymer; Hydrolyzed Wheat Protein/ PVP Crosspolymer',2,2),
  ('ING1488','PPG-15 Stearyl Ether Benzoate','PPG-15 Stearyl Ether Benzoate',2,2),
  ('ING1489','Disodium Ethylene Dicocamide PEG-15 Disulfate','Disodium Ethylene Dicocamide PEG-15 Disulfate',2,2),
  ('ING1490','Phytosphingosine HCL','Phytosphingosine HCL; Phytosphingosine Hcl',2,2),
  ('ING1491','Arabidopsis Thaliana Extract','Arabidopsis Thaliana Extract',2,2),
  ('ING1492','Panthenyl Triacetate','Panthenyl Triacetate',2,2),
  ('ING1493','Oxothiazolidine','Oxothiazolidine',2,2),
  ('ING1494','Oleyl Alcohol','Oleyl Alcohol',2,2),
  ('ING1495','Methylmethionine','Methylmethionine',2,2),
  ('ING1496','C20-22 Alkyl Phosphate','C20-22 Alkyl Phosphate',2,2),
  ('ING1497','Sodium Aсrylate','Sodium Aсrylate; Sodium Acrylate',2,2),
  ('ING1498','Pyrus Communis (pear) Fruit Extract','Pyrus Communis (pear) Fruit Extract; PYRUS COMMUNIS (PEAR) FRUIT EXTRACT',2,2),
  ('ING1499','Prunus Domestica Fruit Extract','Prunus Domestica Fruit Extract; PRUNUS DOMESTICA FRUIT EXTRACT',2,2),
  ('ING1500','bis-ethylhexyloxyphenol Methoxyphenyltriazine','bis-ethylhexyloxyphenol Methoxyphenyltriazine; Bis- Ethylhexyloxyphenol Methoxyphenyltriazine',2,2)
ON CONFLICT (ingredient_id) DO UPDATE SET canonical_name=EXCLUDED.canonical_name, aliases=EXCLUDED.aliases;