INSERT INTO ingredients_dictionary (ingredient_id,canonical_name,aliases,product_count,occurrence_count)
VALUES
  ('ING2001','COCAMIDOPROPYL PG-DIMONIUM CHLORIDE PHOSPHATE','COCAMIDOPROPYL PG-DIMONIUM CHLORIDE PHOSPHATE',1,1),
  ('ING2002','POTASSIUM LACTATE','POTASSIUM LACTATE',1,1),
  ('ING2003','ETHANOLAMINE','ETHANOLAMINE',1,1),
  ('ING2004','Cetyl Alcochol','Cetyl Alcochol',1,1),
  ('ING2005','Hydroxystearyl Cetyl Ether','Hydroxystearyl Cetyl Ether',1,1),
  ('ING2006','Magnesium Acetate','Magnesium Acetate',1,1),
  ('ING2007','Butylparaben','Butylparaben',1,1),
  ('ING2008','Violet 43','Violet 43',1,1),
  ('ING2009','Trimethylglycine','Trimethylglycine',1,1),
  ('ING2010','PEG-4 Rapeseedfmid','PEG-4 Rapeseedfmid',1,1),
  ('ING2011','MIPA Lauryl Sulfate','MIPA Lauryl Sulfate',1,1),
  ('ING2012','Laureth – 10','Laureth – 10',1,1),
  ('ING2013','Bambusa Vulgaris Sap Extract','Bambusa Vulgaris Sap Extract',1,1),
  ('ING2014','Phalaenopsis Amabilis Extract','Phalaenopsis Amabilis Extract',1,1),
  ('ING2015','Ethyl Macadamiate','Ethyl Macadamiate',1,1),
  ('ING2016','Jasminum Grandiflorum (Jasmine) Flower Extract','Jasminum Grandiflorum (Jasmine) Flower Extract',1,1),
  ('ING2017','Eclipta Alba (Bhringraj) Extract','Eclipta Alba (Bhringraj) Extract',1,1),
  ('ING2018','Hibiscus Rosa-Sinensis (Hibiscus) Flower Extract','Hibiscus Rosa-Sinensis (Hibiscus) Flower Extract',1,1),
  ('ING2019','Abrus Precatorius (Gunja) Seed Extract','Abrus Precatorius (Gunja) Seed Extract',1,1),
  ('ING2020','Glycyrrhiza Glabra (Licorice) Stem Extract','Glycyrrhiza Glabra (Licorice) Stem Extract',1,1),
  ('ING2021','Rubia Cordifolia (Manjishtha) Stem Extract','Rubia Cordifolia (Manjishtha) Stem Extract',1,1),
  ('ING2022','Tribulus Terrestris (Gokharu) Fruit Extract','Tribulus Terrestris (Gokharu) Fruit Extract',1,1),
  ('ING2023','Trigonella Foenum (Fenugreek) Seed Extract','Trigonella Foenum (Fenugreek) Seed Extract',1,1),
  ('ING2024','Terminalia Bellirica (Beheda) Fruit Extract','Terminalia Bellirica (Beheda) Fruit Extract',1,1),
  ('ING2025','Terminalia Chebula (Haritaki) Fruit Extract','Terminalia Chebula (Haritaki) Fruit Extract',1,1),
  ('ING2026','Benzene Benzoate','Benzene Benzoate',1,1),
  ('ING2027','Jasmine Oil','Jasmine Oil',1,1),
  ('ING2028','Amla Extract','Amla Extract',1,1),
  ('ING2029','PCA Glyceryl Oleate','PCA Glyceryl Oleate',1,1),
  ('ING2030','Lawsonia Inermis (Henna) Leaf Extract','Lawsonia Inermis (Henna) Leaf Extract',1,1),
  ('ING2031','Starch Hydroxypropyltrimonium Chloride','Starch Hydroxypropyltrimonium Chloride',1,1),
  ('ING2032','HYDROGENATED FARNESENE','HYDROGENATED FARNESENE',1,1),
  ('ING2033','argilla/magnesium aluminum silicate','argilla/magnesium aluminum silicate',1,1),
  ('ING2034','montmorillonite','montmorillonite',1,1),
  ('ING2035','alphaisomethyl ionone','alphaisomethyl ionone',1,1),
  ('ING2036','Hexyldecyl Laurate','Hexyldecyl Laurate',1,1),
  ('ING2037','PEG-200 Glyceryl Palmate','PEG-200 Glyceryl Palmate',1,1),
  ('ING2038','Hydrolizated keratin','Hydrolizated keratin',1,1),
  ('ING2039','Rosmarinus Officinalis (Rosemary) Water','Rosmarinus Officinalis (Rosemary) Water',1,1),
  ('ING2040','Gyar Hydroxypropyltrimonium Chloride','Gyar Hydroxypropyltrimonium Chloride',1,1),
  ('ING2041','Curcuma Longa Extract','Curcuma Longa Extract',1,1),
  ('ING2042','Tocophery Acetate','Tocophery Acetate',1,1),
  ('ING2043','Inca Inchi Oil','Inca Inchi Oil',1,1),
  ('ING2044','CI 47000','CI 47000',1,1),
  ('ING2045','CI 26100','CI 26100',1,1),
  ('ING2046','ZEA MAYS GERM OIL / CORN GERM OIL','ZEA MAYS GERM OIL / CORN GERM OIL',1,1),
  ('ING2047','PENTACLETHRA MACROLOBA SEED OIL','PENTACLETHRA MACROLOBA SEED OIL',1,1),
  ('ING2048','GARDENIA TAITENSIS FLOWER','GARDENIA TAITENSIS FLOWER',1,1),
  ('ING2049','ROSA CANINA FLOWER EXTRACT','ROSA CANINA FLOWER EXTRACT',1,1),
  ('ING2050','SS','SS',1,1),
  ('ING2051','AMINOPROPYL TRIETHOXYSLANE','AMINOPROPYL TRIETHOXYSLANE',1,1),
  ('ING2052','MENTHA PIPERITA OIL/PEPPERMIN OIL','MENTHA PIPERITA OIL/PEPPERMIN OIL',1,1),
  ('ING2053','Avocado Oil Extracts','Avocado Oil Extracts',1,1),
  ('ING2054','Sodium Lauryl Ether Sulfate','Sodium Lauryl Ether Sulfate',1,1),
  ('ING2055','Dipalmoylisopropyl Dimonium Methosulfate','Dipalmoylisopropyl Dimonium Methosulfate',1,1),
  ('ING2056','Acrylates Crosspolymer','Acrylates Crosspolymer',1,1),
  ('ING2057','Dimer Dilinoleyl Dimer Dilinoleate','Dimer Dilinoleyl Dimer Dilinoleate',1,1),
  ('ING2058','Cl1940','Cl1940',1,1),
  ('ING2059','Cl17200','Cl17200',1,1),
  ('ING2060','Methylarachidic Acid','Methylarachidic Acid',1,1),
  ('ING2061','Chenopodium Quinoa Seed Extract','Chenopodium Quinoa Seed Extract',1,1),
  ('ING2062','Hydrolyzed Cicer Seed Extract','Hydrolyzed Cicer Seed Extract',1,1),
  ('ING2063','Abies Sibirica Oil','Abies Sibirica Oil',1,1),
  ('ING2064','Calcium Benzoate','Calcium Benzoate',1,1),
  ('ING2065','HYDROLYZED CHESTNUT EXTRACT','HYDROLYZED CHESTNUT EXTRACT',1,1),
  ('ING2066','Oligopeptide-74','Oligopeptide-74',1,1),
  ('ING2067','Oligopeptide-91','Oligopeptide-91',1,1),
  ('ING2068','Althaea Officinalis Root Extract','Althaea Officinalis Root Extract',1,1),
  ('ING2069','Polyquaternium 72','Polyquaternium 72',1,1),
  ('ING2070','Caprylic Acid','Caprylic Acid',1,1),
  ('ING2071','Caprylic/Capric Glycerides Polyglycerin-10 Esters','Caprylic/Capric Glycerides Polyglycerin-10 Esters',1,1),
  ('ING2072','Ethyl Oleate','Ethyl Oleate',1,1),
  ('ING2073','Olealkonium Chloride','Olealkonium Chloride',1,1),
  ('ING2074','Stearamine Oxide','Stearamine Oxide',1,1),
  ('ING2075','Sodium Bisulfite','Sodium Bisulfite',1,1),
  ('ING2076','SACCHAROMYCES/COPPER FERMENT','SACCHAROMYCES/COPPER FERMENT',1,1),
  ('ING2077','SACCHAROMYCES/IRON FERMENT','SACCHAROMYCES/IRON FERMENT',1,1),
  ('ING2078','SACCHAROMYCES/ZINC FERMENT','SACCHAROMYCES/ZINC FERMENT',1,1),
  ('ING2079','SACCHAROMYCES/MAGNESIUM FERMENT','SACCHAROMYCES/MAGNESIUM FERMENT',1,1),
  ('ING2080','SACCHAROMYCES/SILICON FERMENT','SACCHAROMYCES/SILICON FERMENT',1,1),
  ('ING2081','CI 16255','CI 16255',1,1),
  ('ING2082','Herbal Infusion of Camellia Sinensis (Green Tea) Leaf Extract','Herbal Infusion of Camellia Sinensis (Green Tea) Leaf Extract',1,1),
  ('ING2083','Organic Aloe Barbadensis Leaf Extract','Organic Aloe Barbadensis Leaf Extract',1,1),
  ('ING2084','Brassica Alcohol','Brassica Alcohol',1,1),
  ('ING2085','Brassicyl Isoleucinate Esylate','Brassicyl Isoleucinate Esylate',1,1),
  ('ING2086','1,3-Propanediol','1,3-Propanediol',1,1),
  ('ING2087','Artemisia Umbelliformis Flower Extract','Artemisia Umbelliformis Flower Extract',1,1),
  ('ING2088','nephelium lappaceum branch/fruit/leaf extract','nephelium lappaceum branch/fruit/leaf extract',1,1),
  ('ING2089','pseudozyma epicola','pseudozyma epicola',1,1),
  ('ING2090','sweet almond oil ferment extract','sweet almond oil ferment extract',1,1),
  ('ING2091','Kaempferia Galanga Root Extract','Kaempferia Galanga Root Extract',1,1),
  ('ING2092','Tricaprylyl Citrate','Tricaprylyl Citrate',1,1),
  ('ING2093','Octyldodecyl Citrate Crosspolymer','Octyldodecyl Citrate Crosspolymer',1,1),
  ('ING2094','Benzyl Cinnamate','Benzyl Cinnamate',1,1),
  ('ING2095','Alpinia Officinarum Root Extract','Alpinia Officinarum Root Extract',1,1),
  ('ING2096','CRATAEGUS MONOGYNA FLOWER EXTRACT','CRATAEGUS MONOGYNA FLOWER EXTRACT',1,1),
  ('ING2097','OLIGOPEPTIDE-2','OLIGOPEPTIDE-2',1,1),
  ('ING2098','G LYCOPROTEINS','G LYCOPROTEINS',1,1),
  ('ING2099','Malva Sylvestris Flower/Leaf Extract','Malva Sylvestris Flower/Leaf Extract',1,1),
  ('ING2100','Decapeptide-19','Decapeptide-19',1,1),
  ('ING2101','Nonapeptide-22','Nonapeptide-22',1,1),
  ('ING2102','Oligopeptide-41','Oligopeptide-41',1,1),
  ('ING2103','Acetyl Cysteine','Acetyl Cysteine',1,1),
  ('ING2104','Pueraria Mirifica Root Extract','Pueraria Mirifica Root Extract',1,1),
  ('ING2105','Propylene Glycol Caprylate','Propylene Glycol Caprylate',1,1),
  ('ING2106','Caprylyl Butyrate','Caprylyl Butyrate',1,1),
  ('ING2107','Eriobotrya Japonica Leaf Extract','Eriobotrya Japonica Leaf Extract',1,1),
  ('ING2108','Hydrogenated Coconut Acid','Hydrogenated Coconut Acid',1,1),
  ('ING2109','Lactobacillus/ Centella Asiatica/ Coffee Seed/ Ganoderma Lucidum/ Hops/ Panax Ginseng Root/ Scutellaria Baicalensis Root Extract/ Pea Extract/ Rice Seed Extract Ferment Filtrate','Lactobacillus/ Centella Asiatica/ Coffee Seed/ Ganoderma Lucidum/ Hops/ Panax Ginseng Root/ Scutellaria Baicalensis Root Extract/ Pea Extract/ Rice Seed Extract Ferment Filtrate',1,1),
  ('ING2110','Sodium C14-18 Olefin Sulfonate','Sodium C14-18 Olefin Sulfonate',1,1),
  ('ING2111','Sodium Cocoyl Alaninate','Sodium Cocoyl Alaninate',1,1),
  ('ING2112','Hydroxypropyltrimonium Inulin','Hydroxypropyltrimonium Inulin',1,1),
  ('ING2113','Glycine Soja Extract','Glycine Soja Extract',1,1),
  ('ING2114','Hydroxypropyl Arginine Lauryl','Hydroxypropyl Arginine Lauryl',1,1),
  ('ING2115','Myristyl Ether','Myristyl Ether',1,1),
  ('ING2116','Stearyl Dihydroxypropyldimonium Oligosaccharides','Stearyl Dihydroxypropyldimonium Oligosaccharides',1,1),
  ('ING2117','PEG-90','PEG-90',1,1),
  ('ING2118','Phytosteryl','Phytosteryl',1,1),
  ('ING2119','Octyldodecyl Lauroyl Glutamate','Octyldodecyl Lauroyl Glutamate',1,1),
  ('ING2120','Polyquaternium-64','Polyquaternium-64',1,1),
  ('ING2121','Aqua with infusions of Organic Vaccinium Vulcanorum Fruit Extract','Aqua with infusions of Organic Vaccinium Vulcanorum Fruit Extract',1,1),
  ('ING2122','Organic Rosa Davurica Leaf Oil','Organic Rosa Davurica Leaf Oil',1,1),
  ('ING2123','Triticum Vulgare Germ Oil','Triticum Vulgare Germ Oil',1,1),
  ('ING2124','Organic Salvia Verticillata Extract','Organic Salvia Verticillata Extract',1,1),
  ('ING2125','Argan Oil Polyglyceryl-4 Esters','Argan Oil Polyglyceryl-4 Esters',1,1),
  ('ING2126','Cannabis Sativa Seed Oil Polyglyceryl-4 Esters','Cannabis Sativa Seed Oil Polyglyceryl-4 Esters',1,1),
  ('ING2127','Cocamidopropyl Betain','Cocamidopropyl Betain',1,1),
  ('ING2128','Citrus Aurantium Bergama (Bergamot) Essential Oil','Citrus Aurantium Bergama (Bergamot) Essential Oil',1,1),
  ('ING2129','sodium sulfosuccinate','sodium sulfosuccinate',1,1),
  ('ING2130','isopentydiol','isopentydiol',1,1),
  ('ING2131','Betula Verrucosa Bark Extract','Betula Verrucosa Bark Extract',1,1),
  ('ING2132','OPUNTIA FICUS-INDICA FLOWER EXTRACT','OPUNTIA FICUS-INDICA FLOWER EXTRACT',1,1),
  ('ING2133','HYDROXYPROPYLTRIMONIUM CHLORIDE','HYDROXYPROPYLTRIMONIUM CHLORIDE',1,1),
  ('ING2134','MAGNOLIA ACUMINATA BARK EXTRACT','MAGNOLIA ACUMINATA BARK EXTRACT',1,1),
  ('ING2135','SHEA BUTTER ETHYL ESTERS','SHEA BUTTER ETHYL ESTERS',1,1),
  ('ING2136','musa paradisiaca fruit juice/ banana fruit juice','musa paradisiaca fruit juice/ banana fruit juice',1,1),
  ('ING2137','Hydrolyzed Oats Protein','Hydrolyzed Oats Protein',1,1),
  ('ING2138','Glycine Soja Protein','Glycine Soja Protein',1,1),
  ('ING2139','Carica Papaya Seed Oil','Carica Papaya Seed Oil',1,1),
  ('ING2140','Commiphora Mukul Resin Extract','Commiphora Mukul Resin Extract',1,1),
  ('ING2141','Oxycoccus Quadripetalus (Cranberry) Extract','Oxycoccus Quadripetalus (Cranberry) Extract',1,1),
  ('ING2142','Babassu Nut Oil','Babassu Nut Oil',1,1),
  ('ING2143','Threonune','Threonune',1,1),
  ('ING2144','Polyquaternium-87','Polyquaternium-87',1,1),
  ('ING2145','Isoamyl cocoate','Isoamyl cocoate',1,1),
  ('ING2146','orange oil','orange oil',1,1),
  ('ING2147','Ylang-ylang essential oil','Ylang-ylang essential oil',1,1),
  ('ING2148','Vitis vinifera extract','Vitis vinifera extract',1,1),
  ('ING2149','Macadamia Terniolia Nut Oil','Macadamia Terniolia Nut Oil',1,1),
  ('ING2150','HELIANTHUS ANNUSS (SUNFLOWER) SEED OIL','HELIANTHUS ANNUSS (SUNFLOWER) SEED OIL',1,1),
  ('ING2151','Tocopheryl','Tocopheryl',1,1),
  ('ING2152','Hydrolyzed Horse Chestnut Extract','Hydrolyzed Horse Chestnut Extract',1,1),
  ('ING2153','Peg','Peg',1,1),
  ('ING2154','Ppg-17','Ppg-17',1,1),
  ('ING2155','18 Dimethicone','18 Dimethicone',1,1),
  ('ING2156','Quaternium-33','Quaternium-33',1,1),
  ('ING2157','Saccharum Officinarum (Sugar Cane) Extract\Extrait De Canne A Sucre','Saccharum Officinarum (Sugar Cane) Extract\Extrait De Canne A Sucre',1,1),
  ('ING2158','Rice (Oryza Sativa) Bran Wax','Rice (Oryza Sativa) Bran Wax',1,1),
  ('ING2159','Citrus Aurantium Dulcis Peel Wax','Citrus Aurantium Dulcis Peel Wax',1,1),
  ('ING2160','Fragrances','Fragrances',1,1),
  ('ING2161','Lactobacillus/Tomato Fruit Ferment Extract','Lactobacillus/Tomato Fruit Ferment Extract',1,1),
  ('ING2162','Acyl Coenzyme A Desaturase','Acyl Coenzyme A Desaturase',1,1),
  ('ING2163','Tilia Platyphyllos Water','Tilia Platyphyllos Water',1,1),
  ('ING2164','Triricum Vulgare (Wheat Germ) Extract','Triricum Vulgare (Wheat Germ) Extract',1,1),
  ('ING2165','Cetraria Islandica Extract','Cetraria Islandica Extract',1,1),
  ('ING2166','Cl 42053','Cl 42053',1,1),
  ('ING2167','Cl 19140','Cl 19140',1,1),
  ('ING2168','Diospyros Kaki Fruit Extract','Diospyros Kaki Fruit Extract',1,1),
  ('ING2169','Ceratonia Siliqua (Carob) Fruit Extract','Ceratonia Siliqua (Carob) Fruit Extract',1,1),
  ('ING2170','Cl 17200','Cl 17200',1,1),
  ('ING2171','Cuscuta Japonica Seed Extract','Cuscuta Japonica Seed Extract',1,1),
  ('ING2172','Saccharomyces Cerevisiae Extract','Saccharomyces Cerevisiae Extract',1,1),
  ('ING2173','Lactobacillus / Kelp Ferment Filtrate','Lactobacillus / Kelp Ferment Filtrate',1,1),
  ('ING2174','Peg-40 Castor Oil','Peg-40 Castor Oil',1,1),
  ('ING2175','Hydrolyzed Oat Proteins','Hydrolyzed Oat Proteins',1,1),
  ('ING2176','Basic Blue 99','Basic Blue 99',1,1),
  ('ING2177','Basic Red 51','Basic Red 51',1,1),
  ('ING2178','APHANIZOMENON FLOSAQUAE EXTRACT','APHANIZOMENON FLOSAQUAE EXTRACT',1,1),
  ('ING2179','Sodium Coceth Sulfate','Sodium Coceth Sulfate',1,1),
  ('ING2180','Hypericum Perforatum Flower Extract','Hypericum Perforatum Flower Extract',1,1),
  ('ING2181','Citrus Sinensis Peel Oil','Citrus Sinensis Peel Oil',1,1),
  ('ING2182','Citrus Reticulata Leaf Oil','Citrus Reticulata Leaf Oil',1,1),
  ('ING2183','Citrus Aurantifolia Leaf Oil','Citrus Aurantifolia Leaf Oil',1,1),
  ('ING2184','Cedrus Deodara Seed Oil','Cedrus Deodara Seed Oil',1,1),
  ('ING2185','Melaleuca Leucadendron Cajaput Oil','Melaleuca Leucadendron Cajaput Oil',1,1),
  ('ING2186','Cinnamomum Camphora Linalooliferum Leaf Oil','Cinnamomum Camphora Linalooliferum Leaf Oil',1,1),
  ('ING2187','Thymus Vulgaris Oil','Thymus Vulgaris Oil',1,1),
  ('ING2188','Cinnamomum Cassia Oil','Cinnamomum Cassia Oil',1,1),
  ('ING2189','METHOXYMETHYLBUTANOL','METHOXYMETHYLBUTANOL',1,1),
  ('ING2190','Macadamia Oil','Macadamia Oil',1,1),
  ('ING2191','Dicaprilate/Dicaprate','Dicaprilate/Dicaprate',1,1),
  ('ING2192','Benzyl Salicilate','Benzyl Salicilate',1,1),
  ('ING2193','persicum nucleum pulveris','persicum nucleum pulveris',1,1),
  ('ING2194','pepper cayenne extract','pepper cayenne extract',1,1),
  ('ING2195','pyridoxin','pyridoxin',1,1),
  ('ING2196','ferment extract','ferment extract',1,1),
  ('ING2197','citrate','citrate',1,1),
  ('ING2198','янтарная кислота','янтарная кислота',1,1),
  ('ING2199','яблочная кислота','яблочная кислота',1,1),
  ('ING2200','hydroxyethelene cellulose','hydroxyethelene cellulose',1,1),
  ('ING2201','monard extract','monard extract',1,1),
  ('ING2202','green tea tree extract','green tea tree extract',1,1),
  ('ING2203','mint extract','mint extract',1,1),
  ('ING2204','сорбат калия','сорбат калия',1,1),
  ('ING2205','CYMBOPOGON CITRATUS LEAF OIL','CYMBOPOGON CITRATUS LEAF OIL',1,1),
  ('ING2206','CI 61570','CI 61570',1,1),
  ('ING2207','OSMANTHUS FRAGRANS FLOWER EXTRACT','OSMANTHUS FRAGRANS FLOWER EXTRACT',1,1),
  ('ING2208','Lauramine Oxide','Lauramine Oxide',1,1),
  ('ING2209','Peg-120 Methylglucosediolate','Peg-120 Methylglucosediolate',1,1),
  ('ING2210','Peg-3 Caprylyl Ether','Peg-3 Caprylyl Ether',1,1),
  ('ING2211','Hydroxypropyl Chitosan','Hydroxypropyl Chitosan',1,1),
  ('ING2212','Hydrolyzed Decorn Sudan White','Hydrolyzed Decorn Sudan White',1,1),
  ('ING2213','Zein','Zein',1,1),
  ('ING2214','Hydroxycitronelal','Hydroxycitronelal',1,1),
  ('ING2215','Pistachio Oil','Pistachio Oil',1,1),
  ('ING2216','Fenugreek Seed Extract','Fenugreek Seed Extract',1,1),
  ('ING2217','Natural Fragrances','Natural Fragrances',1,1),
  ('ING2218','Palmaria Palmata Extract','Palmaria Palmata Extract',1,1),
  ('ING2219','Citrus Sinensis Oil','Citrus Sinensis Oil',1,1),
  ('ING2220','Cananga Odorata (Ylang Ylang) Oil','Cananga Odorata (Ylang Ylang) Oil',1,1),
  ('ING2221','Arctium Iappa root extract','Arctium Iappa root extract',1,1),
  ('ING2222','Polyquternium-10','Polyquternium-10',1,1),
  ('ING2223','Linium usitatissimum extract','Linium usitatissimum extract',1,1),
  ('ING2224','pine lead enghua extract','pine lead enghua extract',1,1),
  ('ING2225','kangyeong root extract','kangyeong root extract',1,1),
  ('ING2226','Brilliant Blue FCF','Brilliant Blue FCF',1,1),
  ('ING2227','Aqua with infusions of Abies Sibirica Needle Extract','Aqua with infusions of Abies Sibirica Needle Extract',1,1),
  ('ING2228','Agrostis Sibirica Extract','Agrostis Sibirica Extract',1,1),
  ('ING2229','Ribes Nigrum Leaf Extract','Ribes Nigrum Leaf Extract',1,1),
  ('ING2230','Polyquaternium-46','Polyquaternium-46',1,1),
  ('ING2231','Amaranthus Caudatus Seed Oil','Amaranthus Caudatus Seed Oil',1,1),
  ('ING2232','Linum Usitatissimum','Linum Usitatissimum',1,1),
  ('ING2233','Hippophae Rhaimnoidesamidopropyl Betaine','Hippophae Rhaimnoidesamidopropyl Betaine',1,1),
  ('ING2234','Hydrolyzed Protein','Hydrolyzed Protein',1,1),
  ('ING2235','Vaccinium Vulcanorum Fruit Extractwh (Organic Blueberry Extract)','Vaccinium Vulcanorum Fruit Extractwh (Organic Blueberry Extract)',1,1),
  ('ING2236','Ribes Nigrum Leaf Water (Organic Blackurrant Hydrolate)','Ribes Nigrum Leaf Water (Organic Blackurrant Hydrolate)',1,1),
  ('ING2237','Iris Sibirica Root Extract WH (Organic Sibirian Iris Extract)','Iris Sibirica Root Extract WH (Organic Sibirian Iris Extract)',1,1),
  ('ING2238','Hesperis Sibirica Flower/Leaf/Stem Extract WH (Organic Sibirian Rocket Extract)','Hesperis Sibirica Flower/Leaf/Stem Extract WH (Organic Sibirian Rocket Extract)',1,1),
  ('ING2239','Acid Violet 43','Acid Violet 43',1,1),
  ('ING2240','Aqua with infusions of Yak Milk Protein','Aqua with infusions of Yak Milk Protein',1,1),
  ('ING2241','Organic Usnea Barbata Extract','Organic Usnea Barbata Extract',1,1),
  ('ING2242','Geranium Sibiricum Extract','Geranium Sibiricum Extract',1,1),
  ('ING2243','Organic Agrostis Alascana Extract','Organic Agrostis Alascana Extract',1,1),
  ('ING2244','Organic Schizandra Chinensis Fruit Extract','Organic Schizandra Chinensis Fruit Extract',1,1),
  ('ING2245','Hesperis Sibirica Flower/Leaf/Stem Extract','Hesperis Sibirica Flower/Leaf/Stem Extract',1,1),
  ('ING2246','Bidens Tripartita Extract','Bidens Tripartita Extract',1,1),
  ('ING2247','BUTYROSPERMUM PARKII (SHEA) BUTTER EXTRACT','BUTYROSPERMUM PARKII (SHEA) BUTTER EXTRACT',1,1),
  ('ING2248','PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) SEEDCAKE EXTRACT','PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) SEEDCAKE EXTRACT',1,1),
  ('ING2249','CAPRYLYL GLYCOL SODIUM BENZOATE','CAPRYLYL GLYCOL SODIUM BENZOATE',1,1),
  ('ING2250','MEL EXTRACT / HONEY EXTRACT','MEL EXTRACT / HONEY EXTRACT',1,1),
  ('ING2251','2-BROMO-2-NITROPROPANE-1','2-BROMO-2-NITROPROPANE-1',1,1),
  ('ING2252','Octylacrylamide/Acrylates/Butylaminoethyl Methacrylate Copolymer','Octylacrylamide/Acrylates/Butylaminoethyl Methacrylate Copolymer',1,1),
  ('ING2253','Peg-25 Paba','Peg-25 Paba',1,1),
  ('ING2254','ACRYLATES/PALMETH-25 ACRYLATE COPOLYMER','ACRYLATES/PALMETH-25 ACRYLATE COPOLYMER',1,1),
  ('ING2255','VP/VA acrylates copolymer','VP/VA acrylates copolymer',1,1),
  ('ING2256','Polyglyceryl-4 Caprylate','Polyglyceryl-4 Caprylate',1,1),
  ('ING2257','Dex-panthenol','Dex-panthenol',1,1),
  ('ING2258','Humulus Lupulus (Hops) Cone CO2 Extract','Humulus Lupulus (Hops) Cone CO2 Extract',1,1),
  ('ING2259','Citrus Aurantium Bergamia (Bergamot) Essential Oil','Citrus Aurantium Bergamia (Bergamot) Essential Oil',1,1),
  ('ING2260','Hydrolyzed Pea Piotein','Hydrolyzed Pea Piotein',1,1),
  ('ING2261','Hydrogenated Ethylhexyl Olivate','Hydrogenated Ethylhexyl Olivate',1,1),
  ('ING2262','Jania Rubens Extract','Jania Rubens Extract',1,1),
  ('ING2263','Meristotheca Dakarensis Extract','Meristotheca Dakarensis Extract',1,1),
  ('ING2264','Behentrimonium cloride','Behentrimonium cloride',1,1),
  ('ING2265','Glyceryl Palmitate/Stearate','Glyceryl Palmitate/Stearate',1,1),
  ('ING2266','Polyguaternium-7','Polyguaternium-7',1,1),
  ('ING2267','Arctium Lappa (Burdock) Root Oil','Arctium Lappa (Burdock) Root Oil',1,1),
  ('ING2268','2- hydroxyethyl ether','2- hydroxyethyl ether',1,1),
  ('ING2269','Oligopeptide-3','Oligopeptide-3',1,1),
  ('ING2270','Disperse Violet 43','Disperse Violet 43',1,1),
  ('ING2271','Hydrolyzed Cottonseed Protein','Hydrolyzed Cottonseed Protein',1,1),
  ('ING2272','Fibroin','Fibroin',1,1),
  ('ING2273','Adansonia Digitata Seed Extract','Adansonia Digitata Seed Extract',1,1),
  ('ING2274','Moringa Pterygos- perma Seed Extract','Moringa Pterygos- perma Seed Extract',1,1),
  ('ING2275','Prunus Avium (Sweet Cherry) Fruit Extract','Prunus Avium (Sweet Cherry) Fruit Extract',1,1),
  ('ING2276','Viola Mandshurica Flower Extract','Viola Mandshurica Flower Extract',1,1),
  ('ING2277','ACRYLAMIDE/SODIUM ACRYLOYLDIMETH-YLTAURATE COPOLYMER','ACRYLAMIDE/SODIUM ACRYLOYLDIMETH-YLTAURATE COPOLYMER',1,1),
  ('ING2278','PEG-8 METHICONE','PEG-8 METHICONE',1,1),
  ('ING2279','ETHYLHEXYL HYDROXYSTEARATE','ETHYLHEXYL HYDROXYSTEARATE',1,1),
  ('ING2280','CINNAMIDOPROPYLTRIMONIUM CHLORIDE','CINNAMIDOPROPYLTRIMONIUM CHLORIDE',1,1),
  ('ING2281','BISMUTH OXYCHLORIDE (CI 77163)','BISMUTH OXYCHLORIDE (CI 77163)',1,1),
  ('ING2282','OPUNTIA FICUS-INDICA EXTRACT','OPUNTIA FICUS-INDICA EXTRACT',1,1),
  ('ING2283','POLYURETHANE-39','POLYURETHANE-39',1,1),
  ('ING2284','HYDROLYZED MILK PROTEIN','HYDROLYZED MILK PROTEIN',1,1),
  ('ING2285','bacopa monnieri extract','bacopa monnieri extract',1,1),
  ('ING2286','TRIDECETH-9 PG-AMODIMETHICONE','TRIDECETH-9 PG-AMODIMETHICONE',1,1),
  ('ING2287','PEG/PPG-4/12 DIMETHICONE','PEG/PPG-4/12 DIMETHICONE',1,1),
  ('ING2288','PROPYLENE GLYCOLDICAPRYLATE/DICAPRATE','PROPYLENE GLYCOLDICAPRYLATE/DICAPRATE',1,1),
  ('ING2289','STEARETH-20','STEARETH-20',1,1),
  ('ING2290','PPG-1TRIDECETH-6','PPG-1TRIDECETH-6',1,1),
  ('ING2291','ACRYLATES/STEARYLMETHACRYLATE COPOLYMER','ACRYLATES/STEARYLMETHACRYLATE COPOLYMER',1,1),
  ('ING2292','Ziziphus Jujuba Fruit Extract','Ziziphus Jujuba Fruit Extract',1,1),
  ('ING2293','Calumanium Chloride','Calumanium Chloride',1,1),
  ('ING2294','C12-14 Sec Pareth-7','C12-14 Sec Pareth-7',1,1),
  ('ING2295','Sculeland Baicalensis Root Extract','Sculeland Baicalensis Root Extract',1,1),
  ('ING2296','Rehmannia Glutinosa Root Extract','Rehmannia Glutinosa Root Extract',1,1),
  ('ING2297','Alisma Orientale Tuber Extract','Alisma Orientale Tuber Extract',1,1),
  ('ING2298','Proteine','Proteine',1,1),
  ('ING2299','Hamamelis Virginiana (Hamamelis) Flower Water','Hamamelis Virginiana (Hamamelis) Flower Water',1,1),
  ('ING2300','Sodium Hydrosulfite','Sodium Hydrosulfite',1,1),
  ('ING2301','Stear Trimonium Chloride','Stear Trimonium Chloride',1,1),
  ('ING2302','Set Limonium Chloride','Set Limonium Chloride',1,1),
  ('ING2303','Trideces-12','Trideces-12',1,1),
  ('ING2304','Glycerol Reyl Stearate','Glycerol Reyl Stearate',1,1),
  ('ING2305','Fiji 45m','Fiji 45m',1,1),
  ('ING2306','Hydroxy Acetophenone','Hydroxy Acetophenone',1,1),
  ('ING2307','Disodium Ithiate','Disodium Ithiate',1,1),
  ('ING2308','Hydrodolized Silk','Hydrodolized Silk',1,1),
  ('ING2309','Pyroctone Amine','Pyroctone Amine',1,1),
  ('ING2310','Tea Tree Leaf Oil','Tea Tree Leaf Oil',1,1),
  ('ING2311','Snail Mucus Filtrate','Snail Mucus Filtrate',1,1),
  ('ING2312','Aloe Vera Leaf Extract','Aloe Vera Leaf Extract',1,1),
  ('ING2313','Lactose','Lactose',1,1),
  ('ING2314','Micro Crystalline Cellulose','Micro Crystalline Cellulose',1,1),
  ('ING2315','Ultramarine','Ultramarine',1,1),
  ('ING2316','Yellow 5 Arc','Yellow 5 Arc',1,1),
  ('ING2317','Citronelliol','Citronelliol',1,1),
  ('ING2318','Hydrolyzed Rice Proteins','Hydrolyzed Rice Proteins',1,1),
  ('ING2319','Bambusa Arundinacea Stem Extract','Bambusa Arundinacea Stem Extract',1,1),
  ('ING2320','ALPH-ISOMETHYL IONONE','ALPH-ISOMETHYL IONONE',1,1),
  ('ING2321','CI 16035 (RED 40)','CI 16035 (RED 40)',1,1),
  ('ING2322','argania spinosa oil/ arganiaspinosa kernel oil','argania spinosa oil/ arganiaspinosa kernel oil',1,1),
  ('ING2323','moringa oleifera dees oil','moringa oleifera dees oil',1,1),
  ('ING2324','butylphenyl methylpropionla','butylphenyl methylpropionla',1,1),
  ('ING2325','C9-12 alcan','C9-12 alcan',1,1),
  ('ING2326','ppg-3 caprylic ether','ppg-3 caprylic ether',1,1),
  ('ING2327','glycolipides','glycolipides',1,1),
  ('ING2328','Argania Spinosa Seed Oil','Argania Spinosa Seed Oil',1,1),
  ('ING2329','Schizandra Chinensis Fruit Oil Extract','Schizandra Chinensis Fruit Oil Extract',1,1),
  ('ING2330','Myrtus Communis Oil','Myrtus Communis Oil',1,1),
  ('ING2331','Rethinyl Palmitate (витамин А)','Rethinyl Palmitate (витамин А)',1,1),
  ('ING2332','cinnamyl alc','cinnamyl alc',1,1),
  ('ING2333','alpha–isomethyl ionone','alpha–isomethyl ionone',1,1),
  ('ING2334','HYDROXYPROPYL ARGININE LAURYL/MYRISTYL ETHER HCl','HYDROXYPROPYL ARGININE LAURYL/MYRISTYL ETHER HCl',1,1),
  ('ING2335','Sodium Methyl Lauroyl Taurate','Sodium Methyl Lauroyl Taurate',1,1),
  ('ING2336','Citrus Reticulata Peel Oil','Citrus Reticulata Peel Oil',1,1),
  ('ING2337','Cupressus Funebris Wood Oil','Cupressus Funebris Wood Oil',1,1),
  ('ING2338','Citrus Aurantifolia Oil','Citrus Aurantifolia Oil',1,1),
  ('ING2339','Thymus Zygis Oil','Thymus Zygis Oil',1,1),
  ('ING2340','Cinnamomum Cassia Leaf Oil','Cinnamomum Cassia Leaf Oil',1,1),
  ('ING2341','Melaleuca Leucadendron Cajuputi Leaf Oil','Melaleuca Leucadendron Cajuputi Leaf Oil',1,1),
  ('ING2342','Cinnamomum Camphora Leaf Oil','Cinnamomum Camphora Leaf Oil',1,1),
  ('ING2343','Maltobionic Acid','Maltobionic Acid',1,1),
  ('ING2344','Fomes Officinalis (Mushroom) Extract','Fomes Officinalis (Mushroom) Extract',1,1),
  ('ING2345','Sapindus Mukorossi Extract','Sapindus Mukorossi Extract',1,1),
  ('ING2346','dipelmitoylethyi hydroxyethymonium methosulfate','dipelmitoylethyi hydroxyethymonium methosulfate',1,1),
  ('ING2347','undecylenic acid','undecylenic acid',1,1),
  ('ING2348','С2-13 alkyl lactate','С2-13 alkyl lactate',1,1),
  ('ING2349','ximenia americane bark extract','ximenia americane bark extract',1,1),
  ('ING2350','arctium majus extract','arctium majus extract',1,1),
  ('ING2351','arnica montana axtract','arnica montana axtract',1,1),
  ('ING2352','citrus imonum extract','citrus imonum extract',1,1),
  ('ING2353','hadara helx extract','hadara helx extract',1,1),
  ('ING2354','matricare recutita extract','matricare recutita extract',1,1),
  ('ING2355','nasturtium officinale extract','nasturtium officinale extract',1,1),
  ('ING2356','pinus sylvestris extract','pinus sylvestris extract',1,1),
  ('ING2357','salva ofticinalis extrect','salva ofticinalis extrect',1,1),
  ('ING2358','trapasoium majus extract','trapasoium majus extract',1,1),
  ('ING2359','lamium aba extract','lamium aba extract',1,1),
  ('ING2360','sapindus mukurassi peel extract','sapindus mukurassi peel extract',1,1),
  ('ING2361','acrylamidopropyltrimonium chioride/acrylates copolymer','acrylamidopropyltrimonium chioride/acrylates copolymer',1,1),
  ('ING2362','sohexadecane','sohexadecane',1,1),
  ('ING2363','coceth-','coceth-',1,1),
  ('ING2364','chanoxyethenol','chanoxyethenol',1,1),
  ('ING2365','glycery layrate','glycery layrate',1,1),
  ('ING2366','myristica fragrans extract','myristica fragrans extract',1,1),
  ('ING2367','carnosic acid','carnosic acid',1,1),
  ('ING2368','PEG-75 Dilaurate','PEG-75 Dilaurate',1,1),
  ('ING2369','PEG-120 Methyl Glucose Triisostearate','PEG-120 Methyl Glucose Triisostearate',1,1),
  ('ING2370','Hydrolyzed Keratin PG-Propyl Methysilanediol','Hydrolyzed Keratin PG-Propyl Methysilanediol',1,1),
  ('ING2371','Sodium Silicate','Sodium Silicate',1,1),
  ('ING2372','Humus Extract','Humus Extract',1,1),
  ('ING2373','Polyquaternium-61','Polyquaternium-61',1,1),
  ('ING2374','Glycerylamidoethyl Methacrylate/Stearyl Methacrylate','Glycerylamidoethyl Methacrylate/Stearyl Methacrylate',1,1),
  ('ING2375','Peg-75 Stearate','Peg-75 Stearate',1,1),
  ('ING2376','Trideceth-7','Trideceth-7',1,1),
  ('ING2377','Sorbitan Trioleate','Sorbitan Trioleate',1,1),
  ('ING2378','Polyglyceryl-6 Dioleate','Polyglyceryl-6 Dioleate',1,1),
  ('ING2379','Pca Ethyl Cocoyl Arginate','Pca Ethyl Cocoyl Arginate',1,1),
  ('ING2380','Methoxycinnamidopropyl Hydroxysultaine','Methoxycinnamidopropyl Hydroxysultaine',1,1),
  ('ING2381','Avena Sativa Seed Extract','Avena Sativa Seed Extract',1,1),
  ('ING2382','Hordeum Vulgare Seed Extract','Hordeum Vulgare Seed Extract',1,1),
  ('ING2383','Glyoxylic Acid','Glyoxylic Acid',1,1),
  ('ING2384','Glucosamine HCI','Glucosamine HCI',1,1),
  ('ING2385','C11-15 ALKETH-7','C11-15 ALKETH-7',1,1),
  ('ING2386','DISODIUM EDTA/TETRASODIUM EDTA','DISODIUM EDTA/TETRASODIUM EDTA',1,1),
  ('ING2387','Polyacrylamidopropyltrimonium Chloride','Polyacrylamidopropyltrimonium Chloride',1,1),
  ('ING2388','PPG-1-PEG-9 Lauryl Glycol Ether','PPG-1-PEG-9 Lauryl Glycol Ether',1,1),
  ('ING2389','PEG‑8','PEG‑8',1,1),
  ('ING2390','PEG‑8/SMDI Copolymer','PEG‑8/SMDI Copolymer',1,1),
  ('ING2391','Soy Amino Acids','Soy Amino Acids',1,1),
  ('ING2392','PPG-3 Myristyl Ether','PPG-3 Myristyl Ether',1,1),
  ('ING2393','Αlpha-isomethyl Ionone','Αlpha-isomethyl Ionone',1,1),
  ('ING2394','GLYCIN SOJA OIL / SOYBEAN OIL','GLYCIN SOJA OIL / SOYBEAN OIL',1,1),
  ('ING2395','CANDELILLA CERA / CANDELILLA WAX','CANDELILLA CERA / CANDELILLA WAX',1,1),
  ('ING2396','Orange Wax (Citrus Aurantium Wax)','Orange Wax (Citrus Aurantium Wax)',1,1),
  ('ING2397','Citrus Grandis Oil','Citrus Grandis Oil',1,1),
  ('ING2398','aleurites moluccanus seed oil','aleurites moluccanus seed oil',1,1),
  ('ING2399','Stearyl Acohol','Stearyl Acohol',1,1),
  ('ING2400','Keratin Hydrolyzed Hair Keratin','Keratin Hydrolyzed Hair Keratin',1,1),
  ('ING2401','Psidiumfuajava Fruit Extract','Psidiumfuajava Fruit Extract',1,1),
  ('ING2402','Glycolpids','Glycolpids',1,1),
  ('ING2403','Peg-90m','Peg-90m',1,1),
  ('ING2404','Butyl Methoxydibenzoyl-Methane','Butyl Methoxydibenzoyl-Methane',1,1),
  ('ING2405','Cetyl Ethoylhexanoate','Cetyl Ethoylhexanoate',1,1),
  ('ING2406','Buty-Loctanol','Buty-Loctanol',1,1),
  ('ING2407','Iodopropynly Butylcarbamate','Iodopropynly Butylcarbamate',1,1),
  ('ING2408','COCOS NUCIFERA (COCONUT) LIQUID ENDOSPERM','COCOS NUCIFERA (COCONUT) LIQUID ENDOSPERM',1,1),
  ('ING2409','SEA WATER / MARIS AQUA / EAU DE MER','SEA WATER / MARIS AQUA / EAU DE MER',1,1),
  ('ING2410','STYRENE / BUTADIENE COPOLYMER','STYRENE / BUTADIENE COPOLYMER',1,1),
  ('ING2411','EXT. VIOLET 2 (CI 60730)','EXT. VIOLET 2 (CI 60730)',1,1),
  ('ING2412','SIMMONDSIA CHINENSIS OIL','SIMMONDSIA CHINENSIS OIL',1,1),
  ('ING2413','CRAMBE ABYSSINICA OIL','CRAMBE ABYSSINICA OIL',1,1),
  ('ING2414','CITRUS LEMON OIL','CITRUS LEMON OIL',1,1),
  ('ING2415','Organic Calendula Officinalis Flower Oil','Organic Calendula Officinalis Flower Oil',1,1),
  ('ING2416','Organic Decolorized Aloe Barbadensis Leaf Oil','Organic Decolorized Aloe Barbadensis Leaf Oil',1,1),
  ('ING2417','Organic Cocos Nucifera (Coconut) Fruit Oil','Organic Cocos Nucifera (Coconut) Fruit Oil',1,1),
  ('ING2418','Organic Rosmarinus Officinalis (Rosemary) Leaf Extract','Organic Rosmarinus Officinalis (Rosemary) Leaf Extract',1,1),
  ('ING2419','Gardenia Jasminoides (Gardenia Enfleurage) Oil','Gardenia Jasminoides (Gardenia Enfleurage) Oil',1,1),
  ('ING2420','Passiflora Edulis Seed Oil','Passiflora Edulis Seed Oil',1,1),
  ('ING2421','Tamarindus Indica Fruit Extract','Tamarindus Indica Fruit Extract',1,1),
  ('ING2422','Euterpe Oleracea Fruit Oil','Euterpe Oleracea Fruit Oil',1,1),
  ('ING2423','Oenocarpus Bataua Fruit Oil','Oenocarpus Bataua Fruit Oil',1,1),
  ('ING2424','Bacopa Monnieri Leaf Extract','Bacopa Monnieri Leaf Extract',1,1),
  ('ING2425','linoleamidopropyl pg-dimomium chloride phosphate','linoleamidopropyl pg-dimomium chloride phosphate',1,1),
  ('ING2426','ammonium chloride','ammonium chloride',1,1),
  ('ING2427','glyceryl linolenate','glyceryl linolenate',1,1),
  ('ING2428','Sodium Lauryl Sulfoacetate. Glycerin','Sodium Lauryl Sulfoacetate. Glycerin',1,1),
  ('ING2429','Rosa Hybrid Flower Extract','Rosa Hybrid Flower Extract',1,1),
  ('ING2430','Robinia Pseudoacacia Flower Extract','Robinia Pseudoacacia Flower Extract',1,1),
  ('ING2431','Organic Argania Spinosa (Argan) Seed Oil','Organic Argania Spinosa (Argan) Seed Oil',1,1),
  ('ING2432','bytylene glycol','bytylene glycol',1,1),
  ('ING2433','Cetylpyridinium Chloride','Cetylpyridinium Chloride',1,1),
  ('ING2434','Dipalmitoylethyl Dimonium Chloride','Dipalmitoylethyl Dimonium Chloride',1,1),
  ('ING2435','Triticum Vulgare (Wheat) Seed Extract','Triticum Vulgare (Wheat) Seed Extract',1,1),
  ('ING2436','C15-19 Alkane','C15-19 Alkane',1,1),
  ('ING2437','Sodium Polyacrylate Starch','Sodium Polyacrylate Starch',1,1),
  ('ING2438','Evernia Furfuracea (Treemoss) Extract','Evernia Furfuracea (Treemoss) Extract',1,1),
  ('ING2439','Evernia Prunastri (Oakmoss) Extract','Evernia Prunastri (Oakmoss) Extract',1,1),
  ('ING2440','Verbena Officinalis Leaf Extract','Verbena Officinalis Leaf Extract',1,1),
  ('ING2441','Hydroxyethylcelulose','Hydroxyethylcelulose',1,1),
  ('ING2442','PEG/PPG-25/25 dimethicone','PEG/PPG-25/25 dimethicone',1,1),
  ('ING2443','CI 47005 [Yellow 10]','CI 47005 [Yellow 10]',1,1),
  ('ING2444','Cocamide Methyl Mea','Cocamide Methyl Mea',1,1),
  ('ING2445','Chinese Cinchona Shrub (Paederia Scandens) Extract','Chinese Cinchona Shrub (Paederia Scandens) Extract',1,1),
  ('ING2446','Flatweed Leaf Extract','Flatweed Leaf Extract',1,1),
  ('ING2447','Drynaria Fortunei Rhizome Extract','Drynaria Fortunei Rhizome Extract',1,1),
  ('ING2448','Yellow 1','Yellow 1',1,1),
  ('ING2449','Ginseng Root Extract Ordinary','Ginseng Root Extract Ordinary',1,1),
  ('ING2450','Powdered Aloe Leaf Juice Concentrate','Powdered Aloe Leaf Juice Concentrate',1,1),
  ('ING2451','Polyquaternium-43','Polyquaternium-43',1,1),
  ('ING2452','Chinese Angelica Root Extract','Chinese Angelica Root Extract',1,1),
  ('ING2453','Sapozhnikovia Root Extract','Sapozhnikovia Root Extract',1,1),
  ('ING2454','Red Sage Root Extract','Red Sage Root Extract',1,1),
  ('ING2455','Dereza Bark Extract','Dereza Bark Extract',1,1),
  ('ING2456','Aglaomorph Root Extract','Aglaomorph Root Extract',1,1),
  ('ING2457','Pharmacy Ginger Root Extract','Pharmacy Ginger Root Extract',1,1),
  ('ING2458','Yellowish Sophora Root Extract','Yellowish Sophora Root Extract',1,1),
  ('ING2459','Chinese Quince Fruit Extract','Chinese Quince Fruit Extract',1,1),
  ('ING2460','Notopterygium Incisor Root Extract','Notopterygium Incisor Root Extract',1,1),
  ('ING2461','Ligusticum Striatum Root Extract','Ligusticum Striatum Root Extract',1,1),
  ('ING2462','Australian Twig Seed Extract','Australian Twig Seed Extract',1,1),
  ('ING2463','High Gastrodia Root Extract','High Gastrodia Root Extract',1,1),
  ('ING2464','Common Ginseng Root Extract','Common Ginseng Root Extract',1,1),
  ('ING2465','Lactic-Flowered','Lactic-Flowered',1,1),
  ('ING2466','Speranskii Root Extract','Speranskii Root Extract',1,1),
  ('ING2467','Spatholobus Root Extract','Spatholobus Root Extract',1,1),
  ('ING2468','Pinus Sylvestric Leaf Extract','Pinus Sylvestric Leaf Extract',1,1),
  ('ING2469','Scutellaria Baicalensisrootextract','Scutellaria Baicalensisrootextract',1,1),
  ('ING2470','3-Propanediol','3-Propanediol',1,1),
  ('ING2471','Pisum Sativum (Pea) Extract','Pisum Sativum (Pea) Extract',1,1),
  ('ING2472','Selaginella Lepidophylla (Resurrection Plant) Extract','Selaginella Lepidophylla (Resurrection Plant) Extract',1,1),
  ('ING2473','Centella Asiatica (Indian Pennywort) Heterosides','Centella Asiatica (Indian Pennywort) Heterosides',1,1),
  ('ING2474','Catalase','Catalase',1,1),
  ('ING2475','Ethylbisiminomethylguaiacol Manganese Chloride','Ethylbisiminomethylguaiacol Manganese Chloride',1,1),
  ('ING2476','Caryodendron Orinocense (Kahai) Seed Oil','Caryodendron Orinocense (Kahai) Seed Oil',1,1),
  ('ING2477','Vaccinium Myrtillus (Bilberry) Seed Oil','Vaccinium Myrtillus (Bilberry) Seed Oil',1,1),
  ('ING2478','Sodium Laurylglucosides','Sodium Laurylglucosides',1,1),
  ('ING2479','Cedrus Deodara (Cedarwood) Bark Oil*','Cedrus Deodara (Cedarwood) Bark Oil*',1,1),
  ('ING2480','Catalase Enzyme','Catalase Enzyme',1,1),
  ('ING2481','Stearyl Glycyrrhetinate','Stearyl Glycyrrhetinate',1,1),
  ('ING2482','Meadowfoam Estolide','Meadowfoam Estolide',1,1),
  ('ING2483','Ganoderma Lucidum (Mushroom) Stem Extract','Ganoderma Lucidum (Mushroom) Stem Extract',1,1),
  ('ING2484','Natural Fragrance','Natural Fragrance',1,1),
  ('ING2485','Sodium Laurylglucosides Hydroxypropylsulfonate','Sodium Laurylglucosides Hydroxypropylsulfonate',1,1),
  ('ING2486','Tea Tree (Melaleuca Alternifolia) (Leaf) Oil*','Tea Tree (Melaleuca Alternifolia) (Leaf) Oil*',1,1),
  ('ING2487','Black Cumin (Nigella Sativa) (Seed) Oil','Black Cumin (Nigella Sativa) (Seed) Oil',1,1),
  ('ING2488','East Indian Lemongrass (Cymbopogon Flexuosus) (Leaf) Oil*','East Indian Lemongrass (Cymbopogon Flexuosus) (Leaf) Oil*',1,1),
  ('ING2489','Amla (Phyllanthus Emblica) (Fruit) Oil*','Amla (Phyllanthus Emblica) (Fruit) Oil*',1,1),
  ('ING2490','Red Korean Seaweed (Grateloupia Elliptica) Extract','Red Korean Seaweed (Grateloupia Elliptica) Extract',1,1),
  ('ING2491','Stinging Nettle (Urtica Dioica) (Leaf) Extract','Stinging Nettle (Urtica Dioica) (Leaf) Extract',1,1),
  ('ING2492','Saw Palmetto (Serenoa Serrulata) (Fruit) Extract','Saw Palmetto (Serenoa Serrulata) (Fruit) Extract',1,1),
  ('ING2493','Cedarwood (Cedrus Atlantica) (Bark) Oil*','Cedarwood (Cedrus Atlantica) (Bark) Oil*',1,1),
  ('ING2494','Clary Sage (Salvia Sclarea) (Flower/Leaf) Oil','Clary Sage (Salvia Sclarea) (Flower/Leaf) Oil',1,1),
  ('ING2495','Fo Ti (Polygonum Multiflorum) (Root) Extract','Fo Ti (Polygonum Multiflorum) (Root) Extract',1,1),
  ('ING2496','Grapefruit (Citrus Paradisi) (Peel) Oil*','Grapefruit (Citrus Paradisi) (Peel) Oil*',1,1),
  ('ING2497','Hibiscus (Hibiscus Sabdariffa) (Flower) Extract','Hibiscus (Hibiscus Sabdariffa) (Flower) Extract',1,1),
  ('ING2498','Pygeum (Prunus Africana)( Bark) Extract','Pygeum (Prunus Africana)( Bark) Extract',1,1),
  ('ING2499','White Willow (Salix Alba) (Bark) Extract','White Willow (Salix Alba) (Bark) Extract',1,1),
  ('ING2500','Apple (Pyrus Malus) (Fruit) Extract','Apple (Pyrus Malus) (Fruit) Extract',1,1)
ON CONFLICT (ingredient_id) DO UPDATE SET canonical_name=EXCLUDED.canonical_name, aliases=EXCLUDED.aliases;